### ISSUE TITLE
Retrieval UI: Render Form Response Retrieval Table 

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#1049]
This issue depends on #1045 #1047 and number #1048

Please see the following section [Form Responses Table](https://docs.google.com/document/d/1KNXcSM5xWIn1WeJUy9KzNg9i2KnekGZXxWSNx_ZJ4u4/edit#heading=h.8yvui6w4552x) from `Design Doc 004-1`

Table, Row and Cell components should be plugged into the `/id/[form]/retrieval/index.ts` page. Row and cells should be generated on the page using the array of objects containing form response data passed in from the server side. A checkbox component should be created to handle row selection with the state of that being managed on the page ( see implementation document ). 

Note, it's not shown in the designs however the row selection checkbox column should have a column name. The table should also have a caption containing the summary as described in the [Table Accessibility](https://docs.google.com/document/d/1KNXcSM5xWIn1WeJUy9KzNg9i2KnekGZXxWSNx_ZJ4u4/edit#heading=h.7i1bps1vwm4c) section of the implementation document 

Acceptance Criteria:
- [ ] Table is rendered on the `/id/[form]/retrieval/index.ts` page component 
- [ ]  Row selection, it's state and resulting changes is implemented

**Comment by thiessenp-cds** [comment]
The Responses page and download table have been implemented so we can close this issue
