### ISSUE TITLE
Set given_name and family_name User Pool Attributes to Required

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#1071]
The given_name and family_name attributes should be set to required such that a user cannot register without providing it. This should be done in terraform in the following file (https://github.com/cds-snc/forms-terraform/blob/develop/aws/cognito/user_pool.tf)

**Comment by bryan-robitaille** [comment]
We've decided as a team to go with just `name` instead of `given_name` and `family_name`
