### ISSUE TITLE
Interpolation function

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1093]
A function will need to be written to interpolate the `${user.id}` placeholders with actual values when the rule conditions are added to the users Session Object.  See https://casl.js.org/v6/en/cookbook/roles-with-persisted-permissions#services for example.

This function will be used to interpolate permission rules that have conditions that leverage information placeholders.

```js
const permissions = [
  {action:”view”,subject:”Form”, condition:”user: ${objectX.id}”},
  {action:”update”,subject:”Form”, condition:”group: ${objectY.department.id}”},
]

const objectX = {
  id:  “x234assdk”
}

const objectY = {
  department: {
    id: “0823honasdf”
  }
}

fn(permissions, { objectX, objectY} => [
  {action:”view”,subject:”Form”, condition:”user: x234assdk”},
  {action:”update”,subject:”Form”, condition:”group: 0823honasdf”},
]

```

**Comment by craigzour** [comment]
Here is a Gist of what I have been working on. It is working but I still need to handle possible errors. https://gist.github.com/craigzour/107cd109e13f9763c7df0b0a8a8ede58

**Comment by craigzour** [comment]
Closing now that it was merged (https://github.com/cds-snc/platform-forms-client/pull/1135) to our https://github.com/cds-snc/platform-forms-client/tree/feature/permissions
