### ISSUE TITLE
Configure Amazon SES service to remove Cognito Daily Email Limits

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#1104]
### Acceptance criteria:
- [x] Identify how to implement SES to remove the email limit
- [x] Implement password reset functionality
- [x] Identify a mitigation approach (e.g., sending a notification to #forms-deployment, turning off sign-ups, and tell users)
- [x] Look at a longer term approach after general launch

### Future sprints
- [x] Implement approach

### Context

Cognito only allows 50 emails a day to be sent per amazon account. 

![Screen Shot 2022-10-06 at 3.27.21 PM.png](https://images.zenhubusercontent.com/5e4d99e2b8781e7790b7e8cc/dba254f0-354c-4947-8cd5-5b9310206b49)

An SES service should be configured in one of the following regions to remove this quota 

![Screen Shot 2022-10-06 at 3.35.21 PM.png](https://images.zenhubusercontent.com/5e4d99e2b8781e7790b7e8cc/e60ba0c3-f7fa-4a78-9b5b-744f9754e86c)

**Comment by timarney** [comment]
Noting we found a possible path forward for using a Custom Email Sender i.e. Notify

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-email-sender.html

See:
https://gcdigital.slack.com/archives/C0117FN8G9K/p1670277717957619
