### ISSUE TITLE
Zustand vs React Context API

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1112]
Something to look at when refactoring, or maturing, the Form Builder feature is whether to replace Zustand with React Context API.

The benefits of introducing Zustand in an application are to reduce the number of component rerenders on complex state changes and reduce boiler plate code.

The benefits of leveraging React Context API in an application are to reduce external dependencies by leveraging native functionality in the core React API.

In its current implementation within the application Zustand is not providing the benefit of only targeting components that require rerender but instead rerenders the whole tree.  This is due to the 'form' state object being consumed and watching for changes at the `Layout` and `ElementPanel` components.  These components then pass the `form` object to child components that render on `form` state changes.  Unfortunately any change triggered in a child component causes the `form` state object to change and triggers a rerender of `Layout`, `ElementPanel`, and all child nodes.

The clip below demonstrates which components are rerendered when interacting with the form builder by leveraging react-dev-tools.  Components are highlighted when rerendered.
![react tree rerender performance.gif](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/68bad709-336f-41fe-bb8a-b053e677452c)

**Comment by timarney** [comment]
Form the Form Builder end the plan has been to re-visit / make this performant once the UI settles. Might depend on if we end up with a save button vs the current write back to the store right away as it is now.

We'll be looking at a combination of debouncing (key events) and narrowing how we select state see: 
https://docs.pmnd.rs/zustand/recipes/recipes#memoizing-selectors

Interesting article that related to Context vs X

> In this article we're going to explore some drawbacks of context-based state in typical application architecture, then explore an alternative construct, Stores, which should ultimately help us write cleaner code and increase our in-app performance.

https://formidable.com/blog/2021/stores-no-context-api/

**Comment by bryan-robitaille** [comment]
100% that a state manager like Zustand is the way to go in long term for complex state management on the form building page.  I shouldn't have named the issue Zustand vs React Context.  The only thing I was trying to raise was that if we were not going to refactor in the near to short term then in order to avoid additional project dependencies in Production the React Context API would provide the same level of current performance without the additional dependencies.

**Comment by bryan-robitaille** [comment]
Component performance is being addressed.
