### ISSUE TITLE
Wrap all CRUD functions with checkPrivelage

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1115]
Ensure that all CRUD functions, usually where Prisma is involved, check that the user has the privilege to initiate the action.  

Most CRUD functions can be found under the `./lib` folder and include, but are not limited to:
- templates.ts
- users.ts
- owners.ts

Acceptance Criteria
- [ ] All CRUD functions require an instance of Ability 
- [ ] All CRUD functions check the action and subject against a user's Ability instance

**Comment by craigzour** [comment]
WIP branch https://github.com/cds-snc/platform-forms-client/tree/feature/protect-crud-functions-with-permissions
