### ISSUE TITLE
Prototype Pollution from JSON file upload to Form Builder

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#1118]
When a JSON file is uploaded to the form builder. The lines posted below will check if the content is a string and then immediately call `JSON.parse` to create the object. This opens up a vector for prototype pollution. `JSON.parse` will parse out a `__proto__` key in JSON as the prototype of the object generated. See Mozilla docs on Object initialization. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#object_literal_syntax_vs._json 

https://github.com/cds-snc/platform-forms-client/blob/develop/components/form-builder/layout/Start.tsx#L63-L99

Since the Form Builder is to be made public and JSON will come from untrusted sources this should be addressed

Potential solution 

```
const cleaner = (key, value) => key === "__proto__" ? undefined : value;

// demo
let json = '{"user":{"__proto__":{"admin": true}}}';

let cleanJSON = JSON.parse(json, cleaner)
```

**Comment by timarney** [comment]
> Since the Form Builder is to be made public and JSON will come from untrusted sources this should be addressed

For sure --- thinking there should be shared utilities between "core" and "form builder" to validate these types of things outside of the JSON schema checks etc..
