### ISSUE TITLE
Modify Templates Table to Include UpdatedAt Field

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#1168]
Acceptance Criteria 
- [ ] templates table includes UpdateAt timestamp field which is updated the record is modified.
- [ ] modify return from database so that this field is available in the form client 
- [ ] clean migration with no loss of data

**Comment by craigzour** [comment]
@thiessenp-cds I think this was implemented as part of the work you have done around `/myforms`. Is it correct? If yes then we could close the ticket.

**Comment by thiessenp-cds** [comment]
> @thiessenp-cds I think this was implemented as part of the work you have done around `/myforms`. Is it correct? If yes then we could close the ticket.

Yup, updatedAt was added to the Prisma templates file. So you can mark that off as complete :)
