### ISSUE TITLE
Create the Card Component, Layout and Grid

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#1169]
Acceptance Criteria:
- [ ] Has to be accessible 
- [ ] Matches the figma designs 
- [ ] Create actions with no effects
- [ ] make it mobile-ish friendly 
- [ ] review by design

**Comment by thiessenp-cds** [comment]
PR in the works with some updates: 
https://github.com/cds-snc/platform-forms-client/pull/1290

**Comment by ioanacontu** [comment]
A couple of comments I gathered so far: 
- the draft link should open form editing (not Preview URL). (Rationale: for security reasons, we should never provide a link to a fillable "draft" form).  
- we need a "delete" option in the "More" menu. When selected it should take users to the "Settings" page where the "Delete" button is.
