### ISSUE TITLE
Form Builder Usability Issue - Opening Links

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1173]
### User stories
- As a Form Builder, my progress is lost when I leave the site to read the Terms and Conditions.

### Acceptance criteria
- [ ] All external links that would cause the user to lose information can open in another tab
- [ ] For accessibility, this is announced via screen reader or (opens in a new tab) is included in the link text

**Comment by timarney** [comment]
We've added session storage to help with this.

https://github.com/cds-snc/platform-forms-client/pull/1260
