### ISSUE TITLE
Unlock Publishing Page(s)

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1224]
Add the following flow after a user successfully registers.

-----
Skip this step for now redirects the user to `My Forms`

![Screenshot 2022-11-07 at 9.55.39 AM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/c25f5360-1d5c-4d80-b51c-27758bd0a116)
------

![Screenshot 2022-11-07 at 9.56.31 AM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/19d06d5f-02a9-4638-bec4-6c59e1c7563f)

![Screenshot 2022-11-07 at 9.56.49 AM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/1e05ffe3-b0a3-40e1-8afc-d068a753eea3)

Unresolved Questions:
- Are we storing the department and email message in the application somewhere?
- Does the user get asked about requesting publishing access after every login if they do not have the ability?

**Comment by thiessenp-cds** [comment]
For the UI page routes, I'll start with:
```
/pages/signup/account-created
/pages/signup/unlock-publishing
/pages/signup/unlock-publishing-submitted
```
