### ISSUE TITLE
Notify Template for Support

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1225]
Need more information around support process

Email to send to:
Content of email:

**Comment by craigzour** [comment]
Looks like we can reuse the form response GC Notify template:
<img width="1015" alt="Screen Shot 2022-11-08 at 9 31 41 AM" src="https://user-images.githubusercontent.com/1763961/200591732-2aa685ed-6825-48f2-984b-86e819708e07.png">
