### ISSUE TITLE
Adding link in text could have better usabiility

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1269]
When trying to create / insert a link it automatically selects all preceding text if no text is manually highlighted.  Once text is then set as a link it seems impossible to remove unless all the link text is deleted.

User Frustration Issue:
I just entered a very large piece of text and I need to insert a link.  I stop typing and click on the create link icon in the menu.  Instead of being prompted for the text and url the preceding text is automatically converted to a link.  I now have to delete my large piece of text and retype it.

![link selecting whole sentance.gif](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/4d12a616-32ec-446e-a348-ce5a8fa20a60)

**Comment by timarney** [comment]
We'll need some input from design on this 

Currently you can press the link button again to remove the link from the selection and we also have undo via the keyboard -- but both some those would require discovery by the user.

Wondering if we shouldn't link if no text is selected also curious what others would think is expected behaviour.

cc: @samsadasivan @connorscarolyns @ioanacontu

**Comment by connorscarolyns** [comment]
I assume that just the word my cursor is on would be selected, although that may not be everyone's assumption. We did not test this in usability, so it's impossible to say exactly what users expect. 

The link function (as is) does seem unexpected, but I don't anticipate that it'll slow people down for too long. We can either:
- Take our best guess at how to fix it and wait to see if it's still an issue
-  Do a little more research on how other rich text editors have tackled this issue and emulate 
- Wait and see what feedback we get on this to determine if it's a problem and test it in our next round of usability testing 

Although I agree it's a bit of a crunchy experience, unless there is something easy we can do it patch it up, for now, I would leave it as is. 

I'm really interested to see how things perform in our accessibility testing round. I expect if we target using the text editor in this round we'll get some really rich feedback.
