### ISSUE TITLE
Styling of Element Components under 1200px

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1270]
The styling of the form element components does not wrap well with a screen width less than 1200px.

I'm not sure if this was caused by the merged styling or if it was always an issue.

 ![Screenshot 2022-11-15 at 1.51.23 PM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/8a7dfe2a-2dee-47a8-945c-1c6efc4bba18)

**Comment by timarney** [comment]
> I'm not sure if this was caused by the merged styling or if it was always an issue.

It was better at one point --- but yes there's been a bunch of little styling updates.

We'll get it fixed up.
