### ISSUE TITLE
Default confirmation element on edit page looks weird

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1271]
The element to add the confirmation page text has a really weird default state.

![Screenshot 2022-11-15 at 2.00.04 PM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/c09166a1-8ffa-44cb-9aa5-01a77cb9acbb)

**Comment by timarney** [comment]
@bryan-robitaille are you still seeing this issue -- believe a fix for this was merged

<img width="861" alt="Screen Shot 2022-11-16 at 9 31 02 AM" src="https://user-images.githubusercontent.com/62242/202207848-756ebb2c-38c4-4ea8-a355-6ce6e67039f0.png">

**Comment by dsamojlenko** [comment]
Fixed in #1267
