### ISSUE TITLE
Multiple Save buttons on 'share' path is confusing.

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1274]
Multiple save buttons with the same functionality seem redundant on the same page.

![Screenshot 2022-11-15 at 3.14.14 PM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/0c0e59a0-0c9e-4316-8703-5adc841fe09c)

**Comment by timarney** [comment]
@pcraig3 has been discussing these screens with design

**Comment by timarney** [comment]
Related: https://github.com/cds-snc/platform-forms-client/pull/1283

**Comment by pcraig3** [comment]
Yeah, I talked with @samsadasivan and @connorscarolyns on this, and this was the verdict:

When logged in:
- save button in header
- no save page
When logged out
- no save button in header
- save page

The confusion here is still valid, but the buttons actually do two separate things in this case.
- the one in the header saves a draft
- the one on the "share" page will download the file, which you can then share with someone else

I think the verdict was that we will leave it for now and see what happens in testing.

**Comment by samsadasivan** [comment]
![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/244e8eed-ebf3-4748-8431-89943c32905f)
Save moved to left side nav, sticky
