### ISSUE TITLE
Example hint text missing from pre-formatted email and phone elements

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1330]

**Comment by connorscarolyns** [comment]
When a user adds an email or phone field to the form builder, the field should be pre-formatted with a label and helper text to let users know how to correctly enter their data into the field. This should be prioritized accordingly as it creates usability issues for all end users.

**Comment by craigzour** [comment]
@connorscarolyns Could you give a visual example of what you would like to see exactly? Also, would a placeholder text inside the input field be enough?

**Comment by craigzour** [comment]
@connorscarolyns Nevermind! It appears to be already implemented. Can you confirm that in staging and close the ticket? (https://forms-staging.cdssandbox.xyz/en/form-builder/preview/273)

**Comment by craigzour** [comment]
We just discussed about the issue with @connorscarolyns and what we really want to add here is a default description when a user adds an email or phone input field through the form builder. The description would either be an email or a phone number depending on the input type.

**Comment by connorscarolyns** [comment]
Here are examples of the default descriptions I'd like to add:

These should only be defaults and not locked, users should be able to add or change them if they wish. 

![image](https://user-images.githubusercontent.com/53620052/205150873-7a9a9c90-57fc-41b3-98ff-a26d31435542.png)
