### ISSUE TITLE
Form-builder Toolbar accessibility issues (grouped)

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#1360]
Here are some issues in point form. I can add more detail if it would help:

- [x] Editor buttons should use ARIA-PRESSED=true state when active (WCAG 4.1.2)

- [ ] Editor needs function explanation, like a legend. Currently a user can easily get trapped in the editor (WCAG 2.1.2) - Nice to have

- [ ] Editor buttons need visual explanation, like keyboard/mouse tooltips (WCAG 2.1.4) - Nice to have

- [x] Editor should not override OS keys, e.g. ctrl+z not work 
(this one may be really tough, perhaps put off until later)

**Comment by timarney** [comment]
We can use 

https://lexical.dev/docs/packages/lexical-history for Undo / Redo functionality
