### ISSUE TITLE
Recommendation: BUTTONs for controls, ANCHORs for navigation

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#1361]
A WCAG recommendation, actually general accessibility recommendation, is to have BUTTONs for controls and ANCHORs for navigation. This makes the accessible name (whats read to the user) clear about what it does e.g. Button Click to enable thing.

Currently there is quite a variety of button and anchor usage in the app. For example the main GCForms text in the header is a button but should really be an anchor since it navigates. The Form-Builder main page has buttons that navigate to a URL so they should really be anchors.

### Acceptance criteria:
- [ ] Update existing anchors
- [ ] Buttons should preform an action
- [ ] Links should navigate
- [ ] Ensure design and development are aware of the patterns.

**Comment by samsadasivan** [comment]
Some ideas proposed for this card: 
![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/584f1980-1998-44c9-9cef-f58a28009491)

Sub/page navigation: Styled as tags or pills to emulate a state of the page. Example: Static preview vs Test response preview
