### ISSUE TITLE
After account is created, users are directed to the start page

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#1393]
When there are no draft forms or published forms under My forms, users would be directed to the "Start or Create new" page. 

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/e24c9970-d034-4161-993d-771f5e6b676d)

**Comment by timarney** [comment]
Noting with #1409 we have added a resume editing button --- which would allow the user to initiate moving back to the form editor.
