### ISSUE TITLE
Enhance JSON template validation

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1455]
### Context

Authenticated users:
- Can bypass publishing permissions by updating an existing Form Template with the ‘publishingStatus’ property set to ‘true’ and waiting for an application release.  Each application release, as part of the Prisma migration seed file, will iterate over Form Templates and use the value of ‘publishingStatus’ to overwrite the ‘isPublished’ field.  The ‘publishingStatus’ field is removed from the object to ensure the migration is only run once per form configuration however there is no parsing on a Form Template update or create action that explicitly stops the field from being readded.
**Impact**: Bypassing security controls and publishing a form without authorization.

- Can inject various properties into a Form Template on “api/templates”.  With further testing, it might be found that prototype pollution can be achieved to produce unexpected results when opening / loading a form.  At a minimum it allows an authenticated user a pathway to inject unsanitized input into the Database
**Impact**: Security risk / attack path

### Acceptance criteria
- [ ] Enhance json template validation and do not allow extra properties to be included.

**Comment by craigzour** [comment]
Concerning the "bypass publishing permissions" security issue. We planned on removing that piece of code once the migration will have happen in production. Also I just tried adding the old `publishingStatus` field to the JSON configuration and it cannot be done because of our JSON validation.

**Comment by bryan-robitaille** [comment]
@craigzour I'll test out the "bypassing publishing permissions" but the issue is that the JSON validation allows for ` "additionalProperties": true`.
By changing it to `false` and ensuring that all properties are included in the JSON Validation we should be able to close this potential attack path.

**Comment by bryan-robitaille** [comment]
Confirmed I can bypass publishing with adding the 'publishingStatus' property.

**Comment by craigzour** [comment]
> * publishingStatus

Yes so it is only possible because of https://github.com/cds-snc/platform-forms-client/blob/develop/prisma/seeds/seed.ts#L32 . Now that it ran in production we can remove it and also apply the other fix you mentioned with `"additionalProperties": true` set to false.
