### ISSUE TITLE
CSRF Tokens - Registration

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1459]
### Context
CSRF Tokens can be generated by calling ‘/api/auth/csrf’ and are valid for the lifetime of the session.

#### Issue
- Can repeatedly call the ‘registration’ API with fake users by sending requests with a CSRF Token.  The API will attempt to register the user and return the exact Cogntio error to the sender.

**Impact**

- 3rd Party service impact (Cognito user pool filled with unconfirmed / junk users and Notify emails for confirming users).
- Hitting the maximum number of emails with Notify service.  This impacts GCForms users as no Form Responses, Testing Data Delivery, User Registrations, or passwords will be able to be completed.
- If not caught in time the quota of 40,000,000 users could be hit and disable registration for legitimate GCForms users
- Clean up of Cognito user pool, very time consuming for CDS administrator

### Acceptance Criteria:
- [x] Request rate limiting set at 100 reqs / 5min

**Comment by bryan-robitaille** [comment]
Request rate set to 100 req/ 5 min in Production and Staging
