### ISSUE TITLE
CSRF Tokens - Resend Confirmation

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1460]
### Context
CSRF Tokens can be generated by calling ‘/api/auth/csrf’ and are valid for the lifetime of the session.

#### Issue
- Can repeatedly call the ‘signup/resendconfirmation’ API with fake users by sending requests with a CSRF Token.  The API will attempt to resend the confirmation code to the user and return the exact Cogntio error to the sender.

**Impact**

- 3rd Party service impact (Cognito user pool usage calls and Notify emails for confirming users).
- Hitting the maximum number of emails with Notify service.  This impacts GCForms users as no Form Responses, Testing Data Delivery, User Registrations, or passwords will be able to be completed.
- Significant costs due to usage of Lambdas, Cognito, and Notify to send messages to users

### Acceptance Criteria:
- [x] Request rate limiting set at 100 reqs / 5min

**Comment by bryan-robitaille** [comment]
Request rate set to 100 req/ 5 min in Production and Staging

**Comment by bryan-robitaille** [comment]
Request rate set to 100 req/ 5 min in Production and Staging
