### ISSUE TITLE
CSRF Tokens - Log API

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1461]
### Context
CSRF Tokens can be generated by calling ‘/api/auth/csrf’ and are valid for the lifetime of the session.

#### Issue
- Can stuff the ‘log’ API with fake events by sending requests with a CSRF Token.  The API will log the event in the application logs.

**Impact**

- 3rd Party service impact (AWS Cloudwatch logs filled with garbage entries).
- Searching logs for actual events will be extremely costly ( each log filtered has a cost)

### Acceptance Criteria:
- [ ] Request rate limiting set at 100 reqs / 5min

**Comment by bryan-robitaille** [comment]
Rate limiting already set at 100req / 5 min from a single IP
