### ISSUE TITLE
Issue pasting text into french text box

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1497]
Submitted through the diary study feedback on Jan 5, 2023, 11:48:14 AM

"I did find a bug though. I first created the EN form top to bottom before moving onto the FR copy. In my 4th section (text box), I wasn’t able to save my copy and pasted text. In fact, it looks like the FR copy jumped to the EN version, while the FR copy remains blank."

**Comment by Abi-Nada** [comment]
Issue referenced in [Ticket #1729](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/1729)
