### ISSUE TITLE
Allow users to select the type of question before populating it into the page. 

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1517]
The preselection of the single-choice elements confused users; they expected to be asked which type of question they wanted to use. This was more prominent when users wanted to add text to the page rather than a question.

Allow users to select the type of question before populating it into the page—potentially, dropdown selection type and then pop-up a modal with all the form field options.

**Comment by timarney** [comment]
This is on staging behind a feature flag

Some cleanup work happening here:
https://github.com/cds-snc/platform-forms-client/pull/1601

Once that is merged we'll need some folks to test and someone to "sign-off" to remove the feature flag and release the feature.

**Comment by timarney** [comment]
Needs review on staging for "sign-off" before we remove the feature flag.

**Comment by timarney** [comment]
Further updates here:

Based on some new design updates

https://github.com/cds-snc/platform-forms-client/pull/1615

**Comment by timarney** [comment]
All updates are on staging.

**Comment by Abi-Nada** [comment]
Need a review for accessibility -> might need some iteration
