### ISSUE TITLE
Let the fields titles and labels are entered into expand down to show all the text

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1518]
The form title was cut off when it was too long. Users were concerned that there was a limit they didn't know about or that they couldn't easily review the title for errors. They wanted to box to either expand or offer a scrollbar.

**Comment by Abi-Nada** [comment]
Issue no longer persists in staging.

**Comment by connorscarolyns** [comment]
This issue still exists in staging.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/53620052/225373457-4e88e13e-2844-4855-811c-6dbfd71025a7.png">

**Comment by Abi-Nada** [comment]
Oops, my apologies! I was looking at the Test functionality, didn't realize the issue pertains to the Edit page - I'll reopen the ticket :) ![Screen Shot 2023-03-15 at 1.44.46 PM.png](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/5d76cb02-13f8-4e5d-b9fe-bdcb6e80205f)

**Comment by connorscarolyns** [comment]
We want to improve this usability issue, it has come up in every round of usability testing so far.
It does not have to be for this release.

**Comment by timarney** [comment]
When we do make this update later ...this would be for Form Title input and Question inputs correct?

Pretty sure I saw an issue at one point where Question inputs were getting cut off and causing confusion.

**Comment by connorscarolyns** [comment]
Yes, the form's H1 title and question inputs are where people struggle with it the most.

**Comment by Abi-Nada** [comment]
^ Moving this ticket into the Product Backlog and prioritizing accordingly for a future release.

**Comment by connorscarolyns** [comment]
Yes, it's working great! Thank you so much!
