### ISSUE TITLE
Reintroduce the paste a list of options mode

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1528]
Bulk pasting was removed from MVP because there wasn't time to focus on crafting a better experience. Let's take a closer look at this feature and see how it might be reintroduced to the UI

Usability tests showed that users wished for a way to add and edit a list of items.

**Comment by samsadasivan** [comment]
Closing issue. Refer to: Edit/form builder cards: add list, edit description, add other, expand question field #2003
