### ISSUE TITLE
Make form sharing better

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1530]
Users expected to find a link they could share, not a file.

The decision was made to de-emphasize form sharing because downloading JSON files were too confusing for users. Let's take a look at how to do this better, and create a better solution for form sharing

**Comment by connorscarolyns** [comment]
Carolyn Connors
  9:30 AM
Hey question, I'm investigating what it might look like to share a form. Users expect to be able to share a link, we have identified risks with sharing links to unpublished forms. Could we brainstorm a set of circumstances we could define that would enable us to share links to unpublished forms?
9:32
For instance, what if we put a watermark in the background displaying the draft status, removed the FIP, and disabled submissions


Sarah Hobson
  10:16 AM
Hi! From a policy perspective, those interventions would reduce the risk. Another thing for future testing is whether there are sensitivities around a draft for being available on the public internet i.e. before launching a grants or contribution program.

**Comment by connorscarolyns** [comment]
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/35d274c1-ca8e-4f2c-a977-95c9d3283cf8)
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/a6a4d45a-4905-4ba2-bb30-506464df51b9)
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/3d8605c7-d6c7-416d-9393-221ac70b2ee9)
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/3e67f060-c8d2-489b-8bf2-3abec1020180)

**Comment by connorscarolyns** [comment]
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/b8985f09-863b-4d87-acd7-18e072b9b11c)

**Comment by connorscarolyns** [comment]
@timarney is looking deeper into the options for fly-out navigation, accessibility and other implementation considerations

**Comment by timarney** [comment]
Sharing for auth'd users is on staging behind a feature flag.

PR here to fix A bug.
https://github.com/cds-snc/platform-forms-client/pull/1605

A few more items to tackled based on current feedback

```
- The share button needs a dark grey hover state
- The focus state on the copy and links button should have white text
- Links should open in a new tab
```


@Abi-Nada we should create a fresh card for the unauth'd flow that we can pick up in the next sprint.

**Comment by timarney** [comment]
- Authenticated flow is done
- Non-Authenticated view to be done next week.

**Comment by Abi-Nada** [comment]
Thanks Tim! Card for unauthenticated flow created [here](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/1610)

**Comment by timarney** [comment]
> Non-Authenticated view to be done next week.

As per the "unauthenticated flow created" the unauthenticated flow  is on staging for review.

**Comment by connorscarolyns** [comment]
Can we make the email instructions populate the user's name? So when they copy instructions, it doesn't say, "[name] has shared a ..." but rather, "Carolyn Connors has shared a ..."

Also, for both auth & unauth, can we add a hover and focus state to the accordion button? Like:
![image](https://user-images.githubusercontent.com/53620052/219133259-a708da65-61c7-4d89-a173-74963ff15e14.png)

Also, this scroll bar appears when the modal is too long; is this the expected behaviour? 
![image](https://user-images.githubusercontent.com/53620052/219130151-e4a02815-a617-4090-88fb-6957594b0d4e.png)

**Comment by timarney** [comment]
> Can we make the email instructions populate the user's name? 

For auth'd I'm seeing:

<img width="500" alt="Screen Shot 2023-02-15 at 2 41 34 PM" src="https://user-images.githubusercontent.com/62242/219135731-487fb3a9-191e-48c9-8160-bd4efe3d1f30.png">


No auth - we can't because we don't know who the user is
<img width="500" alt="Screen Shot 2023-02-15 at 2 42 04 PM" src="https://user-images.githubusercontent.com/62242/219135873-4efca5c1-7fa7-484e-a612-8543fe90e115.png">

Are you seeing something different?

**Comment by connorscarolyns** [comment]
Nope, just me being stunned, Let's replace "name" with "A GC Forms user"

**Comment by timarney** [comment]
Todo:

- [ ] Replace "name" with "A GC Forms user"
- [ ] For both auth & unauth, can we add a hover and focus state to the accordion button? 

<img width="400" src="https://user-images.githubusercontent.com/62242/219138700-61f3d6e5-87df-4ab8-bbb7-2fb9a054acfb.png" />

- [ ] Add "inner scroll" for dialog content

**Comment by timarney** [comment]
PR added here:
https://github.com/cds-snc/platform-forms-client/pull/1636

**Comment by timarney** [comment]
@connorscarolyns 

These updates are all on staging if you want to take a look.

**Comment by connorscarolyns** [comment]
Looks great to me! Thank you so much.
