### ISSUE TITLE
Make the password requirements more easily identifiable.

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1532]
## Problem

In a previous round of testing:

Many users did not see the hint text for creating a password and it took more than 1 try to create an acceptable password. 4/6 people put in passwords that did not meet the requirements.

## Solution

Make the password requirements more easily identifiable. Potentially breaking them into bullets.

**Comment by anikbrazeau** [comment]
Working on this here: https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=694-39799&t=yRchStV7VlQ7LSU4-4

**Comment by anikbrazeau** [comment]
Proposed design, splitting password creation on a new page that would mirror the password reset, be more similar to Notify's "Create a password" pattern, and help reduce cognitive load for users:

![Screenshot 2023-05-16 at 3.37.33 PM.png](https://images.zenhubusercontent.com/612f6a0f0d148b7f2b0a72b2/8e3e697f-f055-4242-b05b-fc9900adfdfd)

![Screenshot 2023-05-16 at 3.37.42 PM.png](https://images.zenhubusercontent.com/612f6a0f0d148b7f2b0a72b2/efc6247c-2fd5-45fe-8e78-d08a723352c5)

![Screenshot 2023-05-16 at 3.37.58 PM.png](https://images.zenhubusercontent.com/612f6a0f0d148b7f2b0a72b2/01b31d2e-ecdf-4e2b-b5b3-9388a43cc5a3)

**Comment by anikbrazeau** [comment]
Related to https://github.com/cds-snc/platform-forms-client/issues/2129#issuecomment-1563406793
