### ISSUE TITLE
Sign-ups for trial - Migrate folks to production from CDS

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/platform-forms-client#1578]
### Acceptance criteria

- [x] Review CDS sign-ups on staging
- [x] Draft communications 
  - [x] They create an account in production
  - [x] Ask if they have any forms on production or staging
  - [x] Provide permission to publish
  - [x] Download a live form and republish for staging
  - [x] Assign user to the form for production
  - [x] Remove all permissions on staging
- [x] Send comms, get signed-up for prod, delete staging
- [x] Assign production forms to CDS owners

**Comment by Abi-Nada** [comment]
Just need to migrate over [Keenan's live form](https://forms-staging.cdssandbox.xyz/en/id/clcj97fo920948avrd01fr34l) to the prod environment, and then will remove his publishing permissions on staging.
