### ISSUE TITLE
Unauthenticated Share Modal

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1610]
### User Story:
As an unauthenticated end user of GC Forms, I would like the option to share my draft form without signing in.

![Screen Shot 2023-02-13 at 8.02.22 AM.png](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/bb87a3fb-1be6-444b-9fef-6648e352f1c2)

### Acceptance Criteria:
- [ ] Functionality is implemented

**Comment by timarney** [comment]
This is now on staging behind the feature flag for "sign-off" before release.
