### ISSUE TITLE
Exported Spreadsheet: Email field bug

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1633]
### Description

The email validation field appears with some jumbled text when exported as a spreadsheet from the translation view.

![image (3).png](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/e1fd5b05-c082-45f3-9c3d-e0a38188a4dd)

**Comment by timarney** [comment]
@dsamojlenko can you dig up the PR where this was fixed?

**Comment by dsamojlenko** [comment]
Fixed in https://github.com/cds-snc/platform-forms-client/pull/1656
