### ISSUE TITLE
Duplicated banner on Form Preview

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1648]
# Issue/opportunity

When previewing a form (empty? and signed out?) the banner indicating that users need to "Sign in to test how you can submit and view responses" seems to appear twice both at the top and bottom of the form preview. 

# Screenshot

<img width="1719" alt="Screenshot 2023-02-21 at 9 02 05 AM" src="https://user-images.githubusercontent.com/38330843/220374997-1f86fd57-e947-4595-8656-716c1ab2e087.png">

**Comment by dsamojlenko** [comment]
yeah, pretty sure this was deliberate as SRT notes, but checked latest designs and they don't have the dual placement, not sure if that's just an oversight.

**Comment by timarney** [comment]
Noting the message for response delivery also ends up here which is very important  

<img width="937" alt="Screen Shot 2023-03-30 at 10 02 02 AM" src="https://user-images.githubusercontent.com/62242/228861189-6c19848f-9d8e-4ca7-a9cf-54bcabd21438.png">


<img width="1007" alt="Screen Shot 2023-03-30 at 10 02 48 AM" src="https://user-images.githubusercontent.com/62242/228861557-9c0c7fb7-63fa-4bda-8f2b-cd8f8d7c4763.png">
