### ISSUE TITLE
Menu/Nav discrepancy in English and French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1651]
# Issue/opportunity

In staging, "My forms" appears in French nav but not in English?

https://forms-staging.cdssandbox.xyz/auth/policy
https://forms-staging.cdssandbox.xyz/fr/auth/policy

# Screenshots

![Screenshot 2023-02-21 at 2 52 04 PM](https://user-images.githubusercontent.com/38330843/220444870-10eb395b-57fa-4220-8247-c94a6862e4ef.png)

**Comment by Abi-Nada** [comment]
![Screen Shot 2023-03-26 at 6.43.43 PM.png](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/a384c99d-a80d-42a3-8844-2d2ba1a2851b)

Issue fixed (as per attached screenshot)
