### ISSUE TITLE
Menu alignment differences on "My Forms"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1652]
# Issue/opportunity

Sometimes sidebar menu is left-aligned, sometimes right-aligned.
Same goes for items in the top menu when spanning multiple lines, some are left-aligned, some are center-aligned.

# Screenshots 

![Screenshot 2023-02-21 at 2 59 57 PM](https://user-images.githubusercontent.com/38330843/220446247-050f5f4d-7bce-4f88-b281-c54c9315f64d.png)

![Screenshot 2023-02-21 at 4 02 10 PM](https://user-images.githubusercontent.com/38330843/220457848-c67e2bbf-9741-442a-bb98-90ab77b0960e.png)

**Comment by timarney** [comment]
> Sometimes sidebar menu is left-aligned, sometimes right-aligned.

The left nav part should have a fix on staging already --- @dsamojlenko looks like the top nav is still an issue.

**Comment by dsamojlenko** [comment]
Left nav fixed here: https://github.com/cds-snc/platform-forms-client/pull/1778
Top nav issue fixed here: https://github.com/cds-snc/platform-forms-client/pull/1784

**Comment by anikbrazeau** [comment]
Resolved! Thanks!
