### ISSUE TITLE
Content responsiveness in FormBuilder

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1654]
# Issue/opportunity

Overlapping text depending on window size make it challenging to read/decipher

# Screenshots

![Screenshot 2023-02-21 at 3 23 42 PM](https://user-images.githubusercontent.com/38330843/220451615-10496a88-172c-4c99-9fdc-b14639d6aebd.png)

**Comment by anikbrazeau** [comment]
Heading text is also sometimes obstructed by the "locked" block element

![Uploading Screenshot 2023-03-08 at 10.37.53 AM.png…]()

**Comment by Abi-Nada** [comment]
- Tablet is minimum screen size to design for

**Comment by Abi-Nada** [comment]
@connorscarolyns to design error messaging for when users try to adjust screen smaller than tablet size

**Comment by timarney** [comment]
@dsamojlenko has been working on responsiveness

Please confirm the above issues have been addressed + flag anymore that need to be taken care of.

**Comment by timarney** [comment]
@dsamojlenko has been working on responsiveness

Please confirm the above issues have been addressed + flag anymore that need to be taken care of.

**Comment by anikbrazeau** [comment]
This looks great and all the issues above seem resolved!
