### ISSUE TITLE
Selecting a "long answer block" from the modal, adds a short answer block

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1707]
# Issue/opportunity

Selecting "long answer question" will actually add a "short answer question" once you click "Select block" 

# Screenshots

![Screenshot 2023-03-08 at 10 29 45 AM](https://user-images.githubusercontent.com/38330843/223756478-7222f515-d4ff-42cf-b758-2d095f0236f0.png)

![Screenshot 2023-03-08 at 10 28 48 AM](https://user-images.githubusercontent.com/38330843/223756550-3a10e6e3-462d-4eeb-ac1c-f0bceb9ecaf7.png)

**Comment by timarney** [comment]
Thanks we'll get this fixed up.

CC: @dsamojlenko
