### ISSUE TITLE
AccessControl hook refactor

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1734]
The `useAccessControl` hook currently leverages the Next-Auth `getSession` function which causes a lot of chatter back and forth to `/api/auth/session`.
Refactor to possibly use `useSession` instead to use the value already stored in context in the React tree and figure out a refresh strategy.

https://next-auth.js.org/getting-started/client#usesession

https://github.com/cds-snc/platform-forms-client/blob/40809157a835db300c9b8e59f2e60e94e8959d59/lib/hooks/useAccessControl.tsx#L13

**Comment by timarney** [comment]
Related -- when there's a slow auth check we can end up seeing the UI change i.e.

![test](https://user-images.githubusercontent.com/62242/229810380-857e67da-372d-4ef3-ad75-da2a007fe841.gif)

**Comment by bryan-robitaille** [comment]
closed by #1850
