### ISSUE TITLE
Toast reappears when switching from Published to Draft after deleting a form.

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1762]
![toast bug delete form](https://user-images.githubusercontent.com/25329319/226421706-a8258ade-7e0f-4757-8cd7-5b5038d1a8a8.gif)

Acceptance Criteria:
- [ ] Toast should only appear once after the action and not reappear when navigating through the application.

**Comment by timarney** [comment]
The original issue posted here -- will no longer occur #1774 made an update so deleting a card will just delete / refresh the card display (no success message -- it's no really needed given the card disappearing should be enough of an indication that it was a success).

That said the issue could still occur for a failed delete.
