### ISSUE TITLE
Manual QA Testing

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1782]
### User Story

As a QA tester, I want to ensure the quality of our product by running a series of comprehensive tests on each new feature before it is released to the public, so that we can identify and fix any bugs or issues before they impact our users.

### Relevant Documentation:

- [Test scripts](https://docs.google.com/spreadsheets/d/1_9eZ5436OGbQQJUQLR2xC7J3HrwQ1S4g/edit#gid=1031544131)
- [QA Sprint Approach](https://docs.google.com/document/d/1lS_rAXrF4IcmdXXMrW7D46_O9V9jo0PyQdYQ2WDBc0Q/edit#)
- [Triaging Methodology for bugs (on page 3)](https://docs.google.com/document/d/1rqzafXy3I236vryBMBGPYojalSSxLSw8LC4pSRb8gW8/edit)

### In Progress still (work that is being developed)
- Retrieve data - Not yet ready. **DO NOT SEND FILES TO THE VAULT**
  - Confirmation
  - Retrieve a response
  - Submit a problem response - **not ready**
  - Confirm a response - **not ready** 

### Write Testing Script
- [x] Sign in @Abi-Nada 
  - Create an account
  - Sign in
  - Retrieve a password 
- [x] Design a Form @samsadasivan - write scripts
  - Branding request - @samsadasivan test
  - Repeating questions - @samsadasivan test
  - Add a block - @samsadasivan test
  - Groups of fields (Location, names, names, contact) - @samsadasivan test
  - Attestation block - @samsadasivan test
  - Set autocomplete in a short answer field
- [x] My Forms - @samsadasivan, write script
  - Links do what they say they do
  - File names are correct
- [x] Share a form - @samsadasivan , write script
  - Send email - @samsadasivan test
  - Instructions are clear
- [x] Published - @samsadasivan , write script
- [x] Support & Contact Us - @Abi-Nada , write script
  - Make sure that these go to their correct destinations
- [x] Service Level Agreement - @sarahhobson , write script
  - Make sure the link works - **Not ready**
- [x] [Terms and conditions](https://forms-staging.cdssandbox.xyz/en/auth/policy?referer=/admin) - @sarahhobson , write script
  - Make sure the content is correct

### To be tested
- [ ] Home page 
- [ ] Unauthenticated: end-to-end
- Authenticated: end-to-end
  - @sarahhobson testing on Desktop
    - [x] Chrome
    - [x] Firefox
    - [x] Safari
    - [x] Edge
  - @abi testing on Tablet
    - [x] Chrome
    - [x] Firefox
    - [x] Edge

### What we're testing:
- **Unit test** done by devs: Tests a small piece of functionality (Like, does the sign-in button work?).
- **Functionality testing** done by Support Team and our team: Tests a set of components (Like, does signing in work?)
- **Experience testing** done by our team: Does a set of components work together to achieve a goal? (Like, can I share my form draft with my manager so they can make an edit?)
- **Accessibility testing** done by Devs and Design: Manual accessibility testing using a screen reader, colour contrast checker, etc. Chrome, Firefox, and Edge - **No IE 11**. Desktops and tablets - **no mobile** (for client-facing screens)

### Acceptance Criteria:
- [ ] Dev to flag when currently underway functionality is ready to be tested.
- [ ] Create a detailed test plan for each new feature or update, including all relevant test cases and expected outcomes.
- [ ] Execute all tests using both desktops and tablets as appropriate.
- [ ] Document all issues and bugs found during testing within the top of the New Issues column, including steps to reproduce and any relevant screenshots or logs. **Be sure to include a "Bug" tag**.
- [ ] Work closely with the development team to ensure that all issues are resolved and all tests are re-run to verify that the fixes have been successful.
- [ ] Provide regular updates on the testing progress and any issues or concerns that arise during standup, so that the team can stay informed and make any necessary adjustments to the release plan.
- [ ] Ensure that all test cases are fully completed and signed off before the product is released to the public, in order to minimize the risk of bugs or issues impacting our users.

**Comment by samsadasivan** [comment]
Sam testing: 
Design a form 
- Repeating question 
- Grouped questions 
- Autocomplete 
- Saving drafts 

Sharing via email 

Publish
