### ISSUE TITLE
Placeholder for form name cut off

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1812]
In the form builder the text field for the form name seems to have a fixed max size.
The default placeholders are cut off.

![Screenshot 2023-03-30 at 11.49.03 AM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/f55e7ed6-5474-4436-807c-31a5982af7c8)

![Screenshot 2023-03-30 at 11.49.16 AM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/478ce9d8-f70c-4a4c-a9b4-67eb47389d24)

**Comment by dsamojlenko** [comment]
Should have been fixed in https://github.com/cds-snc/platform-forms-client/pull/1813

**Comment by Abi-Nada** [comment]
Issue fixed as per https://github.com/cds-snc/platform-forms-client/pull/1813
