### ISSUE TITLE
MyForms React Warning - unique key constraint

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#1820]
React Error on MyForms Page.
`Encountered two children with the same key, 'clfu2i6vc00007rqernj2wgcl'. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

![Screenshot 2023-03-30 at 5.35.22 PM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/48df1070-310d-46f4-97bb-d55cfcd2d181)

**Comment by timarney** [comment]
That should be fixed via:

https://github.com/cds-snc/platform-forms-client/pull/1817

**Comment by craigzour** [comment]
I tested it and can confirmed that the issue is fixed.
