### ISSUE TITLE
Pre-filled question text not populating in French

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#1830]
### Description
The pre-filled blocks in the French interface for **"Contact", "Name", and "Name (3 Fields)"** do not populate like they do in the English interface.

### English Interface
https://images.zenhubusercontent.com/315708034/e6c5895a-e732-4fa5-8e90-65c8e4c0d539/screen_recording_2023_04_03_at_9_07_40_am.mov

### French Interface
https://images.zenhubusercontent.com/315708034/70b65e53-8c4e-4d52-b4e8-9e63937316a5/screen_recording_2023_04_03_at_9_08_24_am.mov

### Acceptance Criteria:
- [ ] The pre-filled block for "Contact" in the French interface populates text upon being selected
- [ ] The pre-filled block for "Name" in the French interface populates text upon being selected
- [ ] The pre-filled block for "Name (3 fields)" in the French interface populates text upon being selected
- Might include other Blocks too, haven't tested them all out yet

**Comment by timarney** [comment]
Started a PR here:

https://github.com/cds-snc/platform-forms-client/pull/1833
