### ISSUE TITLE
Responses Confirmation/Report Modal error handling

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#1845]
The Modals have room for improvement, especially the error handling. Below is a comment from a related PR to help get this going.
Note that design should be included in any new error messages as they come up

> 4. Confirm receipt. I entered `c0c42c90-b816-49da-a69a-80bfd8ba15db`  - press confirm  receipt --- first press moves to entered a second code confirm  receipt again closes the dialog without telling me anything happened.
> 
> Checking the request I see an error happened
> 
> ```
> {"invalidConfirmationCodes":["c0c42c90-b816-49da-a69a-80bfd8ba15db"]}
> ```
> 
> 5. Input for more entries likely shouldn't show or at least now allow for inputting more when at the limit.
> 
> <img alt="Screen Shot 2023-04-04 at 8 35 15 AM" width="673" src="https://user-images.githubusercontent.com/62242/229793614-54e7da11-4675-44e6-8e87-0a87ce243adc.png">

**Comment by anikbrazeau** [comment]
Errors drafted here: https://www.figma.com/file/6QAmUEq6d8tyXzWDGKO78s/v2.-Form-builder?node-id=5346-72222&t=kGjpcC6a3fKfTnXU-4
