### ISSUE TITLE
Changing branding: Adding a "Save changes" button to let the user know they have made the change successfully

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#1849]
As a user, I want to know that the selection I have made, has been successfully changed to my form since I cannot preview it until I publish. 

Users currently cannot see their branding selection in the preview (something we could change, larger lift). For now, I was thinking we can add a "Save changes" button similar to the other pages under /Settings. ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/c3891712-9dbb-43dc-87cc-eb06e0ba24bc)

**Comment by timarney** [comment]
> For now, I was thinking we can add a "Save changes" button similar to the other pages under /Settings
 
 Yes I agree this the first step to make
