### ISSUE TITLE
Sharing: Via email not working?

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#1854]
This may be just me - will make a shout out in slack. I tried with two email addresses in french and english interfaces. It was working last week when I tested it so I feel like its on my side 

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/8f3d7071-c2aa-49ea-af23-927f6e6a2033)

**Comment by Abi-Nada** [comment]
Tested it out throughout the week and haven't run into any issues - closing as the error doesn't persist :)
