### ISSUE TITLE
Responses page for unauthenticated users: Remove the "Change settings" button at the top 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#1869]
The button to change the form settings still exits in the unauth path. Its not a show-stopper by any means, it just directs you to sign in. We could just remove it to lighten the cognitive load ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/5694daeb-d4a2-4b2b-b32a-807b489f24c7)

**Comment by samsadasivan** [comment]
Super minor - probably could leave it tbh

**Comment by timarney** [comment]
Responses and Publish (logged out) should also be updated to use the Card design ya?

<img width="1067" alt="Screen Shot 2023-04-06 at 12 29 19 PM" src="https://user-images.githubusercontent.com/62242/230440378-bc5800e5-aa36-418a-9642-3f44f44bc00b.png">

**Comment by timarney** [comment]
@craigzour you can grab code for the `Card` from `SettingsLoggedOut` --- mostly the same outside of text content.
