### ISSUE TITLE
Confirmation modal - confirm button 

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#1873]
When pasting a code into the confirmation modal I have to press the confirm receipt button twice to confirm the receipt

See:
https://www.youtube.com/watch?v=JEkTMdl01K8 (note video has sound so you can hear the clicks + you can see where I'm clicking as well)

Click 1
- Add a "newline" to the input

<img width="594" alt="Screen Shot 2023-04-06 at 12 59 10 PM" src="https://user-images.githubusercontent.com/62242/230446169-adb612f4-9dfa-47fa-a33a-82a033287d7c.png">

Click 2

Confirms + closes the modal (as expected)

<hr>

Expected 

- Paste the code 
- Press confirm once -- to confirm and close

**Comment by thiessenp-cds** [comment]
The problem with the behaviour described in this tiket is it would limit a user to only entering one code. The form should allow multiple codes, so keying enter must go down to the next line for another entry (and not submit).
I agree the current behaviour is not ideal where a user has to either key enter twice or tab to the confirm receipt button then key enter (or click it) to submit.
@connorscarolyns how do you feel about the current behaviour of how this dialog submits? any improvements/changes?

**Comment by connorscarolyns** [comment]
It looks like behaviour has changed with the newest release of download and sign-off. Confirmation codes are accepted when pasted in; you can paste them in bulk, but hitting enter does nothing; the user must click the button to submit. This is okay, but it would be better to allow submission on enter.

**Comment by Abi-Nada** [comment]
Issue no longer persists, as noted above ^
