### ISSUE TITLE
Test/Preview: Viewing new branding selection within the form

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#1875]
Based on issue: #1849, when a user selects a different branding option, they can know they have successfully made the change by saving it (#1849) and previewing in under the "Test/Preview" view. 

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/7821ffb8-6285-4509-833e-4218f6dfb0e5)

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/1326b82b-817a-4296-b485-ec2125a8049d)

[Figma file: PROPOSED/ Section: PREVIEW: Viewing new brand selection](https://www.figma.com/file/6QAmUEq6d8tyXzWDGKO78s/v2.-Form-builder?node-id=2351-11794)

**Comment by timarney** [comment]
@samsadasivan can we close this one?

**Comment by samsadasivan** [comment]
Yep!
