### ISSUE TITLE
Select block call to action requires scroll

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1886]
# Issue/opportunity

In French, the `Sélectionner ce bloc` / `Select block` button / CTA is burried and requires user to scroll to access. This could easily be missed and/or cause confusion.

# Screenshots

![Scroll for CTA](https://user-images.githubusercontent.com/38330843/231167110-b6753fc7-08b8-42f4-a019-12bf6e9c31b5.PNG)

# Test case

- 4.01 (Build + share a form) 
- Surface Tablet
- Microsoft Edge
- In French

**Comment by connorscarolyns** [comment]
There are new designs proposed that should help with the scroll issues by breaking the categories up into different tabs. 
[concept design: figma](https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=173%3A32183&mode=design&t=K8U1CDEluZdGj5CV-1)

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/b6e5debb-f214-4a5f-91b0-894be75c7e78)

**Comment by connorscarolyns** [comment]
This is fixed now
