### ISSUE TITLE
Editing field description not possible without entering 'More'

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1887]
# Issue/opportunity

Should it be possible to edit the description without entering the "More" modal? The description field seems unclickable/uneditable.

# Screenshots

![Edit description](https://user-images.githubusercontent.com/38330843/231167684-ac967cd9-d802-40b0-9ee2-946f7228d4eb.PNG)

# Test case

- 4.01 (Build + share a form) 
- Surface Tablet
- Microsoft Edge
- In French

**Comment by samsadasivan** [comment]
Closing issue. Refer to: Edit/form builder cards: add list, edit description, add other, expand question field #2003
