### ISSUE TITLE
Unable to save form

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1890]
# Issue/opportunity

When trying to save a form in English or French on Edge through Tablet, I was unable to save and got an error message that downloading failed. Once shared by email, the form could also not be opened. Possibly linked to #1899. 

# Screenshots

![Save failed](https://user-images.githubusercontent.com/38330843/231168923-80da95d6-f1c2-48b9-9ecc-671ea01108ad.PNG)

![Edge saving errror](https://user-images.githubusercontent.com/38330843/231170672-66a67a45-c2ed-4acf-9972-86d3bf39f9c2.PNG)

# Test case

- 4.01 (Build + share a form) 
- Surface Tablet
- Microsoft Edge
- In French

**Comment by timarney** [comment]
@Abi-Nada for this one need to confirm if the error exist for forms not using the repeated sets feature.

**Comment by anikbrazeau** [comment]
This seems to be resolved now.

**Comment by anikbrazeau** [comment]
# Steps to reproduce: 

On Edge, In French, to a form:
1. Add page text heading
2. Add Checkboxes
3. Add Contact
4. Add Name
5. Add Address
6. Remove the preferred language question
7. Keep email and phone number fields
8. Remove Address and Province fields
9. Change "City, town or community" to "City"
10. Keep City and Postal Code fields
11. Make all fields required
12. Attempt to save changes -- get error?
13. Go to test to see if order changed / changes maintain

**Comment by Abi-Nada** [comment]
Just wanted to confirm if we're good to close this issue?
