### ISSUE TITLE
Form file name cuts off

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1891]
# Issue/opportunity

Form title cuts off after ~20 characters. Likely need a longer display especially for French names which tend to be longer.

# Screenshots

![Form title cut off](https://user-images.githubusercontent.com/38330843/231169636-b9d585f8-0d22-4ba0-b5bf-c046db1c7602.PNG)

# Test case

- 4.01 (Build + share a form) 
- Surface Tablet
- Microsoft Edge
- In French

**Comment by Abi-Nada** [comment]
Closing this ticket as we already have one up in the Product Backlog :)
https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/1518
