### ISSUE TITLE
Missing button copy in 'Translate' for repeating set

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1895]
# Issue/opportunity

The content for the button "Add another X" does not appear in the Translate interface, even though it would require translation.

# Screenshots

![Missing button text](https://user-images.githubusercontent.com/38330843/231173169-ac73d1b2-87d6-4ca6-af1f-653cae5df924.PNG)

# Test case

- 4.01 (Build + share a form)
- Surface Tablet
- Microsoft Edge
- In French

**Comment by Abi-Nada** [comment]
Issue no longer persists
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklBQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ae8297ac39f73e35c289d9c34ea2297e84c4e2d/Screenshot%202024-12-03%20at%201.19.51%E2%80%AFPM.png" alt="Screenshot 2024-12-03 at 1.19.51 PM.png" />
