### ISSUE TITLE
Style inconsistency

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1896]
# Issue/opportunity

Type and font style changes when signing out.

# Screenshots

![Styles](https://user-images.githubusercontent.com/38330843/231173863-97a2b1cf-6f6c-4c12-afc8-d4b0fb186466.PNG)

# Test case

- 4.01 (Build + share a form)
- Surface Tablet
- Microsoft Edge
- In French

**Comment by Abi-Nada** [comment]
Closing this issue, as [a fix has been pushed](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/2056) :)
