### ISSUE TITLE
Multiple scrolls could be difficult to navigate

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1897]
# Issue/opportunity

Users are faced with three vertical scroll bars to navigate when adding a block to a form. We might consider making the right pane with the preview/example static to help users focus on scrolling only for the block types?

Linked to #1886 

# Screenshots

![Scroll bars](https://user-images.githubusercontent.com/38330843/231174737-12eb09ac-6abc-4378-8f8d-03763a487ddd.PNG)

# Test case

- 4.01 (Build + share a form)
- Surface Tablet
- Microsoft Edge
- In French

**Comment by Abi-Nada** [comment]
Since it's the same issue as #[1886](https://github.com/cds-snc/platform-forms-client/issues/1886) ,  let's close this one out. But feel free to re-open if you think it should stay :)
