### ISSUE TITLE
Focus on error states - creating an account

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1898]
# Issue/opportunity

When error is encountered, relevant summary/field are not in focus.

# Screenshots

![Error focus à](https://user-images.githubusercontent.com/38330843/231175444-f2706b64-b631-4f88-89f7-1f69341afca0.PNG)

# Test case

- 4.01 (Build + share a form)
- Surface Tablet
- Microsoft Edge
- In French

**Comment by thiessenp-cds** [comment]
@samsadasivan @srtalbot Any thoughts on the below? Agree/disagree, improvements? (sorry it's kind of lengthy/wordy :)

Some initial thoughts from testing locally. 

My current plan is to only modify the how server Server errors are displayed. So for these, when a server error occurs, move focus to the top list (just as Tim described in the ticket). Also, when an existing server is displayed but a new Client error occurs, to replace the top server error with the new error.  
-OR- 
Would it be better to keep the top server error behaviour as is and force a user to click the X close button before updating it with any new errors?

Some background:
 - The case for Client (Front-End/Browser) errors: they are handled inline below the form fields and redundantly displayed in the top error list. So arguably no need to interrupt and move the users focus away from the input the user is working on. IMO
 - The case for Server errors: the error is displayed only in the top error list and could easily be missed by a user.  A close button is also shown in the error list. There is no close button for Client side errors. Is it needed? (future thought :)
 - Other parts of the app don't follow the above pattern and each is a little custom. The download table for example displays an error both at the bottom and top of the table. So the app forms/inputs don't need to be updated. *UNLESS* we want a GCForms wide error handling refactoring.

Attaching a screenshot of both cases.

For reference the related pages I can think of are:
-/login
-/register
-/form-builder/support


Client Error
![Screenshot 2023-05-08 at 3 28 07 PM](https://user-images.githubusercontent.com/107579368/236921558-39f37f2b-070e-4c73-a048-ea1cd1f49051.png)

Server Error
![Screenshot 2023-05-08 at 3 31 27 PM](https://user-images.githubusercontent.com/107579368/236921580-0539d7c6-454c-4e08-98ed-98edca500170.png)

App Custom Form Input Error
![Screenshot 2023-05-08 at 2 53 40 PM](https://user-images.githubusercontent.com/107579368/236922023-4bec7195-a0d6-4ee6-a32e-c35ea1ee9095.png)

**Comment by timarney** [comment]
RE: server error

> There is no close button for Client side errors. Is it needed? (future thought **:)**

https://github.com/cds-snc/platform-forms-client/issues/2053#issuecomment-1539016113c
