### ISSUE TITLE
Unable to open form file

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1899]
# Issue/opportunity

Unable to open JSON form that would not save. Linked to #1890 

# Screenshots

<img width="1546" alt="Screenshot 2023-04-06 at 4 57 09 PM" src="https://user-images.githubusercontent.com/38330843/231177230-40d625d5-62e8-4ce6-9fc0-d501f87360c3.png">

![image (1)](https://user-images.githubusercontent.com/38330843/231177442-856f2b8b-beaf-484e-95b0-e95fd181226a.png)

# Test case

- 4.01 (Build + share a form)
- Surface Tablet
- Microsoft Edge
- In French

**Comment by anikbrazeau** [comment]
@timarney This was the error when building the lemonade stand form in French. I'll Slack you the exact JSON file I was able to share by email.

**Comment by anikbrazeau** [comment]
I don't think it ever saved so don't think there's a form ID. 

I'll try to recreate it this afternoon and see if it happens again or if it was a repeating set bug.

**Comment by Abi-Nada** [comment]
@anikbrazeau to retest and confirm if error persists - if not, we can go ahead and close this card.
