### ISSUE TITLE
Remove the word "block" from the add button

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1905]
**Issue identified in usability testing**

Does the “select block” button do what’s expected?
- The word "block was problematic; most users found it unfamiliar,
- some users associated it with technical language,
- some participants hesitated to click on it because they were unsure what to do

**For this release, we'd like to remove the word "Block" from the "Add" button.** 

The word can remain within the add modal and any other place it appears. Further changes will come within future iterations.

@anikbrazeau can you confirm what the French copy should be?

**Comment by anikbrazeau** [comment]
If we're simply removing block from the button, it would be:

**EN:** `Add`
**FR:** `Ajouter`
