### ISSUE TITLE
Branding request page: French and English copy do not match

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1958]
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/554554bd-5dfa-4d40-bd7c-cb803b91ceb0)

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/329635e0-7395-473c-bdb3-4d429f99d8ac)

**Comment by anikbrazeau** [comment]
Updated copy indicated in pink in Figma here: https://www.figma.com/file/6QAmUEq6d8tyXzWDGKO78s/v2.-Form-builder?node-id=5511-68988&t=wdIZbuK8dv69sg3y-4

**Comment by anikbrazeau** [comment]
This has been fixed! Updated in prod.
