### ISSUE TITLE
Sharing fresh form will fail because name is not set

### ISSUE THREAD

**Issue by craigzour** [cds-snc/platform-forms-client#1965]
Sharing a freshly created form without a set name will result in a failure.

The share API will return a `res.status(400).json({ error: "Malformed request" });` if the `filename` is empty in the request payload.
````
const filename = name ? name : i18n.language === "fr" ? form.titleFr : form.titleEn;
````

@connorscarolyns @samsadasivan Should the share feature be deactivated until the form has a name at least?

**Comment by timarney** [comment]
```javascript
if (!emails || !form || !filename) {
      return res.status(400).json({ error: "Malformed request" });
    }
    ```

@craigzour is there any validation of the form data or just looks at least {}

**Comment by craigzour** [comment]
> ```js
> if (!emails || !form || !filename) {
>       return res.status(400).json({ error: "Malformed request" });
>     }
> ```
> 
> @craigzour is there any validation of the form data or just looks at least {}

There is no validation of the form data. The `form` information should just be a string that is not empty. That string is then encoded in base64 and sent as an attached file through GC Notify.
