### ISSUE TITLE
Usability improvements to add question modal

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#1983]
Several non-critical issues were identified with the usability of the add question modal. 

- Users looked for guidance and explanations on each of the options
- Users tried to click on the examples to see how they worked
- The add button was located off the screen, and users had to scroll to find it
- The list of options was long, and the categories of questions were difficult to parse

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/92c01a7e-a496-4442-848a-32119a184b3e)

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/2459cb1e-350e-4c29-a071-85c198d999b4)

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/321d4f4c-7f8d-421d-b2db-90eae5645d77)

If this is helpful, some exploration in code was done to establish styles and structure:
https://connorscarolyns.github.io/sandbox/modal-experiment/

**Comment by connorscarolyns** [comment]
@dsamojlenko @Abi-Nada This is one I'd like to propose for usability improvements.

**Comment by Abi-Nada** [comment]
Copy to be finalized by Monday/Tuesday
