### ISSUE TITLE
Pre-formatted form blocks/questions

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1986]
# Issue/opportunity

Some form blocks insert pre-populated with the question, others do not. 

For example: the date does not show up as the pre-populated question/label (~Date~) even though it is preformatted with the description for `Enter a date. For example: mm/dd/yyyy`?

# Screenshots
<img width="1040" alt="Screenshot 2023-04-25 at 12 13 45 PM" src="https://user-images.githubusercontent.com/38330843/234339591-4f1fac17-3566-4f12-93db-d3dc5de2f15f.png">

<img width="1068" alt="Screenshot 2023-04-25 at 12 16 47 PM" src="https://user-images.githubusercontent.com/38330843/234339603-bd490c32-5110-4644-a1a7-b3e4629992e4.png">

# More details

- Macbook
- Google Chrome
- English

**Comment by connorscarolyns** [comment]
This will be fixed with the release of #1983

**Comment by anikbrazeau** [comment]
This is not fixed yet. Would require new files in "form-builder-templates"

<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRMQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26551d566b1fe208c6e54d046657969cc1ee83dc/Screenshot%202024-01-29%20at%204.29.13%E2%80%AFPM.png" alt="Screenshot 2024-01-29 at 4.29.13 PM.png" />

**Comment by anikbrazeau** [comment]
This issue is no longer relevant
