### ISSUE TITLE
Missing Translation: "Adresse" in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1993]
# Issue/opportunity

Missing translation string for "Address" (EN) in form builder menu. Does not seem to exist in JSON file.

In French, it should be `Adresse`

# Screenshots
<img width="730" alt="Screenshot 2023-04-25 at 5 17 34 PM" src="https://user-images.githubusercontent.com/38330843/234406359-6a7bedfb-5e49-4794-a852-a7a22ca017ef.png">

_Found on: Staging, Mac, Chrome, Signed out, French interface_

**Comment by anikbrazeau** [comment]
Was not able to fix this issue myself. Think this might need dev.

**Comment by thiessenp-cds** [comment]
@anikbrazeau or @samsadasivan are you able to find this in Figma (for translations). I can't seem to find it :)

**Comment by anikbrazeau** [comment]
I'm not sure where it is in Figma. Perhaps [this is related](https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=173-32183&mode=design&t=GEljOv0FnQqyPW8b-4) (but it's still an exploration and a bit ahead of what's in prod right now). 

**I think simply switching "Address" to "Adresse" in French would suffice for this ticket to be resolved.**
