### ISSUE TITLE
Set subject line not appearing on response settings page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#1996]
# Issue/opportunity

Subject line does not appear on Responses page (for email response settings) even when set.

`Subject line will appear as:`
`La ligne d'objet apparaîtra comme :`

# Screenshots

![Screenshot 2023-04-26 at 12 14 09 PM](https://user-images.githubusercontent.com/38330843/234638519-399eac6b-1c2e-4c6a-9a5e-a51252d3f32b.png)
![Screenshot 2023-04-26 at 12 14 17 PM](https://user-images.githubusercontent.com/38330843/234638549-5a77f34b-287c-4116-9f3b-831e0b9fd233.png)

_Found on: Staging, Mac, Chrome, Signed in, English and French_

**Comment by Abi-Nada** [comment]
Issue no longer persists in staging.

![Screenshot 2023-05-02 at 8.39.32 AM.png](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/b6adb4ef-d10c-42e5-8d59-34ea5d672eeb)
