### ISSUE TITLE
Accessing English site with Chrome browser set to French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2006]
# Issue/opportunity

When Chrome browser/profile language is set to French, cannot seem to access site by clicking on English from `https://forms-staging.cdssandbox.xyz`

Getting this screen:

![Screenshot 2023-04-28 at 9 56 13 AM](https://user-images.githubusercontent.com/38330843/235168112-b1d01c4d-8234-43d1-90b0-e1496e43aca5.png)

![Screenshot 2023-04-28 at 10 01 02 AM](https://user-images.githubusercontent.com/38330843/235168643-e3def0b2-457d-4a94-bb03-fb78bd3292f9.png)

![Screenshot 2023-04-28 at 10 02 21 AM](https://user-images.githubusercontent.com/38330843/235168975-be3040bc-d055-40ab-a3e2-531e925b904a.png)

_Identified on: Staging and Production, Mac, Chrome_

**Comment by timarney** [comment]
Looks like /fr/en ends up in the url so the page will for sure break -- will need to look at why that's happening.
