### ISSUE TITLE
Description misaligned with Form Question

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2017]
### Description:

User feedback from Jo Button @ CDS:
When I moved a question further down the survey and tried to edit its description using the “more” function, the field boxes it showed me were for a different question (I think it showed for the original order I created questions in). I guessed that’s what it did and edited the correct field by clicking on a different question’s “more” function – but if others run into this they may not find that workaround!

For context, this happened when I wasn’t signed in, so maybe it’s not an issue then. I was playing around with the design a form tool linked to website.

### Recreated Issue

Persists in staging
https://images.zenhubusercontent.com/315708034/b8acb39b-0978-4983-9c1e-d03acbe5b7bd/screen_recording_2023_05_02_at_9_07_17_am.mov

**Comment by timarney** [comment]
@Abi-Nada a fix for this bug has been merged and is now on staging ready testing.

https://forms-staging.cdssandbox.xyz/form-builder/edit

**Comment by Abi-Nada** [comment]
Tested in staging and the issue no longer persists. Thanks Tim!
