### ISSUE TITLE
Update content on notification that goes to manager when publishing is unlocked

### ISSUE THREAD

**Issue by sarahhobson** [cds-snc/platform-forms-client#2028]
https://gcdigital.slack.com/archives/C03T4FAE9FV/p1683125349373259

https://www.figma.com/file/6QAmUEq6d8tyXzWDGKO78s/v2.-Form-builder?type=design&node-id=5624%3A69415&t=vhAyPPN1ghYloqVF-1

**Comment by sarahhobson** [comment]
![Screenshot 2023-05-03 at 10.45.03 AM.png](https://images.zenhubusercontent.com/60e864dc52a1304c931f9256/88b5ccc8-fbe2-4654-87c1-165541f65ee8)

**Comment by sarahhobson** [comment]
Need to update the content to refer to and link to the Terms of Use and not Service-level Agreement.

**Comment by sarahhobson** [comment]
Also could we check where all the links go?

**Comment by anikbrazeau** [comment]
**Here is [new proposed content](https://www.figma.com/file/6QAmUEq6d8tyXzWDGKO78s/v2.-Form-builder?type=design&node-id=5627-69392&t=7s64mWC0Kj7gsvMo-4):**

> - revising bilingual content
> - addressing user and manager in one notification
> - updating to include Terms of use rather than Service-level agreement
> - clarifying subject line to reflect accurate situation

<img width="910" alt="Screenshot 2023-05-04 at 10 23 02 AM" src="https://user-images.githubusercontent.com/38330843/236237357-a72fbe71-76d5-4c16-af0c-691855c83066.png">

**Comment by anikbrazeau** [comment]
Content tweaked and shared with Jimmy to implement: https://docs.google.com/document/d/1-r_8TgShQGVM1DEtvTHzHk1DuDfqFg4jzvvkzP7YUR8/edit#

**Comment by anikbrazeau** [comment]
Implemented! :)
