### ISSUE TITLE
Responses Download "allow multiple file" browser prompt confusing some users

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#2039]
Some users (especially non technical) are struggling with the responses multiple file download. When a user selects multiple responses to download at once, the browser will prompt them to "allow multiple files..".  The prompt leaves users uncertain what to do.

One solution would be to add some help text/* in the responses page to help guide users through this.

**Comment by connorscarolyns** [comment]
Just spit-balling here; what about the option to zip the files into one file before downloading?

**Comment by anikbrazeau** [comment]
Related to #2954

**Comment by connorscarolyns** [comment]
I believe this is mostly resolved now. I recommend closing this ticket and reopen it when we have more evidence that this issue persists.

**Comment by Abi-Nada** [comment]
Closing as per input above :) ^
