### ISSUE TITLE
Error with valid password requirements

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2095]
### Description

Password must be at least 8 characters with a capital letter, number, and symbol.

It accepted this password: [A-Z]\d{9}[a-z][!@#$%^&*()]

However, the user tried to input the following password and received an error (**it was not able to recognize the ")" symbol**) : F062293504l)

**Comment by craigzour** [comment]
@Abi-Nada Was able to reproduce the problem. Going to investigate. You can ignore my previous message ;)

**Comment by craigzour** [comment]
Looks like the problem comes from the list of symbols the code allows. Right now we have `#?!@$%^&*-`. Will look into what symbols are usually allowed in passwords and make a pull request to adjust our own list.
