### ISSUE TITLE
useAuth hook refactor for 2FA

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#2102]
The current useAuth hook is leveraged as a single lib import at the component level within a page.  In order to reduce duplication of actions and ensuring fluidity of the login flow we may want to look at creating State higher up in NextJS rendering tree that can hold the current step of the login and any error messages.

- We'll need to decide as part of this work if we want to break up the different login screens over different url paths or on the same path but rendering different components based on the login state.
- The error messages returning from the API on sign-in/registration/2fa will change.  Currently unfiltered Cognito errors are being passed back to the client.  From a security perspective these errors should all be sanitized to provide the base amount of info necessary to display the correct error and set state on the client.
- Testing the error flow and login locally will be difficult.  More then likely developers will need to set temporary AWS credentials in their .env file for staging to be able to connect to and interact with the Staging Cognito instance.
- Collaborate with developers working on the app server side to verify API endpoints for registration, password reset, etc. as they may change.

**Comment by timarney** [comment]
Screen ref: https://github.com/cds-snc/platform-forms-client/issues/2043#issuecomment-1542711818
