### ISSUE TITLE
Response page: "1 files" "1 responses"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2116]
# Issue/opportunity

Singular files/responses are written in plural form:
`Downloading 1 files`
`Download 1 selected responses`

Related to #1826 

# Screenshots

<img width="401" alt="Screenshot 2023-05-15 at 1 21 40 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/0e0ab9d6-2d65-4174-9fb3-48883ead8368">

<img width="368" alt="Screenshot 2023-05-15 at 1 21 32 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/e1a21808-d223-4db6-a528-f2c3abc7cdb5">

_Found on: Staging, Mac, Chrome_

**Comment by anikbrazeau** [comment]
Related to #2039

**Comment by connorscarolyns** [comment]
This is no longer an issue, the button does not indicate numbers. But it should be noted that there are still other places where this issue persists.
