### ISSUE TITLE
2FA Screens: Create an account

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#2129]
Implement the new design for "Create an account". [Figma Design here](https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=271-33265&t=CeaNCBYMxwlmUMCE-0)

Tasks for this card
- [x] Add translation keys
- [x] Refactor/Add screens
- [x] Refactor/Add error handling
- [x] Do some basic accessibility and "multi-screen" testing

**Comment by anikbrazeau** [comment]
If it's possible to do the breakdown with bullets in hint text that's awesome! 🥳 
If it's not possible with our current tech constraints (the impression I was under), we can keep the hint as is! 👍

**Comment by samsadasivan** [comment]
Working on a loading screen just in case

**Comment by thiessenp-cds** [comment]
The "send new code" feature will need to be updated with error handling etc. and other minor fixes but I'm thinking these can be done in another PR/task
