### ISSUE TITLE
2FA Screens: Reset password

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#2131]
Implement the new design for "Reset Password" - [Figma Design here](https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=271-33265&t=CeaNCBYMxwlmUMCE-0). 

Tasks
- [ ] Add translation keys
- [ ] Refactor/Add screens
- [ ] Refactor/Add error handling
- [ ] Do some basic accessibility and "multi-screen" testing
- [ ] look for ways to simplify the code

**Comment by timarney** [comment]
@samsadasivan can you update or validate the link to the screens works

 I now only see:
<img width="734" alt="Screenshot 2023-06-07 at 9 14 12 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/a2a02377-e5e3-4375-9028-5df0a1203ffb">

**Comment by timarney** [comment]
@thiessenp-cds thinking we should replace this issue with 

https://github.com/cds-snc/platform-forms-client/issues/2401
