### ISSUE TITLE
Missing info message

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2136]
There is a missing string of content on the Branding page:
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/be831d20-e6f3-49d0-98e5-d19cd4d1913a)

**Comment by anikbrazeau** [comment]
Related to #2121

**Comment by Abi-Nada** [comment]
^ Closing this card, as it's a duplicate of #[2121](https://github.com/cds-snc/platform-forms-client/issues/2121)
