### ISSUE TITLE
Confirmation option available with no responses

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2142]
# Issue/opportunity

"Confirm receipt" shows up in the empty state, when there are no responses yet.
This is confusing as an option/modal as there is nothing that can possibly be confirmed at this point. 

# Screenshots

<img width="1143" alt="Screenshot 2023-05-19 at 3 41 11 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/3ca7c5cb-da9a-4b41-b5c8-e58d63e7d7e6">

_Found on: Staging, Mac, Chrome_

**Comment by connorscarolyns** [comment]
This is no longer an issue.
