### ISSUE TITLE
Language toggle on HTML responses

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2143]
# Issue/opportunity

HTML responses language link skips the data classification and GoC header content. Link to top of response section for each language.

# Screenshots

## Currently

<img width="1651" alt="Screenshot 2023-05-19 at 4 07 26 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/d578a7fa-c98d-4937-bca0-334793d3609a">

<img width="1566" alt="Screenshot 2023-05-19 at 4 07 37 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/235e4230-1377-4242-bd79-f10735629259">

## Ideally

<img width="1631" alt="Screenshot 2023-05-19 at 4 07 44 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/257f23df-6edd-43bf-9ba2-e63206bbd827">

_Found on: Staging, Mac, Chrome_

**Comment by connorscarolyns** [comment]
We could move the classification banner to just below the h1. It's more contextual there, anyway.

**Comment by connorscarolyns** [comment]
New designs with download and confirm should fix this issue. Confirm in the new year.

<img width="791" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fe9ca259f17d3d28720b2f607da250a314739f7/image.png" alt="image.png" />

<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cedbb23fa5030baa9e35334a272d4646ec01a6c1/image.png" alt="image.png" />
