### ISSUE TITLE
Emphasizing the responses with actions to be taken

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2235]
# Issue / opportunity

**Future Enhancement** 
It might be easy to miss the actions that need to be taken on the response page. There are countdowns that begin to ensure responses are downloaded and confirmed but these can become buried with several incoming responses. We might consider different ways to emphasize what needs to be done and which responses require attention, to mitigate the risk of escalation.

# Screenshot

![Screenshot 2023-06-08 at 1 31 34 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/a6590ab5-416f-447c-8f53-4a56feca66db)

![Screenshot 2023-06-08 at 1 31 28 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/23fe4431-e5e6-4b0d-8418-8c23a049db59)

# Potential solutions
- Bolding the "Within 15 days" text
- Highlighting the row somehow
- Adding the steps 
- Grouping / sorting by pending action
- Flagging somehow
- Considering making actions more explicit

**Comment by connorscarolyns** [comment]
This was addressed in the new download UI reslease
