### ISSUE TITLE
2FA - Bullet pasted in when copying code from email

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2251]
# Issue / Opportunity

Consider removing the bullet to avoid having to alter the security/verification code when copy-pasting.

# Screenshots

![bullet](https://github.com/cds-snc/platform-forms-client/assets/38330843/1d98e740-2041-4fc3-9fa5-a763015b6675)
![Brandingà](https://github.com/cds-snc/platform-forms-client/assets/38330843/c2113e1d-c607-4bc0-8440-e1108b3e1e49)

_Found on: Tablet, Edge, English_

**Comment by anikbrazeau** [comment]
Maybe it's more of an Outlook issue? 

Wondering do we have a strong need for the bullet?

**Comment by timarney** [comment]
>  do we have a strong need for the bullet?

Good point I would vote to remove it.

**Comment by timarney** [comment]
Created a PR to remove
