### ISSUE TITLE
Testing sign in flows with 2FA in staging

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2252]
# Testing scripts

https://docs.google.com/spreadsheets/d/1_9eZ5436OGbQQJUQLR2xC7J3HrwQ1S4g/edit#gid=156837428

- 3.01 Create an account
- 3.02 Sign in
- 3.03 Reset password

# Testers

**Team Tablet - Edge, Chrome**

- [x] Anik (EN/FR)
- [x] Abi (EN)
- [ ] Stevie-Ray (Support on reproducing bugs for tickets)

**Team Desktop - Safari, Chrome**

- [x] Carolyn (EN)
- [x] Sarah (EN/FR)
- [ ] Stevie-Ray (Support on reproducing bugs for tickets)

**Comment by Abi-Nada** [comment]
Closing as testing has been completed.
