### ISSUE TITLE
2FA - Shorter input label for security/verification code

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2253]
Related to #2250 

# Issue / Opportunity 

Shorten input label to make the page more clear and navigable:

Rather than a whole sentence, simply "Verification code" or "Security code" will do.

**EN** = Verification code
**FR** = Code de vérification

OR

**EN** = Security code
**FR** = Code de sécurité

# Screenshot

<img width="508" alt="Screenshot 2023-06-09 at 3 43 21 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/53e2f414-8f66-4fee-85b5-d86c77cf241f">

**Comment by craigzour** [comment]
After talking with @anikbrazeau it appears that this is not a problem anymore. UI got updated after the ticket was created.
