### ISSUE TITLE
2FA - Toast in English only

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2254]
# Issue / Opportunity

Missing confirmation feedback in French, shows up in English only.

**EN** = New code sent
**FR** = Un nouveau code a été envoyé

![Code resent](https://github.com/cds-snc/platform-forms-client/assets/38330843/82905726-8c7f-486e-965a-1031ae6f76b8)

_Found on: Tablet, Edge, French_

**Comment by timarney** [comment]
PR is up for the fix just need the translated string.
