### ISSUE TITLE
2FA: No redirection to "Sign In" after getting locked out from incorrect verification codes

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2271]
- [Slack Thread](https://gcdigital.slack.com/archives/C01K40T8K5L/p1686666092726439?thread_ts=1686665214.625749&cid=C01K40T8K5L)

### Description

When I input too many wrong verification codes, I run into an error message but it doesn't redirect me back to login after I'm locked out. I'm still able to click "Send new code" but it doesn't do anything. Impact is that it might be really confusing for the user.

This is a janky video of it happening (can't screen record on my tablet so I got ✨creative✨:

https://images.zenhubusercontent.com/315708034/a6b0416f-b52e-4a03-8351-9c82b542865a/352589019_5841700295935483_7227741041895112772_n.mp4

**Comment by anikbrazeau** [comment]
Related to #2244

**Comment by Abi-Nada** [comment]
^^ Oops! Will be closing this ticket as a duplicate. Thanks for flagging!
