### ISSUE TITLE
HTML download file: columns misaligned

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2272]
The columns don't line up, making it hard to read answers easily:
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/62b6300f-2a83-4316-85c1-b6f02117f46d)

**Comment by anikbrazeau** [comment]
Related: #2110

**Comment by Abi-Nada** [comment]
Closing as a duplicate of #[2110](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/2110)
