### ISSUE TITLE
User Deactivation Process Table-Top Exercise

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2299]
### Description

This table-top exercise aims to simulate the process of deactivating a user in GC Forms (for a user who has an unconfirmed form response for over 60 days). The exercise will involve Support, Policy, and Product, with Design leading the session. The objective is to collaboratively go through, discuss and get comfortable with running through the user deactivation process, ensuring a smooth and secure experience for our clients.

### Acceptance Criteria:

- [x] Test account/scenario is set up for the table-top exercise
- [x] The existing user deactivation process is discussed and analyzed to gain a comprehensive understanding
- [x] Support understands exactly **what steps** _they_ need to do when a user detactivation is flagged
- [x] Key pain points, challenges, and potential risks associated with the current workflow are identified and documented, providing a foundation for improvement discussions when work starts on O3.

**Comment by Abi-Nada** [comment]
Table top exercise scheduled for Thursday, July 27

**Comment by anikbrazeau** [comment]
https://miro.com/app/board/uXjVM2sNUkQ=/
