### ISSUE TITLE
Test Scripts Creation

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2307]
### Description

For the third week of our Sprint, we'll need to have Test scripts created for:

### Acceptance Critiera:

- [x] Deactivating a user, Managing permissions
- [ ] (Updating) Reset a password, Return user (display security questions), Edit security questions

**Comment by samsadasivan** [comment]
✅ 
Deactivate a user, 
Managing permissions, 
Reset password (for PBMM), 
Return user 

🟡 
Edit security questions 

Notes: 
- Password reset flows may change based on implementation
- Will write the "Edit security question" flows after implementation to make sure I did not miss any error states with the redesign
