### ISSUE TITLE
Guidance on downloading and confirming responses

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2323]
Context: https://gcdigital.slack.com/archives/C03T4FAE9FV/p1687449133343749

Editing in Freshdesk: https://cds-snc.freshdesk.com/a/solutions/articles/61000307441?lang=en&portalId=61000000728

**Comment by anikbrazeau** [comment]
Drafted some guidance in Freshdesk: 
- EN: [Getting form responses](https://assistance.cds-snc.ca/en/support/solutions/articles/61000307441-getting-form-responses)
- FR: [Obtenir les réponses de formulaires](https://assistance.cds-snc.ca/fr/support/solutions/articles/61000307441-obtenir-les-r%C3%A9ponses-de-formulaires)

Possible to get another set of eyes on the content before sharing with Support and client? 
@srtalbot @sarahhobson @connorscarolyns

**Comment by connorscarolyns** [comment]
@anikbrazeau I'll review and provide some feedback today

**Comment by sarahhobson** [comment]
7. Choose where responses should be saved on your computer. **Choose where responses should be saved based on your department and agencies information management policies and processes.** 
9. Select the “Confirm receipt” pill in the top menu. **I don’t think pill is a known term.** 

- I would add a note about the report a problem workflow. 

- I would add a note that we recommend opening up the responses and ensuring that the content reflects a genuine form response before confirming to ensure it was retrieved without errors.

**Comment by connorscarolyns** [comment]
> Choose where responses should be saved based on your department and agencies information management policies and processes.

@sarahhobson I'm not sure that a user will be able to select a location other than the computer they are downloading to. They should likely need to know where it's safe to save before they attempt to download. I think the added context may add more confusion here. Maybe there is something about before your start besure you have answers to these considerations...

**Comment by anikbrazeau** [comment]
Feedback incorporated (thank you!!)

Bilingual how-to guidance shared with Jimmy P: 
https://gcdigital.slack.com/archives/C03T4FAE9FV/p1687882038001199?thread_ts=1687449133.343749&cid=C03T4FAE9FV

**Comment by anikbrazeau** [comment]
Jimmy P to share guidance with clients as needed. :)
