### ISSUE TITLE
Long form emails expand beyond the card/container, last edited date not legible

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2339]
# Issue / opportunity

Long form emails expand beyond the card/container

![Screenshot 2023-06-27 at 4 09 47 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/17c9a051-37d4-4f62-bde5-9ae484911345)

![Screenshot 2023-06-28 at 9 22 18 AM](https://github.com/cds-snc/platform-forms-client/assets/38330843/76081212-4e16-4a27-8e8e-3542cbbabc68)

Additionally, a few development notes:

Part 1
1. Truncate the responses email line
2. For the description line, if the language is French, swap the order

Part 2
1. Look into whether there are (many?) forms without file names
2. Migrate the card design to. match the cards on the admin page

**Comment by connorscarolyns** [comment]
Can we migrate the card style on this page to align with the updated style on the admin card page?

**Comment by thiessenp-cds** [comment]
@anikbrazeau when you have a chance, could you check production to see if the description line is still overflowing? Looks like an update should resolve the first issue.

Note: the Email line still needs to hide overflow. Adding the below for posterity :) to make it easier to pick this bug up again.
![Screenshot 2023-09-05 at 2 09 34 PM](https://github.com/cds-snc/platform-forms-client/assets/107579368/31f0d6bd-99b4-49f6-9fd4-175f1e33155a)

**Comment by connorscarolyns** [comment]
@samsadasivan I don't believe the card's proposed new layout includes the form title, just the file name. If that's the case, we could remove it. Sam, can you confirm?

**Comment by timarney** [comment]
>  just the file name

I would suggest someone with Manage all forms permissions should check on production before making this update to see how many "Unnamed form file's" we have

**Comment by connorscarolyns** [comment]
Don't unnamed files show as unnamed? Would there be an issue with that?

**Comment by timarney** [comment]
> Don't unnamed files show as unnamed? Would there be an issue with that?

Given multiple published forms that don't have file names there won't be a way to tell them apart  (worse for a screen reader) --- this should only be a  problem if we notice a bunch of folks who don't enter a filename. 

This isn't accurate as it's draft forms on staging but thought it should be mentioned.

<img width="600" alt="Screenshot 2023-09-07 at 2 08 01 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/94e529dc-2366-416c-a197-8d13ad028fa1">

**Comment by connorscarolyns** [comment]
I see how if the forms are published, it could be a problem. Easy for users to change in draft forms. 

I just browsed through the forms audit I conducted in the summer, and I don't see any unnamed published forms. But I may not have documented that properly. Best to check, but I don't think it is a widespread problem.

**Comment by thiessenp-cds** [comment]
@srtalbot How would you feel about splitting this task into two separate ones? This card for the current task of modifying the existing layout (then release it). A new card, for updating the card style (then release it)?
