### ISSUE TITLE
[deactivate] Move form ownership control under form / form management

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#2344]
Form ownership page is currently using the "old" form management page 

This issue is to bring the ownership control  inline with the Figma design

https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?node-id=1427%3A54259&mode=dev

<img width="582" alt="Screenshot 2023-06-29 at 10 39 43 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/c0151754-ef05-481a-8461-612c4a98ed42">

**Comment by dsamojlenko** [comment]
Added here: https://github.com/cds-snc/platform-forms-client/pull/2365
