### ISSUE TITLE
[deactivate] - Ensure form has at least a single owner

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#2348]
It's currently possible to remove all form owners from a form.

We need to update to ensure at least a single user is assigned to a form.

- We should update at the UI and API level

  
<img width="1086" alt="Screenshot 2023-06-29 at 11 22 08 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/68f0b7e7-3626-440a-8475-c0cca0e1e6b0">

**Comment by dsamojlenko** [comment]
Work completed here: https://github.com/cds-snc/platform-forms-client/pull/2365
