### ISSUE TITLE
Long Privacy Statement obscures Submit

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#2349]
A relatively short form with a large Privacy Notice could lead to confusion on how to submit the form.

**As a user after filling out all the required fields I was unable to quickly find the submit button.**

*Live form using this pattern*

![Screenshot 2023-06-29 at 11-52-06 Contact Form Funding for Clean Energy in Indigenous Rural and Remote Communities.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/2fba9ad8-5ca3-43d8-bdfa-7cf7c0f00b97)

**Comment by sarahhobson** [comment]
- Most of the information included in the client's privacy statement is unnecessary.   
- We could consider implementing [expand/collapse](https://design.canada.ca/common-design-patterns/collapsible-content.html).

**Comment by connorscarolyns** [comment]
another potential solution for consideration: add a character limit to the privacy statement and generate a (read more) full content page for statements over the limit
