### ISSUE TITLE
[GC Forms UI] Typography set with tailwind classes

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2357]
Up to this point, we have been using typography tokens from the CDS GC design system. As we were adding features the base size was too large and having a secondary font-family for headers has become cumbersome. 

**Sizing is set to match tailwind classes**
**Font family is set to match canada.ca brand, but simplified to just the body font suggestion**

🔴 ignore instances of "Lato" and "Noto sans: Display" in older components. Working to unravel this ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/dd70975c-4f35-43f9-b685-39b58c30dc8e)

**Comment by samsadasivan** [comment]
I would like to change the to: slate-700. Would like some input from the team as it is a big change, but I think the black is starting to become too much. 

slate-700, with a slate-50 background could be nice

**Comment by samsadasivan** [comment]
When we get to this card - we can look into why the fonts aren't rendering on certain browsers and certain components [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2F1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6025d63dd601b8a7106530d1bcdb79b7bb8f5329/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2V1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0aa8a017f52a79baf41494cf95a93217bd670088/image.png)

**Comment by dsamojlenko** [comment]
https://github.com/cds-snc/platform-forms-client/pull/2677
https://github.com/cds-snc/platform-forms-client/pull/2722
