### ISSUE TITLE
[GC Forms UI] Alert style set 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2364]
Our alert style is a bit heavy and so I have lightened up the background and bumped up the contrast on the content within. Only links and buttons will be the _action_ blue. 

All alert colours are associated with tailwind classes, with a consistent split of 700>50 ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/48be5d57-c1fc-4d63-9a27-07c848f288fe)

![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/e22c43f4-c24e-4c1a-80f7-56aefe04d2b3)

**Comment by samsadasivan** [comment]
Current state: ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/5ceb107e-9407-4dc2-9eff-4c7741e7cb74)

**Comment by connorscarolyns** [comment]
@Abi-Nada Isn't this in progress now?
