### ISSUE TITLE
UI Adjustments: Spacing of Manage ownership

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2377]
This will create more consistent spacing and better visual grouping. 

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/a49213b9-a6bb-4a89-b5bc-1b0e1179ce79)

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/60231819-4ac8-4004-b140-2fd3d932f0c9)

**Comment by timarney** [comment]
Updates merged.
