### ISSUE TITLE
Manage ownership: Accessibility UI adjustments

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2378]
**H1 appears under H2:**
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/5a693e63-0984-4405-9d52-81caa09a876e)

**Input missing label:**
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/adc95a4b-11da-4f2f-b308-1d33904c0300)

**Comment by thiessenp-cds** [comment]
Resolved in the PR and ready for future testing
