### ISSUE TITLE
Screen position does not persist after clicking lock/unlock publishing

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2379]
If I lock or unlock publishing, I get unexpectedly bumped back to the top of the page.

**Comment by timarney** [comment]
There's no quick fix for this as the page is doing a (useRefresh) for the data.

We'll need to re-look at how we handle pages that have potentially a large amount of scrolling (possibly an optimistic update client side).

I would suggest looking into this outside of the `deactivate` feature.

**Comment by timarney** [comment]
Closing this as we have a couple of PRs merged to handle.
