### ISSUE TITLE
missing request to publish banner for users who skipped the initial request

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2381]
In staging, if I don't have permission to publish, I can see a checklist but no button or explanation as to why I can't publish; there used to be a banner here to direct people to the unlock request.

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/778ae01a-d760-473a-842f-bb89ebe200b4)

Figma example:
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/5c6ff6df-b639-440d-8c19-0926e8a866bc)

**Comment by timarney** [comment]
Logged in with an account that doesn't have access to publishing and I can't re-create the issue

 
<img width="500" alt="Screenshot 2023-08-10 at 10 49 35 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/80bfc9dc-cc52-4b5c-8629-aaec58274d27">

**Banner showing**
<img width="700" alt="Screenshot 2023-08-10 at 10 50 55 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/e77737ea-2715-4ff9-8286-06ad0ba53290">

**Comment by connorscarolyns** [comment]
Hmmm, must have been a blip.

**Comment by Abi-Nada** [comment]
Closing this card as the issue no longer persists :)
