### ISSUE TITLE
Semantic improvements for on page alerts

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2390]
The nagware alerts didn't sound great through voiceover:

- It was hard to tell that the alert information was grouped together
- It was difficult to tell the information hierarchy, and 
- br tags disrupted the flow.

Revise content to include aria-label, heading, paragraphs, and strong regions, and remove br tags.

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/8123c256-c2bf-4120-9dcb-8e1bdff705ba)

**Comment by connorscarolyns** [comment]
@dsamojlenko, I'm pinging you on this ticket for awareness.

**Comment by connorscarolyns** [comment]
@Abi-Nada

**Comment by dsamojlenko** [comment]
This issue will have been addressed with the recent Alerts overhaul:
https://github.com/cds-snc/platform-forms-client/pull/2446
https://github.com/cds-snc/platform-forms-client/pull/2547
https://github.com/cds-snc/platform-forms-client/pull/2557
