### ISSUE TITLE
Deactivate account modal should link to manage forms

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2392]
The "deactivate account" should provide a link to where the user needs to go to fix the problem. 

![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/8ad1f1f9-b086-4653-bc6d-e6da9d56515e)

Figm example:
![image.png](https://images.zenhubusercontent.com/620427f3846ebb620d78e582/26f7da97-8127-4b76-80da-1bbf633264de)

**Comment by timarney** [comment]
With the user in this case is an admin / support person 

If there's multiple published forms where can we link to?

**Comment by connorscarolyns** [comment]
The manage forms page is fine

**Comment by timarney** [comment]
Update merged.
