### ISSUE TITLE
[Form output] container size, layout, footer 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2396]
The mandatory elements include 
🟡 typography (#2358), 
🟡 container width (1140 px wide)
🟡 header (blue 4px line underscoring the FIP images, #2288) 
✅ red underscore for the main header 
🟡 footer (date modified) 

Most of this can be tackled async, with the exception of the footer. I think the "date modified" would be based on when they publish their form. 

This work is detailed out in [GC Forms component library](https://www.figma.com/file/93udAjdrHbzOOCxaC5lqN1/GC-Forms-component-library?type=design&node-id=58-13336&mode=design&t=ovWH9uVlqhUIpD1x-0): Form output/Examples ![image.png](https://images.zenhubusercontent.com/611408c194b5030c28d18261/bf01b4e4-8a6e-444a-8449-1fa9e2ff320f)

**Comment by timarney** [comment]
This is merged --- typography will be handled in a follow-up PR cc @dsamojlenko

**Comment by timarney** [comment]
Will close this as the rest is covered under #2358
