### ISSUE TITLE
Security Questions - Add Account Dropdown to header navigation

### ISSUE THREAD

**Issue by dsamojlenko** [cds-snc/platform-forms-client#2412]
<img width="619" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/28ccef7a-b9f8-4e11-81de-4dade8b65e46">

<img width="674" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/c84b3e21-04df-46fb-8e88-a3219a6ec2ce">

https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=271-33265&mode=design&t=P2sX4NNyOlzHMlD5-0

**Comment by samsadasivan** [comment]
Thank you Dave!

**Comment by timarney** [comment]
Merged.
