### ISSUE TITLE
Better Error Handling for Templates Lambda

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/platform-forms-client#250]
In the [templates Lambda](https://github.com/cds-snc/forms-staging-terraform/blob/main/forms/aws/lambda/templates/templates.js), there is currently error handling that hard codes a formID=1 when a malformed formID is passed in. This was a quick fix for sandbox, since we knew there would not be a formID = 1, and could guarantee it would pass back 0 records.

Instead, we should wrap the function in a try catch and report an error back if formID is malformed.

**Comment by bryan-robitaille** [comment]
This issue will be rendered moot by #286
