### ISSUE TITLE
Password reset: receiving an Error Message and no code?

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2524]
### Description:
_On Edge, using the Tablet_

In order to reset my password for "abi.nadarajasundaram@cds-snc.ca", there's a box to "Enter the security code you received", however I never ended up receiving a code?

### Steps to Recreate:
1. Go to the Sign In page and click "Reset Your Password"
2. Input your email ("abi.nadarajasundaram@cds-snc.ca" and click onto the link that gets sent to your inbox
3. Correctly input the answers to your security questions
4. Arrive at the page below: observe the error message? And no security code was received. (Tested this out 5 times on my end, same result and error message each time)

![Error message.PNG](https://images.zenhubusercontent.com/62a20a7f24877d05c343bf75/611ac3df-9217-4daa-a146-ccf81d4b638d)

**Comment by timarney** [comment]
Checked in Notify 

I see a few "Magic" link emails but non with a security code.

**Comment by timarney** [comment]
I have now marked the account as verified -- please re-test :)

**Comment by Abi-Nada** [comment]
It worked!!! Thanks so much Tim! :O
