### ISSUE TITLE
Revise "Forms" / "Your forms" for consistency

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2540]
# Issue / Opportunity

With a switch of the menu item to "Forms" in EN and "Formulaires" in FR, we should consider all the other places that were formerly "My forms" / "Your forms" and match H1s to the nav.

![Screenshot 2023-08-18 at 2 06 40 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/e646db12-60b2-4440-9113-bd5d572c774b)

![Screenshot 2023-08-18 at 2 07 01 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/30253f9e-9b52-452f-92e0-c61b235a0a8f)

**Comment by connorscarolyns** [comment]
linked with issue #2217
