### ISSUE TITLE
Alert about security code on security question page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2549]
The alert here does not match the context of the page.

<img width="925" alt="Screenshot 2023-08-16 at 9 21 36 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/5d706736-4534-421e-a63b-95e99284a92e">

**Comment by timarney** [comment]
PR https://github.com/cds-snc/platform-forms-client/pull/2550
