### ISSUE TITLE
"Your account" / "Profile" missing translations in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2564]
## Issue / opportunity

In French interface, "Your account" menu shows up in English

**EN** "Your account"
**FR** "Votre compte"

**EN** "Profile"
**FR** "Profil"

**EN** "Locked"
**FR** "Vérouillé"

**EN** "Unlocked"
**FR** "Dévérouillé"

## Screenshots

<img width="1322" alt="Screenshot 2023-08-18 at 1 53 05 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/a3ce4e5d-3904-4707-bd25-b0ec6ad414cf">

<img width="1646" alt="Screenshot 2023-08-18 at 1 26 50 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/3c6826a6-ce7d-4dc6-8fa4-e0607333ff78">

![Screenshot 2023-08-18 at 1 58 01 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/3b3e766f-65e1-49ca-ad09-adb221c454b6)

<img width="282" alt="Screenshot 2023-08-18 at 1 32 26 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/13214a9d-dcea-4664-a805-18f288b971f5">

**Comment by thiessenp-cds** [comment]
@timarney if I remember right, you pushed a fix for this (at least on develop)?
