### ISSUE TITLE
Clicking on "Formulaires" in top nav switches to EN

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2565]
## Issue / opportunity

Clicking on "Formulaires" in the top navigation/menu in French, switches the interface to English

_Staging, Chrome, Desktop_

## Screenshot 

Before clicking on "Formulaires" = FR
<img width="1405" alt="Screenshot 2023-08-18 at 1 33 34 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/fae22e04-c191-47c8-aacc-6b272bd0cf3d">

![Screenshot 2023-08-18 at 1 59 57 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/fa766999-658c-4ab9-b345-00de5786133f)

After clicking on "Formulaires" = EN
<img width="1390" alt="Screenshot 2023-08-18 at 1 33 40 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/c35e6136-c24c-4946-b201-84a925362a67">

![Screenshot 2023-08-18 at 1 59 46 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/2a111e09-1aff-47a9-99a1-04d5fab51fec)

**Comment by Abi-Nada** [comment]
Tried to recreate: issue no longer persists, so we'll close this one out :)
