### ISSUE TITLE
Side navigation in admin extends into main content

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2567]
## Issue / opportunity

Side navigation (in French) seems to extend beyond the column or container width?

_Staging, Chrome, Desktop_

## Screenshots

![Screenshot 2023-08-18 at 1 59 31 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/12987de1-ab7d-41cb-b18c-a8be511a4ddd)

![Screenshot 2023-08-18 at 1 59 37 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/66d7105d-c0bf-4a7a-9f0d-5a17ed73907d)

**Comment by Abi-Nada** [comment]
Issue no longer persists.
