### ISSUE TITLE
Language switches unexpectedly in admin interface

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2568]
## Issue / opportunity

When clicking "Gérer les permissions" (aka "Manage permissions") in French the interface switches to English unexpectedly

_Staging, Chrome, Desktop_

## Screenshots 
 
![Screenshot 2023-08-18 at 1 58 58 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/64b8fd64-5587-4789-9a00-4bf770e564éa)

![Screenshot 2023-08-18 at 1 58 49 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/b86dad42-2bd8-4e6a-8e4a-663fc8bc6726)

**Comment by daine** [comment]
Potentially fixed by #2593 (needing to verify)

**Comment by anikbrazeau** [comment]
This is fixed!
