### ISSUE TITLE
[GC Forms UI] Style proposal for Modals 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2580]
There are generally two types of modals we have: 
1. Guidance related: Explaining features of the app before or in addition to making an action. Usually includes an image or chart for a visual reference. 
2. Action related: Users complete an action within the modal. Usually includes input fields and trigger the action upon saving or confirm within the modal, and the modal closes. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVVtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5937fc75cede1abf9a5a658bd56ce6d9d9e0f431/image.png)

I have just added some small styling to the modals to add some consistency and reduce the black on white. 

Some notes:
- Buttons always flushed to the left (with the exception of the "add" modal) 
- Users can close the modal by using the top-right "X" or make the decision to "cancel" the action as a secondary button. Both buttons do the same thing 
- A slate-50 bg for the title or title + image of the modal 
- 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlVtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--20e750e3e61f77d31b80f667b004f155c6c0f715/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlltIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7659327fb2c2cdb6a9f5400f6cd07ae4b1228ec4/image.png)

**Comment by connorscarolyns** [comment]
@samsadasivan Do we have any thoughts on whether the primary action should be located on the right or left of the secondary action? From the accessibility perspective, placing the primary action on the far left reduces the amount a person needs to navigate to select the most relevant option. From a general usability perspective, the right-hand placement often indicates moving forward in a process. I'm up for either option, although I prefer the more accessible option.

**Comment by samsadasivan** [comment]
@connorscarolyns Thats a great point - I went with the how our "Add element" modal is set up with the primary button on the right (in that case it is on formatted on the far right of the modal which we won't do for all modals for accessibility reasons) but I did select the right to create the idea that you are moving forward in the process. When we start pagination, my assumption would be that the primary button would be on the right as well. 

I am more than happy to change this though - especially if it causes friction for those using assistive tech

**Comment by connorscarolyns** [comment]
We have no evidence that it's causing issues yet; we can go with best practice and best guess what works and feels the best. Maybe do some light research to see if anything is definitive from the accessibility community, and use your best judgment. We can always revisit it later if we find there is an issue.

**Comment by timarney** [comment]
Updated and merged https://github.com/cds-snc/platform-forms-client/pull/2666
