### ISSUE TITLE
Number of responses selected for download does not match CTA

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2585]
## Issue / opportunity

Notice how 3 responses are selected but only two are referenced in the button to "Download 2 selected responses"
![Screenshot 2023-08-22 at 1 32 50 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/5754ccff-5553-4fe1-94b9-dbe2dad28314)

## Found on

- Production
- Chrome
- Desktop
- English

**Comment by Abi-Nada** [comment]
Issue no longer persists as we currently don't indicate how many responses have been selected.<img width="1260" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenFOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ffa143e11186da4463bcda3f3cf38b34fbd07ec/Screenshot%202023-12-28%20at%209.33.52%20PM.png" alt="Screenshot 2023-12-28 at 9.33.52 PM.png" />
