### ISSUE TITLE
Links to different versions of the Contact form

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2599]
# Issue / opportunity

The menu and button on the Marketing homepage link out to different versions of the Contact form.

<img width="557" alt="Screenshot 2023-08-28 at 4 23 16 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/b0ead78f-079f-4c26-bc3b-0d909db19ebc">

CC @jose-cds

**Comment by jose-cds** [comment]
Ou, good catch. Fixing it!

**Comment by Abi-Nada** [comment]
Closing this card as the issue no longer persists :)
