### ISSUE TITLE
[GC Forms UI] Refining form building cards for forms with a lot of content

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2625]
As users start to create large forms, the thick stroke/widths and the black and white will become draining on their eyes. I have a proposal for some small changes to the cards themselves that will reduce the cognitive load of the **Edit** page. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3g1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58cae3ba10c8a384fc18837555d2ec34f06a4f78/image.png)

**Card style**
border-color: slate-700
border-width: 1px

**Drop down within the card**
height: 42px 
border-color: slate-700
border-width: 1px
font-size: text-lg/18px

**Other input fields (including required checkbox)**
border-color: slate-700
border-width: 1px

**Content**
font-family: Noto-sans,
// question // 
font-size: text-lg, font-bold / 150% / 18px
font-color: slate-700

// required, options // 
font-size: text-lg
font-color: slate-700

// question number // 
font-size: text-lg, font-bold / 150% / 18px
font-color: slate-700
background-color: slate-300

Work detailed /GC Forms UI/Components/[Section: Builder cards](https://www.figma.com/file/93udAjdrHbzOOCxaC5lqN1/GC-Forms-component-library?type=design&node-id=503-36733&mode=dev)

**Comment by timarney** [comment]
@samsadasivan working on a PR for this one here:
https://github.com/cds-snc/platform-forms-client/pull/2654

I see the borders listed in this issue as slate-700 but I don't see slate-700 in the palette (for now I'm using slate-500) --- does 500 work?

<img width="918" alt="Screenshot 2023-09-18 at 10 42 23 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/0befa687-d8e7-404e-b832-bed06c03a141">

> Drop down within the card

The dropdown no longer exists in the app so should likely updates the designs to follow suit.

**Comment by timarney** [comment]
@dsamojlenko I'll leave this open --- and we can look at the typography in #2358 and #2357 is worked out.

**Comment by dsamojlenko** [comment]
https://github.com/cds-snc/platform-forms-client/pull/2677
https://github.com/cds-snc/platform-forms-client/pull/2722
