### ISSUE TITLE
[GC Forms UI] Select a language for the UI of the tool 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2627]
All public Canada.ca sites have a page where users can select the language (French or English) of their UI before entering the website/tool. We have a simple version to start (thank you to the dev who implemented this). 

Here is a proposed design based on the look and feel of our Sign In flow. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHA2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8cf2ce851d260503a2c75c0ef9775baa0beac83e/image.png)

**Comment by timarney** [comment]
@samsadasivan I can start on this one.

Picking this one as it has implications for https://github.com/cds-snc/platform-forms-client/pull/2583

**Comment by samsadasivan** [comment]
Made an update to the footer colour - recommendation taken from GC Design system. Colour is not a tailwind class, and will span across the public facing flows and the app/tool[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkNZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1ca58cccd112c12e5d37b9e0c56a855b7858af6a/image.png)

**Comment by timarney** [comment]
Merged and on staging.
