### ISSUE TITLE
[GC Forms UI] Aligning the background colour of the "builder pages" with the sign in flow 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2656]
The builder pages are overwhelming when you have a lot of content. The high contrast of black on white is a lot of visual stimuli and therefore harder to parse or read. Proposal: change the background to gray-50 like the sign up flow [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHlzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--293c9ef6cff4b0823d59529b887bcdef0d1fde22/image.png)

**Comment by timarney** [comment]
Going to close this one and we can pick up the rest per 

https://github.com/cds-snc/platform-forms-client/issues/2625#issuecomment-1728126814
