### ISSUE TITLE
UI/UX for selecting a data classification and data delivery method  

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2695]
### User stories
As a form builder
I need to know that I cannot send unclassified or protected A data via email
So that I select the right data delivery method for the classification of my form. 

### Acceptance criteria
- [ ] Screens and pages work on MS Edge and Google Chrome
- [x] Screens and pages work on Tablet and Desktop
- [x] Screens and pages meet WCAG 2.1 AA requirements
- [ ] Data required for analytics:
  - [ ] Number of total forms by classification (Unclassified, PA, PB) and total
  - [ ] Number of currently live forms by classification and total
- [ ] Update WAF rules for any new URL paths

**Comment by samsadasivan** [comment]
Will have a proposed design EOD

**Comment by samsadasivan** [comment]
PROPOSAL 

Navigation change, content change, additional modal 

- Bolded the classification of the form in the description line to make it more explicit. 
- Added a link after to “change classification” 
- Added “Classification and Delivery method to the checklist 
- There is no default settings for classification and delivery method. They will remain unselected until a user makes a decision on the settings page. If the user does not make a selection, a ‘X’ will appear next to the classification item on the publishing page
- The “Settings” page is below “Publish” in the flow. I think we have gone back and forth on this. We want to treat the left navigation as a step-by-step process, so I have moved settings above “Publish” - Open to feedback on this change
- User selects “Change classification” > Settings page: Updates the classification via dropdown > Delivery method adjusts based on the classification selection 
- User navigates back to Publish page via the left navigation 
- The “What you need to know” guidance updates to add the information related to using the vault + test responses 
- User selects publish > modal appears to reiterate form responsibilities. I had “Response responsibilities” but it gave “locked block” vibes lol. In the past we have had users apply their login information again, but I felt like that was too much. Right now there is placeholder text, but we would want some information related to the response flow. Hoping to have content design help.

**Comment by samsadasivan** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVBiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b8708827aff3f2dce204c87c22e3b93a3dd7303a/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVhiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6b58e71e4d31d9ff5b8c23f0d27680d81a0b466a/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWJiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50ee7513caa972e33998d511dce1b99c9748c8b2/image.png)

**Comment by samsadasivan** [comment]
This flow is detailed here: [Adding data classification and delivery method checks](https://www.figma.com/file/H4LvcuQADU6QJouZ1Vswpr/Adding-data-classification-and-delivery-method-checks?type=design&node-id=1-36&mode=design)

**Comment by connorscarolyns** [comment]
One thing I wonder about is why we have a line item for "data classification and delivery method." It's never incomplete; it always has a green checkmark. 

I would like to see more intentionality in the process; we are making assumptions and defaulting things without intentionally bringing awareness to it.

What I mean is that it's okay to set a default, but passively informing the user that the form is "protected A" is easily missed. I would like to see what it looks like to make this a conscious step in the building/publishing process.

**Comment by samsadasivan** [comment]
@connorscarolyns So sorry - it is not an image in the flow, but detailed in the notes: 

"There is no default settings for classification and delivery method. They will remain unselected until a user makes a decision on the settings page. If the user does not make a selection, a ‘X’ will appear next to the classification item on the publishing page"

**Comment by connorscarolyns** [comment]
Sorry, I was just deleting my comment, I should read first before I open my mouth ;)

**Comment by samsadasivan** [comment]
I think that is why I am hoping to re-organize the left-side menu so that they see that page before getting the big "X" beside that item

**Comment by connorscarolyns** [comment]
Yeah, I like the reorg of the nav, I think it makes sense. 

And yay to no defaults! For choices this important we should ask people to make an informed decision

LOL! to "Response Responsibilities"

**Comment by timarney** [comment]
@samsadasivan do you think it would be safe to start on some of the smaller pieces ?

Thinking:
- Re-org the left nav + add a link to settings from the publish page

**Comment by samsadasivan** [comment]
New proposal: 

Desire - To ensure users are aware of the data classification before the default classification is saved in our database. This makes the selection more explicit without them missing it down the line. This also surfaces the default selections made by the tool upfront. 

Some notes:

- Quick actions: selection of branding and classification
- Only one flyout opened at a time - selecting one, would close the other
- Max character length for the branding name would be 45
- Focus and hover would show the info tag "More" - would like to try this concept as it will be helpful for the future
- Selecting more would open the modal
- Modal will have the quick actions at the top and the response delivery at the bottom. Any changes would require a "save" in the modal
- the /Settings page can still have this information displayed there. In this case, I don't think repetition is a bad thing considering the risk of folks missing this selection could be higher than what we want. This panel is also an extra push for our needs
- FUTURE: I think this whole layout will change when we get to conditional logic so I didn't want to add too much design here and use our modal component to do some of the detailed work. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWYrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--73a48b997ee5d721f1d893550a431005f10eba11/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWorIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2159028d5ab497b907763a70fc7010f3db0f94fd/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXIrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0e9be94633596771d4fe987dadc8b60a1e8b0469/image.png)

**Comment by samsadasivan** [comment]
The publish page from the previous proposal will remain :)

**Comment by samsadasivan** [comment]
Taking feedback until EOD - then moving everything to Phase 3: Ready for dev. 
- Bilingual screens 
- Tablet view 
- Component specs 

Devs more than welcomed to start. Mostly content is in flux

**Comment by timarney** [comment]
Merged.
https://github.com/cds-snc/platform-forms-client/pull/2739
