### ISSUE TITLE
Data output integrity assessment 

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2697]
What we want to know for every format we provide:
- What are the ways data could be lost, corrupted, or otherwise compromised?
- Where does that happen? (e.g.: In our system, in the program admin's system, on the client's clipboard, etc.)
- How likely is the data to be lost, lost, corrupted, or otherwise compromised?

**Comment by thiessenp-cds** [comment]
I started a Google doc to keep track of ideas/brainstorming: https://docs.google.com/document/d/14pa8u9ivggkxxrb3OWPYV7DEp-dwXtH5rhKgpg7G1dQ/edit#heading=h.ku8q45yahoe0

**Comment by Abi-Nada** [comment]
Closing this card as completed.

Added as documentation [to this card](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/2694), so we can identify how our solutions mitigate these risks.

The steps after that will be to bring this documentation in when we're testing the implemented solution, in order identify the likelihood of dropping responses. (i.e. We can add it into our test scripts to check for French character malformations. Etc.)
