### ISSUE TITLE
Migrating Notify API Keys

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2719]
### Description:
As a security precaution, Notify now adds a prefix to API keys. The prefix helps safeguard information and recipients’ privacy. We must revoke our old API keys that do not have the prefix and replace them with new API keys, by **November 18, 2023**. 

### Steps to Migrate:

Follow these steps to replace API keys without experiencing interruptions:
1. Sign in to GC Notify.
2. Create new API keys.
3. Update your application code to use the new API keys.
4. Test your application.
5. Revoke your old API keys.

### Acceptance Criteria:
- [x] Check to see if our current Notify API keys contain the prefix
- [x] If not, follow the steps above to replace the API keys
- [x] Change keys on Staging
- [x] Test form response submissions
- [x] Change keys on production
- [x] Test form response submissions
- [ ] Remove previous API keys once we know everything is working fine

**Comment by craigzour** [comment]
Was able to just redeploy our last infra update to take the new GC Notify API key into account. App has been redeployed too. The new key is now live in production.

**Comment by craigzour** [comment]
`Production API ` API key to be deleted in a few days once we know everything is working properly in production.
