### ISSUE TITLE
Settings page: Alert content change 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2728]
Users are allowed to change their response delivery settings at anytime before publishing, but we have an alert on the settings page that says you have to choose a classification before selecting the method. Since the classification is default anyways, we can adjust the alert to the following: 

EN: You can change these settings anytime before publishing. 
FR: Vous pouvez modifier ces paramètres à tout moment avant de publier le formulaire. 

Current state: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjNxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ec1b7a281b5ea1bd541e338c9714b77af2ffb474/image.png)
 

Desired state 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjdxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--970a1dc3f659711df853a0a1d58252273bb0712b/image.png)

**Comment by Abi-Nada** [comment]
Designs have been implemented.
