### ISSUE TITLE
Breakpoint issue with editing language toggle

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2744]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01RQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--250836d7c5709da60d00529e111bc6d3d291a8b5/image.png)

**Comment by Abi-Nada** [comment]
@connorscarolyns was this on tablet? Can you re-test and see if the issue still persists?

**Comment by connorscarolyns** [comment]
Yes, this issue still persists

**Comment by Abi-Nada** [comment]
Issue no longer persists with new navigation
