### ISSUE TITLE
Text on the translation page does not match the choices in the add modal

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2753]
The single-choice option is labelled as a radio button on the translation page. Change one to be consistent,

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzBlQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d36f4d5aa7334333ad86e6dbc656cf24b67dff0a/image.png)

**Comment by anikbrazeau** [comment]
** Review all copy in EN and FR for all question types and blocks

**Comment by connorscarolyns** [comment]
@anikbrazeau now is probably a good time to look at this since we've made some language adjustments to the modal

**Comment by connorscarolyns** [comment]
@anikbrazeau can you review the copy on the translation page to ensure alignment with the new add modal?
