### ISSUE TITLE
Inconsistent containers/page layouts on pages where access is limited (signed out)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2760]
# Issue / opportunity

- Include H1 for all pages (add "Responses"
- Include "Settings" on "Form management page to have consistent nav
- Adjust size of "Publish" container to match "Settings" and "Responses"

# Screenshots

<img width="1791" alt="Screenshot 2023-10-10 at 3 52 52 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/3ba3c492-b144-4a43-b2fd-9fa51c6d7242">

<img width="1792" alt="Screenshot 2023-10-10 at 3 53 08 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/ed2aee59-e337-4403-a54e-903d4b6c7ead">

<img width="1792" alt="Screenshot 2023-10-10 at 3 53 01 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/b9e221c4-0080-4a50-a5b7-2dc9b76e3013">

<img width="1792" alt="Screenshot 2023-10-10 at 3 55 52 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/0463fa67-dc4b-44c0-a44c-c0b309aafb76">

**Comment by timarney** [comment]
Noting headings have already been updated in https://github.com/cds-snc/platform-forms-client/pull/2739

**Comment by anikbrazeau** [comment]
# Signed out experience could be more polished:

https://github.com/cds-snc/platform-forms-client/assets/38330843/4ac6cf8d-f90b-41a9-a995-b0ccf4e9ce5d

**Comment by Abi-Nada** [comment]
Issue no longer persists
