### ISSUE TITLE
Update Terms of Use: opening files

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2778]
### Description:

Revise the Terms of Use to specify that clients are responsible for handling and opening downloaded files.

### Acceptance Criteria:
- [ ] Terms of Use are updated to specify client responsibility for opening downloaded files.

**Comment by hegazynourhan** [comment]
@Abi-Nada tagged you in retrieval responsibilities in [[terms of use doc](https://docs.google.com/document/d/1ThGNKO_oyKBSgm7R5Smi8goBIphCV-VTa3249J5sdDc/edit)

**Comment by Abi-Nada** [comment]
Thank you, @hegazynourhan ! Will review and get back to you soon (if not by EOD, then early tomorrow morning)
