### ISSUE TITLE
HTML Official Record

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2779]
### Description:

Generate HTML official records that aggregate multiple form responses into one HTML document. 

### Acceptance Criteria:
- [ ] ~File is downloaded with a CSV selection~
- [x] Official records in HTML format are generated correctly.
- [x] Aggregated data displays accurately.
- [x] Test file for WCAG 2.1 AA requirements

**Comment by thiessenp-cds** [comment]
Starting brainstorming on this.
I suspect getting the copy to clipboard part to work well across apps will be the most difficult part.
Dependencies: CSV work,  probably a new API call

**Comment by thiessenp-cds** [comment]
FYI here is the [Figma design](https://www.figma.com/file/SBkP2G0bV4jwoghIvlZ1zg/v2.-Download-and-confirm-responses?type=design&node-id=1-37&mode=design&t=ClgOcR2HpGuOt8wd-0) (note to self - on the left side :)

**Comment by thiessenp-cds** [comment]
Started the HTML aggregate data task. I'll be working off (forked) [Dave's branch](https://github.com/cds-snc/platform-forms-client/pull/2793)

**Comment by thiessenp-cds** [comment]
For CSV, I did some digging and here some [rough notes on CSV injection](https://docs.google.com/document/d/14pa8u9ivggkxxrb3OWPYV7DEp-dwXtH5rhKgpg7G1dQ/edit#heading=h.ok9tfxs5t7t6) (scroll to the bottom)

**Comment by thiessenp-cds** [comment]
The CSV download part looks like it will be controlled in a download modal. So it may not be downloaded alongside the html formats. I'll remove it from the acceptance criteria for now
