### ISSUE TITLE
Set up end date: Open and close form with generic message 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#2791]
### Scope of UI Changes for V1:
- [x] Open and close a form from receiving responses on a published form (Functionality) 
- [x] Add option to open close form on the settings screen for Draft and Publish, authenticated
- [x] Generic page in FR and EN to let users know "Form is no longer accepting submissions" 
- [x] Error messages 

### Out of scope until Download and Confirmation work is completed:
- [ ] Personalized message on Settings, Edit, Preview, Translation
- [ ] Preset end-date

**Comment by samsadasivan** [comment]
**PROPOSAL FOR INTERIM SET UP END DATE** 

Toggle component on /Settings, moving the “Save button, Generic messaging. 

- The ability to accept form submissions will live under /Settings/Form management -similar to the original design proposed 
- The component used to indicate “Open/Closed” is a toggle to save some vertical space
- The “save” button will now be moved to the top right hand corner, in-line with the sub nav items. This button will appear when there is a change. This pattern will start to be more of a global pattern across the app for primary CTA’s to ensure they are not missed when we add new features to page that pushes content below the fold. This also connects to where the “Download responses” CTA will end up being
- The “Closed” page will be default messaging provided by the form builder in EN and FR for now - this is an interim solution. Open to making a nice illustration to make it look nioce :D 
- In the “Delete a form” flow we have a modal that lets users know what end-users will see when they delete a form. I don’t believe this is necessary for this feature as it isn’t a permanent action and you don’t need to download your form file just in case. I am open to having the preview be a link to what users will see in the /Settings page.
- “View closed form” would open on an external tab with the header and footer matching form output style

**Comment by samsadasivan** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUJnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae89005dc2d391dd6edd469412054a4ded0b825b/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70b0917d9a85fe28617b80675641f5368ea3feb8/image.png)

[Proposed screens live under v2. Download and confirm responses/PROPOSAL/"Set up end date: Open and close form with generic message #2791"](https://www.figma.com/file/SBkP2G0bV4jwoghIvlZ1zg/v2.-Download-and-confirm-responses?type=design&node-id=1-36&mode=design)

**Comment by samsadasivan** [comment]
Decision: Removing "View closed form" external link

**Comment by samsadasivan** [comment]
Investigating: "Back" routing end-users back to the previous destination they were at. Currently, the back button is using the branding image "link" as the destination

**Comment by Abi-Nada** [comment]
On staging for testing
