### ISSUE TITLE
Iterate on download and confirmation flow and HTML response output

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2802]
### Description

> As a form builder,
I want to get form responses in my preferred format,
So I can process form data efficiently.

> As a form filler,
I want to trust that my personal information is stored temporarily,
So I can trust government that risk has been reduced and my data is treated with care.

> As GC Forms,
We want to reduce confusion and guide people to avoid overdue responses,
So we can avoid tedious support processes and incidents.

### Acceptance Criteria:
- [x] Collaborate with designers to create user flows that integrate learnings, guiding users through the feature effectively.
- [ ] Content creation for the interface, including error messaging.
- [x] Content creation for the HTML output, including feedback on actions.
- [ ] Content review: ensuring all content is reviewed/approved by product and design.
- [x] Localization of content/ensuring that content is available in English and French.
- [ ] Content is tested within prototype to ensure accuracy, clarity, and consistency.
- [x] Relevant updates are made to content after prototype testing findings.

### Link to findings
https://miro.com/app/board/uXjVNTmmwYg=/?messenger=slack&utm_source=slack&utm_medium=messenger&utm_campaign=notifications&utm_content=unfurled_chat_link&utm_term=messenger_analytics

### Link to prototype
https://www.figma.com/file/SBkP2G0bV4jwoghIvlZ1zg/v2.-Download-and-confirm-responses?type=design&node-id=1%3A37&mode=design&t=j6MFDXUL0tmEJVEf-1

**Comment by anikbrazeau** [comment]
## Issues to solve or things to consider

- [ ] Shift design pattern from pills to tabs to avoid confusion between "actions", "filters" and "places"
- [ ] Rethink "select" interaction which is not always meaningful and applies to `download` but not `delete`
- [ ] Clarify "select all" interaction which was missed by users
- [ ] Provide #/# indication to signal which subset number of responses is selected/downloaded/deleted
- [ ] Reframe HTML as "official record" with log of answers and confirmation codes as "receipt codes"
- [ ] Provide more context about the "transfer of ownership" or "handshake" involved in confirming/deleting
- [ ] Make it clearer for users when the required actions or transactions involved in responses are done
- [ ] Simplify HTML response file by removing table and instructions
- [ ] Think about form file names
- [ ] Rethink tooltips (are they necessary? can they be clearer? shorter?)
- [ ] Add JSON file format
- [ ] Set expectations so users know why they are doing the confirmation code step

**Comment by anikbrazeau** [comment]
Latest work is here:

- Figma: https://www.figma.com/file/SBkP2G0bV4jwoghIvlZ1zg/v2.-Download-and-confirm-responses?type=design&node-id=2040-37261&mode=design&t=CuVSNYMOHtTx2mpO-4
- PR: https://github.com/cds-snc/platform-forms-client/pull/2831
