### ISSUE TITLE
Form Builder Side Menu on Edge/Tablet looks different?

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2809]
### Description

The side menu of the Form Builder UI looks different on Edge/Tablet, compared to the rest of the browsers on both Mac and tablet.

### Steps to recreate:

1. Log in to your tablet
2. Access GC Forms (https://7xkkl3ul72swysmdfuqx67ufsy0imnvk.lambda-url.ca-central-1.on.aws/en/form-builder) through Edge
3. Navigate to the Form builder and start adding questions

### Tablet view on Edge
**(I _had_ to use my phone because I was way too lazy at this point in time to figure out screenshots on the tablet, so pardon the quality!)**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab13ee58ec0b567870c701ffd36574d56fc2d7b9/373464864_1006822393955705_6534200091089633567_n.jpg)

### vs Tablet view on Chrome
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--646d7be19ae43dcbcf095545696d1566fb7f4fa2/369053715_370085525367955_5729081763100290844_n.jpg)

**Comment by timarney** [comment]
This is intentional as far as the "blue" menu being under for smaller screens and the "fly out" for larger screens.

Thinking there's maybe a bit more screen space to work with when using Chrome ?  We're both full width on your tablet?

**Comment by Abi-Nada** [comment]
@timarney I believe both were full width, but I can double check!
