### ISSUE TITLE
Form Status toggle is inverted

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2810]
### Description

Looks like the button for "Form Status" is inverted - when you toggle to "Close", it opens a form. When you toggle to "Open", it closes a form.

_Tested on both Mac and Tablet using Chrome_

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13f5f6deed8393868623043ca553df189b1638a3/Screen%20Recording%202023-10-30%20at%209.56.07%20PM.mov)

**Comment by timarney** [comment]
Will get this fixed up ---  the labels we're flipped yesterday as we noticed screen readers  we're reading on / off as flipped

https://github.com/cds-snc/platform-forms-client/pull/2792/commits/6cae7e26fd73c5865b2a553ea14bab982051f907#diff-e2b39b900348473614a0ad1bbb880f7e2c3ba9848f94f22bfe6e5071e05ebdd1R41

**Comment by timarney** [comment]
This should be fixed now --- will be a few minutes for the update to deploy.

**Comment by Abi-Nada** [comment]
Just tested it out and it works! Thanks so much, @timarney !
