### ISSUE TITLE
Side Menu stays for each question

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2811]
### Description

_Tested on Macbook, Chrome + Edge_

The side menu seems to stay and overlap for each question added - it disappears when I click back onto the question. Not sure if this what it is suppose to do (and if so, maybe it shouldn't be overlapping?)

### Steps to Recreate

1. Navigate to the Form Builder and start adding multiple questions (short answer and long answer seem to overlap)
2. Click on each question to remove the side menu

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHFHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3ff701d85700fa80c74a182fcccd554c266de96/Screen%20Recording%202023-10-30%20at%2010.04.49%20PM.mov)

**Comment by timarney** [comment]
This appears to be the famous "more and more bug"

https://www.youtube.com/watch?v=nNC3HkXjx6k

Will have to take another look it's been in the code base for a while now.

**Comment by Abi-Nada** [comment]
Thanks for advising, @timarney ! I'll take it out of Sprint Backlog for now, since it's unrelated to the work on closing forms.

**Comment by Abi-Nada** [comment]
Closing this issue as the upcoming V3 nav layout we'll be implementing will remove the side card menu ;)
