### ISSUE TITLE
Unable to save form if field contains HTML

### ISSUE THREAD

**Issue by jprince-cds** [cds-snc/platform-forms-client#2821]
The form was unable to be saved because it contained < > brackets that look similar to HTML tags. Unfortunately, the error is non-descriptive to the clients so they don't know what is happening or what needs to be fixed.

Would it be possible to HTML-encode problematic characters to avoid this error?

Freshdesk Ticket #15927

**Comment by jprince-cds** [comment]
The form was unable to be saved because it contained < > brackets that look similar to HTML tags. Unfortunately, the error is non-descriptive to the clients so they don't know what is happening or what needs to be fixed. 

Would it be possible to HTML-encode problematic characters to avoid this error? 

Freshdesk Ticket #15927

**Comment by timarney** [comment]
@samsadasivan @connorscarolyns wondering how we should proceed here for the design end.

We've seen several support tickets where this has come up.

@dsamojlenko and I looked into what we can do on the dev end and have determined that we can pinpoint the field or fields where the markup or what appears to the editor as markup appears.  

Should we look to remove the markup upon when trying to save --- which should fix the save problem or display am alert indicating the problems(s) -- and possibly link back to the specific text area.  If we go this direction I think we should move the error outside of the save button and look to display it in a more prominent location (and larger i.e. a full alert).

**Comment by timarney** [comment]
Ref: https://github.com/cds-snc/platform-forms-client/pull/2832

**Comment by connorscarolyns** [comment]
I think in French, < kjjkkj > is used as a quotation mark? Telling people they need to remove it could be problematic. Is there a way er can escape these characters when the template is saved?

**Comment by timarney** [comment]
Notes from some some further testing

« Je voudrais du thé. C'est combien ? »


<img width="880" alt="Screenshot 2023-11-08 at 9 35 29 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/b9d35e28-665e-40ef-add4-235e93077cd6">

This also passes 
```
< a >
```

This fails
```
<a>
```


Copying and pasting links also works

<img width="400" alt="Screenshot 2023-11-08 at 9 38 59 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/c4006cdb-9a71-4d57-9056-7180a6d035f9">

---


We can look into converting the < and >

**Comment by timarney** [comment]
Another support ticket 

https://cds-snc.freshdesk.com/a/tickets/15993

This time outside of the Richtext area


```
 "descriptionEn": "Please provide your education details in the following format  1.\t <Level of Education (eg: Degrees/Diploma>, <Field of Study>, <type of degree/diploma that applies (eg: Bachelors, Masters, Doctoral, Diploma, Other)>, Year (YYYY)2.\t<Level of Education (eg: Board certifications)>, <Certification>, Year (YYYY)3.\t<Level of Education (eg: Credentials/Accreditation/Licensing)>, < Credentials >, Year (YYYY)",
```
