### ISSUE TITLE
SLA updates

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2906]
### Description:

A list of things to update within the SLA:

- [ ] Communicate in our SLA that it is the client’s responsibility to understand how their department or agency implements the [Policy on Communications and Federal Identity](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=30683)

**Comment by hegazynourhan** [comment]
@Abi-Nada we have a reference to this under responsibilities in our terms of use. but happy to chat if it doesn't suffice. Will tag you in document as making updates at the moment.
