### ISSUE TITLE
User Testing for confirming bulk responses

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2907]
### Description
UAT (user acceptance testing) for confirmation codes with clients who have many form submissions.

### Acceptance Criteria:
- [x] Recruitment list is compiled
- [x] [Privacy notices](https://docs.google.com/document/d/1mf4r_IXUHmfQ3SkEuSvfEvK0-gD7gdjr5FW1lnQEI3w/edit) are updated and sent to participants ahead of the session
- [x] Research plan is put together
- [x] Facilitation guide is put together (if need be)
- [x] Findings are synthesized and shared with Product

**Comment by connorscarolyns** [comment]
Research plan:
https://docs.google.com/document/d/1wjUaqjjuPl76tnuwvls1Y2LifSkRP0k0B4S9ArxJNpk/edit?usp=sharing

Facilitation guide:
https://docs.google.com/document/d/1dMbI6K-dL764cjPJoAHnjjj3U0bbKMrTK4lWSGUTQzE/edit?usp=sharing
