### ISSUE TITLE
Broken Skip the response table link

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2913]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b2a44a46d110e1ec89d22c98084fa6f52ab9464/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f7af364650452176efda69c957a8eea98145a96/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca19beef8ab8ac740d4bf68b4e7e553b15fae539/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ca9e317b131cb4e4c3645b041561262d36f1822/image.png)

**Comment by thiessenp-cds** [comment]
Fixed/For review in PR https://github.com/cds-snc/platform-forms-client/pull/2928
