### ISSUE TITLE
Heading of empty states not coded as headings.

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2914]
H1's on empty state pages are hidden, and the empty state heading is coded as a paragraph. This may confuse users of screen readers; they will scan the page and hear that new responses are available when there are none. The same condition exists on each of the other tabs as well.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0VPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66a3c037f5d1ac55c8639ed63f491f5dd7877fc8/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58159c3cca0fb97a443221fd720f155cdb1a715d/image.png)

**Comment by thiessenp-cds** [comment]
Fixed/For review in PR https://github.com/cds-snc/platform-forms-client/pull/2928
