### ISSUE TITLE
Update text on individual HTML download to new language

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2917]

**Comment by connorscarolyns** [comment]
Individual HTMl needs a little tweak to align the language with the new release.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUFPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38ac38282fdba9d8d4f06bd31526054893d44473/image.png)

**Comment by connorscarolyns** [comment]
New designs proposed in phase 3 of download and sign-off:
https://www.figma.com/file/SBkP2G0bV4jwoghIvlZ1zg/v2.-Download-and-confirm-responses?type=design&node-id=2735-106195&mode=design&t=LjyPuKOIyMkiBVJp-4

**Comment by Abi-Nada** [comment]
Issue no longer persists
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3lKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f008e77700f90c1515036576b94a871fddf9ac3d/Screenshot%202024-06-24%20at%203.25.53%E2%80%AFPM.png" alt="Screenshot 2024-06-24 at 3.25.53 PM.png" />
