### ISSUE TITLE
Error while downloading appears behind download modal

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2922]
# Issue / opportunity

When trying to download hundreds of responses at once, there seems to be a lag and eventually an error that appears on screen. However this shows up behind the modal which remains open and does not provide feedback to users on what's happening.

# Screenshot

<img width="1792" alt="Screenshot 2023-11-28 at 10 51 49 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/1612810a-70c0-43fa-9c80-afcb345090f2">

**Comment by Abi-Nada** [comment]
Let's double check to see if this persists within the Staging environment as well.

**Comment by Abi-Nada** [comment]
@connorscarolyns @dsamojlenko to pair on where error messaging should go with the modal.

**Comment by anikbrazeau** [comment]
This was still an issue as of Wednesday November 29 at 2 pm. 

Replicated: 

![Screenshot 2023-11-29 at 2 08 05 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/0779d444-588f-40e0-809a-664006d048f4)

**Comment by connorscarolyns** [comment]
I believe it would also be okay to dismiss the modal after clicking download, and a spinner would be excellent while the system generates and serves responses.
