### ISSUE TITLE
Receipt shows up at the bottom of the list f files, it should show up at the top

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#2933]
Because the response files start with a date, and the receipt starts with R alphabetically, it shows up below all the responses in the file folder. Perhaps add an asterisk to the name or other character so that it appears above all the responses in the folder.

**Comment by anikbrazeau** [comment]
Ideally, receipt would download first, even when just two files (ex: json and csv scenarios).
On Edge/Tablet, when multiple files being downloaded was blocked by the browser, the first file still downloaded.

**Comment by dsamojlenko** [comment]
https://github.com/cds-snc/platform-forms-client/pull/2988
