### ISSUE TITLE
HTML response tab has no page title when opened

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2951]
# Issue / opportunity

Tab shows up as `-`. Could the file name appear instead?

# Screenshot

<img width="787" alt="Screenshot 2023-11-29 at 9 18 55 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/595627c4-2f16-4822-8dbb-2d9cfa1a7ae4">

**Comment by Abi-Nada** [comment]
Issue no longer persists - the tab shows the Form title.
