### ISSUE TITLE
How might we avoid "multiple downloads" being blocked?

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2954]
# Issue / opportunity

Yesterday, did not have multi-downloads enabled and could not find where to do this, no popup was appearing as I would expect either, essentially blocking me from accessing responses.

Today, the pop up showed up, but how might we mitigate this problem for clients.

# Screenshot

<img width="345" alt="Screenshot 2023-11-29 at 9 09 57 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/3c4c20a6-7053-4f28-bc27-3b00b8c1aed2">

**Comment by connorscarolyns** [comment]
I believe this is mostly resolved now. I recommend closing this ticket and reopening it when we have more evidence that this issue persists.
