### ISSUE TITLE
lag between when it says responses were downloaded and when I see the downloads

### ISSUE THREAD

**Issue by hegazynourhan** [cds-snc/platform-forms-client#2955]

**Comment by hegazynourhan** [comment]
when downloading zipped individual files, it says files were moved to download folder about 10-20 seconds before they appear in my downloads.

**Comment by anikbrazeau** [comment]
Potentially: some sort of download progress indicator?

**Comment by hegazynourhan** [comment]
its still about 30 second lag for me... maybe cause I'm using edge/tablet.

video reference: https://github.com/cds-snc/platform-forms-client/assets/146020428/1b32705e-6825-4b1a-9026-ee6583612dbe

**Comment by anikbrazeau** [comment]
The confusing aspect here might be more about the action and success message being decoupled. You get "success" even if it was not successful... It seemed there's no actual way to actually "detect" that responses were downloaded and then to display at that moment? Maybe a different intervention to indicate the change in "response status" could be considered in future? Or we might consider the illusion of a delay here to bridge the expectation and reality?

**Comment by hegazynourhan** [comment]
my main concern is not that theres a lag but that when someone sees the message before the folder appears they will close the tab too soon and lose the download. Testing to see in this scenario if they move to downloaded anyways.

**Comment by anikbrazeau** [comment]
I wonder if this "simulation" or "assumption" is the problematic aspect we might need to find a way around / avoid? If it's not linked to actual "downloading" it seems highly likely something could go wrong.
