### ISSUE TITLE
Time of download listed in HTML does not match current time

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2960]
# Issue / opportunity

Responses downloaded: 2023-11-29 3:04 pm
They were actually downloaded at 10:04 am

# Screenshot

<img width="1541" alt="Screenshot 2023-11-29 at 10 05 15 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/6a55e59d-f03d-410a-9999-1599b79b1377">

**Comment by anikbrazeau** [comment]
Specify timezone as GMT

**Comment by anikbrazeau** [comment]
Perhaps we should also specify the timezone in the response table?

**Comment by thiessenp-cds** [comment]
For this task is the goal to convert the time GMT for example (see screenshot of a download at 4:32 my time). Should the time should be printed as `2023-11-30 9:32 PM GMT`
![Screenshot 2023-11-30 at 4 32 37 PM](https://github.com/cds-snc/platform-forms-client/assets/107579368/2e5e4bd2-8a64-4d99-a000-d7b099505ebe)

**Comment by anikbrazeau** [comment]
We use this time format below in the responses themselves? `2023-11-28 14:23:30 UTC`
Is UTC the same? Maybe we should be consistent if so?

**Comment by anikbrazeau** [comment]
Related to #2985
