### ISSUE TITLE
Report a problem link is buried when there are hundreds of responses

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2971]
# Issue / opportunity

Consider bringing the "report a problem" link up on the screen

<img width="960" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/62621c1e-8535-4f54-98b0-579b603701be">

# Screenshots

**Comment by Abi-Nada** [comment]
Issue no longer persists now that we have "pages" for every 150 responses
