### ISSUE TITLE
Dialog expands to 150 extra rows in length

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2981]
## Issue / opportunity

On Edge, copy-pasting 150 receipt codes, expanded the modal to be very long and scrollable with lots of white space.

## Screenshot

![Large scroll modal](https://github.com/cds-snc/platform-forms-client/assets/38330843/17ac1b16-df5f-4480-9f3c-f48ee354f976)

**Comment by Abi-Nada** [comment]
Closing as a duplicate of #[3639](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3639)
