### ISSUE TITLE
Contrast with focus state

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2983]
## Issue / opportunity

Switch to white when background is dark blue

# Screenshot

![Focus](https://github.com/cds-snc/platform-forms-client/assets/38330843/9a198456-ce12-415b-aaf4-56df5549a1fc)

**Comment by thiessenp-cds** [comment]
Added to this PR https://github.com/cds-snc/platform-forms-client/pull/2972
