### ISSUE TITLE
Clarify when date is "Date of submission" (New) vs. "Date of download" (Downloaded and Signed off)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2985]
# Issue / opportunity

When responses are new they include the "Date of submission" in the response table
When these are downloaded and move to the Downloaded tab, the "Date" changes to the download date.
Currently the column header always indicates "Date" which is ambiguous for users.

# Screenshot

<img width="966" alt="Screenshot 2023-12-01 at 9 04 04 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/d88132ab-2d4a-4a8e-9354-33381aa90fe8">

**Comment by Abi-Nada** [comment]
Issue no longer persists, with help text included for better clarification
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--997f4ed6df26ef2e8d03d0272d7b976bea7612f1/Screenshot%202024-06-10%20at%207.20.11%E2%80%AFAM.png" alt="Screenshot 2024-06-10 at 7.20.11 AM.png" />

<img width="1334" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUJNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f40c1a81268ddaa619874734ebc98114faa2485b/Screenshot%202024-06-10%20at%207.20.28%E2%80%AFAM.png" alt="Screenshot 2024-06-10 at 7.20.28 AM.png" />
