### ISSUE TITLE
Entering one wrong receipt code, deletes all others

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#2986]
# Issue / opportunity

What happens if 1/150 codes is wrong, none seem to get submitted and all codes pasted disappear.
Revise behaviour and/or error message (since no codes are shown below)

# Screenshot

<img width="837" alt="Screenshot 2023-12-01 at 10 00 06 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/77951d95-652d-4481-a692-85ac19c60ed2">

**Comment by connorscarolyns** [comment]
This issue no longer persists.
