### ISSUE TITLE
Implementing Cognito out-of-country alarms

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3008]
### Description:

Context: [Slack Thread](https://gcdigital.slack.com/archives/C02KUU7TKL1/p1702040405135829)

An alarm on out of country access could be an indicator of a compromised account, so hoping to implement Cognito out-of-country alarms for prod and possibly staging.

Existing alarms: https://docs.google.com/spreadsheets/d/1FXChe3eJq6BJgMBbF8Y_SXCnoOXoO3IiXMRWt7GoW0w/edit#gid=0

### Acceptance Crieria:
- [ ] Calvin flagged that SRE might have an easy way to implement this. Can connect with SRE to see if they already have a way to do this
- [ ] Implementation of Cognito out-of-country alarm for Prod
- [ ] Investigation into whether we need it for Staging

**Comment by wmoussa-gc** [comment]
The issue originally raised by the Sentinel (CDS SIEM) system was unrelated to Forms. However, we have chosen to address the configuration of an alert that will notify us if a public servant attempts to sign in to Forms from outside Canada. The severity level of such an event is to be determined.

**Comment by wmoussa-gc** [comment]
started design doc: https://docs.google.com/document/d/1-6vOzXhLJiXTTWe8COgyyu-L0z4TJbQiYcUaziYVMjw/edit#heading=h.986p0fzckyo7

**Comment by wmoussa-gc** [comment]
Example to follow https://github.com/cds-snc/forms-terraform/pull/174/files#diff-1a95778637ec7287ffb20f531c16cf87577872a9f0e7476c056dd65f93440cb8 (Option 4 in design document)

**Comment by wmoussa-gc** [comment]
<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--773a96e1048b09460182b72dd613dd91d5d2bb6c/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
Not thrilled with the alarm details, but let's see what comes next and, more importantly, how big of a deal this is. I think I'm done with my part for now, but I'll check with the team to be sure.
