### ISSUE TITLE
Newline character causes share email to fail to send

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#3010]
https://gcdigital.slack.com/archives/C03T4FAE9FV/p1702047751238239?thread_ts=1701975333.327129&cid=C03T4FAE9FV

When using the share modal to share a json file via email - the form "file name" is used as the.json filename.

If the form "file name" contains newlines and possibly other characters the email fails to send from Notify

<img width="1314" alt="Screenshot 2023-12-08 at 9 58 14 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/d4c11cac-9fc7-4a68-86ab-c5eae64947e6">

We should `slugify` the file name that will be shared before sending.

**Comment by jprince-cds** [comment]
Is it possible it could also affect the Subject line of the email, and not just the attached filename? Just being overcautious here.

**Comment by thiessenp-cds** [comment]
> Is it possible it could also affect the Subject line of the email, and not just the attached filename? Just being overcautious here.

Good call out! In this case, for a form share, the subject should be hard coded to `Form shared | Formulaire partagé`
