### ISSUE TITLE
Text inconsistencies between Interface, Receipt, HTML and CSV static content

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3012]
We have various ways to refer to the Submission number, Submission date, and receipt code. Let's create consistency here.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzVHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e65bc63b8160c449b4eeefcc78311315d1dea9f9/image.png" alt="image.png" />

<img width="1620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba67703e29481eee870712549ebdb32b94d18bae/image.png" alt="image.png" />

<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22cf0dd40576ccc4ea6e35e4a8c9bd710cf613be/image.png" alt="image.png" />

**Comment by anikbrazeau** [comment]
Working on this here: https://www.figma.com/file/SBkP2G0bV4jwoghIvlZ1zg/v2.-Download-and-confirm-responses?type=design&node-id=2991-12614&mode=design&t=hGp3jWMLrvLBSNoG-4

**Comment by anikbrazeau** [comment]
Prioritize CSV changes for consistency

**Comment by anikbrazeau** [comment]
Related issue: https://github.com/cds-snc/platform-forms-client/issues/2985
