### ISSUE TITLE
inconsistent number of responses communicated

### ISSUE THREAD

**Issue by hegazynourhan** [cds-snc/platform-forms-client#3022]

**Comment by hegazynourhan** [comment]
<img width="1780" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5UQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--352a43d7eabf82b99281bd9fc957da984f94d80c/Screenshot%202023-12-12%20at%201.33.12%20PM.png" alt="Screenshot 2023-12-12 at 1.33.12 PM.png" />

says have more than 150 but on left says 99 (should be 150 since I downloaded a batch)

**Comment by connorscarolyns** [comment]
So let me see if I understand: 
You had 249 responses, you downloaded 150, and then you saw this?

**Comment by hegazynourhan** [comment]
in the downloaded tab > had 249 responses > confirmed 150 > so left with 99 > but message on top says I have more than 150

**Comment by connorscarolyns** [comment]
Perfect, that's exactly what I thought. Thanks for clarifying. 

The banner with more than 150 responses should have disappeared after the last batch of confirmations.

**Comment by dsamojlenko** [comment]
Fixed in: https://github.com/cds-snc/platform-forms-client/pull/3005

(Hides message when there is only one page of results)
