### ISSUE TITLE
assumed number represents pages not responses

### ISSUE THREAD

**Issue by hegazynourhan** [cds-snc/platform-forms-client#3023]

**Comment by hegazynourhan** [comment]
Upon first use assumed its 150 pages brain goes to email model where it has number of pages. Maybe label as "showing 1-150 responses"


<img width="1970" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenRUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9c0e5b8229e26d506bf3e1db8a711e006ed78fc/Screenshot%202023-12-12%20at%201.41.54%20PM.png" alt="Screenshot 2023-12-12 at 1.41.54 PM.png" />


<img width="1974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d519d5606acafbcd5c1cda46bf705ed0ba16e6c8/Screenshot%202023-12-12%20at%201.20.51%20PM.png" alt="Screenshot 2023-12-12 at 1.20.51 PM.png" />

**Comment by Abi-Nada** [comment]
@connorscarolyns / @anikbrazeau : Can you advise on if we need a content update? (If we do, I can move this card over to the Sprint Backlog and flag the changes to dev)

**Comment by anikbrazeau** [comment]
Good catch! Maybe we can try something like:

`Responses 1-150` // `Responses 151-300`
`Réponses 1 à 150` // `Réponses 151 à 300`

Or maybe even conform to the expected pagination pattern by moving the text over instea:

`You have more than 150 responses. Showing 1-150`
`<-- Previous `Page 1` --> Next`

`Vous avez plus de 150 réponses. Affichage de 1 à 150`
`<-- Précédent `Page 1` --> Suivant`

**Comment by connorscarolyns** [comment]
I would be fine to keep a watch on this to see if more content will help. It's fairly text-heavy already and I'm hesitant to add more.

**Comment by Abi-Nada** [comment]
Thanks for the input, folks! +1 to what Carolyn said, let's move this back to New Issues and keep an eye on if this comes up as confusing for users.

**Comment by connorscarolyns** [comment]
This has been fixed as part of a bug fix which added a back to start icon.<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--715ff06fcdef7da2c5e24bec5f1aceb0b18fe055/image.png" alt="image.png" />
