### ISSUE TITLE
A little thing: overlapping text on one of the tabs

### ISSUE THREAD

**Issue by hegazynourhan** [cds-snc/platform-forms-client#3025]

**Comment by hegazynourhan** [comment]
on the sign off page the "previous" text was overlapping and not legible. It was totally fine on the other pages.

<img width="1818" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cfb28985619b8f0df8fee94f56e85702515c10b/Screenshot%202023-12-12%20at%201.57.47%20PM.png" alt="Screenshot 2023-12-12 at 1.57.47 PM.png" />

**Comment by dsamojlenko** [comment]
Fixed in: https://github.com/cds-snc/platform-forms-client/pull/3005
