### ISSUE TITLE
Error code missing in confirmation modal

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3027]
The user copied and pasted submission IDs into the confirmation modal and got a message that it was sending. They didn't get an error that it was the wrong format.

**Comment by wmoussa-gc** [comment]
<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUtTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ebc9f21f706937e78ed881efe98a19bff860433/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
Slack thread https://gcdigital.slack.com/archives/C01GFD150MC/p1704211313882579

**Comment by wmoussa-gc** [comment]
Can still see the errors if multiple invalid codes are pasted

<img width="774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2235a53daa544a60e953d4e9bad59949f6ae9e4a/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
https://github.com/cds-snc/platform-forms-client/pull/3072
