### ISSUE TITLE
Checkmark in check box doesn't display correctly in Edge

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3028]
The checkmark is cut off and doesn't display correctly in Edge

**Comment by connorscarolyns** [comment]
<img width="466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWRaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcd7d0795354eff2c850ff2bcf66980866a0c3b2/image.png" alt="image.png" />

**Comment by Abi-Nada** [comment]
Re-tested in Edge: issue no longer persists.<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3hwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00019f9068360c4f71157b26ff3bdc428a740b52/Screenshot%202023-12-17%20at%209.11.04%20PM.png" alt="Screenshot 2023-12-17 at 9.11.04 PM.png" />
