### ISSUE TITLE
Fable Testing Privacy Notice

### ISSUE THREAD

**Issue by hegazynourhan** [cds-snc/platform-forms-client#3031]

**Comment by hegazynourhan** [comment]
adding consent and privacy notice to testing descriptions. We can adapt what notify is using [here](https://docs.google.com/document/d/1gochXRGKQbdfwBOXUGEAYhPNDNm8DKW51d0wf4ZIGA4/edit#heading=h.k99xncfdmaa2).

**Comment by connorscarolyns** [comment]
Privacy statement has been published in articles and linked to from the special instructions in the Fable platform:
https://articles.alpha.canada.ca/forms-formulaires/decide-if-youll-participate-in-our-research/
