### ISSUE TITLE
[Bug] Full street address autocomplete value is incompatible with short answer blocks

### ISSUE THREAD

**Issue by EricDunsworth** [cds-snc/platform-forms-client#3037]
I've noticed that the short answer block's ``autocomplete`` dropdown currently contains an option for "Full street address (includes address lines 1-3)". Unfortunately, that value isn't compatible with short answer blocks since full addresses are expected to contain multiple lines of text.

The [``autocomplete`` section in WHATWG's HTML spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute) contains a large table with an outline of all possible values. Among other things, it defines their intended formats and which "[control groups](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#control-group-text)" they belong to. Control groups aren't compatible with all types of form fields. Although ``input type="text"`` is compatible with the vast majority of control groups (everything except [multiline](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#control-group-multiline)).

**Reproduction steps:**
1. Visit the [form builder editor](https://forms-staging.cdssandbox.xyz/form-builder/edit)
2. Press the "+ Add" button, pick "Short answer" and press the "Select block" button
3. In the right-hand menu, open the "... More" link
4. In the "Select an autocomplete attribute" dropdown, pick "Full street address (includes address lines 1-3)"
5. Press the "Save" button
6. Switch to the "Preview" tab
7. Open your browser's DOM inspector
8. Use the inspector to highlight the empty form field
9. Observe the ``input type="text"`` element's ``autocomplete`` value

**Expected result:**
Step 4 shouldn't list "Full street address (includes address lines 1-3)".

Why? Because step 2's short answer block generates a single-line text input (``input type="text"``). On the other hand, "Full street address (includes address lines 1-3)" maps to ``autocomplete="street-address"`` - which is associated to the [multiline control group](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#control-group-multiline).

It shouldn't be possible to set a multiline ``autocomplete`` value on a single-line text field.

**Actual result:**
Step 4's dropdown lists "Full street address (includes address lines 1-3)" and step 9 demonstrates it mapped to ``autocomplete="street-address"`` in an unsupported field type (``input type="text"``).

End result is that user agents may be unable to autofill it correctly. [HTML validation](https://validator.w3.org/nu/) and [WCAG 2.x SC 1.3.5](https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html) (via [F107](https://www.w3.org/WAI/WCAG22/Techniques/failures/F107)) also fail.

**Proposed solution:**
Remove the "Full street address (includes address lines 1-3)" option from the short answer block's ``autocomplete`` options.

**Food for thought:**
* Consider adding an ``autocomplete`` dropdown to the long answer block and diverting the "Full street address (includes address lines 1-3)" option there
* Consider grouping ``autocomplete`` values by control group [behind-the-scenes](https://github.com/cds-snc/platform-forms-client/blob/7e1da8108228f3adca1e7388843791a8196a54e2/public/static/locales/en/form-builder.json#L137-L162) (to make it easier for GC Forms to "draw" compatible ``autocomplete`` values for different kinds of field types in the future)

**Comment by EricDunsworth** [comment]
This issue also affects the address component's street address field (which uses ``input type="text"`` - i.e. single line text field).

**Comment by timarney** [comment]
Thanks @EricDunsworth we'll take a look and get this into one of our sprints cc: @Abi-Nada

**Comment by EricDunsworth** [comment]
@timarney Thanks :)! Btw would you prefer that I create a spinoff issue for the address component?

**Comment by timarney** [comment]
Yes a separate issue for the address would be great thanks.
