### ISSUE TITLE
[Bug] Address block's street address field (input type="text") is incompatible with autocomplete="street-address"

### ISSUE THREAD

**Issue by EricDunsworth** [cds-snc/platform-forms-client#3046]
Spinoff of #3037.

The address block's street address field (which looks like a [short answer block with preset values](https://github.com/cds-snc/platform-forms-client/blob/1550c8280d05736b4a256a9b8c6abe1bb79226da/form-builder-templates/address.json#L23-L43)) uses an ``autocomplete="street-address"`` attribute. That makes sense given the field's purpose.

But [``street-address``](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-street-address) belongs to the [multiline control group](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#control-group-multiline)... which is incompatible with the ``input type="text"`` element. That element only supports a single line of text.

**Reproduction steps:**
1. Visit the [form builder editor](https://forms-staging.cdssandbox.xyz/form-builder/edit)
2. Press the "+ Add" button, pick "Address" and press the "Select block" button
3. Switch to the "Preview" tab
4. Open your browser's DOM inspector
5. Use the inspector to highlight the "Street address" form field

**Expected result:**
Step 5 should show a ``textarea`` element with an ``autocomplete="street-address"`` attribute.

**Actual result:**
Step 5 shows an ``input type="text"`` element with an ``autocomplete="street-address"`` attribute.

End result is that user agents may be unable to autofill it correctly. [HTML validation](https://validator.w3.org/nu/) and [WCAG 2.x SC 1.3.5](https://www.w3.org/WAI/WCAG22/Understanding/identify-input-purpose.html) (via [F107](https://www.w3.org/WAI/WCAG22/Techniques/failures/F107)) also fail.

**Proposed solution:**
* Base the address block's street address field on a long answer block (which uses a ``textarea`` element and is therefore compatible with ``autocomplete="street-address"``)
* Add support for ``autocomplete`` values in long answer blocks

**Comment by EricDunsworth** [comment]
I just wanted to note that #3104's solution still leaves something to be desired for address blocks :(.

The HTML validation issue has been resolved. But IMO the solution that was implemented (replacing ``autocomplete="street-address"`` with ``autocomplete="address-line1"``) still technically fails WCAG.

There's now a mismatch between the street address field's label/instructions vs its ``autocomplete`` attribute:
* The field's label implies it's expecting a full street address
* The ``aria-describedby`` paragraph below the label instructs users to "Include your civic number and street name, **apartment or suite, and other address details**"

So... the ``autocomplete="address-line1"`` attribute is instructing user agents to autofill the first line (i.e. civic number + street name), whereas users are being instructed to insert lines 1-3 :S.

Should this issue be re-opened? I think the only viable way of resolving this would be to use a ``textarea`` element and ``autocomplete="street-address"`` attribute.

@thiessenp-cds Thoughts?

**Comment by thiessenp-cds** [comment]
Hi @EricDunsworth thanks for taking another look. Yes the content should be updated, I missed that.
I also agree about changing from a input to textarea field. The change is not trivial but in the future we (forms team) should come back to it.
