### ISSUE TITLE
Move "Save Draft"

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3059]
### User Story:
As a form builder of GCForms,
I want the "Save Draft" button to be relocated from the left navigation to a more intuitive and accessible place,
So that I can easily save my progress on a form, especially when the left navigation is collapsed.

### Description:
This task involves moving the "Save Draft" button from its current position in the left navigation to a new location. This change is part of the broader navigation update work, which includes making the left navigation collapsible. The goal is to enhance the UI by making it more intuitive and accommodating the new collapsible feature of the left navigation.

### Acceptance Criteria:
- [x] The "Save Draft" button is relocated to a prominent, easily accessible position that remains visible and intuitive for users, even when the left navigation is collapsed
**Note:** The new location should be tested for ease of access and visibility.
- [ ] Test that the button functions correctly in saving drafts

**Comment by timarney** [comment]
@Abi-Nada FYI - this should happen prior to the left nav updates if possible.

**Comment by samsadasivan** [comment]
Doing the "back button" at the same time - Will have an update tomorrow @ noon

**Comment by samsadasivan** [comment]
PROPOSAL: 
Save draft as a link
- we could have save draft as a link that isn't as eye-catching as before
- It only appears on the edit page
- When there is a change, the link to save the draft will be available just before the components where you add content (basically above the first cards for /edit and /translate)
- Once they select "Save draft", it will show success by changing to "save". When another change is made, it will return to the above ^
- If it fails, then the link will change to "Failed - Contact support" and link to our support form. It will turn red-700, and a toast message will also appear reiterating the message just in case someone starts scrolling

**Comment by samsadasivan** [comment]
<img width="626" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmEyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba256fadc469f24a4268c98070fee983a7fd65b1/image.png" alt="image.png" />

<img width="1009" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmUyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--037bbfb10856bd0190ff95faee9a5bf495354274/image.png" alt="image.png" />

<img width="1036" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm0yQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--829fa4f953da2b0350b5eca418de95c51de3bf43/image.png" alt="image.png" />

<img width="1015" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnEyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb48cd80860f6717d7ad989e9ae3317d3fa47c42/image.png" alt="image.png" />

<img width="1019" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnUyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b770f3ad1a4ced66e34a0a7f02ec69c0266e4a1c/image.png" alt="image.png" />
