### ISSUE TITLE
Panel: Logic

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3065]
### Description:
Develop branching logic capabilities for the logic view.

### Acceptance Criteria:
- [x] Users can create and edit conditional logic rules
- [x] Decision needs to be made on how to approach "auto-flow"/how the flow appears if users don't set logic rules
- [x] Competing conditional questions ("last rule wins")

**Comment by samsadasivan** [comment]
**PROPOSAL: Panel — Logic** 

General UI 
- Background is a bit darker at slate-300 
- Language toggle remains at the top in the middle 
- Panel button will be labelled "Form setup • Pilot" 
- Default state: Will always be on the first section: Start 
- When a section is selected, the <active state> is indigo-500, 1px stroke 
- Restriction: the "Add rule" Icon (plus symbol) will only appear when the section has a form element that. For example: The START section will not have any form elements in it to add rules to, so the ability to add a rule will not be available. The right panel will be in an empty state, with intructions on adding content. 
- Technical feasibility: Instead of scrolling left to right, I have proposed a Panning zoom option. This is available in the react-flow library
- 
<img width="949" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHNXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36b7e454fee2589a5b2e787ac581f8c43eccf85c/image.png" alt="image.png" />


Flows: 
From Default state -> Adding content -> adding logic 
Delete a rule 
Add a dynamic or “Hide show” field 
Add Other 
Moving a question with a rule applied to it to another section

**Comment by samsadasivan** [comment]
From Default state -> Adding content -> adding logic

As stated above, the user must add content before adding rules. 

Default state: 
- Empty state for panel 
- Default sections with essential elements displayed in a mapping visual 
- Users are prompted via content to add content under "Questions"

<img width="1017" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c38eb4aca223726ef8945bb08371cd235cf9a32/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Final output: 
- Once they save the rule, there is a branch applied to the map 
- There is still a linear flow to the confirmation page 
- The right panel has a receipt of the rule that has been applied with the ability to edit it or remove it 
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e6663a47b4e5e31293d1efea94149eab07b6948/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
**Add a dynamic field** 
- Links to "adding a rule" in the question elements will be removed. The ability to add a rule (or logic) will not happed in the panel 
- User selects add a new rule, and adds a rule to show a question on the same page (or section ;))

<img width="1682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4d695142d66a50ad85a05ae2390311cf030d7b7/image.png" alt="image.png" />

- User saves question, and the dynamic element is represented in the colour yellow in the map and with an "eye" icon on the panel. We are thinking of using the "branch" and "eye" icon in the mapping visuals as well but left it out for mvp. Feedback is welcomed on this 

<img width="845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDRXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b927efb4aac5cac02fa977120e01b41af423fcae/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Add Other
- After a long (really long actually) back and forth about this and observing some of the initial accessibility testing, we are going to remove "other" quick selection. Reason: "Other" quick selection appears with the other rules in the panel. Users don't realize it is the same as rules. So they don't know to go to the modal to "edit" the rule. For simplicity, we are proposing to remove it, and to hopefully bring it back when we know a little bit more on where to put it.

**Comment by samsadasivan** [comment]
Moving a question that has a rule applied to it, to another question

- A modal will be triggered when a user moves an element with a rule to another section (as it will break anyways) 
- We could prompt them to reorganize their content or delete the rule. In this proposal, I added the concept of moving the rules. I am unsure if this works. Even now as I am writing it, I think it may not for branching. But it does for dynamic elements. Would love a developers persp. on this one. 

<img width="1694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10796d5a73670b3d8f397cbd50664434c5f91e28/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
**_SHOWCASE MOCKUP: Online feedback form_** 

I made a small mock up of what one of the forms could possibly look like with dynamic fields. Would like to make one with branches as well. 

<img width="1742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13271ce86d20ab77e844b2578b382c8beff1ca1e/image.png" alt="image.png" />
<img width="1091" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWtXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--341fb9ed169faf530dbb9839938b6271172c48d4/image.png" alt="image.png" />
<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9XQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08dee78f214308af6af41a9b6ecab861ae73cd2e/image.png" alt="image.png" />
<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f494658064e2e16b4ec3d620942259cd0ac34371/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Oops I forgot 

**Delete a rule**
- User uses the "remove" link in the panel 
- The map auto updates the edges 

<img width="1732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8a7d8b839130f05d077e33a1359f814d6f931ed/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Flows and designs are documented under [Dynamic fields + Grouping questions/ Right Panel (dev test)](https://www.figma.com/file/2bmknDRpZXN3lwqhs7mqNH/Dynamic-fields-%2B-Grouping-questions?type=design&node-id=1443-9511&mode=design)

**Comment by timarney** [comment]
RE: 

> Competing conditional questions ("last rule wins")

Given a scenario where I have next actions setup based on "values"
Radio
- choice A goes to section A
- choice B goes to section B
Dropdown
-choice C goes to section C


If a user selects A for the radio and C for the dropdown I can't go to both sections I have to pick one.

Currently "C" would win as it comes last. 

<img width="806" alt="Screenshot 2024-05-13 at 10 39 56 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/e66bceb5-2091-4210-b1c0-29248844dfc4">

<hr>



<img width="485" alt="Screenshot 2024-05-13 at 10 38 15 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/ae085edb-fe3d-41f9-bead-166cf7372265">

**Comment by timarney** [comment]
@samsadasivan @samsadasivan @anikbrazeau 

This view is quite functional at this point --- 

Can ya'll start breaking out some todos / pieces that need attention ?  Look for bugs etc...
