### ISSUE TITLE
Set up OpsGenie for sev1

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3069]
### User Story
As an Incident Commander/Operations Lead,
I want OpsGenie to be set up specifically for handling Severity 1 alarms,
So that we can quickly and efficiently respond to critical incidents, ensuring minimal downtime and impact on GCForms operations.

### Description
We need to set up OpsGenie to handle Severity 1 (S1) alarms for our 24/7 support structure. This setup includes creating an OpsGenie account, configuring S1 alert policies, and integrating it with Slack to ensure a prompt and effective response to critical issues.

### Acceptance Criteria:
- [x] OpsGenie account is successfully created and configured for S1 alarms
- [x] Teams and roles are correctly set up in OpsGenie
- [x] Integration with Slack is complete and functional for S1 alarms
- [x]  Define and set up alerting rules specifically for Severity 1 incidents
- [x] All relevant team members are trained on handling S1 alarms using OpsGenie
- [ ] Conduct a test run to ensure that S1 alarms are correctly identified, escalated, and addressed
- [ ] Managing S1 alarms through OpsGenie is added to our documentation and made available for the team

**Comment by wmoussa-gc** [comment]
Notify opsgenie cloudwatch config: https://github.com/cds-snc/notification-terraform/blob/ed865840fbe88bfdf6fb88dfc28b2780ae39b722/aws/common/sns.tf#L123

**Comment by wmoussa-gc** [comment]
Technical analysis: https://docs.google.com/document/d/1u4b_jf5BvMkv6Z4lyE8lENYY3aNIxySnjlHS2ZCn6mQ/edit
