### ISSUE TITLE
Move "Left nav" back button

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#3078]
Per https://gcdigital.slack.com/archives/C0676D34GPR/p1704463247374939?thread_ts=1704463121.636149&cid=C0676D34GPR we need to move the "back" link out of the Left nav to above the H1

> Maybe it could go above the H1?

>   18px and above the h1 makes sense

<img width="1148" alt="screenshot_2024-01-05_at_8 57 25___am" src="https://github.com/cds-snc/platform-forms-client/assets/62242/1954538d-bb26-4e78-a9eb-f77db118be8c">

cc: @Abi-Nada

**Comment by samsadasivan** [comment]
PROPOSAL: 

Notes

- Styled as a link, slate-800, text-lg (18 px)
- back arrow with a frame (icon + padding) of 24 x 24 px, slate-800
- will always appear in the top left corner of the screen, above the h1 where applicable.
- con: it took the spot of the "expand menu" I am currently thinking about perhaps not expanding the left panel. Or make a more condensed version of what we have because of this.

**Comment by samsadasivan** [comment]
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3UyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11110d331b96fe422b7de5962740f7303042514b/image.png" alt="image.png" />
<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3kyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ac8c4c48a62f927899d0b3427d74238c0a1e5b2/image.png" alt="image.png" />
<img width="994" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzIyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5803dcfe7950c9ac645d29091154af8fb3cb56e4/image.png" alt="image.png" />
<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzYyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f5880c1094285b91b2701d38069e234edb32b40/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
Work is being done under PROPOSED/ [Section: BACK BUTTON - iteration 2](https://www.figma.com/file/2bmknDRpZXN3lwqhs7mqNH/Dynamic-fields-%2B-Grouping-questions?type=design&node-id=1-36&mode=design)
