### ISSUE TITLE
Character limit attribute shows up in wrong form blocks

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3111]
# Issue / opportunity

Noticed basic form blocks like radio buttons, checkboxes, dropdown, and legal attestation, give the option to set character limits even though they do not involve entering text. Might character limits only apply (or show up in the More modal) for fields/elements where there is a text entry component?

## Currently

- Short answer ==> does not have character limit
- Long answer ==>  has character limit
- Radio buttons ==>  has character limit
- Checkboxes ==>  has character limit
- Dropdown list ==>  has character limit
- Attestation ==> has character limit

## Expected

- Short answer ==> should have character limit rule option
- Long answer ==>  should have character limit rule option
- Radio buttons ==>  should NOT have character limit rule option
- Checkboxes ==>  should NOT have character limit rule option
- Dropdown list ==>  should NOT have character limit rule option
- Attestation ==> should NOT have character limit rule option

<img width="775" alt="Screenshot 2024-01-10 at 2 12 55 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/ba3fc883-36bc-4f3c-b206-c13fa9f892be">

**Comment by anikbrazeau** [comment]
Brainstorming: Might there be other types of limits that could apply for other fields? For example, for **checkboxes** could you set a minimum/maximum number of boxes to be selected?

**Comment by timarney** [comment]
Is this happening on prod and staging?

**Comment by anikbrazeau** [comment]
@timarney yes, both prod and staging.

**Comment by anikbrazeau** [comment]
Do we want limits on all inputs of all kinds:

short answer
long answer
full name
individual names (first name, middle name, last name)
contact fields (phone number, email)
address (street address, city, province, postal code)
date
number

**Comment by thiessenp-cds** [comment]
This should be fixed in #4053
