### ISSUE TITLE
"Copy" text strings being generated when using the duplicate button

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3130]
Chrome on MacBook

STings of the word "copy are inserted into the form when using the duplicate feature. These strings do not appear in the builder or the translation page

<img width="753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0xtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6938db624bb5b6e07add792f47f08bdb80e3cec6/image.png" alt="image.png" />

<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1BtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b2546f8e41716ab8c9323b48b37a079f22eeb6d/image.png" alt="image.png" />

<img width="1560" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1htQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4528c0de7e3c36b1781b76b454030f9193a83de5/image.png" alt="image.png" />

**Comment by connorscarolyns** [comment]
[designops-efforts-and-challenges-2024-01-22 (1) copy.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ptQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e96f5a0eed9a8ed9c43dd647148cf51211a0d749/designops-efforts-and-challenges-2024-01-22%20%281%29%20copy.txt)

**Comment by connorscarolyns** [comment]
@Abi-Nada this is a bug people can't recover from on their own.

**Comment by timarney** [comment]
> These strings do not appear in the builder or the translation page

<img width="618" alt="Screenshot 2024-01-22 at 10 35 02 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/832d4afd-741d-4fc1-9e9f-3dbf9a1534fd">

Thinking this is related to only rich text areas?

In that case the description is being used vs the title --- and this would be the bug.

**Comment by dsamojlenko** [comment]
Fix: https://github.com/cds-snc/platform-forms-client/pull/3131
