### ISSUE TITLE
Overlap in action menu for form elements

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3133]
# Issue / opportunity

Side action menu with "move up/down" "duplicate" "delete" etc. shows up multiple times when adding elements with conditionals.

# Steps to replicate

1.  Create/edit a form
2. Add radio buttons with multiple options
3. Add option for "Other"
4. Add another form element, ex: checkboxes

_MacOS, Google Chrome, Staging, French_

# Screenshot
![Screenshot 2024-01-23 at 10 12 03 AM](https://github.com/cds-snc/platform-forms-client/assets/38330843/6eb12063-534c-4d3b-ab0a-fe08dd53376b)

**Comment by timarney** [comment]
https://www.youtube.com/watch?v=nNC3HkXjx6k

ref: https://github.com/cds-snc/platform-forms-client/issues/2811

**Comment by Abi-Nada** [comment]
Pre-known issue that will be addressed when we remove the menu here (#[3729](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3729))
