### ISSUE TITLE
Developer Onboarding to New App Router

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3154]
### Description:
To facilitate the smooth transition and effective utilization of the new App Router, we need to conduct an onboarding process for our development team. This involves conducting syncs that will guide the developers through the new system, ensuring they are equipped with the necessary knowledge and skills.

### Acceptance Criteria:
- [x] Onboarding sync is set up and covers all essential aspects of the App Router
- [x] All developers are set up with the new App Router

**Comment by timarney** [comment]
Going to close this as @bryan-robitaille gave a walk through on Tues.

<img width="347" alt="Screenshot 2024-02-02 at 9 43 22 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/49197db2-abf0-4416-8e36-b63eaeb1d8f5">
