### ISSUE TITLE
Sign-in flow not working properly when getting the Restricted access to responses dialog

### ISSUE THREAD

**Issue by craigzour** [cds-snc/platform-forms-client#3159]
After getting the Restricted access to response dialog, the navigation is acting weird (see video below). User is redirected to the language selection page and when you click on one of the options you end up on a blank page.

It appears to be a bugged since it works great in the current staging version of the app.
https://github.com/cds-snc/platform-forms-client/assets/1763961/f6b0657b-0b39-47dd-9e4e-586e8773152a

**Comment by anikbrazeau** [comment]
+1 I also encountered this same issue

**Comment by wmoussa-gc** [comment]
I'd like to work on this bug (which will help me familiarize myself with how authentication has been implemented). Is there an easy way to set myself up with "restricted access"?

**Comment by craigzour** [comment]
> I'd like to work on this bug (which will help me familiarize myself with how authentication has been implemented). Is there an easy way to set myself up with "restricted access"?

Search for `data.hasOverdueSubmissions` in the `Verify.tsx` file. Setting this to a static `true` should do the trick as the issue happens when we get to the restricted access dialog.

**Comment by wmoussa-gc** [comment]
fix: https://github.com/cds-snc/platform-forms-client/pull/3208/

**Comment by wmoussa-gc** [comment]
https://6bfxg5775nrab3woforujwvpri0zlxoc.lambda-url.ca-central-1.on.aws/ @craigzour can you test your flow here?
