### ISSUE TITLE
Publishing a form does not show the success screen

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#3161]
## Description
Deleting a form should show the success/error screen but on publishing shows the edit screen.

## Steps to reproduce
1. Go to a form ready to publish
2. Click on publish
3. The form is put back into edit mode 

## Expected behaviour
The success screen is displayed

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/107579368/f1453fdf-e05e-4f70-811f-aba05844be1d

**Comment by timarney** [comment]
Ref: https://github.com/cds-snc/platform-forms-client/pull/3218
