### ISSUE TITLE
A dropdown in Settings > Form Management is missing some style

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#3163]
## Description
A dropdown in Settings > Form Management is missing some style

## Steps to reproduce
1. Go to Forms  > any form > Settings
2. Look for the Manage Ownership heading
3. The dropdown lost its style :(

## Expected behaviour
The dropdown is styled :)

## Screenshots or videos
![Screenshot 2024-01-29 at 1 40 11 PM](https://github.com/cds-snc/platform-forms-client/assets/107579368/691efe19-d7f8-40ce-bc32-b487c88eca16)

**Comment by timarney** [comment]
Styles load locally on the preview env I see inline styles get blocked.

<img width="1130" alt="Screenshot 2024-02-02 at 8 32 27 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/222196e5-3525-43f3-9a2b-efb37770b51c">

**Comment by thiessenp-cds** [comment]
This works as expected for me now. I suspect it was fixed in another PR. I'll close this ticket
