### ISSUE TITLE
App router: Sign in flow - padding is large on the right side 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3164]
Issue: 
The widget has some styling issue. 

![image](https://github.com/cds-snc/platform-forms-client/assets/70960477/eccc8285-97e9-48d2-9a88-df8773881c58)

**Comment by wmoussa-gc** [comment]
image is not snowing up @samsadasivan

**Comment by samsadasivan** [comment]
Oh weird, here ill post again <img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5f7e5c72102ecc8a6c1a73b67394d6c76e4eb91/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
Oh, it seems the image was not visible when viewing this issue on GitHub: https://github.com/cds-snc/platform-forms-client/issues/3164. I pasted the image differently in your first comment using GitHub directly, but it looks like from ZenHub, the image doesn't render in GitHub.

**Comment by timarney** [comment]
Should be fixed via https://github.com/cds-snc/platform-forms-client/pull/2583/commits/72d7165783ac40d43439d807ea7b95cfaf0450c0

**Comment by timarney** [comment]
Confirmed - going to close this.
