### ISSUE TITLE
Closing a form does not save state

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#3165]
## Description
Closing a published form does not move it into the closed state

## Steps to reproduce
1. Go to Forms > any published form > Settings > Form Management
2. Under "Form status" click the toggle button to move the form into "Closed" state
3. Navigate back to Forms and then return to this form's Settings screen
4. The form remains in "Open" state

## Expected behaviour
Change a published form's status to "Closed" sets the form state to "Closed"

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/107579368/91fce8c0-b018-475e-919f-e67affc88dbd

**Comment by anikbrazeau** [comment]
Possibly related to #3177

**Comment by timarney** [comment]
@thiessenp-cds can you re-test?

Thinking this will be related to

https://github.com/cds-snc/platform-forms-client/pull/3218

**Comment by Abi-Nada** [comment]
Closing as issue no longer persists:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13b95279df0b136c561625dcbfa12e1985c2c2d8/Screen%20Recording%202024-06-28%20at%2010.36.07%E2%80%AFAM.mov)
