### ISSUE TITLE
Error creating a new user

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#3167]
## Description
Trying to create a new user results in an error.

## Steps to reproduce
1. Go to the Sign up page
2. Enter in a new user's details
3. Submit
4. An error is shown (403 error)

## Expected behaviour
User is created and forwarded to the Security Questions screen

## Screenshots or videos
Showing the user doesn't exist and should be ok to use to create an account.
![Screenshot 2024-01-29 at 2 42 20 PM](https://github.com/cds-snc/platform-forms-client/assets/107579368/126a6be2-f26a-40f0-9294-f88730b43dd2)

Showing the error creating an account with the above email
![Screenshot 2024-01-29 at 2 43 46 PM](https://github.com/cds-snc/platform-forms-client/assets/107579368/a6392b42-4317-4c50-b949-d66cb3a92563)

**Comment by wmoussa-gc** [comment]
works locally 
<img width="854" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/70960477/36db5c00-d936-479c-b100-3dcc7b5cd14f">
