### ISSUE TITLE
Click More > Settings button on a published form loads a settings page for a different form

### ISSUE THREAD

**Issue by craigzour** [cds-snc/platform-forms-client#3169]
## Description
On the dashboard, when using the More > Settings button on a published form we end-up being redirected to a settings page that does not belong to that selected form. It appears to load a settings for a different form.

## Steps to reproduce
1. Go to my forms page
2. Click on More > Settings on one of your published forms

## Expected behaviour
Should redirect to the right form edit page.
<img width="1792" alt="Screenshot 2024-01-29 at 2 56 46 PM" src="https://github.com/cds-snc/platform-forms-client/assets/1763961/55dc8b11-383d-4f3d-985a-bcaf26a8f1fa">

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/1763961/c07f6650-9157-4480-accb-f4f55cecee10

**Comment by anikbrazeau** [comment]
This also happened with "More" > "Preview"
It links to an empty form

https://github.com/cds-snc/platform-forms-client/assets/38330843/e99feb2d-cad2-4b95-a311-ef148608b34a

**Comment by craigzour** [comment]
I updated the ticket after seeing that it only applied to published forms

**Comment by craigzour** [comment]
> This also happened with "More" > "Preview" It links to an empty form
> 
>  Screen.Recording.2024-01-30.at.4.32.59.PM.mov

This will be fixed in https://github.com/cds-snc/platform-forms-client/issues/3169
