### ISSUE TITLE
`Sign off on ?X? responses` button redirects user to 404 page

### ISSUE THREAD

**Issue by craigzour** [cds-snc/platform-forms-client#3170]
## Description
`Sign off on ?X? responses` button redirects user to 404 page

## Steps to reproduce
1. Go to my forms page
2. Find a form that has restricted access to responses
3. Click on `Sign off on ?X? responses` button

## Expected behaviour
<img width="1792" alt="Screenshot 2024-01-29 at 3 01 02 PM" src="https://github.com/cds-snc/platform-forms-client/assets/1763961/eb460ec5-cc25-4a70-8ff7-ea9bae6f32cb">

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/1763961/a7cf7cc1-4d6e-40ba-9280-54c3a05c5eff

**Comment by timarney** [comment]
Looks like this might have something to do with placeholders

```
 "linkSingular": "<a href=\"{{link}}\">Sign off on {{responses}} response</a>",
 "linkPlural": "<a href=\"{{link}}\">Sign off on {{responses}} responses</a>"
```
I see &#x2F; ending up in the url - Unicode Hex Character for /
```
https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/en/&#x2F;en&#x2F;form-builder&#x2F;responses&#x2F;clpiotewe000ox281scc3vm9x
```

**Comment by timarney** [comment]
@wmoussa-gc @craigzour 

This should fix.

https://github.com/cds-snc/platform-forms-client/pull/3237

**Comment by timarney** [comment]
Merged fix for this
