### ISSUE TITLE
French-first editing when using French interface

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3173]
## Description
When using the application in English, editing in English is the norm and expected. When using the application in French, it might reasonably be expected that the working language is French and for features to be French-first to match. Interface language shoudl match the language default of app features.

## Steps to reproduce
1. Sign in using French interface ("Se connecter")
2. Go to "Modifier" (Edit) in left nav
3. Land on form building interface
4. See "Modifier en: **anglais**" toggle at the top of the screen
5. Click "Ajouter un élément" to add a block
6. Select "Noms individuels" for separate names
7. The element is added in English

## Expected behaviour
Expected to start editing in French.

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App router PR
- **Language**: French

## Screenshot
<img width="1410" alt="Screenshot 2024-01-29 at 2 48 54 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/31598f3b-5d40-4d7f-8232-a72de359bdf1">

**Comment by wmoussa-gc** [comment]
fixed..Ill wait for Anik to confirm

**Comment by anikbrazeau** [comment]
Fixed! :D Thank you!
