### ISSUE TITLE
Error submitting form in "Preview/Test" and when published

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3175]
## Description
Unable to submit a form using the "Test" feature in draft and using the URL when published.

### Draft
1. Go to a draft form
2. Click on "Test" in the left side menu
3. Fill out the required fields
4. Click "Submit"
5. See error

### Published
1. Go to a published form
2. View form at published URL
3. Fill out the required fields
4. Submit
5. See error

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App router PR
- **Language**: English and French
- **Viewport**: Desktop
- **Form ID**: `clievkyuz0000yl67qanq34z8`
- **Form Link**: https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/fr/id/clrzeny430003eckylhqjgti0

## Expected behaviour
Ability to submit and see responses for forms.

### Draft
https://github.com/cds-snc/platform-forms-client/assets/38330843/2b1deb63-c27e-4177-b7d1-2c2c392376a8

### Published

https://github.com/cds-snc/platform-forms-client/assets/38330843/bc90874d-3866-40a6-ac07-73022f4c4137

**Comment by thiessenp-cds** [comment]
I had the same issue. Looks like another error 403

**Comment by bryan-robitaille** [comment]
Resolved - Tested in PR Review environment.
