### ISSUE TITLE
Changing response delivery option to "Email" reverts back to "Download"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3177]
## Description
When trying to change the Setting for the response delivery option to "Email delivery", and then navigating away, the changes do not appear to stay saved.

## Steps to reproduce
1. Go to a draft form
2. Click on "Settings" in the left nav
3. In "Response delivery options" select "Receive responses by email" and "Save changes"
4. Go to "Responses" in the left nav
5. Return to "Settings"
6. See how it reverts the setting to "Download responses..."

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App Router PR
- **Language**: English and French
- **Viewport**: Desktop
- **Form ID**: clrzenydk0005ecky6lcy3zke

## Expected behaviour
Maintaining the choice of setting even after navigating away from the page.

## Recording

https://github.com/cds-snc/platform-forms-client/assets/38330843/4d3b6cbe-4e87-44eb-afe6-bd88ec7aeb45

**Comment by timarney** [comment]
@anikbrazeau can you re-test this one 

I think https://github.com/cds-snc/platform-forms-client/pull/3218 should fix

**Comment by timarney** [comment]
Closing as this is fixed -- can re-open as needed.
