### ISSUE TITLE
Publishing checklist not recognizing empty Privacy statement / Confirmation message

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3178]
## Description
The publishing checklist helps ensure people meet all the criteria before publishing a form, this includes the need for a privacy statement and a confirmation message. There seems to be some inconsistencies in this list recognizing whether the criteria are met -- it checks off items that are still empty.

## Steps to reproduce
1. Create a form without a privacy statement and without a confirmation message
2. Go to Publish
3. See what items are checked 

## Details
- **Browser**: Chrome
- **Operating system**: (Mac
- **Environment**: App router PR
- **Language**: English/French
- **Viewport**: Desktop

## Expected behaviour
Only allow publishing when there is a privacy statement and when there is a confirmation message

## Screenshots or videos

https://github.com/cds-snc/platform-forms-client/assets/38330843/1311b8d1-2d55-49d0-9676-78664a72483b

**Comment by dsamojlenko** [comment]
Fixed here: https://github.com/cds-snc/platform-forms-client/pull/2583/commits/9df7acadc668ac2ab5a15b724501fd94e7247d4a

**Comment by anikbrazeau** [comment]
Fixed, thank you!
