### ISSUE TITLE
Publishing a form does not bring you to the post-publishing page with links

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3179]
## Description
Something is not working when publishing a draft form.

## Steps to reproduce
1. Go to draft form
2. Click on "Publish" in the left menu
3. Complete all the requirements in the checklist
4. Click Publish
5. End up on a blank form in "Edit"

## Video recording

https://github.com/cds-snc/platform-forms-client/assets/38330843/ff145d64-0464-4d6c-b9c1-9964f9a1b6d1

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Aoo router PR
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
A page with links to the published form.

https://github.com/cds-snc/platform-forms-client/assets/38330843/7024db88-1b22-4ff5-ade1-455ec7a2c573

**Comment by anikbrazeau** [comment]
Linked to #3161

**Comment by timarney** [comment]
ref: https://github.com/cds-snc/platform-forms-client/pull/3218
