### ISSUE TITLE
Cannot access "sign off on x responses"

### ISSUE THREAD

**Issue by wmoussa-gc** [cds-snc/platform-forms-client#3180]
## Description
Accessing sign off on responses leads to page not found

<img width="1081" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/70960477/7dd66a63-addf-4583-a07e-c65f5824a016">

<img width="1323" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/70960477/50eb8fa6-f4db-4bc9-818d-72fb25824706">

URL being sent to: https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/en/&#x2F;en&#x2F;form-builder&#x2F;responses&#x2F;clpsy56bk000mvq83k8pyyrxa

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: [Preview](https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/)
- **Language**: English
- **Viewport**: (screen size, zoom level, pixel ratio...)
- **Output**: (form ID, link, JSON form file...)

## Expected behaviour
A clear and concise description of what's expected instead.

## Screenshots or videos
Visual proof to help explain the problem.

## Additional context
Any other information about the problem here.

**Comment by timarney** [comment]
Is this on staging or the app router ?

**Comment by wmoussa-gc** [comment]
app router

**Comment by timarney** [comment]
Added the app router label

**Comment by wmoussa-gc** [comment]
dupe of https://github.com/cds-snc/platform-forms-client/issues/3170
