### ISSUE TITLE
Cannot submit "Support form"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3184]
## Description
Problem when submitting support form

## Steps to reproduce
1. Go to `/en/form-builder/support`
2. Fill out required fields
3. Submit

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App router PR
- **Language**: EN/FR
- **Viewport**: Desktop

## Screencapture
https://github.com/cds-snc/platform-forms-client/assets/38330843/5ee13ed7-0685-4171-86a5-0ada93363de9

## Expected behaviour 
https://github.com/cds-snc/platform-forms-client/assets/38330843/dd004f8b-8f0e-41b1-961b-20a11eb98dbd

**Comment by thiessenp-cds** [comment]
Looks like an issue with the environment. It works locally but not in the PR environment. I'll close this for now
