### ISSUE TITLE
App router: Test responses throw an error on a draft form

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3186]
## Description
When I test out a form in /Test, I get an error saying "Sorry there is a problem submitting your response" within the dotted border. 

## Expected behaviour
To see the response submitted successfully based on the requirements of the form in /Test. 

## Screenshots or videos
Video attached 

https://github.com/cds-snc/platform-forms-client/assets/16671230/24dd6670-10dd-4beb-bf1e-fdcd59701296

Any other information about the problem here.

**Comment by anikbrazeau** [comment]
Related to #3175

**Comment by timarney** [comment]
@anikbrazeau can you re-test now?

https://gcdigital.slack.com/archives/C06FNT23KBR/p1706885071368139?thread_ts=1706818671.457889&cid=C06FNT23KBR

**Comment by anikbrazeau** [comment]
Still encountering the error when I re-test: 
![Screenshot 2024-02-05 at 8 34 34 AM](https://github.com/cds-snc/platform-forms-client/assets/38330843/8f1a5d1c-a620-487a-969a-cbff0671e44c)

**Comment by anikbrazeau** [comment]
https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/en/form-builder/preview

[give-us-feedback-2024-01-30.json](https://github.com/cds-snc/platform-forms-client/files/14170874/give-us-feedback-2024-01-30.json)

**Comment by timarney** [comment]
Works via https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/en/form-builder/preview/cls9bboqu00005ybde8sfjvk7

Closing per Slack
