### ISSUE TITLE
Confirmation message and privacy statement do not import from JSON file to form builder

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3187]
## Description
Missing confirmation message and privacy policy when importing a form file

## Steps to reproduce
1. Go to GC Forms
2. Click on Open a form file
3. Import this form file
[give-us-feedback-2024-01-30.json](https://github.com/cds-snc/platform-forms-client/files/14100675/give-us-feedback-2024-01-30.json)
4. Go to "Edit"
5. Notice empty Privacy and Confirmation sections
6. Go to Publish
7. See how items also appear checked (see #3178) 

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: App router PR
- **Language**: English
- **Viewport**: Desktop
- **Output**: cls0izj0g0001111d5g17lmm0

## Expected behaviour
Maintain all parts of the form that should be imported

## Screenshots or videos

https://github.com/cds-snc/platform-forms-client/assets/38330843/654fc0d5-efac-4b1d-8150-b35b6c9024f4

**Comment by dsamojlenko** [comment]
Fixed here: https://github.com/cds-snc/platform-forms-client/pull/2583/commits/9df7acadc668ac2ab5a15b724501fd94e7247d4a

**Comment by anikbrazeau** [comment]
Appears to be fixed! Thank you!

**Comment by dsamojlenko** [comment]
the previous fix introduced another bug. re-opening to continue tracking.

**Comment by timarney** [comment]
@anikbrazeau can you re-test now I think 

https://github.com/cds-snc/platform-forms-client/pull/3218

Fixed.

**Comment by timarney** [comment]
Closing --- re-tested on preview link.
