### ISSUE TITLE
Back button does not work to go back to "All forms"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3189]
## Steps to reproduce
1. Go to "Forms" dashboard
2. Click on "Responses page" for a form
3. Try to go back
4. Sometimes nothing happens
5. Sometimes goes elsewhere (Ex: Profile)

## Details
- **Browser**: Chrome
- **Operating system**: Mac Sonoma
- **Environment**: App router PR
- **Language**: English and French
- **Viewport**: Desktop

## Expected behaviour
Ability to navigate site with back button

## Screenshots or videos

https://github.com/cds-snc/platform-forms-client/assets/38330843/04f27f3b-b45c-4f6b-b409-6e16dfc8b7cd

**Comment by thiessenp-cds** [comment]
I wasn't able to reproduce this. Maybe there was a fix in the mean time. @anikbrazeau are you able to reproduce this error?

**Comment by anikbrazeau** [comment]
Fixed!
