### ISSUE TITLE
App router: Tabs for /Response page is not formatted properly

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3194]
## Description
The "Change settings" pill is not on the far right of the screen (where it was before).

## Details
Just a styling/placement fix

## Screenshots or videos
<img width="1709" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/16671230/b077918a-4502-401d-8e6a-53e56ad0948d">

**Comment by anikbrazeau** [comment]
Related to #3174

**Comment by timarney** [comment]
@thiessenp-cds 

I pushed up a fix for this 
<img width="989" alt="Screenshot 2024-02-05 at 12 50 16 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/5fc829f1-0b61-4f6e-880e-01a17595edf6">
