### ISSUE TITLE
Application error (full screen) when previewing

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3196]
## Encountering full screen application error:

`Application error: a client-side exception has occurred (see the browser console for more information).`

<img width="1002" alt="Screenshot 2024-01-30 at 4 14 19 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/7ba37e5d-9985-4742-af77-f0ac9e3eb347">

## Steps to reproduce
Not quite sure... was just navigating between left-menu elements: "Edit" / "Preview" / "Settings" / "Publish" when it happened

## Details
- **Browser**: Chrome
- **Operating system**: Mac Sonoma
- **Environment**: App router PR
- **Language**: English
- **Viewport**: Desktop
- **Link**: https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/en/form-builder/preview

## Expected behaviour
Continue to use app or get a path to help resolve situation.

## Screencapture
https://github.com/cds-snc/platform-forms-client/assets/38330843/72e3d3cf-324d-4401-80a4-1b5d63faa43c

https://github.com/cds-snc/platform-forms-client/assets/38330843/8aa6ce9d-51a6-4c49-b294-45091f09b2df

**Comment by thiessenp-cds** [comment]
I wasn't able to reproduce this bug. It may have been fixed through resolving a different issue. @anikbrazeau could you try again and see if the bug still exists?

**Comment by anikbrazeau** [comment]
Wasn't able to reproduce it, so may be fixed?
