### ISSUE TITLE
Link to Settings to open a form does not work

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3197]
## Description
On the Responses page, the link to open a closed form does not redirect to settings. It also is not accurately portraying whether the form is open or closed.

## Steps to reproduce
1. Go to Form "Lost of responses"
2. Click on "Open the form in Settings", notice nothing happens
3. Then go to "Settings" > "Form management" to see the form status

## Details
- **Browser**: Chrome
- **Operating system**: Mac Sonoma
- **Environment**: PR App Router
- **Language**: EN + FR
- **Viewport**: Desktop
- **Form ID**: `clrz94gmi0001yw08zkxzynx0`

## Expected behaviour
Navigate to Form status in Settings as expected

## Screenshots or videos
https://github.com/cds-snc/platform-forms-client/assets/38330843/426b3d02-3105-486a-8128-1b0c2cc6dc9c

**Comment by thiessenp-cds** [comment]
Resolved in #[3217](https://github.com/cds-snc/platform-forms-client/pull/3217)
