### ISSUE TITLE
No validation for sharing a form

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3198]
## Description
Appear to "send" form (share a form file) without entering an email address

## Steps to reproduce
1. Go to a form
2. Click on "Share" > "Share by email" > "Send"
3. Appears successful even with empty email field

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR App router
- **Language**: English
- **Viewport**: Desktop
- **Form ID**: `cls0tzcw30000auo270xzhpyo`

## Expected behaviour
- Error if email is not valid
- Only show success message sent if actually sent

## Screenshots or videos

https://github.com/cds-snc/platform-forms-client/assets/38330843/85ce408d-023d-4c50-93f6-d2dfb5cec5f4

**Comment by thiessenp-cds** [comment]
@connorscarolyns and @samsadasivan would you know the expected behavior? I just tested this on Staging and I see the same behavior. 
Currently the code has validation in place for an email. If the input fails validation, the text is not added as tag. But the form can still submit the invalid email and does not show an error.
E.g. https://forms-staging.cdssandbox.xyz/en/form-builder/settings/cls3luu49000012u1xergaobf

**Comment by timarney** [comment]
Going to remove the app router label for this one --- we can look to fix outside of the app router updates.

**Comment by anikbrazeau** [comment]
# Expected behaviour

## Prevent empty or invalid submission

## Display error message

**EN**: `Enter a valid email address.`
**FR**: `Veuillez entrer une adresse courriel valide.`

**Comment by Abi-Nada** [comment]
Closing this card as the issue no longer persists. Created a new issue to update the error messaging here (#[3916](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3916)). ^


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1abe701977b6fedf5919ef5bf27e4bce7c05d7a/Screen%20Recording%202024-06-28%20at%2010.15.15%E2%80%AFAM.mov)
