### ISSUE TITLE
Feature flag titles missing

### ISSUE THREAD

**Issue by wmoussa-gc** [cds-snc/platform-forms-client#3200]
![image](https://github.com/cds-snc/platform-forms-client/assets/70960477/c51d003e-fe96-41b0-90d2-8045f723da21)

**Comment by wmoussa-gc** [comment]
https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/en/admin/flags

**Comment by timarney** [comment]
Going to add can't reproduce as it works locally --- might be a preview env issue.

<img width="744" alt="Screenshot 2024-02-02 at 8 37 09 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/1440b653-fa36-4ccf-bc90-94f52dbfd343">
