### ISSUE TITLE
Can't see the Manage Ownership section in Form Management

### ISSUE THREAD

**Issue by wmoussa-gc** [cds-snc/platform-forms-client#3201]
My form id: https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/en/form-builder/settings/cls17s8ci0001ygrdhasbaidx/form

![image](https://github.com/cds-snc/platform-forms-client/assets/70960477/9a71a512-a16c-4129-b8de-98edeb35d248)

**Comment by timarney** [comment]
@wmoussa-gc is this as a user or "admin" manage all forms?

Only admins / manage all forms can modify the form owners correct @dsamojlenko (I think you set this up)
