### ISSUE TITLE
Error not working for deleting a published form with responses

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3211]
## Description
When trying to delete a form, nothing happens and no error message is displayed. This is blocked because there are responses that need to be downloaded, however the user is unaware of what needs to happen.

## Steps to reproduce
1. Go to "Forms"
2. Ensure you have a published form with at least one response that has not yet been signed off
3. Click on "More" on the form card
4. Select "Delete"
5. Nothing happens

## Details
- **Browser**: Chrome 
- **Operating system**: Mac Sonoma
- **Environment**: Production
- **Language**: EN
- **Viewport**: Desktop

## Expected behaviour
Delete or get error with what needs to be done before deleting

## Screenshots or videos

https://github.com/cds-snc/platform-forms-client/assets/38330843/3469440b-a0a7-4527-b735-27fc218365e8

**Comment by anikbrazeau** [comment]
Related to #3160

**Comment by wmoussa-gc** [comment]
Im also having an issue deleting in staging, @anikbrazeau can you record what you see in staging?

**Comment by anikbrazeau** [comment]
Also get it in staging: 

https://github.com/cds-snc/platform-forms-client/assets/38330843/4f8ca667-07f5-44b8-9bbf-478ef3e2217f

**Comment by anikbrazeau** [comment]
Happens in production too: 

https://github.com/cds-snc/platform-forms-client/assets/38330843/40985d83-4f04-46fb-ab32-ced0db2636f2
