### ISSUE TITLE
Padding on Admin back button

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3236]
## Description
The "Back to Accounts" link is glued to the side of the window

## Steps to reproduce
1. Sign in on an account with admin privileges
2. Go to "Your account" > "Administration" > "Accounts" > "Manage forms"
3. See the back button with no spacing

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
A consistent margin across the application

## Screenshot

<img width="1372" alt="Screenshot 2024-02-05 at 3 41 54 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/91dfae34-9361-45b5-bf5f-04f8cbe65a42">

**Comment by timarney** [comment]
Noting we'll be updating the left nav

https://github.com/cds-snc/platform-forms-client/issues/3219

So we should likely follow suit and move the back button out of the left nav per https://github.com/cds-snc/platform-forms-client/pull/3115

**Comment by Abi-Nada** [comment]
Issue no longer persists
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c2e4a7c79bf20b305f6c15df57687a0000eaa22/Screenshot%202024-06-28%20at%2010.10.31%E2%80%AFAM.png" alt="Screenshot 2024-06-28 at 10.10.31 AM.png" />
