### ISSUE TITLE
Saved form not showing up in "Forms"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3238]
## Description
Form shows as saved in edit mode but going back to all forms, there is no card that shows.

## Steps to reproduce
1. Create account
2. Create a form
3. Add some blocks
4. Name form
5. Go to "Forms"
6. No form appears
7. Open a form
8. Go to "Forms"
9. No form appears
10. Go back to Edit
11. Says "Saved"

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR preview
- **Language**: English and French
- **Viewport**: Tablet

## Expected behaviour
Form saves and shows up in Forms once it exists

**Comment by timarney** [comment]
Merged a fix for this --- should be up on preview env soon.

**Comment by anikbrazeau** [comment]
Tested on preview, thanks for the fix! :D
