### ISSUE TITLE
Inconsistencies in top nav and card layout 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3240]
## Description
Getting inconsistent top nav (sign in / sign out) and form card layout (one column / two column) occasionally.

## Steps to reproduce
_Not quite sure what triggered the differences but did something close to this:_
1. Created a new account
2. Created a new form without a name
3. Noticed the form card in "Forms" was long (one-column layout)
4. Named the form file in "Edit"
5. Went back to "Forms" and noticed form card was smaller (two-column layout)
6. Navigating in French noticed the unauthenticated top nav with "Sign in" as an option appeared even though I was signed in
7. Went back to form and it reverted to signed in top nav as expected

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR preview env
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Predictable and consistent behaviour and layouts

### Card layout discrepancies

![Capture](https://github.com/cds-snc/platform-forms-client/assets/38330843/a0292509-edd7-428b-a080-1004aac1fe57)

![card small](https://github.com/cds-snc/platform-forms-client/assets/38330843/d6681633-6d3d-4257-af77-c6b08151385f)

**Comment by anikbrazeau** [comment]
Potentially related to #3168

**Comment by thiessenp-cds** [comment]
I was unable to reproduce this behaviour on Windows+Edge (or MacOS+Chrome). Is this error still happening for you?

**Comment by anikbrazeau** [comment]
Yes, getting the one-column layout with the creation of a new account and then the creation of a new form saved without a name.

**Comment by thiessenp-cds** [comment]
Thanks for retesting. The language switching idea, nice, but hmm I still can't reproduce this locally in my windows virtual machine. Also it looks like the PR environment is no longer reachable - maybe it destroys itself after N days. So I couldn't test on my tablet.
We'll be doing some serious refactoring of the application code in the coming weeks. I suspect this bug will resolve itself but I'll leave it open for re-testing just encase.
