### ISSUE TITLE
Radio button becomes distorted when text is too long

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3243]
## Description
When you add a lot of text to a radio button option, the radio button becomes distorted.

## Steps to reproduce
1. Add "Radio Button" element
2. Fill in an option with a long text
3. Preview the form

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Prod
- **Language**: English

## Expected behaviour
Ideally the text shouldn't be squished against the radio button/should be consistent with the other radio buttons.

## Screenshot
<img width="1392" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGs0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19fefca8fe7167bf4773c47dc2ab572668326bbc/Screenshot%202024-02-06%20at%204.05.53%E2%80%AFPM.png" alt="Screenshot 2024-02-06 at 4.05.53 PM.png" />

**Comment by jprince-cds** [comment]
Reported in [Freshdesk ticket 16615](https://cds-snc.freshdesk.com/a/tickets/16615)

**Comment by timarney** [comment]
Merged a fix for this as it came up in a support ticket --- 

https://github.com/cds-snc/platform-forms-client/pull/3593

I didn't test radio elements but should be fixed as well
