### ISSUE TITLE
GC Forms Public Knowledge Repository

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3259]
### User Story:
As a GC Forms user, I need access to an updated, comprehensive knowledge repository that provides clear instructions and support for using the application, so that I can self-serve to find solutions to my problems and answers to my questions without needing to schedule 1:1 video calls with the support team, allowing for more independence and efficiency in my use of the application.

### Description:
The need for a public knowledge repository has become evident due to an increasing demand for 1:1 video calls with our support team, indicating that our current support channels may not fully meet client needs. This repository will house up-to-date documentation, guides, FAQs, and tutorials designed to empower our clients to effectively use GC Forms. It aims to reduce the strain on the support team and provide clients with immediate, 24/7 access to help resources. The project will also explore the balance between providing self-serve resources and the desire for personal walkthroughs, potentially including feedback mechanisms to understand client preferences better.

#### Content Audit and Needs Analysis:
- [x] Conduct an audit of existing materials, identifying what is outdated or missing
- [x] Work with Support/Analyze support tickets and feedback to identify common questions and challenges faced by users

#### Content Development Strategy:
- [x] Develop a strategy for creating and maintaining the knowledge repository, including guidelines for regularly updating content to keep pace with product changes
- [x] Decide on the mix of content types (written guides, video tutorials, FAQs, Support canned responses) based on user behaviour and preferences

#### Content Creation and Organization:
- [x] Create comprehensive, easy-to-understand content covering all aspects of using GC Forms, from basic functionalities to advanced features

#### Feedback Mechanism Implementation:
- [x] Implement a mechanism for collecting user feedback on the repository's usefulness and areas for improvement
- [x] Include options for users to contact Support if they cannot find the help they need within the repository

#### Promotion and Education:
- [x] Product to collaborate with Growth on a plan to promote the knowledge repository to existing and new clients, ensuring they are aware of this resource (potentially consider integrating repository highlights or tips into regular communication with clients to encourage ongoing engagement?)

**Comment by anikbrazeau** [comment]
Flag to check in with Gayaneh on growth who is analyzing and categorizing issues.

**Comment by anikbrazeau** [comment]
Updates: 

- Cleaned up outdated articles in FreshDesk and archived those that were public for GC Forms
- Folded templates and getting started into guidance on how to use GC Notify
- Added section to top menu of GC Articles Marketing Site
- Ported over help articles on collaborating and updating a published form
- Linked the request for alternate branding in this "help centre" of sorts
- Added a search bar to help people find things based on keywords
- Added a banner and button (CTA) to contact support if didn't find adequate help
- Published and gathering feedback from key stakeholders

Next: 
- Supplement basic articles with more info on "Responses" and "Conditional logic"

**Comment by anikbrazeau** [comment]
Meeting with Gayaneh Thursday March 28 to go through the ticket analysis which is now complete.

**Comment by anikbrazeau** [comment]
Analytics here: https://analytics.google.com/analytics/web/#/p348891142/reports/intelligenthome
