### ISSUE TITLE
File Upload Scanner: File validation component

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3293]
### User Story
As a developer,
I want to fix the file validation component and enhance our file scanning feature,
So that the application can reliably identify file types and ensure that all uploaded files are free from malware, corruption, or malicious content.

### Context:
Initially with this work, we were uploading files and storing them in S3 buckets. These weren't being scanned because we were relying on email delivery/Outlook to perform these checks for us. But now that we're using the Response Database as a delivery response destination, we need to ensure that these files are being scanned to validate that they're clean and not corrupted/malicious.

#### Technical Obstacles
- We currently try to validate the file type during submission however the `mmmagic` library that were previously relied on does not interact well with the newer versions of Node.  

### Out of Scope
Any type of file retrieval of uploaded files is currently out of scope and will be handled in a separate Issue.
### Acceptance Criteria:
- [x] Implement, if possible,  a new file validation function to replace `mmmagic`.  If not possible then we'll need to document and come up with some mitigation strategies.  (Can be performed on the App Router or Develop branch)
- [x] Document where the attribute can be found on an uploaded file that determines if it has succeeded or failed the malicious file scanning process.
- [x] Use latest scan files module (v9.2.3)

**Comment by craigzour** [comment]
WIP How to retrieve and use file scan results https://docs.google.com/document/d/1tUTzEafp3V5hNiD1ghVU1OXRbMlq421x9dyTNoxrHlc
