### ISSUE TITLE
Forms Publishing Page/Modal + (Non-)Administrative Form Setting

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3313]
### User Story

As a member of the GC Forms team,
I want to collect data on the forms being published,
So that we can make informed decisions and understand how the application is being used by users, without manually validating each individual published form.

### Acceptance Criteria:
- [x] Publishing Page modal designs are updated based off testing findings/feedback
- [x] We include a way to collect whether or not the form is being used for administrative purposes (consideration: we are not making that designation for them. We’re asking the client to make a selection somewhere in the product, rather than us seeing what kind of form it is and determining whether we think that’s administrative or not)
- [x] Implementation of designs

**Comment by anikbrazeau** [comment]
Latest content: https://www.figma.com/file/yQmBXLZ07qFElbRE89kdal/GC-Forms---Preview-and-Share?type=design&node-id=3844-7394&mode=design&t=nCyWyPbB9vw5YpCV-4

**Comment by anikbrazeau** [comment]
**Latest content**: https://www.figma.com/file/aFRMxTx2rGCJp2xTYdYc5Z/GC-Forms-SalesForce-Integration?type=design&node-id=3002-78&mode=design&t=ksJFzlI5b88Q7it5-0

**Comment by Abi-Nada** [comment]
Figma file: https://www.figma.com/file/aFRMxTx2rGCJp2xTYdYc5Z/GC-Forms-SalesForce-Integration?type=design&node-id=3002-78&mode=design&t=KVCvJIL82zt9jJso-0
