### ISSUE TITLE
Blank form responses show up as "No Response" (EN) after filling out a FR form

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3329]
## Description
Blank form responses show up as "No Response" (EN) in email delivery, after filling out a FR form
Flagged from client: [Support Ticket 16930](https://cds-snc.freshdesk.com/a/tickets/16930)

## Steps to reproduce
1. Go to any Form (**with responses set to email delivery**)
2. Toggle to the French interface
3. Leave some blank questions and submit the form
4. See error in the email: it shows as "No Response"

## Expected behaviour
Blank answers should show in French if filling out the French form?

## Screenshots or videos
<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1BhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1303c617da717c69d7b0572309a662441bd2b601/Screenshot%202024-03-13%20at%201.50.24%20PM.png" alt="Screenshot 2024-03-13 at 1.50.24 PM.png" />

**Comment by anikbrazeau** [comment]
This is no longer an issue, blank answers have been replaced by a `-`.

**Comment by anikbrazeau** [comment]
A potential solution: use a dash `-` instead of a string of words so that it work in EN and FR if translation isn't possible?
