### ISSUE TITLE
QA Testing: Settings

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3338]
### Description:

To compile all the issues raised when specifically testing the Settings page of GC Forms.

**Comment by timarney** [comment]
PR is up for this

https://github.com/cds-snc/platform-forms-client/pull/3521

@Abi-Nada 

For now a work around has been added to get the current component that selects user to work for us.

Moving forward I think we should do a few things:

1) Look at replacing that component with something that does use style tags that get inlined to the page.

2) Look at moving the form ownership out of "form builder manage forms" and into the admin itself
There's really no need to be in the admin -> click multiple links to land form builder manage tab _. set the owners and than go back to the admin.

**Comment by Abi-Nada** [comment]
Hi @timarney , thanks for the follow-up!

For 1) Makes sense to replace the component so it aligns with the new updates with the CORS script. How complicated is it/what's the level of effort to replace the component?

For 2) Just wanted to flag that as part of our OKR's this year (OKR4.2), we'll be looking into turning the "add a collaborator" self-serve for users, so they don't have to rely on Support (aka Jimmy) to add folks to their forms. I think we should keep it within the form builder for now, until we start tackling that piece of work and we can see what makes sense then, if possible?
