### ISSUE TITLE
[solution pending] Blank conditional responses confusing

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/platform-forms-client#334]
The Public Service Award of Excellence Form has questions that are conditional on whether it's a team or individual nomination. During testing participants using different forms of assistive technology were confused by questions with "no response" as answer, as there's no indication that they're linked to the individual or team condition that wasn't selected, and therefore wasn't applicable.

**Recommendation**
- If a form uses section headings, print the headings in the email
- Use conditional logic to eliminate questions that don't apply
- If not using conditional logic, include the condition beside the question labels they're linked to

![Screen Shot 2021-08-03 at 7.40.11 PM.png](https://images.zenhubusercontent.com/60e730a033423eca358a84c7/4d8a1073-ad20-48c9-9f30-87ecf27134e3)

**Comment by bryan-robitaille** [comment]
@falila @craigzour Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/GCForms-60cb8929764d71000e481cab/issues/cds-snc/platform-forms-client/334?planning-poker)
