### ISSUE TITLE
"Forms" cards switched to single file.

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3343]
## Description
It seems like toggling to "Forms" took a little bit of a longer time. When I tried to toggle between the "All", "Drafts" and "Published" tabs, there was a bit of a lag and then eventually the cards switched from two cards in each row to single file.

## Steps to reproduce
1. Go to "Forms" in the PR Environment
2. Toggle between the tabs All/Drafts/Published
3. See error: At some point it turned to single file

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
Expected consistent format of the cards

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODNuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ca4a5660e9259aef04bedd7f689516f4758182d/Screen%20Recording%202024-03-16%20at%205.25.11%E2%80%AFPM.mov)

## Additional context
Also happens when you refresh your screen:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODduQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad09e042c96e6a998902782eeac04ade60125ba9/Screen%20Recording%202024-03-16%20at%205.36.53%E2%80%AFPM.mov)

**Comment by thiessenp-cds** [comment]
@Abi-Nada are you still able to reproduce this bug? If you can, are you testing on your laptop or on an external monitor? Just wondering about the browser window size.
I'm not able to reproduce it in Chrome on an external monitor or on my macbook e.g. running full screen

**Comment by thiessenp-cds** [comment]
Update: 
I was able to reproduce this bug consistently in FireFox. If I navigate from the Forms page to the Form-builder and then use the Browser back button, the Form page renders cards in a 1-column view.
In Chrome, I could sometimes reproduce this by doing the same as above but the behaviour was not consistent.

**Comment by thiessenp-cds** [comment]
I tried removing the inline style and replacing it with a custom CSS class:
```.cards-layout-grid {grid-template-columns: (auto-fill, minmax(27rem, 1fr));}```
The CSP error no longer showed up in the dev console BUT the 1-column layout bug would still occasional happen. So it doesn't look like a CSP related error.

**Comment by thiessenp-cds** [comment]
Today I can't reproduce this bug.. I'll label this as "cannot reproduce" and see if I can reproduce it at a later time

**Comment by thiessenp-cds** [comment]
I'm going to try using Tailwind classes instead of inlining CSS styles for the Grid layout. I can't think of anything else to try and this may fix the problem.

**Comment by thiessenp-cds** [comment]
This seems to have fixed the issue. If it comes up again, feel free to reopen this ticket or create a new one
