### ISSUE TITLE
[QA Testing - New Router] Address Autocomplete Not Populating in Preview

### ISSUE THREAD

**Issue by ShadeWyrm** [cds-snc/platform-forms-client#3347]
## Description
Following the QA Testing Steps in the Excel, the Preview does not auto-complete address fields.

## Steps to reproduce
"1.  Select “Add form element” 
2.  Scroll to the Address input block and select it
3. Select a input field under the Address block 
4. Navigate to the input block menu and select “More” 
5. Scroll to “Select an autocomplete attribute”
6. Select “Full address” in the drop down menu 
7. Save your selection"
8. Go to Preview.
9. Type in any of the newly added fields, they're treated as regular textboxes.

## Details
- **Browser**: Chrome
- **Operating system**: Mac OSX
- **Environment**: Staging
- **Language**: English

## Expected behaviour
The autocomplete autocompletes any of the fields.

**Comment by dsamojlenko** [comment]
Clarification required: don't believe there is a "Full address" autocomplete option in the dropdown?
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGpyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4fcad80c4d8666d08df931458b3ce401a334d24/image.png" alt="image.png" />

... and from my testing, looks like the appropriate autcomplete property is being added to the inputs <img width="1620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5yQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a36c11831519799cff0aedf59058554db803644/image.png" alt="image.png" />

From here, the behaviour of the inputs is browser-dependent.

**Comment by ShadeWyrm** [comment]
I may of mistaken the functionality!~ I assumed it was a functional autofill ala : Type in Ont and get Ontario.

**Comment by timarney** [comment]
In this case it's just the browser auto-complete.  

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

Going to close.

Note see: https://github.com/cds-snc/platform-forms-client/pull/3139 work that was done on a typeahead component
