### ISSUE TITLE
[QA Testing - New Router] Duplicating a Field with Logical Flow + Page Text doesn't display the duplicate.

### ISSUE THREAD

**Issue by ShadeWyrm** [cds-snc/platform-forms-client#3349]
## Description
When you duplicate a question that was a logical flow from another question, that question never appears. It may be related to a feature flag from notes in the QA Testing script? 

Note: This also happens when you duplicate a "Page Text"

## Steps to reproduce
"1. Navigate to /Builder 
2. Add a form element: radio, checkboxes, or dropdown 
3. Fill in the name of the question 
4. Populate 3 options in the form element 
5. Add another form element: Short answer 
6. Fill in the name of the short answer question 
7. Navigate back to the first form element and “Add a rule” 
8. Connect one of the options to the second short answer question 
9. Save rules 
10. Navigate to /Test 
11. Select the option to show the short answer question 
12. Duplicate this field, the new duplicate never appears in the preview.

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
-  **Language**: English

## Expected behaviour
The duplicated field appears as if it was a new question.

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2pyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8419b04a908aabbd1fa14d22ef9fe8e7d3d36e6c/Screen%20Recording%202024-03-18%20at%2011.10.14%E2%80%AFAM.mov)

**Comment by ShadeWyrm** [comment]
Checkboxes and Radio Buttons.

If you check the question "Do We" should make "Do you like?" and "Do you like ANIMALS?" appear, but it only makes the first.

[complex-questions-for-think-thoughts-2024-03-18 (1).json.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXZzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0144b95480e942b7053ac9864b5c05d199d80ae6/complex-questions-for-think-thoughts-2024-03-18%20%281%29.json.zip)

**Comment by timarney** [comment]
@ShadeWyrm 

Thinking the form might have been created when a feature flag for groups was on in the preview environment when it should have been.

If I empty out the groups field in the json file

```
"groups":{},
```

Here's the fixed file
[complex-questions-for-think-thoughts-2024-03-18-edited.json](https://github.com/cds-snc/platform-forms-client/files/14641856/complex-questions-for-think-thoughts-2024-03-18-edited.json)

I believe the rules now behave as they should.

Now that the flag is off for the preview environment there shouldn't be a way for that groups node to get populated ...

Can you try re-creating with the current preview environments

**Comment by timarney** [comment]
Okay looks like this on is related to https://github.com/cds-snc/platform-forms-client/issues/3358 which is now fixed.

Note a fresh form will need to be created.

**Comment by timarney** [comment]
@ShadeWyrm when you get a chance can you re-test?

**Comment by ShadeWyrm** [comment]
Looks good!~  :D

**Comment by timarney** [comment]
Okay will close this one thanks.
