### ISSUE TITLE
[QA Testing - New Router] Submit during Preview (Test) of Form Fails 403 Error

### ISSUE THREAD

**Issue by ShadeWyrm** [cds-snc/platform-forms-client#3350]
## Description
Clicking Submit on the Preview page fails with an error. Console opens to a 403 error.

## Steps to reproduce
1. Make a form.
2. Add a question.
3. Submit

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging

## Expected behaviour
It saves the response, and can be viewed.

Instead of :

{
    "message": "Request failed with status code 403",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 403\n    at https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/_next/static/chunks/7908-59e916e2d9d33bc5.js:6:40162\n    at XMLHttpRequest.h (https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/_next/static/chunks/7908-59e916e2d9d33bc5.js:6:40302)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 60000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "Content-Language": "en",
            "X-CSRF-Token": "48ebd53473e83581c907dbc2e84877a9b22f44c1a2c8daaded93571188ca8596"
        },
        "url": "/api/submit",
        "method": "post",
        "data": "{\"1\":\"{\\\"value\\\":[\\\"Be Me.\\\"]}\",\"formID\":\"cltwzkhoy0000iimyd3bmqeao\",\"securityAttribute\":\"Protected A\"}"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 403
}

**Comment by dsamojlenko** [comment]
Form submission in both Preview and public forms is currently broken due to CSRF protection which has changed in next-auth. This submit action likely needs to be converted to a Server Action.

**Comment by Abi-Nada** [comment]
Re-tested and issue no longer persists!
