### ISSUE TITLE
Link to published form on Published page not working

### ISSUE THREAD

**Issue by dsamojlenko** [cds-snc/platform-forms-client#3351]
<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMC9zQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63309be0e03af6d6dc241b6b51dde415afc2fb4d/image.png" alt="image.png" />

This code  depends on the old NEXTAUTH_URL environment variable that has been removed.

<img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMURzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f32268fcff4f32cdccf1b08429342e9a375c4636/image.png" alt="image.png" />

**Comment by timarney** [comment]
PR https://github.com/cds-snc/platform-forms-client/pull/3374

**Comment by timarney** [comment]
merged
