### ISSUE TITLE
"Manage Ownership" search box

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3352]
## Description
The search box for "Manage Ownership" doesn't appear.

## Steps to reproduce
1. Open up a form (draft)
2. Go to Settings
3. Go to the "Form Management" tab
4. Scroll down to the "Manage Ownership" section and see error.

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
Ideally we (not other clients, to date) should be able to search folks to add to the form.

<img width="1652" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--412d70fcc3f8b0998277ce068e33190ba8134c6a/Screenshot%202024-03-18%20at%201.24.15%E2%80%AFPM.png" alt="Screenshot 2024-03-18 at 1.24.15 PM.png" />

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkhzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68d916a42d17fa4e3478493a6753c5838049e920/Screen%20Recording%202024-03-18%20at%201.22.51%E2%80%AFPM.mov)

## Additional context
Any other information about the problem here.

**Comment by timarney** [comment]
> 6958-0492abac00a8e2d0.js:1 Refused to apply inline style because it violates the following Content Security Policy directive: 

Believe this issue is limited to the preview server --- 

I would suggest we take a look once the PR is on the staging server.

**Comment by timarney** [comment]
@Abi-Nada going to assign this to you --- **we'll need to re-check once this is on staging** -- the styles get blocked on the preview url.

Maybe we add a check on staging label or something?

**Comment by timarney** [comment]
I took a further look at this --- looks like the CORS scripts we're updated to block how the styles are loaded for that component (in the app router branch --- better security) -- which means it's different vs current staging works. 

Will look into finding a solution for this.

**Comment by timarney** [comment]
This is fixed --- mostly.

@Abi-Nada code has been merged that uses the `nonce` value to ensure the styles are as safe as can be for inline styles.


That said --- depending on your entry point server components ...

The box may display as "slightly" styled.

<img width="600" alt="Screenshot 2024-04-29 at 3 48 11 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/f782c55b-47d5-47cc-933b-86f3c57d26fb">


If this happens --- refreshing the page will end up rendering the page with the nonce and things will style themselves properly.

<img width="600" alt="Screenshot 2024-04-29 at 3 48 33 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/892564db-612a-4d1d-8b9f-b30de11192da">

<br>

So this unblocks as far as actually being able to use the component.

I would suggest we look to replace it and or dig into how we can ensure the CSP / nonce is always set and made available to the page.
