### ISSUE TITLE
"Last Edited" form cards do not appear in chronological order

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3353]
## Description
The form that I last edited does not appear at the top of "Forms"

## Steps to reproduce
1. Go to create a new form
2. Save Draft
3. Toggle back to "Forms"
4. Observe it get lost into the void hehe (or alternatively, search for today's date and see different forms spread out)

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
The form that you last Edited would move up to the top of the "Forms" page

## Screenshots or videos
<img width="1445" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW5zQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1baf1dacfaadf6e7b773f19f18379f1111e286a/Screenshot%202024-03-18%20at%201.48.30%E2%80%AFPM.png" alt="Screenshot 2024-03-18 at 1.48.30 PM.png" />

**Comment by thiessenp-cds** [comment]
PR is ready for reviewing #3378

**Comment by Abi-Nada** [comment]
Re-tested and issue no longer persists! Woo!
