### ISSUE TITLE
Test 1.07 failed on preview - Duplicating a form question

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3358]
1. Add a “drop-down” element, type “1” in the question title - passed
2. Duplicate the drop-down element, type “2” in the question title - passed
3. Navigate to /Preview to see both drop-down questions labelled differently - failed

The duplicated question failed to appear in the preview screen.

- Refreshed the page, but it is still not there
- Navigated back to the editing screen, the question is present
- Navigated to the translation screen, the question is present
- Navigated to the preview screen, the question is still missing.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi93QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fa3ed2dbd540d5c928bcfc73c7b61e5d05967e1/screen-capture%20%281%29.webm)

**Comment by connorscarolyns** [comment]
[test-form-carolyn-2024-03-19.json.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3Z3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68257fd8d930daef3a5ca36a2aef2a13b4e9a060/test-form-carolyn-2024-03-19.json.zip)

**Comment by timarney** [comment]
This issue should now be corrected.

Note you will need to start a fresh form -- as forms created with this bug will not be able to recover.   This bug is limited to the preview env.

**Comment by Abi-Nada** [comment]
Re-tested and issue no longer persists! 🥳 @timarney as always you're the bestttttt
