### ISSUE TITLE
Keyboard nav: Translations loses contrast on hover

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3363]
## Description
When navigating the "Edit" page the text in the pill that says "Translations" turns white (cannot be read) when hovered.

## Steps to reproduce
1. Go to `/fr/form-builder/0000/edit` to create a new form
2. Tab through the parts of the page until you get to "Traductions"
3. See how the text disappears

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: QA Testing PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Be able to read the text in the pill

## Screenshots or videos

![empty pill](https://github.com/cds-snc/platform-forms-client/assets/38330843/53d1c275-a494-4816-9d52-9c46fd57a2b4)

**Comment by timarney** [comment]
Fix is merged.

**Comment by Abi-Nada** [comment]
@anikbrazeau can you re-test? :)

**Comment by anikbrazeau** [comment]
It's fixed!
