### ISSUE TITLE
Representative levels of hierarchy for titles and headings

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3366]
## Description
When creating a form on the "Edit" page, the size of the title is smaller than the headings and paragraph text that are levels below it in terms of hierarchy. 

## Steps to reproduce
1. Go to `/fr/form-builder/0000/edit` to create a new form
2. Enter a Form title
3. Add H2 and H3 to description
4. See discrepancy in text sizes

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: QA Testing PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
It's expected that H1/title will be bigger in font size than H2/H3/body text.

## Screenshots or videos
![hierarchy](https://github.com/cds-snc/platform-forms-client/assets/38330843/90968699-9cac-4b8a-8b77-068192d00c9a)

**Comment by dsamojlenko** [comment]
Bumped the font size up a bit
