### ISSUE TITLE
Typo FR - type ahead list

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3367]
## Description
"pstmi" --> "parmi"

## Steps to reproduce
1. Go to French "Edit" page
2. Click on "Ajouter un élément"
3. Scroll down to "Liste consultable"
4. See description with typo in fifth word of description

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App Router PR
- **Language**: French
- **Viewport**: Tablet

**Comment by dsamojlenko** [comment]
Fixed https://github.com/cds-snc/platform-forms-client/pull/2583/commits/0cacdd8fa58b410b32e8403e5f6f8ebe9dc880eb
