### ISSUE TITLE
Conditional rules link to English preset question label based on option, not French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3369]
## Description
When adding a rule to show a question based on a selection, the content in the modal is in French, but switches to English once in the form builder "Edit" interface.

## Steps to reproduce
1. Go to `/fr/form-builder/0000/edit`
2. Click on "Ajouter un élément"
3. Add checkboxes: "Cases à cocher"
4. Click on "Ajouter un élément" 
5. Add individual names "Noms individuels"
6. Add "Option 1" "Option 2" for the checkboxes
7. Add a rule "Ajouter une règle"
8. When "Option 2" is selected, show "Deuxième prénom" (middle name)
9. Save changes and see English in French interface even when editing in French

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Consistent language

## Screenshots or videos
![modald](https://github.com/cds-snc/platform-forms-client/assets/38330843/9a3d8ca4-6836-407d-99d2-b040f6bdd247)

![edit rules](https://github.com/cds-snc/platform-forms-client/assets/38330843/5397872a-720d-49d0-b9ef-a9b7965a3dcc)

**Comment by timarney** [comment]
Can you provide the JSON for this?

The options etc... are controlled via 

<img width="456" alt="Screenshot 2024-03-20 at 1 01 48 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/c2f38e6e-ff59-44b3-a090-d584e50a3ab2">

**Comment by Abi-Nada** [comment]
@anikbrazeau ^ Just following up on the JSON :)

**Comment by anikbrazeau** [comment]
[nom-2024-03-21.json](https://github.com/cds-snc/platform-forms-client/files/14696523/nom-2024-03-21.json)

**Comment by anikbrazeau** [comment]
This is happening when editing in French on the French interface.
<img width="934" alt="Screenshot 2024-03-21 at 10 22 57 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/e8b1dc5c-5b83-49d7-83c5-7435cffed696">
<img width="876" alt="Screenshot 2024-03-21 at 10 22 04 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/42fe8f13-7b74-4f3c-aa73-f6cd2e4d67d5">
<img width="1565" alt="Screenshot 2024-03-21 at 10 21 22 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/cb6bbc26-fe84-4a10-b23e-9469f5f76e30">
<img width="1335" alt="Screenshot 2024-03-21 at 10 18 14 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/91a2259d-f40e-4764-b498-bb6b11edaf5c">

**Comment by timarney** [comment]
PR:

https://github.com/cds-snc/platform-forms-client/pull/3380

**Comment by timarney** [comment]
@anikbrazeau fix for this is merged now.

**Comment by anikbrazeau** [comment]
Looks great! Thanks for the fix!
