### ISSUE TITLE
Right-side spacing on Translations page

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3370]
## Description
There doesn't seem to be any spacing on the right side of the Translations page, compared to Staging.

## Steps to reproduce
1. Go to the Translate page
2. See issue on the right side

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
(See right side spacing in Staging)

<img width="1576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUwyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f736f1fdbafa6200e6679d9b3123da35ce887efe/Screenshot%202024-03-20%20at%208.40.17%E2%80%AFAM.png" alt="Screenshot 2024-03-20 at 8.40.17 AM.png" />

## Screenshots or videos
<img width="1389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVAyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ec178904aac3b4c44cceae267e651105d975fe9/Screenshot%202024-03-20%20at%208.40.02%E2%80%AFAM.png" alt="Screenshot 2024-03-20 at 8.40.02 AM.png" />

**Comment by timarney** [comment]
This fix is up on the preview env now.

**Comment by Abi-Nada** [comment]
Re-tested and issue no longer persists!
