### ISSUE TITLE
Right-side spacing in Responses page

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3375]
## Description
There doesn't seem to be any spacing on the right side of the Responses page, compared to Staging.

## Steps to reproduce
1. Create a form, input a response to the database
2. Go to the Responses page
3. See issue on the right side

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
(See right side spacing in Staging)
<img width="1533" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjM0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c6c262086026363aee7f90a3132ebc6b56d181b/Screenshot%202024-03-20%20at%202.35.01%E2%80%AFPM.png" alt="Screenshot 2024-03-20 at 2.35.01 PM.png" />

## Screenshots or videos
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjc0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--633635995934b886bea09b34795a7254472da15c/Screenshot%202024-03-20%20at%202.34.54%E2%80%AFPM.png" alt="Screenshot 2024-03-20 at 2.34.54 PM.png" />

**Comment by connorscarolyns** [comment]
<img width="1245" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzc0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62b56ace43f80da2031b7a3239020e7cd95e7ee5/image.png" alt="image.png" />

**Comment by Abi-Nada** [comment]
More spacing issues documented in #[3403](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3403) 

Closing this card, as the card above encompasses more
