### ISSUE TITLE
Footer not at bottom of window on form confirmation when confirmation page content is short

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3381]
## Description
When filling out a published form and hitting submit, the confirmation page footer is not at bottom of window (white space below it) after submitting.

## Steps to reproduce
1. Go to a published form like https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/fr/id/cled7i3qj04478ax63lh1c0yg
2. Submit a response
3. See confirmation page be one line with footer not at bottom of page

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet
- **Output**: (form ID, link, JSON form file...)
- 
## Screenshots or videos

![footer](https://github.com/cds-snc/platform-forms-client/assets/38330843/16a38928-9700-46dd-9f82-b3f157f47a22)

**Comment by timarney** [comment]
This should be fixed now

https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/fr/id/cled7i3qj04478ax63lh1c0yg/confirmation

https://github.com/cds-snc/platform-forms-client/pull/2583/commits/4dfd1783ed2a7e688d50981ceb2349143cf8232d

<img width="1071" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bcb096d9395674c8319db417234d6c3346043d5/Screenshot%202024-03-22%20at%209.29.14%E2%80%AFAM.png" alt="Screenshot 2024-03-22 at 9.29.14 AM.png" />

**Comment by anikbrazeau** [comment]
Looks great! Thanks!
