### ISSUE TITLE
Error submitting Support and Contact forms

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3382]
## Description
When filling out the Support form or the Contact form in the App Router PR for QA, "Something went wrong" page shows up on submit.

## Steps to reproduce
1. Go to `Support` in the footer
2. Fill out the form and submit a response
3. See error page

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet
- **Output**: /contact /support
- 
## Screenshots or videos

![submit](https://github.com/cds-snc/platform-forms-client/assets/38330843/d3b090a1-57d9-4f96-82e6-e5ab522cdeb8)

**Comment by wmoussa-gc** [comment]
```
ERROR: Freshdesk API key not found
    err: {
      "type": "Error",
      "message": "Freshdesk API key not found",
      "stack":
          Error: Freshdesk API key not found
              at createTicket (webpack-internal:///(action-browser)/./lib/integration/freshdesk.ts:87:26)
              at support (webpack-internal:///(action-browser)/./app/(gcforms)/[locale]/(support)/support/actions.ts:42:102)```

**Comment by wmoussa-gc** [comment]
Bug fixed and tested in PR preview.
