### ISSUE TITLE
Preview icon not showing up for all forms

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3383]
## Description
First published form in "Forms" page does not have icon next to "Afficher le formulaire..."

## Steps to reproduce
1. Go to "Formulaires" (all forms) on the French interface
2. Look at first form card

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Consistency in when icons show up

## Screenshots or videos

![forms icon](https://github.com/cds-snc/platform-forms-client/assets/38330843/cccb3f14-47a2-426d-948d-ba875fc7182d)

**Comment by thiessenp-cds** [comment]
Interesting. I wonder if an unrelated fix, fixed that? I'm not able to reproduce the above.
Is this bug still happening for you @anikbrazeau

**Comment by anikbrazeau** [comment]
Seems fine now? Weird. 😅

**Comment by thiessenp-cds** [comment]
Agreed :) I'll close this for now
