### ISSUE TITLE
Saving not possible without form name

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3384]
## Description
Saving a form does not register until form file is named. Adding title/questions/privacy/confirmation will say "Saved" in "Edit" but won't actually show up in "All forms" until the unnamed form file gets named. However nothing nudges the user to have to do so? 

## Steps to reproduce
1. Go to "Create new form"
2. Without naming the form file in the top bar, fill something in for: Form title, form description, add a question, privacy statement, confirmation page.
3. Click "Save" and see "Saved"
4. Go to "All forms" and Ctrl+F for the form title

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour

Saved form should appear in list of forms.

Possible options: taking the form title if the form file was not filled in OR error/nudge to name the form file before navigating away and losing changes potentially. 

## Screenshots or videos

![saved](https://github.com/cds-snc/platform-forms-client/assets/38330843/22f5da6a-4018-4a94-921d-06480c338207)

**Comment by timarney** [comment]
Going to test with @dsamojlenko but I seem to see.

<img width="631" alt="Screenshot 2024-03-21 at 1 24 31 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/bf3a7cad-e598-4a15-a7dd-799e473f1640">

**Comment by dsamojlenko** [comment]
In testing, looks like a cache problem on the All Forms page.
- Started a new form
- Updated the title (not the name of the form)
- Clicked "Save draft"
- Check database - record is created
- Navigate to All forms - not there
- Refresh page - huzzah

Same thing happens with a named form.

**Comment by timarney** [comment]
@thiessenp-cds see Dave's comments above

**Comment by anikbrazeau** [comment]
Could it be something that happens when editing/using in French first?

**Comment by dsamojlenko** [comment]
@anikbrazeau tested same in French, same result.

@thiessenp-cds I'm not sure what the right solution is here- it's either fire a revalidation on /forms every time we create a new form or update a form title, or some other caching change for /forms (lower cache time? or don't cache for people that don't have manage all forms permission?)

**Comment by timarney** [comment]
Noting it does "save" to the DB just the the result set in "forms" isn't showing or at least not right away.

**Comment by thiessenp-cds** [comment]
You are correct, it is an issue with caching. There is a fix ready to go in [another PR](https://github.com/cds-snc/platform-forms-client/issues/3353) for this and sorting.

**Comment by thiessenp-cds** [comment]
This was probably resolved in this ticket: https://github.com/cds-snc/platform-forms-client/issues/3353

**Comment by anikbrazeau** [comment]
Fixed! Thanks all!
