### ISSUE TITLE
"All Forms" string in top nav

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3385]
## Description
Missing consistency in top nav.

## Steps to reproduce
1. Create a form or go in an existing form to edit
2. Look at the top nav bar
3. Notice "All Forms [FR]"
4. Toggle to English
5. Navigate through the site and notice changes in reference between "Forms" / "All Forms" / "All forms"

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

# Expected behaviour

`Forms` or `All forms` in English consistently throughout
`Formulaires` or `Tous les formulaires` in French consistently throughout

## Screenshots or videos

![All forms2](https://github.com/cds-snc/platform-forms-client/assets/38330843/f27c3a73-c996-4525-9bc9-c616aa2c3d70)
![top nav](https://github.com/cds-snc/platform-forms-client/assets/38330843/794bb978-3473-4f35-b219-65b92b844d8e)

![All forms](https://github.com/cds-snc/platform-forms-client/assets/38330843/6eda2920-7f60-4ed8-91e4-35fcfa290fbb)

**Comment by anikbrazeau** [comment]
Let's go with "Forms" in EN and "Formulaires" in FR

**Comment by thiessenp-cds** [comment]
Fixed in PR #340
