### ISSUE TITLE
Checklist does not link directly to privacy statement and confirmation page fields

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3387]
## Description
The items in the publishing checklist are meant to take you directly to the place where the action/decision must be taken. "Déclaration de confidentialité" and "Message de confirmation" go to the top of the "Edit" page rather than directly to the place where to enter.

## Steps to reproduce
1. Go to "Publish" for any draft form without a privacy statement and confirmation message
2. Click on the link for each of these required items
3. Scroll down to get to those form elements

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Link directly to the field in question or anchored spot on page

## Screenshots or videos

![checklist](https://github.com/cds-snc/platform-forms-client/assets/38330843/bdbd8e43-c1ad-4949-9763-8c58b5b586ca)]

![after](https://github.com/cds-snc/platform-forms-client/assets/38330843/8368dc8f-be35-4a85-bf85-a5eb011ce03f)

**Comment by Abi-Nada** [comment]
@timarney Agree, I don't think we should spend time investigating for a temporary solution when this will change when it comes to grouping. It's not a severe or critical bug that'll stop a user from being able to create and publish a from, so I'll descope it from the App Router fixes.

**Comment by Abi-Nada** [comment]
Created a new card considering CL here #4026
