### ISSUE TITLE
String key showing up for hint text of basic form element

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3388]
## Description
Hint text for basic elements shows string name

## Steps to reproduce
1. Go to "Create a form" > "Edit"
2. Add "basic" form elements
3. Notice the prepopulated hint text ex: "defaultElementDescription.radio"
4. Go to "Translations" and see how it appears in both language fields

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
No preset hint text for basic elements

## Screenshots or videos

![default](https://github.com/cds-snc/platform-forms-client/assets/38330843/7bd20b75-6282-4a95-b9fc-aaa61efaa89f)
![radio translate](https://github.com/cds-snc/platform-forms-client/assets/38330843/69e264e7-801e-4f74-b7ae-c4c00dae1c53)

**Comment by dsamojlenko** [comment]
ah, that bug was introduced in a [previous bugfix](https://github.com/cds-snc/platform-forms-client/pull/3379), and has been patched. Should be good now
