### ISSUE TITLE
Translation CSV in English only even when downloaded from French interface

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3389]
## Description
Exporting the CSV file on the "Translation" page provides a file that is in English only even if using GC Forms in French.

## Steps to reproduce
1. Go to a draft form
2. Go to "Edit" --> "Modifier" in FR
3. Go to "Translations" --> "Traductions" in FR
4. Export file: "Exporter en fichier CSV" 
5. Open file
6. Notice heading etc. in EN only

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Language of interface it was downloaded in? Or bilingual headings? 

## Screenshots or videos

![en_xl](https://github.com/cds-snc/platform-forms-client/assets/38330843/d964dbb3-7222-4b9b-9b10-260b8942d067)

**Comment by dsamojlenko** [comment]
Noting this was an existing bug (exists in staging/prod)
Pushed a fix to include bilingual labels in the CSV.
