### ISSUE TITLE
Subject line does not appear in FR when email delivery is set

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3390]
## Description
Subject line does not appear on Response page in FR when set.

## Steps to reproduce
1. Go to "Paramètres" (settings)
2. Select "Protégé A" (Protected A)
3. Select "Recevoir les réponses par courriel" (email delivery)
4. Enter subject line "Ligne d'objet" in EN and FR
4. Go to "Responses"
5. See how FR subject is not appearing

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
FR subject line appears on response page when email subject is not empty

## Screenshots or videos
![responses email](https://github.com/cds-snc/platform-forms-client/assets/38330843/8f82424f-f5b3-443b-9686-c3d5da4406f4)
![settings responses](https://github.com/cds-snc/platform-forms-client/assets/38330843/6a7a8a92-a9ae-47e7-90e4-eab6cb854dda)

**Comment by timarney** [comment]
Found a typo -- pushed a commit

https://github.com/cds-snc/platform-forms-client/pull/2583/commits/4bf211d9eceab94e8ed4fb8ec37bbd9b093d1578

**Comment by anikbrazeau** [comment]
Thanks Tim! Fix looks good!
