### ISSUE TITLE
Unable to submit "draft" / "test" responses

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3391]
## Description
When trying to submit a response to a draft form in the preview page, getting an error that there's a problem.

## Steps to reproduce
1. Go to Draft form (FR)
2. Click on Test / Preview
3. Fill out the fields
4. Submit
5. See error

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Get test responses to see how the process works

## Screenshots or videos

![submission](https://github.com/cds-snc/platform-forms-client/assets/38330843/42d9730e-a61a-463b-b1ad-afd0e0bfee01)

**Comment by Abi-Nada** [comment]
Can you try re-producing the issue? Wondering if it still persists

**Comment by anikbrazeau** [comment]
Still an issue, here's a JSON file for a form where I was just able to reproduce. Note: it's not for all forms... 🤔 

Found this time on Desktop, Chrome, English:

[titre-de-formulaire-trs-trs-trs-long-2024-03-22.json](https://github.com/cds-snc/platform-forms-client/files/14724556/titre-de-formulaire-trs-trs-trs-long-2024-03-22.json)


![screencapture-7b326hq3bwxyh2tym7gc23dwcm0tmzog-lambda-url-ca-central-1-on-aws-fr-form-builder-0000-preview-2024-03-22-11_18_44](https://github.com/cds-snc/platform-forms-client/assets/38330843/3d3f8ce3-9cd2-4b5e-95ac-c36c4e09424c)
![screencapture-7b326hq3bwxyh2tym7gc23dwcm0tmzog-lambda-url-ca-central-1-on-aws-en-form-builder-0000-preview-2024-03-22-11_19_12](https://github.com/cds-snc/platform-forms-client/assets/38330843/fd0a0ddc-3409-4cff-957a-d131d5fbf060)

**Comment by dsamojlenko** [comment]
Not sure what's happening here yet .. but this is the error that pops up on the console on submit

"'An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.'"

**Comment by dsamojlenko** [comment]
I think this is a form saving issue.
If I use that .json file to create a new form and then attempt to submit on the Preview page right away, the form is not saved yet and so fails. Locally, the error message is more explanatory: "No form could be found with that ID"

But if I navigate to edit, make any minor change, save as draft, and return to Preview then it works as expected.

Not sure the fix here. Probably should just prevent submission if the form hasn't been saved yet.

**Comment by dsamojlenko** [comment]
Ended up blocking submissions if the form has not saved yet.

**Comment by anikbrazeau** [comment]
I'm getting the error when form is saved without a question, even after naming it. Could we block submissions without a question added potentially @dsamojlenko? 

![Screenshot 2024-03-27 at 3 55 17 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/b7593627-4877-458e-896d-cf3ac06326b2)

**Comment by dsamojlenko** [comment]
Done: https://github.com/cds-snc/platform-forms-client/pull/2583/commits/f708dd37d40ef5b0a461e9fe64a692c563085b22

**Comment by anikbrazeau** [comment]
This works now! Thanks!
