### ISSUE TITLE
After publishing a form, side menu still shows "Edit" / "Publish" / etc. but gives an error

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3393]
## Description
After going through the publishing checklist and publishing a form, the side nav remained the same as the draft state even though some functionalities are no longer possible.

## Steps to reproduce
1. Go to draft form
2. Complete requirements for publishing
3. Click publish
4. Go to side nav and navigate to "Edit"
5. See error
6. Returning to the form, it appears it wasn't published

## Details
- **Browser**: Edge
- **Operating system**: Window
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Cannot edit once published
Does navigation menu change or do some items become inactive?

## Screenshots or videos

![post-publish](https://github.com/cds-snc/platform-forms-client/assets/38330843/4769ce60-c4c6-4ca4-af23-d09dbe88feae)

![not published](https://github.com/cds-snc/platform-forms-client/assets/38330843/a7ac9f4c-8d55-471d-b278-397894e0938d)

**Comment by anikbrazeau** [comment]
Looks like I might have a draft instance and a published instance of the same form, which is causing it to glitch?

**Comment by anikbrazeau** [comment]
Seems this might be related to the fact that you can publish a form without naming it, which creates a bunch of problems?

**Comment by timarney** [comment]
@anikbrazeau --- merged at least a partial fix for this --- should be up in about 5 min or so.

I believe there's still an edge case if you manually visit the edit page after publishing will take a look at that next week.

For now if you can re-test the happy path that would be great.

**Comment by timarney** [comment]
Yes -- if you see it :)

It seems to be a bit hit and miss if it goes away or not after published.

But if you see it let me know --- it should handle that page with a redirect to settings as it currently does on staging.

**Comment by timarney** [comment]
Okay thanks we'll do some further testing on Mon.

**Comment by anikbrazeau** [comment]
<img width="1283" alt="Screenshot 2024-03-22 at 3 22 28 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/658ebabb-40fb-4d45-967d-d28ef46d8f6a">

**Comment by Abi-Nada** [comment]
@anikbrazeau @timarney following up on this card - Tim, did you end up testing it out?

Just flagging that this currently persists in Prod/isn't related to the App Router work. The form still publishes, but it could cause some confusion to the user if they toggle back to Edit after clicking "Publish". Since it's not related to the App Router, I'm going to de-scope it from that work, but still keep it up in New Issues as a bug

**Comment by anikbrazeau** [comment]
This appears to be fixed now, only showing relevant side nav items post-publish :) 
<img width="1788" alt="Screenshot 2024-04-22 at 9 41 39 AM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/e1029f14-df70-45ab-928a-1952a9366b43">
