### ISSUE TITLE
Issue with accents and special characters

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3394]
## Description
Form responses/receipts replace accents with question mark and form file name does not include letters with accents

## Steps to reproduce
1. Name form title with é or è 
2. Publish form
3. Submit a response
4. Download response
5. Notice file removes the é from the file name
6. Open response
7. Notice the accents in the csv file and html receipt do not render

## Details
- **Browser**: Edge
- **Operating system**: Window
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Accuracy in FR and special characters

## Screenshots or videos

![character](https://github.com/cds-snc/platform-forms-client/assets/38330843/9c28a6c9-659a-4355-924a-32b4eca8be7b)
![csv](https://github.com/cds-snc/platform-forms-client/assets/38330843/42aab2c9-ff16-4d74-a37f-a75d82bc1c69)

**Comment by anikbrazeau** [comment]
[titre-de-formulaire-trs-trs-trs-long-2024-03-21-responses-reponses (2).zip](https://github.com/cds-snc/platform-forms-client/files/14705895/titre-de-formulaire-trs-trs-trs-long-2024-03-21-responses-reponses.2.zip)

**Comment by dsamojlenko** [comment]
Ok, I think this is all resolved.
For filenames, it will no longer just strip accented characters, but normalize them to their non-accented equivalents. This is done for file system safety, as character encoding can be problematic in filenames.

For the special characters in the files- I am no longer able to recreate. I added a fix for something seemingly unrelated- the JSON/zipped download was not resolving a promise and so the output was messed up. Perhaps in fixing this, it fixed this other issue peripherally?

Let me know if you are still finding the issue.

**Comment by anikbrazeau** [comment]
Seems fixed all around! Thanks for this Dave! 

<img width="1122" alt="Screenshot 2024-03-27 at 4 01 30 PM" src="https://github.com/cds-snc/platform-forms-client/assets/38330843/62760763-4980-4674-9f9a-684af6ededbd">
