### ISSUE TITLE
Time in EN format in FR screen

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3396]
## Description
Time formatting for responses in French

2:56 pm in English --> 14 h 56 in French

## Steps to reproduce
1. Go to "Réponses" (responses in FR)
2. Click on "Signaler un problème avec les réponses"
3. Report a submission ID
4. Go to "Afficher les réponses signalées"
5. See how the time is in English format on French interface
6. This is also the case across the "New" / "Downloaded" / "Signed off" tabs

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
2:56 pm in English --> 14 h 56 in French

**Comment by dsamojlenko** [comment]
Fixed: https://github.com/cds-snc/platform-forms-client/pull/2583/commits/f8fcddf3dc468c982466d65c56cdfd7a94b1ba7c

**Comment by anikbrazeau** [comment]
Fixed! Thank you!
