### ISSUE TITLE
Buttons in HTML responses don't contain all the copy

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3397]
## Description
Copy extends beyond the container

## Steps to reproduce
1. Go to download responses for a form with submissions
2. Select reponses and download HTML zip
3. Open the receipt file (from french interface)
4. Notice how text extends beyond button

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: tablet

## Expected behaviour
Shorter button text?
Adjustable copy that contains text?
Link?

## Screenshots or videos
![buttons](https://github.com/cds-snc/platform-forms-client/assets/38330843/8b3d8fc0-a78b-4196-89e1-32866fa42325)

**Comment by dsamojlenko** [comment]
Fixed: https://github.com/cds-snc/platform-forms-client/pull/2583/commits/57e6d8d96e6c7c94077da9fc51b54d367a88bc59

**Comment by anikbrazeau** [comment]
Fixed! Thank you!
