### ISSUE TITLE
Padding/margin on right side of screen

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3403]
## Description
Some components seem tight to the right side of the window

## Steps to reproduce
1. Go to Responses page --> Notice the space between "Download" in the table and the side of the screen
2. Go to Publish a draft form --> Notice the "What you need to know" is squished on the right side of the screen
3. Click Publish to actually publish the form --> Notice the purple box extends beyond the screen

## Details
- **Browser**: Chrome
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Breathable interface

## Screenshots or videos
![padding](https://github.com/cds-snc/platform-forms-client/assets/38330843/c57f5ef0-f4f6-4020-aeca-a790d9b4fe7f)
![padding2](https://github.com/cds-snc/platform-forms-client/assets/38330843/38345d5b-c4a6-4708-aba8-d9ea6790a012)
![padding 3](https://github.com/cds-snc/platform-forms-client/assets/38330843/4cdda0a4-a640-404f-8f79-4b5702fd572f)

**Comment by connorscarolyns** [comment]
To add to this, the div height on the main content block does not extend the full height of the page, causing the left nav item to cut off <img width="1309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--994f2ee2ef15687edeafd6d8e4a3ef4ccec24ef7/image.png" alt="image.png" />

**Comment by timarney** [comment]
Pushed a commit for "published"

https://github.com/cds-snc/platform-forms-client/pull/2583/commits/424071203799338e7483c33493b3bf52e7827578

<img width="800" alt="Screenshot 2024-03-22 at 9 50 15 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/8f3191a0-1efc-4fd6-983a-169d49be880a">

**Comment by dsamojlenko** [comment]
Fixed: https://github.com/cds-snc/platform-forms-client/pull/2583/commits/2a1060888ecd5e70f7c0185f59d45f28d134ba90
