### ISSUE TITLE
Consider differentiating icons for dropdown list and searchable list

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3405]
## Description
Icons should help people differentiate between form elements when making that choice.

The reason for when to choose dropdown list vs. searchable list is unclear

## Steps to reproduce
1. Go to "Add form element"
2. Scroll down to "Dropdown" and "Searchable list"

## Details
- **Browser**: Chrome
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Either combining similar components like "Name"/"Names" and "Dropdown"/"Searchable" or differentiating them enough to make the choice easier for users (including making the difference clearer in the name and in the icon if they are distinct enough to each warrant their own type)

## Screenshots or videos
![icon](https://github.com/cds-snc/platform-forms-client/assets/38330843/c1954db3-9a80-41f4-9fc1-947c8064cbba)

**Comment by Abi-Nada** [comment]
This will need design input, so we'll descope this from the App Router bug fix work.

(Flagging as a heads up @connorscarolyns )
