### ISSUE TITLE
"Other" field shows EN in FR translation

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3411]
## Description
When I add an "Other" field in the English interface, it shows up as "Other" in the French translation side.

## Steps to reproduce
1. Add a question
2. Within the question, add an input field for "Other"
3. Toggle over to the Translations tab
4. Scroll down to see error: "Other" appears in EN and FR

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
The FR translation for "Other" should appear in Translations, not the EN.

## Screenshots or videos
<img width="1065" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18acb9b399d0f636c06fe2cdc8d74db815adf1a3/Screenshot%202024-03-25%20at%208.52.32%E2%80%AFAM.png" alt="Screenshot 2024-03-25 at 8.52.32 AM.png" />

<img width="1973" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTRIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36594bf487f326c5d5841fe28e88c2b5ec5e8a04/Screenshot%202024-03-25%20at%208.52.46%E2%80%AFAM.png" alt="Screenshot 2024-03-25 at 8.52.46 AM.png" />

**Comment by timarney** [comment]
PR merged

**Comment by Abi-Nada** [comment]
Re-tested and issue no longer persists :)
