### ISSUE TITLE
"Know your responsibilities" can be skipped

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3440]
## Description
I'm able to toggle away from the "Know your Responsibilities" without confirming my agreement.

## Steps to reproduce
1. Login
2. Input security code
3. On the "Know your responsibilities" page, toggle away from it (click "Sign In:)
4. Wait a couple seconds while the screen load
4. See error: it takes you to the "Forms" page

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
Anytime a user tries to navigate to a different link after Signing In, they should be redirected to the "know your responsibility" page to ensure they agree.

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmN4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01bbbf738831afe4f133672b3e8d8ed226f77a90/Screen%20Recording%202024-04-03%20at%202.09.55%E2%80%AFPM.mov)

**Comment by wmoussa-gc** [comment]
nice find!
