### ISSUE TITLE
"Open a form file" button doesn't seem to work

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3444]
## Description
"Open a form file" button doesn't seem to work

## Steps to reproduce
1. Go to the Forms homepage
2. Click on "Open a form file"
3. See error - nothing happens

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English

## Expected behaviour
You should be able to select the file you need uploaded.

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0l4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6b8f8864ef39897aa6c12096c8d113e2b589de4/Screen%20Recording%202024-04-03%20at%203.19.38%E2%80%AFPM.mov)

**Comment by timarney** [comment]
PR:

https://github.com/cds-snc/platform-forms-client/pull/3447

**Comment by timarney** [comment]
@Abi-Nada can you give this url a try?

https://5agcgbg3uem2gyl536sa4qewse0mjrnx.lambda-url.ca-central-1.on.aws/

**Comment by Abi-Nada** [comment]
@timarney new link doesn't seem to let me open up a form file either - I wonder if it's something to do on my end? Versus with the actual product? (Are you able to replicate this issue?)

**Comment by Abi-Nada** [comment]
Note: I'm able to open it up with the link on Firefox and Edge, just not Chrome

**Comment by timarney** [comment]
Not sure --- worst case we can re-open as needed.
