### ISSUE TITLE
Radius' on form building cards are broken

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3449]
Some of the corner radius' on the form builder are broken. Some of them were before the app-router work, but I noticed another one this morning. 

<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb246eb79094af2ed67424b3a34442ce00e469d8/image.png" alt="image.png" />
<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejFHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4f7477ff31addfe374882f46ff987e727ac53ad/image.png" alt="image.png" />
<img width="1556" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19343d7411e52e1a2b6338af87b6c69386bf0a50/image.png" alt="image.png" />

**Comment by timarney** [comment]
Pushed a commit for the Policy / Confirm issue

https://github.com/cds-snc/platform-forms-client/pull/2583/commits/80de6ecf7c2e9fc5932c45e8dc63ab73dafee351

**Comment by timarney** [comment]
Looking for this to be re-tested / verified.

**Comment by samsadasivan** [comment]
On testing - this looks fixed! Thank you!
