### ISSUE TITLE
Padding on right side of Log in widget is big

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3450]
<img width="1573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejlHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5b1d876b020182485d90f2ecb2cba104dbebf91/image.png" alt="image.png" />

I believe what we settled on for this widget was 16px all around, content still left aligned.

**Comment by Abi-Nada** [comment]
Closing as a duplicate of [3441](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3441)
