### ISSUE TITLE
Profile security questions appear in English on French interface

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3451]
## Description
When navigating to the profile page with account information and security questions in the French interface, English security questions appear. However when modifying they are in French? 

## Steps to reproduce
1. Sign in, on the French interface
2. Go to "Votre compte" > "Profil"
3. See security questions in English
4. Click "Modifier"
5. See security questions in French

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet 100%

## Expected behaviour
Expect either language to be in interface language or in language initially used to configure security questions.

## Screenshots or videos

![questions](https://github.com/cds-snc/platform-forms-client/assets/38330843/5f51cb60-8e1b-4917-bdae-7a7a653bc842)

**Comment by Abi-Nada** [comment]
@anikbrazeau can you confirm if this issue still persists?

**Comment by anikbrazeau** [comment]
This appears to be fixed now.
