### ISSUE TITLE
Cropped "Forms" page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3455]
## Description
A clear and concise description of what the problem is.

## Steps to reproduce
1. Create an account
2. Unlock publishing
3. Go to "Forms"
4. See page taking up reduced real estate in window

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet 100%

## Expected behaviour
Interface maximizing full window.

## Screenshots or videos

![Forms EN](https://github.com/cds-snc/platform-forms-client/assets/38330843/bd366ac7-9462-4709-8669-10f55fef2843)

![FR post submit](https://github.com/cds-snc/platform-forms-client/assets/38330843/6e4f0e57-d4c8-425c-811e-9aad38985648)

**Comment by timarney** [comment]
@anikbrazeau this should be updated on the preview link now.

**Comment by anikbrazeau** [comment]
This is fixed, thanks!

<img width="954" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODkvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b53b4a02eef487b14dbe85c9f7346f921ebe5af7/image.png" alt="image.png" />
