### ISSUE TITLE
FR Typos - Profile page 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3456]
## Description
Mistake in French

## Steps to reproduce
1. Create an account, setting up security questions but without unlocking publishing (FR)
2. Go to "Votre compte" > "Profil"
3. In French interface notice "Vérouillé" for "Locked" which is spelled wrong
4. Also notice the spaces before question marks in the security questions

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet 100%

## Expected behaviour
Should be **"Verrouillée"** rather than "Vérouillé.
Can remove spaces before question marks in security questions.

## Screenshots or videos

![typo and question mark](https://github.com/cds-snc/platform-forms-client/assets/38330843/88ca45e7-437c-431c-ba70-1db2172c642e)

**Comment by anikbrazeau** [comment]
This issue persists (as of Apr 22, 2024)

<img width="337" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmQvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2822bc2745b6b35f878c82402ccaf86714a037c2/Screenshot%202024-04-22%20at%2010.14.02%E2%80%AFAM.png" alt="Screenshot 2024-04-22 at 10.14.02 AM.png" />

**Comment by bryan-robitaille** [comment]
@anikbrazeau PR review environment with the fix is now up: https://mdbwzapcu7h6ugg2m22szbuuyi0thmvx.lambda-url.ca-central-1.on.aws/

PR #3497

**Comment by anikbrazeau** [comment]
✅

![Screenshot 2024-04-22 at 10 14 02 AM](https://github.com/cds-snc/platform-forms-client/assets/38330843/af6b4223-dd3b-49e7-95c8-8bfa292d5f6d)
