### ISSUE TITLE
French page with English main content and footer

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3458]
## Description
Only header appears in French on "Forms" page when toggle to French. Main content and footer are in English.

## Steps to reproduce
1. Create an account (FR)
2. Create a form
3. Go to "Formulaires" from top header
4. Notice English content on French toggle

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet 100%

## Expected behaviour
French content/page/footer on French interface.

**Comment by Abi-Nada** [comment]
@anikbrazeau can you confirm if this issue still persists?

**Comment by timarney** [comment]
Fix for this pushed to preview url

https://github.com/cds-snc/platform-forms-client/assets/62242/8fa1a1c8-4ae5-4941-b27d-be296ab74043

**Comment by anikbrazeau** [comment]
This appears to be fixed! :D
