### ISSUE TITLE
Email link to reset password not working, footer reverts to EN

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3460]
## Description
When resetting password the link received by email leads to a page that cannot be found.

## Steps to reproduce
1. Go to Sign in (FR)
2. Click on "Réinitialiser votre mot de passe"
3. Enter email address and continue
4. See message to check email
5. Go to Email and click link
6. Land on page not found
7. Footer also reverts to English even though in French interface?

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet 100%

## Expected behaviour
Ability to reset password with link.
Footer stays in language of interface.

## Screenshots or videos

![Footer and link](https://github.com/cds-snc/platform-forms-client/assets/38330843/735535d7-2e3e-436d-8fb8-5f5f3b13dc06)
<img width="1605" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e44f49faa7d218741c3c85f9686814bf75d8ca41/Screenshot%202024-04-09%20at%209.10.16%E2%80%AFAM.png" alt="Screenshot 2024-04-09 at 9.10.16 AM.png" />

**Comment by Abi-Nada** [comment]
@anikbrazeau can you confirm if this issue still persists?

**Comment by anikbrazeau** [comment]
Link now works, but footer is in English on French page for the "Know your responsibilities" page (as of Apr 22, 2024)

https://7b326hq3bwxyh2tym7gc23dwcm0tmzog.lambda-url.ca-central-1.on.aws/fr/auth/policy
![image](https://github.com/cds-snc/platform-forms-client/assets/38330843/dade1408-b565-490f-a994-5a94269c3fa6)

**Comment by anikbrazeau** [comment]
Similarly when creating an account in French, the footer is in English

![Screenshot 2024-04-22 at 2 58 51 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/676c80db-1fb0-4450-b14b-87a6f8aaf3d9)

**Comment by timarney** [comment]
Very high chance this is related to the fix for https://github.com/cds-snc/platform-forms-client/issues/3458

**Comment by timarney** [comment]
@anikbrazeau  can you re-test?

**Comment by anikbrazeau** [comment]
This appears to be fixed! :)
