### ISSUE TITLE
Image not showing up on Publish (unauth)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3461]
## Description
Image appears as broken.

## Steps to reproduce
1. Go to GC Forms
2. Stay signed out
3. Toggle to French
4. Go to "Publier"
5. See empty image 

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Production (unauthenticated)
- **Language**: French
- **Viewport**: Desktop, 100%

## Screenshots or videos
![Screenshot 2024-04-09 at 10 07 02 AM](https://github.com/cds-snc/platform-forms-client/assets/38330843/fc1776f7-5228-40ff-ab15-11e35839c8dd)

**Comment by Abi-Nada** [comment]
Issue no longer persists:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJlQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ca3db5c398442aaf9d0fe5038f00d6c2a505936/Screenshot%202024-06-28%20at%2010.01.20%E2%80%AFAM.png" alt="Screenshot 2024-06-28 at 10.01.20 AM.png" />
