### ISSUE TITLE
Submitting Contact and Support forms in French gives English confirmation pages

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3462]
## Description
Submitting form in French, provides confirmation in English (header remains French, but content and footer go to English)

## Steps to reproduce
1. Go to Support form in French
2. Fill out and submit
3. Notice content language changes
4. Go to Contact form in French
5. Fill out and submit
6. Notice content language changes

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: App router PR
- **Language**: French
- **Viewport**: Tablet 100%

## Expected behaviour
Consistent, predictable, matching language.

## Screenshots or videos

![FR support](https://github.com/cds-snc/platform-forms-client/assets/38330843/9a14cf55-d31e-4a9b-a9df-131ddb2ae748)

![post contact](https://github.com/cds-snc/platform-forms-client/assets/38330843/212d3e62-e55f-4250-9819-7535a9821f1e)

## Additional context

Potentially related to other language issues #3454 #3451 #3458, #3460

**Comment by dsamojlenko** [comment]
Same issue as #3454

**Comment by anikbrazeau** [comment]
Thanks! This is fixed for Contact and Support (FR submit gives FR post-submit) ✅
