### ISSUE TITLE
French confirmation page with English text

### ISSUE THREAD

**Issue by muoyopopo** [cds-snc/platform-forms-client#3467]
<img width="1579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVZOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bacf5bae69554b02f85d44f55f806e1e83bdcdf/Screenshot%202024-04-10%20at%2011.25.33%E2%80%AFAM.png" alt="Screenshot 2024-04-10 at 11.25.33 AM.png" />
Steps to Recreate:

1. Click on submit form
2. Switch to French
3. Fill test responses and submit form in French
4. Confirmation page appears in English

Browser: Chrome
Operating system: Mac
Environment: Staging
Language: French

**Comment by anikbrazeau** [comment]
Related issues: #3462 #3454

**Comment by Abi-Nada** [comment]
@muoyopopo can you re-test and let us know if the issue still persists?

**Comment by anikbrazeau** [comment]
I was not able to replicate this, perhaps it's fixed now based on fixes to #3462 and #3454?

**Comment by Abi-Nada** [comment]
Thanks for advising, Anik! Will be closing out this card if the issue no longer persists :)
