### ISSUE TITLE
Blank state and page text should not appear at the same time

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3468]
<img width="1739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVpOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f35f6837a332f9b131e93cd4ec4ae2269b2c4ef8/image.png" alt="image.png" />

When the blank state is shown, the rest of the text on the page should be hidden.

**Comment by connorscarolyns** [comment]
Once a response is downloaded, the "new" tab shows the table with the disabled response and the message "move to...", which is what I would expect for the "downloaded" tab and "problems" page. Instead, the table disappears and the blank state is shown right away along with the page text. 

This is corrected to just the blank state after navigating away and back.

**Comment by dsamojlenko** [comment]
Fixed the issue with the conflicting states.
The suggestion that the Downloaded and Problems page should have the same behaviour as New tab with the "ghost" records should be considered new development and should be addressed separately.

**Comment by Abi-Nada** [comment]
@connorscarolyns can you re-test and confirm if the issue still persists?

**Comment by connorscarolyns** [comment]
The blank states appear as expected, but there is a new issue where the title and sign-off button are missing from the Downloaded tab. I'm sure this is probably related to this change, but I've made a new ticket for it, just incase we want to close this one. #3502

**Comment by Abi-Nada** [comment]
Confirmed issue no longer persists - closing out card, and pulling #3502 into the Sprint Backlog to be worked on. Thanks Carolyn!
