### ISSUE TITLE
Move Template CRUD to NextJS

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#347]
Move the functionality from the Lambda function to the NextJS server side.  

**Considerations to take into account before completing**
Can the Reliability Lambda function connect/reach the `/template` api endpoint on the ECS task instance.

** Benefits of completing**
Reduces time delay for user experience when loading forms or home page.  When there is low user traffic a new Lambda instance is needed to be spun up in order to answer the request from the NextJS server.

**Comment by bryan-robitaille** [comment]
@falila @craigzour Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/GCForms-60cb8929764d71000e481cab/issues/cds-snc/platform-forms-client/347?planning-poker)

**Comment by craigzour** [comment]
This was completed a while ago :)
