### ISSUE TITLE
Batching of Confirmation Codes generating DynamoDB bursts.

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#3494]
The confirmation batching system used to limit the number of requests to the API endpoint requires verification to ensure it does not create bursts on the primary key.

The API call to the DynamoDB should also be able to handle Throttle Errors appropriately without returning an error to the client.

<img width="1273" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0768fed9d89a2406b85108d3fb7b82459d4ce5b/Screenshot%202024-04-22%20at%2012.02.47%E2%80%AFPM.png" alt="Screenshot 2024-04-22 at 12.02.47 PM.png" />

Acceptance Criteria:
- [ ] DynamoDB API call can handle Throttle errors and retries accordingly after a small delay
- [x] The client Confirmation modal ensures that multiple requests cannot be sent within 750ms of each other.

**Comment by wmoussa-gc** [comment]
<img width="1091" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVBCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56f351c49892956d9b0b67d1e9988026c16e3236/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
current behaviour (when validation works) 

<img width="775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmpCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb8ffe94823ba5ad016f2fc58afc32f6f4d10446/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
Is 20 still the maximum number of entries we can confirm at once?

But the real issue is that validation appears to be bypassed when pasting a list of IDs.

**Comment by wmoussa-gc** [comment]
Before implementing error throttling logic, I'd like to gain a deeper understanding of how the SDK handles such scenarios. From the documentation, it appears that some form of retry mechanism is already in place: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-dynamodb/Class/ProvisionedThroughputExceededException/ (if that is the error that was raised in the logs)

If we choose to write our own solution, we need to consider the added complexity. Is it truly necessary, or can we mitigate the issue by merging the first PR, which limits requests via the UI?

**Comment by bryan-robitaille** [comment]
It's my understanding that the TransactWriteItems command we are using is not covered by the automated retries of the SDK.  https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html
     

> **DynamoDB rejects the entire TransactWriteItems request if any of the following is true:**
>  - A condition in one of the condition expressions is not met.
>  - An ongoing operation is in the process of updating the same item.
>  - There is insufficient provisioned capacity for the transaction to be completed.
>  - An item size becomes too large (bigger than 400 KB), a local secondary index (LSI) becomes too large, or a similar validation error occurs because of changes made by the transaction.
>  - The aggregate size of the items in the transaction exceeds 4 MB.
>  - There is a user error, such as an invalid data format.

**Comment by wmoussa-gc** [comment]
second PR https://github.com/cds-snc/platform-forms-client/pull/3619
