### ISSUE TITLE
Investigation: Replace Jest unit tests with Vitest

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3515]
Vitest has native support for ECMAScript Modules (ESM), making it easier to work with modern JavaScript/TypeScript codebases such as GC Forms App. Vitest can test our code without additional configuration or transpilation.

Vitest offers a unified experience by providing similar APIs and concepts as Jest (so migration should not take long)

Vitest is designed to work well with TypeScript, making it easier to write and test type-safe code.

- [ ] Review existing Jest-based test suite
- [ ] Review Jest plugins usage
- [ ] See how Jest is used in our CI/CD pipeline

**Comment by wmoussa-gc** [comment]
## Test Pyramid

<img width="1441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1NaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da1edecdeafa98b6deb43d5f6d3a6284a55e9d67/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
## Forms Client Application Analysis

We are currently using Jest for unit tests, with 488 tests enabled and passing, and 176 disabled (many of the disabled ones are for API endpoints, some of which have been converted to server actions or will be in the future).

**Comment by wmoussa-gc** [comment]
Tests location:

```
/lib/utils/form-builder/__tests__/
/lib/store/__tests__/
/lib/hooks/__tests__/
/lib/tests/
/app/(gcforms)/[locale]/(user authentication)/components/client/
/app/(gcforms)/[locale]/(user authentication)/auth/policy/components/server/
/app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/tests/
...
/components/clientComponents/forms/TextInput/
/components/clientComponents/admin/FormAccess/
...```

**Comment by wmoussa-gc** [comment]
new draft PR https://github.com/cds-snc/platform-forms-client/pull/3522

**Comment by wmoussa-gc** [comment]
The PR is ready for review. As mentioned in our stand-up, we'll continue the migration at the appropriate time.
