### ISSUE TITLE
Wrong error message when invalid 2FA code is entered

### ISSUE THREAD

**Issue by wmoussa-gc** [cds-snc/platform-forms-client#3523]
If you input an invalid 2FA code the UI throws this message: 

<img width="456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--571f1bcc61d00487d9cc1c57e83022bd39c1c41b/image.png" alt="image.png" />

I believe we should be showing this:

<img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21qQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32b59e22c924b043dc0d0efc09358eb4e11b9031/image.png" alt="image.png" />

**Comment by wmoussa-gc** [comment]
Cannot reproduce locally, but first observations:

the log in PR env shows this error: `"msg": "NextAuth error - Code: c: Read more at https://errors.authjs.dev#credentialssignin. Error: []"`

However  in local environment I get `NextAuth error - Code: CredentialsSignin: Read more at https://errors.authjs.dev#credentialssignin. Error: []` 

the fact that the code is trimmed fails the error handling logic..if ((err as AuthError).name === "CredentialsSignin")  Im not able to reproduce this error code behavior locally

**Comment by wmoussa-gc** [comment]
for the record, a fix in that area few weeks ago: https://github.com/cds-snc/platform-forms-client/pull/3439

**Comment by Abi-Nada** [comment]
Wait until PR is merged into Staging

**Comment by wmoussa-gc** [comment]
related #3657
