### ISSUE TITLE
Document Upload Functionality - Component Validation

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#353]
Linked to #280 
- NextJS file upload component
  - set validation to only accept the following file types (limited by what Notify can handle)
    - PDF
    - CSV
    - .jpeg
    - .png
    - .odt
    - .txt
    - .rtf
    - Microsoft Excel and Microsoft Word Documents
- Ensure max file size 8MB

- Form validation 
  - Files total size cannot exceed 8MB
  - Ensure no duplicated files

==> Out of Scope <==
File upload functionality for form component already exists.

**Comment by craigzour** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept

**Comment by craigzour** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
