### ISSUE TITLE
App Router QA Testing: Staging

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3567]
### Description
Following significant changes to the application (App Router work), we need to conduct comprehensive end-to-end QA testing **in STAGING** to ensure the integrity, functionality, and performance of GCForms. Testing will be performed on Chrome and Edge browsers and will cover both desktop and tablet devices, in both the English and French interface.

### Documentation
[Test Scripts](https://docs.google.com/spreadsheets/d/1kIvHK2uK0EZcgXtEjw8NLPgQpSgNr7n-Pdcdi4WamyY/edit?pli=1#gid=1415624312)

### To be tested
  - testing on Desktop
    - [x] Chrome
    - [x] Edge
  - testing on Tablet
    - [x] Chrome
    - [x] Edge

### Acceptance Criteria:
- [x] Dev to flag when currently underway functionality is ready to be tested.
- [ ] Execute all tests using both desktops and tablets as appropriate.
- [ ] Document all issues and bugs found during testing within the top of the New Issues column, including steps to reproduce and any relevant screenshots or logs. **Be sure to include a "Bug" tag, and label the appropriate Epic**.
- [ ] Work closely with the development team to ensure that all issues are resolved and all tests are re-run to verify that the fixes have been successful.
- [ ] Provide regular updates on the testing progress and any issues or concerns that arise during standup, so that the team can stay informed and make any necessary adjustments to any upcoming release plans.
- [ ] Ensure that all test cases are fully completed and signed off before the product is released to the public, in order to minimize the risk of bugs or issues impacting our users.

**Comment by anikbrazeau** [comment]
## Anik Testing Tracking Progress

### Staging x Edge x Desktop x French

- [ ] Unauthenticated
- [ ] Create account
- [ ] Unlock publishing
- [ ] Sign in / Sign out
- [ ] Reset password
- [ ] Design a form / Add form elements
- [ ] Remove / Duplicate / Move Up / Move Down
- [ ] Hint text / Autocomplete / Character limits
- [ ] Conditional logic / Rules
- [ ] Language toggling
- [ ] Open a form file
- [ ] Share a form
- [ ] Forms view
- [ ] Translation view
- [ ] Publish form
- [ ] Email responses
- [ ] Test / Preview draft form
- [ ] Branding / Classification
- [ ] Download responses (HTML, CSV, JSON, ZIP)
- [ ] Sign off on responses
- [ ] Report a problem with responses
- [ ] Open / Close form
- [ ] Contact / Support forms
- [ ] ToU / T&C / SLA
- [ ] Profile / Security questions
- [ ] Fill out published form
- [ ] Delete form
- [ ] Admin 

### Staging x Edge x Tablet x French

- [ ] Unauthenticated
- [ ] Create account
- [ ] Unlock publishing
- [ ] Sign in / Sign out
- [ ] Reset password
- [ ] Design a form / Add form elements
- [ ] Remove / Duplicate / Move Up / Move Down
- [ ] Hint text / Autocomplete / Character limits
- [ ] Conditional logic / Rules
- [ ] Language toggling
- [ ] Open a form file
- [ ] Share a form
- [ ] Forms view
- [ ] Translation view
- [ ] Publish form
- [ ] Email responses
- [ ] Test / Preview draft form
- [ ] Branding / Classification
- [ ] Download responses (HTML, CSV, JSON, ZIP)
- [ ] Sign off on responses
- [ ] Report a problem with responses
- [ ] Open / Close form
- [ ] Contact / Support forms
- [ ] ToU / T&C / SLA
- [ ] Profile / Security questions
- [ ] Fill out published form
- [ ] Delete form
- [ ] Admin
