### ISSUE TITLE
User not automatically logged out after 2 hours of inactivity

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3574]
## Description
I logged into Staging the previous night and left the tab open - 12 hours later, I'm still logged into Staging/didn't need to input a security code.

## Steps to reproduce
1. Log into Staging
2. Keep the tab open for over 2 hours
3. Navigate around the application

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English

## Expected behaviour
It should have logged me out after 2 hours of non-activity.

## Screenshots or videos
Date of last security code sent was May 7 at 8:06 PM. On May 8 around 8:20AM, I'm still able to move around the application without getting logged out.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFBEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0386d81e11beb9d35857f69f75683ad2d3fa019/Screen%20Recording%202024-05-08%20at%208.27.31%E2%80%AFAM.mov)

**Comment by bryan-robitaille** [comment]
Confirmed that this is not an issue in Production and is only showing up in Staging.
