### ISSUE TITLE
No Response in English only in response email

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3621]
## Description
Empty fields in French yield an English string

## Steps to reproduce
1. Go to a French form with email delivery
2. Fill out leaving some fields blank
3. See "No Response" in email for unanswered questions in French

## Details
- **Browser**: Edge
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
- `Aucune réponse` in French?

## Screenshots or videos
<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--364d3fbd6d5942e35de02e1423af5b39026f0e55/Screenshot%202024-05-14%20at%207.21.09%E2%80%AFAM.png" alt="Screenshot 2024-05-14 at 7.21.09 AM.png" />

**Comment by Abi-Nada** [comment]
Issue already [created here ](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3329), so will be closing this one :)
