### ISSUE TITLE
Link to resume editing persists after deleting form

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3622]
## Description
When working on a form and going to the "Forms" view, there is a link to "Resume editing form".
If that same form is "Deleted", the link persists and it is possible to return to the editing mode.
This eventually causes an error.

## Steps to reproduce
1. Go to GC Forms
2. Create/edit a draft form
3. Go to "Forms"
4. Delete the form you were working on
5. Click on "Resume editing form"

## Details
- **Browser**: Edge
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
When a form is deleted it's not expected that it be available for editing.

## Screenshots or videos

<img width="1622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1RiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--176542246bb2a411c397e1703f41a833770fdf1e/Screenshot%202024-05-14%20at%208.05.58%E2%80%AFAM.png" alt="Screenshot 2024-05-14 at 8.05.58 AM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4d58073c8a881103791cc7794cbc549198aa0fb/Screenshot%202024-05-14%20at%208.05.47%E2%80%AFAM.png" alt="Screenshot 2024-05-14 at 8.05.47 AM.png" />

<img width="1617" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be36196577c5657b1f28100c30357bbf612a265c/Screenshot%202024-05-14%20at%208.06.10%E2%80%AFAM.png" alt="Screenshot 2024-05-14 at 8.06.10 AM.png" />

**Comment by anikbrazeau** [comment]
Also having issues deleting draft forms in general in staging on tablet / Edge, not sure why?

**Comment by timarney** [comment]
@anikbrazeau can you give this link a try please 

https://c2lgmns5n5zjrvo7fvqq2puvuy0fqkcw.lambda-url.ca-central-1.on.aws/

**Comment by anikbrazeau** [comment]
Looks good! Tested ✅ Thanks, Tim!
