### ISSUE TITLE
Time on Sign out page does not match actual time

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3625]
## Description
Time discrepancy between interface and system. Time is four hours in the future?

## Steps to reproduce
1. Go to GC Forms
2. Sign in
3. Sign out
4. See time on page

## Details
- **Browser**: Edge
- **Operating system**: Mac / Windows
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop / Tablet

## Expected behaviour
Accurate time stamp?

## Screenshots or videos
<img width="1249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3872da1f837e150b78ced017d9cb72d7682741b3/Screenshot%202024-05-14%20at%207.43.44%E2%80%AFAM.png" alt="Screenshot 2024-05-14 at 7.43.44 AM.png" />

![TIME](https://github.com/cds-snc/platform-forms-client/assets/38330843/621df0b9-ac77-4735-b28e-08a6b7cd2371)

**Comment by Abi-Nada** [comment]
The time reflects correctly in Prod - this is a new bug introduced in Staging

**Comment by anikbrazeau** [comment]
Perhaps we can simply add timezone = UTC if this is a heavier lift?
