### ISSUE TITLE
Dynamic fields "Other" and rules behaving weirdly when associated option is removed

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3627]
## Description
When adding a rule such as "Go to Other" or "Go to X question", and changing the configuration or removing it, the rule seems to stick around even after the option is removed and a new option is added.

See related ticket here for more information: https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3606

## Steps to reproduce
1. Go to GC Forms
2. Add a radio button or other select type question
3. Add options
4. Add "Other" rule
5. Remove option
6. Add option
7. See how rule remains associated with the latest option

## Details
- **Browser**: Edge
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
Removing the option should eliminate any rules that were associated to that option

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6d72cbe0207353de1750f1c611b3058f9f14e88/Screen%20Recording%202024-05-14%20at%207.57.20%E2%80%AFAM.mov)

**Comment by samsadasivan** [comment]
[Hide/show: Only show the questions within that section in the dropdown#3873](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3873)

**Comment by Abi-Nada** [comment]
^ Issue fixed in 4153
