### ISSUE TITLE
Icons disappear when clicked

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3629]
## Description
On "Forms" Clicking on "Edit" or on "Responses" makes the corresponding icon disappear?

## Steps to reproduce
1. Go to GC Forms > /forms
2. Click on any link in a form card
3. Notice the icon vanish

## Details
- **Browser**: Chrome and Edge
- **Operating system**: Mac and Windows
- **Environment**: Staging
- **Language**: French and English
- **Viewport**: Desktop and Tablet

## Expected behaviour
Go to destination with icon static

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9jQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--406ed0119e56f7b4ee38cf6e9c99609347360e11/Screen%20Recording%202024-05-14%20at%2012.19.12%E2%80%AFPM.mov)

**Comment by timarney** [comment]
PR 

https://github.com/cds-snc/platform-forms-client/pull/3648

**Comment by Abi-Nada** [comment]
Issue no longer persists in Staging :)
