### ISSUE TITLE
Inconsistency in when questions actions appear

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3633]
## Description
The "Move up" "Move down" "Duplicate" "Delete" "More" menu appears on some but not all questions

## Steps to reproduce
1. Go to GC Forms
2. Add a bunch of different form elements including dynamic fields
3. Scroll down and see how some elements "not selected" have the menu appear
4. See inconsistencies across different blocks

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Consistent behaviour across questions, menu appearing when question is in focus?

## Screenshots or videos

![Inconsistency](https://github.com/cds-snc/platform-forms-client/assets/38330843/a6584dfe-013b-4566-b820-4d40a935be07)
![NotMore](https://github.com/cds-snc/platform-forms-client/assets/38330843/134075b1-44dd-4a50-84b6-cb91938e3bc5)
![More menu](https://github.com/cds-snc/platform-forms-client/assets/38330843/f2f5f417-84a7-4399-ad61-44ba21023999)

**Comment by Abi-Nada** [comment]
Pre-known issue that will be addressed when we remove the menu here (#[3729](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3729))
