### ISSUE TITLE
Two horizontal scroll bars appear

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3644]
## Description
Two horizontal scroll bars appear in the row table of the HTML response.
Only one appears to function.

## Steps to reproduce
1. Go to GC Forms > Responses
2. Download single HTML
3. Scroll down to Row table in HTML file

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Single scroll bar, and/or do we need this format given we have csv?

## Screenshots or videos

![two scrolls](https://github.com/cds-snc/platform-forms-client/assets/38330843/89c3688c-dff6-45f6-b043-100518830665)

**Comment by Abi-Nada** [comment]
@anikbrazeau can you try re-testing and see if it still happens? I can't seem to replicate the issue

**Comment by anikbrazeau** [comment]
This is still the case on Edge, seems to be when there's more questions than fit?

Only one scroll bar actually is functional.

**Comment by anikbrazeau** [comment]
![two](https://github.com/cds-snc/platform-forms-client/assets/38330843/a9f3fd37-e1f5-4246-8707-a55b8ea219ad)

![one](https://github.com/cds-snc/platform-forms-client/assets/38330843/38ebd706-6b0a-40ab-a115-1736f18fd759)

**Comment by thiessenp-cds** [comment]
@anikbrazeau I tried to duplicate this bug using my VM with Edge. I'm not seeing the two scroll bars. Is this error still happening for you?
![Screenshot 2024-05-27 at 10 29 02 AM](https://github.com/cds-snc/platform-forms-client/assets/107579368/e5f2cdc5-9de6-4807-97b9-f27602fe71da)
