### ISSUE TITLE
Manage ownership dropdown: Styling issue 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3646]
**Re-create bug** 
- Design form 
- Add content, Save 
- Settings > Form management > Manage ownership 

<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9pQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0eae5f855bd1c02eb0414cf04f5b4c1771a1b27e/image.png" alt="image.png" />

**Comment by Abi-Nada** [comment]
This is a known bug that we chose to accept re: styling, if you refresh the page the styling should update normally. This is something we'll flag to Support when we release, as they'll just need to refresh the page if they encounter this when adding collaborators to a form.

[A card has been created here](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3531)
