### ISSUE TITLE
Check displaced when two multi-select fields are selected

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/platform-forms-client#365]
![Screen Shot 2021-08-13 at 1.26.52 PM.png](https://images.zenhubusercontent.com/60e730a033423eca358a84c7/fbf6b88e-4d4e-43d4-be12-076180b16399)

When both multi-selects are selected, or both are selected and one is then unselected, one of the checkmarks is shifted left in the box and repeats around the edges.

Occurs on [live microaquisition mailing list form](https://forms-formulaires.alpha.canada.ca/id/36) using Chrome 92.0.4515.107.

**Comment by bryan-robitaille** [comment]
@falila @craigzour Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/GCForms-60cb8929764d71000e481cab/issues/cds-snc/platform-forms-client/365?planning-poker)

**Comment by falila** [comment]
@hillaryl I've tried to reproduce this issue https://forms-formulaires.alpha.canada.ca/id/36
but i couldn't and I keep landing on "Sign-up to receive updates" page . Do you mind to share more details ?

**Comment by hillaryl** [comment]
@falila this form has since been updated to remove the multi-select (not because of this issue, but another one).

You can see the issue on this form: https://forms-formulaires.alpha.canada.ca/id/37
