### ISSUE TITLE
Link to "Forms" appears after Signing out 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3661]
## Description
Signing out of GC Forms you get a confirmation of the time you signed out and the option to sign in again. When going to sign in, there is still the "Forms" link in the header.

## Steps to reproduce
1. Go to GC Forms
2. Sign in
3. Sign out
4. Notice header

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Only present available options. Cannot have saved forms unless signed in.

## Screenshots or videos
<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWJwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb3cd66dcd8c44ddf1fddb138d8a20f305b674d8/Screenshot%202024-05-16%20at%2012.03.43%E2%80%AFPM.png" alt="Screenshot 2024-05-16 at 12.03.43 PM.png" />

**Comment by timarney** [comment]
<img width="800" alt="Screenshot 2024-05-21 at 8 26 22 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/f0cbdd19-8b2b-4973-96db-709472327399">


@anikbrazeau believe this may have been fixed when I was looking into a different issue https://github.com/cds-snc/platform-forms-client/pull/3662

Can you re-test?

**Comment by anikbrazeau** [comment]
Yes! Fixed! Thank you!
