### ISSUE TITLE
Issue moving elements up/down/duplicating in tree view

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3716]
## Description
Unable to reorder/rearrange form elements within a section

## Steps to reproduce
1. Create new section
2. Add contact information element
3. Try to reorder component parts
4. Nothing happens

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Preview
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
Move when clicked

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dba69d9082f7720d94cd8405e1562ad35b803f41/Screen%20Recording%202024-05-30%20at%201.58.08%E2%80%AFPM.mov)

**Comment by timarney** [comment]
Moving elements up / down using "Move up" or "Move down" should be working now --- didn't look at duplicate

**Comment by timarney** [comment]
Will look at duplicate today.

**Comment by timarney** [comment]
PR for duplicate https://github.com/cds-snc/platform-forms-client/pull/3727

**Comment by anikbrazeau** [comment]
Tested! Fixed! Thanks!
