### ISSUE TITLE
Order not as expected when adding questions to start section in relation to privacy statement

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3717]
## Description
When starting to build a form and adding questions they show up before the Privacy statement in the central interface but below it in the section/tree view on the right panel.

## Steps to reproduce
1. Go to design a form
2. Add title and description
3. Click on add form element
4. Add radio buttons
5. Add text to question
6. See where it shows up on left side and on right panel

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Preview
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
Match the order in the edit interface centrally and in the table of contents in right panel

## Screenshots or videos
<img width="1396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22cb859c680a5ecc16f4a9e82d4ba291f23d46bb/Screenshot%202024-05-30%20at%201.38.21%E2%80%AFPM.png" alt="Screenshot 2024-05-30 at 1.38.21 PM.png" />

**Comment by timarney** [comment]
@anikbrazeau @samsadasivan 

Just to confirm --- we're looking to move the privacy statement block up in the editor correct?

If we do that ... which I do think makes sense the Add a form element button get a little more buried especially for screen readers needed to read all the policy text.  Any thoughts on if we should address that or is that a later task?

**Comment by anikbrazeau** [comment]
That's a good consideration... I wonder if the Privacy Statement might eventually become a default section, which could solve this? 

Just flagging, because the difference between the order on the left and on the right seemed jarring, but maybe it's just temporary?

**Comment by timarney** [comment]
I'll move it up as a starter.

**Comment by anikbrazeau** [comment]
![image](https://github.com/cds-snc/platform-forms-client/assets/38330843/a5087ebc-a367-48d8-b3d6-d3c13d1fe6ae)

![image](https://github.com/cds-snc/platform-forms-client/assets/38330843/adfdf452-abcd-4bef-9af4-2eaa47e89a09)

**Comment by anikbrazeau** [comment]
Short-term solution: collapse in-line guidance for privacy statement, move up privacy statement, do communications well in advance about impact to form order and layout

Justification: as we add sections and conditional logic, repositioning privacy statement, may alter forms, spacing issue, as we yield out more complex forms putting it upfront to help people decide whether they want to provide information

**Comment by anikbrazeau** [comment]
LATEST UPDATE: https://www.figma.com/design/2bmknDRpZXN3lwqhs7mqNH/Conditional-logic-MVP-(Groups%2C-Dynamic-fields%2C-Branching)?node-id=2797-5493&t=zpTXKzc6CthqTdnV-4
