### ISSUE TITLE
[CL] Tree view: Can't drag and drop into new section

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3720]
:octagonal_sign: I can't seem to drag a new item into another section - I believe people may want to reorder
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb34fbf0fa9225827eb21c8f383af24be6c92f73/Screen%20Recording%202024-05-30%20at%202.56.07%E2%80%AFPM.mov)

**Comment by samsadasivan** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMndsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94910fc09ceebb21f2cbf8de0a28969645854a19/Screen%20Recording%202024-05-30%20at%202.56.07%E2%80%AFPM.mov)

**Comment by timarney** [comment]
@samsadasivan can you re-test?

**Comment by samsadasivan** [comment]
This works!
