### ISSUE TITLE
Internal CDS Testing

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3728]
### Description:

In order to refine and highlight bad experiences early, we will be sharing a task to the Canadian Digital Service team to start testing the new features. 

> Manual functionality testing; not concept or usability testing.

### Acceptance Criteria:
- [x] Word document created with a list of tasks to be completed in order to create form content, organize form content, add rules, and review the form. 
- [x] Create callout for potential CDS participants
- [x] Gather feedback and triage findings

**Documents**

[Feature document](https://docs.google.com/document/d/1nF5YW6lLQMLGdyljwxtKqUH4FoYaebw71w_Nv0Kt2Ew/edit#heading=h.ru24wrgw4m14)
[Alpha test plan](https://docs.google.com/document/d/1ZRkE1rLmo5PgYIp2TuGqeHfhCr0nFudCQunIhWywq4g/edit?pli=1#heading=h.yw2n0rsslon6)
[Internal CDS testing + Fable task draft](https://docs.google.com/document/d/10hknEQ13mHtXcUEhOt0c2tda8tpQxrbZAS0tBX7wUe0/edit#heading=h.yp22ocgrla7w)
[Internal CDS testing: Participant set up](https://docs.google.com/spreadsheets/d/1UgqvoICMx1uvraM8mXVN2wxcUj4lmXuY-ibESr7F96o/edit#gid=0)
[Internal CDS testing: Task (sent out to participants)](https://docs.google.com/document/d/1QAS33aUYtSY0N156vqIyhZNDS0izbDx5xISpCUC8DGI/edit#heading=h.yp22ocgrla7w)

**Comment by Abi-Nada** [comment]
Open call for sign-up but only take as many as you can process in a week

**Comment by samsadasivan** [comment]
Will update all the artifacts here when I am done gathering and triaging feedback haha
