### ISSUE TITLE
Section title is not behind conditional logic feature flag

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3755]
## Description
Section title for the confirmation message is a new concept that has not yet been introduced.

## Steps to reproduce
1. Go to staging
2. Click on Edit
3. Scroll down to confirmation message
4. See Section title tag

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
Only release mentions of sections when available?

## Screenshots or videos
![Screenshot 2024-06-06 at 11 09 58 AM](https://github.com/cds-snc/platform-forms-client/assets/38330843/bd0d28b6-aefe-4d25-83f5-60a6d094eab9)

**Comment by timarney** [comment]
@Abi-Nada @samsadasivan 

I can make a quick PR on Monday to fix this before release 

Should we just hide the "Section title" badge or do we need to do anything else?

**Comment by Abi-Nada** [comment]
@timarney I think it should be fine if we just hide the Section Title, but deferring to @samsadasivan on any design input

**Comment by timarney** [comment]
PR is ready to go

https://github.com/cds-snc/platform-forms-client/pull/3769
<img width="949" alt="Screenshot 2024-06-10 at 7 48 46 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/cfe452ff-75af-4b2c-be7f-0e91a92c908c">
