### ISSUE TITLE
Problem saving form settings when form file is unnamed

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3761]
## Description
In trying to set up settings in a draft form, encountered error 552.

## Steps to reproduce
1. Go to GC Forms 
2. Click on Publish
3. Scroll down to Settings
4. Change data classification or delivery option
5. Save changes
6. See error

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR #3757 
- **Language**: English and French
- **Viewport**: Desktop

## Expected behaviour
Ability to save when changes are made and things are clickable? Or is this related to the environment?

## Screenshots or videos

![Screenshot 2024-06-06 at 2 57 57 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/e714df6e-e333-42ce-82e7-f9d6736598ad)

![Screenshot 2024-06-06 at 3 22 28 PM](https://github.com/cds-snc/platform-forms-client/assets/38330843/ad0a737a-7741-44eb-af90-b0db1fec490c)

**Comment by timarney** [comment]
Shipped 2 "related" PRs

**Quick panel**

https://github.com/cds-snc/platform-forms-client/pull/3777

**Settings Modal**

https://github.com/cds-snc/platform-forms-client/pull/3775

**Comment by Abi-Nada** [comment]
Closing this issue as tackling [3628](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3628) will solve this
