### ISSUE TITLE
Content design: Some missing translations, such as Start / End on the right is not translated to French or "What to include in a privacy notice" either.

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3785]
All the collapsed blocks should be reviewed by Content Design in FR and EN. 

We would like to have active language like "Add a..." Rather than "What to include.." so it is not missed. 

**[Decision and discussion](https://gcdigital.slack.com/archives/C0676D34GPR/p1717443861012569)** 

If this persists:
We may have to show the rich text fields 

[Participant 5 (French flow) - Form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718118471278139)

**Comment by anikbrazeau** [comment]
This is partially addressed in PR #3818, creating a new ticket for missing translation keys for objects that show up in EN only in tree view and logic view
