### ISSUE TITLE
Sections: Section Title not editable

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3786]
"Created a new section, unable to type in the title box (Titre de la section). Why does it seem like an input box if I can’t type anything in it? " 

Within the FR flow, user cannot add a section title

[Participant 5 (French flow) - Form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718118471278139)

**Comment by Abi-Nada** [comment]
Looks like issue no longer persists (tested using the same form provided, and a new form):

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXByQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00477e23b03908729e9190b6a42c89bd2ba8ccaf/Screen%20Recording%202024-06-17%20at%208.32.56%E2%80%AFAM.mov)
