### ISSUE TITLE
Logic panel: Saving a rule and not updating right away -- it is seen as an error. 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3790]
"I changed the logic to change the flow, and when saved, it didn't update the graph so I was confused." 

"Adding logic
When I added logic, the flow chart didn’t update.  I ended up clicking the translations tab and then back to logic to force an update."

We are aware of this one. We may have to figure out a way sooner than later if we can update the graph right after you save a rule. 

[Participant 5 (French flow) - Form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718118471278139)

**Comment by timarney** [comment]
When you've seen this happen is it when your going 

section to section
or value to section 

or both?

**Comment by samsadasivan** [comment]
section to section

**Comment by samsadasivan** [comment]
More participants logged this issue - insight is added to the description

**Comment by timarney** [comment]
Possibly fixed by 

https://github.com/cds-snc/platform-forms-client/pull/3828

Which is merged now.

If someone can test

**Comment by samsadasivan** [comment]
Tested. Works! Closing issue
