### ISSUE TITLE
Logic panel: There is a bug when saving your section

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3791]
"There seems to be a bug when saving the “Go to section” (see video I sent to Sam): "
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c90269ba5eaae455cb84bde533c908cfb1a8271/Forms%20%281%29.mov)

[Participant 5 (French flow) - Form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718118471278139)

**Comment by samsadasivan** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e597921524ebf4de9210177ee58693284d181dc/Forms%20%281%29.mov)

**Comment by timarney** [comment]
Fixed here

https://github.com/cds-snc/platform-forms-client/pull/3832
