### ISSUE TITLE
Logic view: The graph "messing up" based on rules added + not being able to move the boxes to fix the view 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3792]
"I changed 2 rules in the logic section and the graph is messed up. Can it be rearranged, automatically or manually? I don’t seem to be able to move the boxes. At that point I was totally confused on how to fix it. "

We removed the ability to move nodes around in the Map view because it was too dynamic (not fixed to the grid so it would just wiggle all over the screen). But this linear view is hard. I wonder if we should try the top down view? Scrolling downward is more intuitive. 

[Participant 5 (French flow) - Form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718118471278139)

**Comment by timarney** [comment]
@samsadasivan any actions to take on this one?
