### ISSUE TITLE
Logic panel: Reset Rules didn't change the map view

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3796]
"Ended up clicking on "Réinitialiser toutes les règles" to see what it does. The page/graph doesn't refresh so it's confusing. Hit the browser's refresh button, but the graph part is now completely blank. I had to navigate away for it to appear again. "

On refresh, we can revert the map back to what the flow looked like prior to the Reset Rules action. 

Related note: 
"I found it very easy to break the flow and then wonder how to fix. Maybe an undo feature, or revisions would allow to go back to a working version more easily than trying to figure out what just happened. "

[Participant 5 (French flow) - Form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718118471278139)

**Comment by timarney** [comment]
Possibly fixed by

https://github.com/cds-snc/platform-forms-client/pull/3828

Which is merged now.

If someone can test

**Comment by samsadasivan** [comment]
Tested - works great! Closing this ticket
