### ISSUE TITLE
Confirmation heading: French isn't displayed on toggle

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3798]
This is a general bug after app-router! 

When I toggle the language to French, it does not update the confirmation h1 to french <img width="1662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba6bad3f081ea5b4ad346996b63c79fc78542d35/image.png" alt="image.png" />

<img width="1391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2705de2347f93b6a70af4d40f210556712c145e/image.png" alt="image.png" />

**Comment by timarney** [comment]
Which lang toggle?

I see this when I use the "site level" toggle

<img width="1019" alt="Screenshot 2024-06-12 at 11 09 31 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/64834ee0-5e2c-404e-b888-334cce641564">

**Comment by Abi-Nada** [comment]
Validated that this isn't a bug
