### ISSUE TITLE
Auto-flow: Reordering sections after setting a custom rule 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3802]
"At first, I wasn’t aware of the Logique panel, so I tried reordering the section to change the form’s flow and it didn’t work so I struggled with that" 

"Maybe I had set a custom rule, I’m not sure anymore :disappointed: Because it seems to be working now"

This should be fixed, I think Dave worked on this. I am going to log this as a bug. You should be able to reorder your sections even after a rule is set.

**Comment by timarney** [comment]
@samsadasivan can you confirm if this still needs work?
