### ISSUE TITLE
Logic view: reorganizing the flow chart didn't save when they toggled to other Nav items 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3815]
"Toggle interactivity
This setting defaults to unlocked, but I can’t drag anything around unless I lock and then proceed to unlock it again
After organizing my flow chart, if I navigate away from the logic tab and back again, it resets, undoing everything I just did" 

This could be a bug. It is interesting that it only updates rules when you toggle away, and then doesn't save the rules when you toggle away again haha. 

[Participant 1 (English flow) form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718195555405529)

**Comment by timarney** [comment]
Removed iteractiive mode 

Fixed by

https://github.com/cds-snc/platform-forms-client/pull/3828

Which is merged now.

If someone can test

**Comment by samsadasivan** [comment]
Test - works great! Closing issue
