### ISSUE TITLE
Review page: Displayed a section that wasn't interacted with 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3816]
"Time travel
After saying I had an allergy, I indicated what the allergy was in the question that was revealed
On the review page, I clicked edit for that section, changed my response to NO, continued back to review page
The review page still showed my allergy selection, even though I said I had none (at statcan we had the concept of “off-path” data for this, so we could receive the data but also let our clients know explicitly that the user ended up flowing past this question)" 

This could also be a bug. I know we designed and implemented around this scenario. This is for an English flow. 

[Participant 1 (English flow) form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718195555405529) 

## Note:
This ticket can be re-purposed to do some manual testing for this ticket #3862

**Comment by thiessenp-cds** [comment]
This ticket may need more discussion. Here is a [related thread on slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718297774581869).
