### ISSUE TITLE
Logic panel: Direct link to the panel doesn't load the chart 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3817]
"Direct navigation
If you navigate directly to the logic page (i.e. /form-builder/{form_id}/edit/logic or by reloading the page), the flowchart doesn't load" 

[Participant 1 (English flow) form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718195555405529)

**Comment by timarney** [comment]
I have narrowed this down to our Content security policy blocking something when this page is loaded directly.

Not sure how to solve yet .

**Comment by timarney** [comment]
Merged a fix for this.
