### ISSUE TITLE
Keyboard shortcuts: Typo: “Pick up and item”

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3820]
Keyboard shortcuts tooltip
Typo: “Pick up and item”

[Participant 1 (English flow) form file in slack](https://gcdigital.slack.com/archives/C0676D34GPR/p1718195555405529)

**Comment by timarney** [comment]
Looked in the code --- looks like this is fixed already.

<img width="502" alt="Screenshot 2024-06-21 at 8 52 36 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/92718033-5ea4-4d6d-9ff9-224907bf95ed">

**Comment by Abi-Nada** [comment]
Issue no longer persists
<img width="620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de05d26d721294a4562a072fa6a485c597d39e5b/Screenshot%202024-06-24%20at%207.57.54%E2%80%AFAM.png" alt="Screenshot 2024-06-24 at 7.57.54 AM.png" />
