### ISSUE TITLE
Language of preview/test does not match 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3844]
## Description
English content in French for Preview/Test

## Steps to reproduce
1. Go to Conditional logic environment
2. Create sections
3. Go to test form
4. Notice "Review your answers before submitting the form." in English even when in French
5. Notice "Edit" in English even when in French
6. Notice "Go back" in English even when in French

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: CL/Staging
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
Preview content should match language of previewing.

## Screenshots or videos
<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dce664616bc373515d0b89d0b5939cea46f45b6c/Screenshot%202024-06-17%20at%209.47.33%E2%80%AFAM.png" alt="Screenshot 2024-06-17 at 9.47.33 AM.png" />

**Comment by anikbrazeau** [comment]
This is still an issue, the buttons are in the interface language but should be in the form preview language.

**Comment by Abi-Nada** [comment]
Thanks for validating, Anik! @thiessenp-cds we've confirmed this issue still persists, so I've assigned you to take a look during this sprint :) Thank you!

**Comment by timarney** [comment]
@thiessenp-cds 

I started a PR here

https://github.com/cds-snc/platform-forms-client/pull/3899
