### ISSUE TITLE
Alert - Warning to test for conditional logic outlining responsibilities and the expectation to test all paths before publishing

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3846]
## User story
As a form builder publishing a form with branching logic and show/hide rules
I need know that I'm responsible for testing the form to check that all paths function as expected
So that the risk of flow errors, dead-ends, infinite loops, and bad experiences for users of my form are mitigated.

## Context

This is a risk mitigation strategy to make it more explicit that functional / logical forms are the client's reponsibility.

## Proposed solution

Alert to nudge people to test their form flow thoroughly --> before publishing

https://www.figma.com/design/bIcbQm61JbkCy9Nu8XE7u6/Conditional-logic-Alpha?node-id=4450-1323&t=ZZJakBGDl5bWHyy2-4 

![Screenshot 2024-07-11 at 10 20 05 AM](https://github.com/cds-snc/platform-forms-client/assets/38330843/cf015266-8a6d-48f6-b306-bc2c7e681850)

## Acceptance criteria
- [x] EN alert content
- [x] FR alert content
- [ ] Dev implementation

**Comment by anikbrazeau** [comment]
## 1. Warning modal when resetting to autoflow

[Coming soon]
