### ISSUE TITLE
Policy page loading is unclear

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#3847]
## Description
When clicking the "Agree" button on the policy page there is no indication the page is loading. Ideally there would be an indicator the page is loading to avoid confusion.

Related threads:
- [slack thread 1](https://gcdigital.slack.com/archives/C01GFD150MC/p1718292356453139)
- [slack thread 2](https://gcdigital.slack.com/archives/C0117FN8G9K/p1718393687708149l)

**Comment by timarney** [comment]
@thiessenp-cds we can close this now yes?
