### ISSUE TITLE
Clarify terminology (holistically) to differentiate dynamic fields from branching logic panel/ rules

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3848]
## User story

As a form builder
I need to clearly understand the new concepts linked to **pages/logic**
So that I can focus on my form and use this feature with ease

As a form builder
I need to understand how to affect the flow within the **panel / rules**
So that the experience makes sense holistically

As a form builder
I need to recognize that there are **rules that apply to questions** and **rules that apply to sections** that are different
So that I can leverage GC Forms to create better forms for my users 

As a form builder
I need to know **how to show a question on the same page with hide/show display logic**
So that I can flow from question value to another question

## References

[Glossary](https://docs.google.com/document/d/1nF5YW6lLQMLGdyljwxtKqUH4FoYaebw71w_Nv0Kt2Ew/edit#bookmark=id.v3ws4dx584q1)

## Acceptance criteria
- [x] Sections / Pages concept
- [ ] Logic / Branching concept
- [ ] Rules / Show-hide concept
- [ ] Autoflow concept
- [ ] In English and French

**Comment by anikbrazeau** [comment]
#3960 #3962 #3980
