### ISSUE TITLE
Banner: Set expectations for new UI and release (2 banners, before and after release) 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#3849]
**User story**: Persona based
As a form builder and stakeholder
I need to know what is going to change in the form builder
So that I don't get lost

**Story context**
*Link to relevant user research, analytics, data, or design documentation*

**Acceptance criteria**
- [ ] *feature* provides equal service in French and English.
- [ ] *feature* works on Chrome, Firefox, Edge, Safari, and Opera.
- [ ] *component* provides and auto-fill response if the field is saved on the end-users browser.
- [ ] *component* provides error messages and validation.
- [ ] *goal* can be completed using a screen reader.
- [ ] *visual elements* observe colour contrast requirements. 
- [ ] manual accessibility testing meet WCAG 2.1 AA requirements.
- [ ] risk register is updated to reflect new risks and their treatments. Treatments are implemented or a new card is created.
- [ ] *feature* collects the data intended, stores, and submits it in the correct format via email, API, or other retrieval method

**Comment by anikbrazeau** [comment]
@samsadasivan is there a concept already under development somewhere in Figma?

**Comment by anikbrazeau** [comment]
https://www.figma.com/design/bIcbQm61JbkCy9Nu8XE7u6/Conditional-logic-Alpha?m=dev#874716701
