### ISSUE TITLE
Accents not showing up properly in Excel on Windows

### ISSUE THREAD

**Issue by jprince-cds** [cds-snc/platform-forms-client#3877]
## Description
When opening a CSV file that contains French accents (questions and/or responses), they don't show up properly on Windows. The accents get converted to 2 other symbols. The reason for this is the file is in Unicode format, while Windows Excel seems to be expected ANSI/iso-8859-1 encoding. 

## Steps to reproduce
1. On a Windows PC, double-click a CSV file containing responses with French accents. 
2. You will notice that accents are displayed incorrectly, for example **é** becomes **Ã©**

## Details
- **Browser**: Any
- **Operating system**: Windows
- **Environment**: Production
- **Language**: English
- **Viewport**: Any

## Expected behaviour
Accents should be displayed correctly.

Here is the workaround needed for the files to open up correctly in Excel on Windows.

Right-click the CSV file, Open With, choose Notepad.
Select File, Save as...
In the save dialog, change the encoding to ANSI.
Save the file and double-click to open in Excel. The accents are loading properly. 

## Screenshots or videos
<img width="768" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2lEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67f60fb41dde58ce10e7194ade0054b109d3ab23/image.png" alt="image.png" />

**Comment by jprince-cds** [comment]
[testing-sign-up-form-2024-06-11-responses-reponses.csv.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3VEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--841b116bd2faa43c56173f27c8769e301fdd4650/testing-sign-up-form-2024-06-11-responses-reponses.csv.zip)

**Comment by jprince-cds** [comment]
We should inform client in [Ticket 17757](https://cds-snc.freshdesk.com/a/tickets/17757) once this is resolved, as they are using this workaround now.

**Comment by anikbrazeau** [comment]
Related to #3878

**Comment by timarney** [comment]
How often are we seeing support requests for this type of issue come up?

Is this happening for all / most users or a few?


----

For now I found a couple of alternative ways to get excel to pick up the utf-8 encoded files properly at the file level vs making OS level changes.

1) Data import

<img width="689" alt="from-csv" src="https://github.com/user-attachments/assets/d2c34ce7-2f46-4d87-8fe8-aedccd53f173">


![import](https://github.com/user-attachments/assets/296f05d5-e43e-48b0-9a7c-48209f5ab6d6)


2) Rename the .csv extension to .txt

Open the .txt file in Excel 

Excel will prompt with import step

 
![txt](https://github.com/user-attachments/assets/e9aa04e5-a95e-4386-8948-8b359069ce69)

**Comment by timarney** [comment]
RE: converting to a .txt file

Found this note under the Excel help docs

> Note: When Excel opens a .csv file, it uses the current default data format settings to interpret how to import each column of data. If you want more flexibility in converting columns to different data formats, you can use the Import Text Wizard. For example, the format of a data column in the .csv file may be MDY, but Excel's default data format is YMD, or you want to convert a column of numbers that contains leading zeros to text so you can preserve the leading zeros. To force Excel to run the Import Text Wizard, you can change the file name extension from .csv to .txt before you open it, or you can import a text file by connecting to it (for more information, see the following section).

**Comment by timarney** [comment]
Found this Microsoft article 

> You can open a CSV file encoded with UTF-8 normally if it was saved with BOM (Byte Order Mark). Otherwise, you can open it through either of the following ways.

https://support.microsoft.com/en-us/office/opening-csv-utf-8-files-correctly-in-excel-8a935af5-3416-4edd-ba7e-3dfd2bc4a032

Testing with the file attached to this issue 

There is no - Byte order mark (BOM)

https://validator.w3.org/i18n-checker/check#validate-by-upload+ 

<img width="684" alt="Screenshot 2024-08-29 at 2 41 58 PM" src="https://github.com/user-attachments/assets/cc209c14-5239-4b24-a359-ac979c27e08d">

Ref: https://github.com/cds-snc/platform-forms-client/pull/2659

**Comment by timarney** [comment]
https://github.com/cds-snc/platform-forms-client/pull/4237

Testing here https://o52ubyux2llkeflxz3qkqbbs4i0yzada.lambda-url.ca-central-1.on.aws

Created a form 

Added response --- download CSV

Uploaded to checker the file is showing with Byte order mark (BOM)

Tested on tablet --- opened with chars showing.

<img width="714" alt="Screenshot 2024-08-29 at 2 58 15 PM" src="https://github.com/user-attachments/assets/be5d5408-6ce4-4ea2-9751-3b04c3cc6914">

**Comment by timarney** [comment]
@Abi-Nada @anikbrazeau 

Are you able to generate a response file that doesn't have a Byte order mark (BOM) ?

I tested under a fresh PR and on staging (no updates) and the files have the Byte order mark which per note open on my tablet fine vs the file attached to this issue doesn't (and doesn't have the BOM).


You can check a file to see if it has a BOM by uploading a file here:
https://validator.w3.org/i18n-checker/check#validate-by-upload+

i.e detects BOM as UTF-8
<img width="714" alt="362855253-be5d5408-6ce4-4ea2-9751-3b04c3cc6914" src="https://github.com/user-attachments/assets/4469c964-f00f-4e97-94ab-465c90d53ef6">

**Comment by anikbrazeau** [comment]
@timarney I wonder if this is an issue with files when they are not zipped. 

Just tested 
1. downloading CSV zipped
2. downloading CSV not zipped

## 1. CSV - zipped

Accents show up as expected, when opened in Excel on Windows:



File does not seem to have a Byte order mark (BOM)


## 2. CSV - not zipped

Accents glitch as described in the issue, when opened in Excel on Windows


File does not seem to have a Byte order mark (BOM)

**Comment by timarney** [comment]
@anikbrazeau can you try this preview environment for the "files when they are not zipped" scenario 

It should apply the BOM to non zipped files.

https://o52ubyux2llkeflxz3qkqbbs4i0yzada.lambda-url.ca-central-1.on.aws

**Comment by anikbrazeau** [comment]
Works! :D

**Comment by timarney** [comment]
The fix in https://github.com/cds-snc/platform-forms-client/pull/4237 has been merged and was released in 3.21.0
