### ISSUE TITLE
Conditional Logic Diary Study

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3879]
### GC Forms:
Conduct a diary study to evaluate and understand the user experience and challenges faced by participants when using the conditional logic feature in GC Forms.

### Documentation:
[Alpha Research Plan](https://docs.google.com/document/d/1ZRkE1rLmo5PgYIp2TuGqeHfhCr0nFudCQunIhWywq4g/edit)
[Facilitation Guide](https://docs.google.com/document/d/1PACFytxIba7MxZDUiUBwvcWXFJfb6_xmH2ePIf8q93U/edit#heading=h.5zuj97ucryw9)
### Acceptance Criteria:
- [x] 4-6 participants recruited and scheduled for kick-off meetings
- [x] Kick-off meetings conducted and initial data gathered
- [x] Participants actively engage in the diary study and log their observations
- [x] Exit interviews conducted and final insights collected
- [x] Participant logs analyzed for common themes and challenges.
- [x] All identified bugs logged in Zenhub - **will only be prioritizing Critical and Severe issues for V1**

**Comment by Abi-Nada** [comment]
@connorscarolyns to create cards for flagged bugs - flag to @Abi-Nada once done

@Abi-Nada to include steps to recreate for cards

**Comment by anikbrazeau** [comment]
https://miro.com/app/board/uXjVK4Bp0Ho=/

**Comment by Abi-Nada** [comment]
No response from remaining 3 clients, so we're good to wrap up this card! Thanks so much for all the work!
