### ISSUE TITLE
SLA/ToU Updates: Clarify expectations and responsibilities

### ISSUE THREAD

**Issue by hegazynourhan** [cds-snc/platform-forms-client#3900]
## Updates in order of priority:

1- Not manipulating JSON files ✅
2- Clarify timelines for data download #
3- Clarify responsibility for PB data transfer ✅
4- Abandoned forms/accounts #3920

https://docs.google.com/document/d/1N53LZ7rEmCdoOdA4wbsY9-_REbR4ZKXRSgISCL4sRpI/edit

## Links

- [Terms of Use ](https://docs.google.com/document/d/1ThGNKO_oyKBSgm7R5Smi8goBIphCV-VTa3249J5sdDc/edit)
- [Service-level Agreement](https://docs.google.com/document/d/16Wi9ySVvY6oTA9kGIL-fRRPswSmHbgnMToXOzj5Tz2c/edit)
- [Context](https://docs.google.com/document/d/1N53LZ7rEmCdoOdA4wbsY9-_REbR4ZKXRSgISCL4sRpI/edit#heading=h.wlhotxq6csiq)

## Acceptance criteria:
- [x] Content drafted in EN
- [x] Reviewed by Policy
- [x] Reviewed by Product
- [x] Reviewed by Content
- [x] Translated in FR
- [x] PR created
- [ ] Reviewed by dev and shipped

**Comment by anikbrazeau** [comment]
Updates here: https://github.com/cds-snc/platform-forms-client/pull/3911
