### ISSUE TITLE
Logic panel in French shows English sections in dropdown

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3929]
## Description
When using the French interface and editing in French, the options to jump to a specific section only appear in English

## Steps to reproduce
1. Go to a form with complex logic ex: `cly4tn2hm0001dnn6jpmi6h62`
2. Navigate in French
3. Click on "Logique" tab
4. In the dropdown "Aller à la section" notice how options pick up English section names
5. Also notice how in the logic branching view names change to French

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
Matching names in the logic view and logic panel.
Matching the editing / interface language as expected.

## Screenshots or videos

<img width="1772" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDJyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--990ed4e717d0f2c8af818532ef05ae355d7a60b2/Screenshot%202024-07-02%20at%203.52.04%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 3.52.04 PM.png" />

<img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcbfaaa2511d94e12edbbe7c58a6bbbdf530bb4e/Screenshot%202024-07-02%20at%203.52.17%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 3.52.17 PM.png" />

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--313d51ca5ccadb68e1bc5cbe97ffcf140dcacd6b/Screenshot%202024-07-02%20at%203.52.10%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 3.52.10 PM.png" />

**Comment by timarney** [comment]
Looks 

Looks like this is a case of Section Name (whatever the user inputs)  vs Section title (bilingual  + if the user fills it in)

<img width="538" alt="Screenshot 2024-07-10 at 12 07 05 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/b563e989-02ee-4efe-9cb2-4343fd10d589">


<img width="524" alt="Screenshot 2024-07-10 at 12 07 15 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/961f536b-af93-4ed2-ba25-16976fd126b6">

**Comment by timarney** [comment]
@anikbrazeau @Abi-Nada 

Thinking we should stick to using the section names here correct?

**Comment by Abi-Nada** [comment]
@timarney that makes sense to me! @anikbrazeau any input on your end?

**Comment by anikbrazeau** [comment]
That makes sense! Thanks Tim and Abi!

**Comment by timarney** [comment]
PR:
https://github.com/cds-snc/platform-forms-client/pull/3989

**Comment by timarney** [comment]
This is merged will close.
