### ISSUE TITLE
Order of sections in tree view does not match order in logic view (end before beginning) when opening a file

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3930]
## Description
The confirmation page shows up first, then the beginning of the form, then the different pages

## Steps to reproduce
1. Open the dental form
2. Notice the order of sections/questions in tree view 
3. Notice the order of sections/questions in logic view

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English / French
- **Viewport**: Desktop
- **Output**: form ID `cly4tn2hm0001dnn6jpmi6h62`

## Expected behaviour
Order that matches throughout different views
Titles in tree view rather than names? If not get a mix of EN and FR

## Screenshots or videos

<img width="313" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95fee38c6544e642d1948f39c15ee7aefd4061f7/Screenshot%202024-07-02%20at%203.55.33%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 3.55.33 PM.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d70ce16b7c19e799d482255cbbe5eb2e1a05b1fb/Screenshot%202024-07-02%20at%203.55.29%E2%80%AFPM%20%282%29.png" alt="Screenshot 2024-07-02 at 3.55.29 PM (2).png" />

<img width="330" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6ff42873c3fa6ffd91ed89a34ff6b976587c005/Screenshot%202024-07-02%20at%203.55.27%E2%80%AFPM.png" alt="Screenshot 2024-07-02 at 3.55.27 PM.png" />

**Comment by Abi-Nada** [comment]
Issue no longer persists
<img width="1028" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzYwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--360a3d7e4cb3f6bc344d4531ce86869d3b3ce635/Screenshot%202024-07-04%20at%209.18.11%E2%80%AFAM.png" alt="Screenshot 2024-07-04 at 9.18.11 AM.png" />
