### ISSUE TITLE
Overlapping sections in Map view

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3933]
Below are my notes re: the glitched form. If you’d like additional details, let me know.
 
June 28, 2024
Notes for the Form that appears to be glitched. I will send my other notes from this session separately (i.e., not related to the glitched form).
Browser: Microsoft Edge
Windows 10 Enterprise
Json file attached

Issue summary:
I don’t remember exactly what I was doing when I noticed this, but I believe I was just working on adding in our own privacy statement so that I could see how the start of the form would look with the full statement.  
Sections "End" and "Beginning"  just appeared in the order as shown in screenshot below and I couldn't drag and drop to rearrange the sections back to how they were originally. I can drag and drop the sections I created but I can’t do anything with the locked sections. This prevented me from being able to set up a proper logic flows so I opted to just create a new form and start from scratch. Screenshot included.

<img width="457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2F1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00d748ae6bd490bfb67e0133f38643a83b0fbc47/image.png" alt="image.png" />

In the Logic tab, the logic flow tables are merged together and couldn't find a way to reassemble them because I can’t move individual tables within the logic section, just the entire workflow as a whole. I tried resetting the linear logic but that didn't help. Screenshot included.

<img width="974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2V1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7a05d02b07c46aa88b53c125456d00d52a76c4c/image.png" alt="image.png" />

**Comment by connorscarolyns** [comment]
[psohp-sr-form-glitched-2024-07-02-json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3l1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68cab2d682f538734b2553c6c605c9d2b9a4e655/psohp-sr-form-glitched-2024-07-02-json.txt)

**Comment by timarney** [comment]
We've seen this before where end section gets flipped to the top but haven't been able to reproduce yet.

If anyone can re-create we would love to get the steps so we can fix this issue.

**Comment by connorscarolyns** [comment]
This happened live in our first session I believe. Let's review the video to see what happened. The user stared with a JSON form file they uploaded then started to modify

**Comment by connorscarolyns** [comment]
more context from one of our participants:
I’m starting from scratch each time. I’m seeing this happen when I continue working on a form I previously started. In the case that I described, I had logged back in the day after I had started the form.
 
Although the tables in the Logic tab weren’t affected in the same way as my example below, when I logged back in yesterday to take a look at the new form I had started on Friday that the “End” and “Beginning” sections were doing the same thing as my glitched form and the sections I had added weren’t in the order I had left them. But in my new form, I was able to move the sections back into the right order (with the exception of the locked ones).
 
I created a third mini form out of curiosity. I simply added a couple of new sections (no questions/content). I saved the draft and left the form to go back to my main testing form. When I returned, the sections had reordered themselves with the “End” at the top and “Beginning” second. In this case, I was still in the same session; I didn’t log out and log back in.
 
If it helps, here are my notes from yesterday, minus the third little experiment I noted above.
 
July 2, 2024 NOTES
Noticed that sections "End" and "Beginning" have moved to the top of the section list, with "End" appearing first and "Beginning" appearing second. When first creating/working on a form, the first section is "beginning", the last section is "end" and any new sections I create are positioned between these. The sections I had created also appeared out of order from how I had left them at the end of my last session. I couldn't get the keyboard shortcuts to work (maybe because I'm using Edge?). When I navigated to a section using my arrow keys, clicking ctrl + D saved the page to my favorites rather than pick up the item.
The workflow/tables in the Logic tab appear to be ok, though there's now overlap between one of my tables and the confirmation message found in the "End" section. I can still get at my table when I click on it so this looks to be more of a visual issue and not causing any technical problems.
Would be nice to be able to move individual tables myself in order to rearrange them into an easier to see format. The auto positioning that's applied tends to move the tables far away from one another (vertically). I wouldn't need to drag my screen up to view tables out of my view if I could position them closer to one another myself. Would also help in fixing positioning glitches when they happen (e.g., tables get positioned on top of one another).
image001.png
Went back to the tab "Questions". Decided to put the sections I had created back in their logical order as  shown with the tables in the Logic tab. I could rearrange them without affecting the rules I had already developed but sometimes the sections would not allow me to drop them between sections where I wanted them dropped.
When I left the form and went back in, the order of the tables in the Logic tab had shifted; the tables weren't overlapping anymore.

**Comment by connorscarolyns** [comment]
recreating the bug:

[Uploading... screen-capture (8).webm]

**Comment by connorscarolyns** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2l4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da88c39a3072c3c53b75f25ca189c8c005f9ff59/screen-capture%20%288%29.webm)

**Comment by timarney** [comment]
Need to dig into how the json is getting into this state but adding a reset as a way to get out of this state here

https://github.com/cds-snc/platform-forms-client/pull/3953

**Comment by timarney** [comment]
Going to spend some time on this and make a schema update to handle the Group ordering for the TreeView based on a Group layout array the same as the way the elements are handled.  To date I avoided doing this as it makes some things more complicated but it will ensure the groups will not end up out of order.

The TreeView will need updates to use Group layout array vs the groups object.

Overall this will be a lift but will bring the most safety as far as the ordering goes.

**Comment by timarney** [comment]
Merged the PR

The schema for groups now includes a groupsLayout array

https://github.com/cds-snc/platform-forms-client/pull/3985

Noting existing forms on staging won't have that data until the form is resaved ---

The issue with End etc... moving to the start of the Tree and other sections getting out of order should be corrected now.

Tested with @thiessenp-cds multiple ways and times.

@Abi-Nada thinking we should close this one and open fresh tickets as needed.

**Comment by Abi-Nada** [comment]
Amazing! Sounds good, will close it out :) Thanks so much!
