### ISSUE TITLE
Accessible upload form component does not work in IE11. 

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#394]
The new accessible upload component unfortunately does not work on IE11 as we are required to support it we should fix this before this hits production. 

https://user-images.githubusercontent.com/26819992/130997280-3c84b18a-d3b5-42b4-8377-7cf5b5c1e618.mov

**Comment by craigzour** [comment]
Linked to #399

**Comment by craigzour** [comment]
See #399 . Both issues are linked.
