### ISSUE TITLE
V1 - Create Repo for API Server

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#3944]

**Comment by wmoussa-gc** [comment]
related design doc https://docs.google.com/document/d/1MK_aPiJIYBvO8K_5OJZ-bqrkS7hHYeeO5SPpvqMjyUU/edit#heading=h.11co1vkweuti

**Comment by wmoussa-gc** [comment]
Repo ready https://github.com/cds-snc/forms-api
