### ISSUE TITLE
V1.2 - Implement Token Throttling for API Server

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#3947]
Plan / Tasks:

API:
- [x] Configure low and high capacity token buckets
  - Low: 100 requests per minute
  - High: 300 requests per minute
- [x] Consume token for each request
- [x] Refund token when request fails because of internal error
- [x] Inform user about bucket status (capacity, remaining tokens, time before refill) using HTTP response headers
- [x] Write unit tests
- [x] Add procedure for switching to High capacity token bucket in https://github.com/cds-snc/platform-forms-client/issues/4489
- [x] Load tests in Staging to see how much of an impact the rate limiter layer has on the API
- [x] Communicate with @anikbrazeau to update our documentation

**Comment by craigzour** [comment]
Load tests did not reveal any impact on the API response time.

@srtalbot Going to close the ticket but you can consider the rate limiting feature as releasable.
