### ISSUE TITLE
Mis-matched text: Beginning / Start

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3962]
The start page is labelled "Beginning" in the question view and tree view but labelled "Start" in the logic dropdown list.

**Comment by anikbrazeau** [comment]
Potentially also related #3930?

**Comment by connorscarolyns** [comment]
No, this is unrelated. It's just a labelling consistency issue.

**Comment by anikbrazeau** [comment]
## Consideration

Now that we've switched from "sections" to "pages" and added early exits, we might consider changing the "start" and "end" concepts to make the page concept more explicit:

## Proposal: 

EN: `Start page` // `Review page` // `Confirmation page`
FR: `Page de départ` // `Page de révision` // `Page de confirmation`
