### ISSUE TITLE
User unable to add a branching rule unless they clicked off and came back to the question in the tree view

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#3971]
The user encountered disabled branching options that should have been enabled. By clicking another question and returning to the original question, they could enable the options.

> Had a glitch where it was preventing me from adding a rule based on a question in our Form (the function was greyed out; couldn't add a rule). The glitch disappeared when I clicked through to a different question and went back to my original on

**Comment by Abi-Nada** [comment]
To validate if this issue persists in QA Testing

**Comment by Abi-Nada** [comment]
Unable to recreate this issue.
