### ISSUE TITLE
Front facing form: Privacy Statement should be before questions

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4015]
### Description:

[Slack thread for reference](https://gcdigital.slack.com/archives/C0676D34GPR/p1721231029417039)

Currently when you create a form in Staging that contains a Privacy Notice and Form questions, when you preview the form -> the Privacy Notice appears to be underneath the inputted questions. This does not reflect the order in the Form Builder.

### Video:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG5xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--144ca1bf6b1bec084396c87aa39ed7abd2c299bb/Screen%20Recording%202024-07-17%20at%2012.30.38%E2%80%AFPM.mov)

### Acceptance Criteria:
- [ ] We need to make the change on the front-facing form to reflect the Privacy Notice _before_ the form questions

**Comment by Abi-Nada** [comment]
PR Ready for testing

**Comment by timarney** [comment]
https://g5bgkt44nwurujzbi67mnzmln40gimcd.lambda-url.ca-central-1.on.aws/

**Comment by Abi-Nada** [comment]
Can confirm that privacy notice is display in the correct order, in Preview **and** when the Form is published!

**Comment by timarney** [comment]
merged

**Comment by Abi-Nada** [comment]
Hi @timarney ! Just confirming if this PR's been merged/ready to close out? I don't see the PR merged in Staging 👀
