### ISSUE TITLE
Removing “Start Page” in Translations

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4028]
## Description
Do we need “Start Page” within the Translation page? You can’t edit it in the interface, so maybe it shouldn't be included as a string in the Translation page.

## Steps to reproduce
1. Create a new form
2. Go to Translation tab
3. Edit the "Start Page" field
4. Navigate back to the Edit page
5. See error - nothing changes

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: EN/FR

## Expected behaviour
Since this field isn't editable, there shouldn't be a need to have it included in Translations. So we should remove it from Translations.

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUx2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0199907d155c075785ea7f401a8496e85a98a76d/Screen%20Recording%202024-07-18%20at%2011.33.03%E2%80%AFAM.mov)

**Comment by timarney** [comment]
Ya the start page title can't be editable and shouldn't show up.

**Comment by Abi-Nada** [comment]
Hi Vivian! The Translations csv still reflects the Start Page in both the EN/FR column - can we have that removed?

<img width="704" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmdXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9694149082af0de6d3b0dc9e5fb0a45bc56265c/Screenshot%202024-07-29%20at%207.09.41%E2%80%AFAM.png" alt="Screenshot 2024-07-29 at 7.09.41 AM.png" />

**Comment by Abi-Nada** [comment]
Actually nvm, I'll create a separate card for it since there's a couple other EN fields in the csv + it's a more minor fix :)
