### ISSUE TITLE
Right panel is not fixed and requires too much scrolling to use

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4031]
The right panel should be fixed similarly to the left menu so that the list items in the tab can scroll independently from the main content pane.

**Comment by connorscarolyns** [comment]
This additional css styling will get us an MVP fixed bar without any additional reconstruction

<img width="1013" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW54QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b70438da63002c6259fce85bbb00560e68e518d/image.png" alt="image.png" />

**Comment by timarney** [comment]
For reference here's a PR I started previously and closed  

https://github.com/cds-snc/platform-forms-client/pull/3902

Was looking at https://www.radix-ui.com/primitives/docs/components/scroll-area which is nice but ran into CSP issues with the styles --- using just Tailwind should suffice vs pulling in this lib.


Of note:
Scrolling a form element in the editor into view - 

https://github.com/cds-snc/platform-forms-client/pull/3902/files#diff-1bd5268e1ecc8d4de6c1b0cf3f39a74adaa3594800f0379dbc2c2f695cc48bbdR145

There's code moving the ref provider up to make form elements available from the Right Panel 

That work was moved into a  PR here https://github.com/cds-snc/platform-forms-client/pull/3935 which has been merged.

**Comment by timarney** [comment]
Ideally I think we should `stick` the right nav so it's not fixed until the header is offscreen (doesn't go over the header).  The left nav already operates like this so be nice to keep it consistent.


In this example I'm using `isIntersecting` which is already available in the code ...



https://github.com/user-attachments/assets/9ff78f0b-c484-4e09-bb93-fd3814169c46

**Comment by Abi-Nada** [comment]
PR #4100
