### ISSUE TITLE
Template not found error on Slack when accessing settings/manage page with invalid form identifier

### ISSUE THREAD

**Issue by craigzour** [cds-snc/platform-forms-client#4038]
## Description
An error is thrown in the web application when accessing the settings/manage page with an invalid form identifier. This causes an alert log to be sent on Slack.

## Steps to reproduce
1. Go to https://forms-staging.cdssandbox.xyz/en/form-builder/thisisatest/settings/manage
2. See error `Error: Template not found` on Slack in the `#forms-staging-events` channel

## Expected behaviour
We should not be notified of such error on Slack.

## Additional context
Discussion about the problem https://gcdigital.slack.com/archives/C05G766KW49/p1721329614030249

**Comment by Abi-Nada** [comment]
Issue has been fixed with PR #4571
