### ISSUE TITLE
Back button on "Test" in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4041]
## Description
The back button and continue button are not responsive in the same way.
Not enough spacing with banner alert in unauthenticated mode.

## Steps to reproduce
1. Create a multi-page form
2. Click on Test
3. Adjust screen size

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English and French
- **Viewport**: Desktop / Tablet / Mobile

## Expected behaviour
Similar behaviour for all buttons
Spacing / relationship with alert banner

## Screenshots or videos

<img width="483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenIyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f17eb526ade80f1b1f73e01b9d2b06555a12a526/Screenshot%202024-07-19%20at%202.57.11%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 2.57.11 PM.png" />

<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenYyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03344a6afbd181712067b7f527954f5b711fcea3/Screenshot%202024-07-19%20at%202.56.08%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 2.56.08 PM.png" />

**Comment by Abi-Nada** [comment]
@anikbrazeau can you re-test to see if this issue persists? I can't seem to recreate it

**Comment by anikbrazeau** [comment]
Looks fixed!!
