### ISSUE TITLE
Conditional Logic QA Testing

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4052]
###  Description:
End-to-end testing of the Conditional Logic feature to catch any bugs and validate that the feature works as intended.

#### Feature Functionality:
- [x] Add pages: Move them up/down/delete
- [x] Exit pages
- [x] Display logic (show-hide rules)
  - [x] Rules can be applied to values and route to a different page 
- [x] Branching logic (routing rules)
  - [x] Using auto-flow
  - [x] Validating that the Logic view works: add rules, remove, update
- [x] Translation View
  - [x] Export spreadsheet

#### Conditional Input History:
Prerequisite: Build a form with show/hide logic and multiple pages.
- [x] 1. (In Staging) Test on the Preview page AND on the published form: answer questions going down one path that includes show hide logic, and then check out the Review page -> THEN go Back, go down another path, and then validate your new answers show up correctly on the Review page ([reference Pete's video](https://github.com/cds-snc/platform-forms-client/pull/4036))
- [x] **TEST THIS FIRST: 2. ([PR Environment](https://4ouzqz4a6gfkj4pxecb6jjky5i0zfqfc.lambda-url.ca-central-1.on.aws/)): Exactly the same as above, but testing that the submitted responses show up correctly. (i.e. look at the csv file, see empty columns + the columns that you expect answers. There shouldn't be any inputted answers missing, or multiple answers from previous paths taken) -> ONCE THIS IS DONE, FLAG TO PETE**

#### Responses:
- [x] Validate Responses appear correctly in all download options (validating #4081):
  - [x] Email
  - [x] HTML
  - [x] CSV
  - [x] JSON
 
### Testing coverage:

**Device:**
- [x] **Tablet**
- [x] Desktop

**Browser:**
- [x] **Edge**
- [x] Chrome

**Language:**
- [x] **French**
- [x] English

**Comment by anikbrazeau** [comment]
Will start testing on Tablet/Edge/French today, focusing on the above first and also checking for broader coverage of this [testing checklist](https://docs.google.com/document/d/1MZEtW632oSQiERvJndGccSfFnZg2gE9CdEyo6WCF4Tk/edit#heading=h.6f2e976l7a9h).

**Comment by connorscarolyns** [comment]
<img width="880" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3acba7fcdcd40e55afa8c8d8a6f66d6c1a2c0b5b/image.png" alt="image.png" />
 "Add a rule" should be something like "add a branch" , or " add a branching rule"

We want to distinguish these rule from the hide/show rule.

**Comment by Abi-Nada** [comment]
Testing requirements have all been checked off - thanks so much, folks!!!!!!!!!!!!!!!!!
