### ISSUE TITLE
English option for "Review" and "Start" in dropdown of Branching/Logic set-up

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4064]
## Description
When using the product in French and navigating to the French branching page, there is a mix of English and French, in the dropdown to control the destination from the node.

## Steps to reproduce
1. Go to GC Forms staging
2. Go to the French interface
3. Create a form
4. Go to branching
5. Add a branch
6. See "Review" in English even when editing in French on the French interface

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop

## Expected behaviour
Matching language

## Screenshots or videos
<img width="1690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8728d94d879dc6eba050241f7f658a367ec4507/Screenshot%202024-07-24%20at%203.17.03%E2%80%AFPM.png" alt="Screenshot 2024-07-24 at 3.17.03 PM.png" />

**Comment by timarney** [comment]
PR - https://github.com/cds-snc/platform-forms-client/pull/4088

**Comment by anikbrazeau** [comment]
Fixed! Thanks Tim!

**Comment by anikbrazeau** [comment]
This seems to be happening again. 

In testing the staging environemtn on Tablet/Edge/French noticed both "Start" and "Review" show up.
