### ISSUE TITLE
Users find it hard to extract response information, sections in the response output are not in the order of the form.

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4081]
When we chatted previously I asked about extracting submitted responses, noting that we’d need to save responses to each individual’s file/record.
 
As you suggested, I tried submitting my test form to see how it would look and PDF from the html view. Unfortunately, the html view did not show the form sections and associated fields in any sort of logical or grouped order. Is this how it normally functions? I didn’t get a chance to try again to see if it behaves the same way but if you know this isn’t how it’s supposed to behave, I’ll go try again.

sections and what order they come in. I’ve also outlined it below to make it easier.
 
You can see in the PDF that there’s no way for us to easily distinguish which fields belong to which sections of the form. The PDF also incorporates all the possible fields that I have in my test form, regardless of whether they were applicable to the form filler, making it more crucial that we have obvious distinctions between the sections. In the test example I’m using, this PDF would need to be used by our clinical admin staff in preparing a service request for a health examination and also saved to that individual’s medical file as an official record.  
 
The PDF shows fields for the sections in the following order:

1. Dependants
2. OHEG Info
3. Service Requested
4. Receiver of Evaluation
5. Signatures
6. Posting Info
7. Candidate and Employee

 
To help with interpreting the branching screenshots, here’s the order of sections in the form:

1. Service Requested
2. Dependants | Candidate and Employee (identifying it at the same level because it’s an either/or question at Service Requested)
3. Service Requested
4. Posting Info
5. OHEG Info
6. Signatures

<img width="812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN01XQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a45700c5478fae85225f0ed636d3aed3c875e844/image.png" alt="image.png" />
<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97b450816b788b87346cb189b243473561efa761/image.png" alt="image.png" />
[Public Service Occupational Health Program Occupational Health Service Request -.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1VXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69f25ee0e9477b31cd6560cdb667a6276c130f20/Public%20Service%20Occupational%20Health%20Program%20Occupational%20Health%20Service%20Request%20-.pdf)

**Comment by Abi-Nada** [comment]
Issue fixed in [4146](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/4146) ^
