### ISSUE TITLE
Testing: Side panel should be opened when moving from more modal

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4087]
When a user clicks on the "open branching tab" from the more menu, the side panel should also open to display the branching options.

**Comment by connorscarolyns** [comment]
[screen-capture (10).webm.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1VZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36fa71991a8c4b29add0a40c378463887c2a9bfa/screen-capture%20%2810%29.webm.zip)

**Comment by connorscarolyns** [comment]
steps to recreate:

1. add a selection element
2. Ann an option
2. add a rule to the option
3. click on the accordion for complex rules
4. click the button to open the branch tab

The result is the branch tab is open
The expected result is that the branch tab and side panel are open

**Comment by Abi-Nada** [comment]
QA tested and the fix works! ✅
