### ISSUE TITLE
Conditional Logic input history - form response missing

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4096]
## Description
After filling out and submitting a response to a published form, I didn't see an answer reflected in the downloaded response.

## Steps to reproduce
1. Create a form with Show/Hide and branching
2. Publish the form
3. Fill out the form, Submit
4. Download the form response as a CSV
5. See error

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR (https://4ouzqz4a6gfkj4pxecb6jjky5i0zfqfc.lambda-url.ca-central-1.on.aws/)
- **Language**: English

## Expected behaviour
Form submission answers should be reflected in the downloaded response.

## Screenshots or videos
This is a super goofy form that I made at 10pm while watching TV - please excuse it haha. But the screen recording shows me filling out the published form, and downloading the form response.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWNhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b4918a790a11173be59d228914c52a9fb759f96/Screen%20Recording%202024-07-29%20at%2010.23.41%E2%80%AFPM.mov)

<img width="745" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWdhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--056b83c262d2ed1337381dd6315d24edb54b838c/Screenshot%202024-07-29%20at%2010.27.15%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 10.27.15 PM.png" />

<img width="1206" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWthQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc48a03f4eb2a857a9a64d88bb557f0d97309a4c/Screenshot%202024-07-29%20at%2010.27.41%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 10.27.41 PM.png" />

**Comment by thiessenp-cds** [comment]
Hi @Abi-Nada, was this tested on the forms-forms PR environment? (https://github.com/cds-snc/platform-forms-client/pull/4036)

**Comment by Abi-Nada** [comment]
Yup! It was tested on the [forms-forms PR environment ](https://4ouzqz4a6gfkj4pxecb6jjky5i0zfqfc.lambda-url.ca-central-1.on.aws/)(in the video, you can see a peek of the URL when I'm filling out the form)

**Comment by Abi-Nada** [comment]
@Abi-Nada to retest to see if I can produce consistent results for this bug

**Comment by Abi-Nada** [comment]
Retested specific edge case, and issue no longer persists! Not going to close out this card yet - once the PR gets merged in, I'd like to test one more time in Staging
