### ISSUE TITLE
Error 552 when editing a form file (template) that was opened/uploaded (without a file name)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4111]
## Description
Encountering `Error 552` again when trying to save changes to a form or changes to settings.
This seems to happen only when the form does not have a name.

## Steps to reproduce
1. Go to GC Forms
2. Create a form by opening a form file
3. Go to Settings
4. Change administrative purpose
5. Try to save
6. See error

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour

Perhaps prompting users to name the file when opened/uploaded or to preserve the previous name could help solve this problem? 

Can we maintain the form file name when sharing form files? 

## Screenshots or videos
![Capture](https://github.com/user-attachments/assets/d7e1218b-6c1c-4751-8ec5-870f7e648a40)

![saving](https://github.com/user-attachments/assets/014c0e35-2bdd-4d88-9ffc-57ac20f6a386)

## Related issues with Error 552
#3955 #3761

**Comment by Abi-Nada** [comment]
Closing this issue as tackling [3628](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3628) will solve this
