### ISSUE TITLE
Issue with display rules when removed

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4113]
## Description
Adding display logic to an option on a question that shows/hides another question, does not get removed when the parent option is removed.

## Related issues

#3969 
#3627 
#4143

## Steps to reproduce
1. Go to GC Forms > Edit
2. Add a radio button or other selectable option question
3. Add options
4. Add rules to options
5. Remove option
6. Add rule
7. Rule gets reattached to new option
8. Deleting an option in the middle makes all other rules cascade upward breaking the intended logic

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Deleting an option deletes associated rules
Deleting a question deletes associated options
Deleting a page deletes associated form elements

## Screenshots or videos

https://github.com/user-attachments/assets/a06a597d-784a-4b0f-8cb7-24dd6eee8433

![other](https://github.com/user-attachments/assets/ef127ae1-7d2c-4146-a63d-61d10f6d8531)

**Comment by Abi-Nada** [comment]
^ Issue fixed in 4153
