### ISSUE TITLE
Cannot add "searchable list" form element in FR on Edge

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4117]
## Description
When adding form elements, the searchable list does not seem to be able to be added.

## Steps to reproduce
1. Go to GC Forms staging
2. Toggle to French
3. Add a page
4. To that page add radio, checkbox, dropdown and searchable list
5. See how searchable list does not get added

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Insert new form element when added from modal.
Works in English on tablet/edge?
Works on Mac in English and French?

## Screenshots or videos

No video as on tablet...

**Comment by Abi-Nada** [comment]
Going to test this and validate if it persists on my end

**Comment by Abi-Nada** [comment]
Test without the feature flag as well to see if this is something outside CL/already in Prod

**Comment by Abi-Nada** [comment]
Not able to recreate the issue/looks like the issue no longer persists
