### ISSUE TITLE
Character limits should only be presented for relevant form elements

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4118]
## Description
A number of form elements that are selectable rather than inputs have character limits that can be specified, which doesn't really apply.

For example: number might benefit from character limit but does not have that feature, while radio button cannot and has it.

## Steps to reproduce
1. Go to GC Forms > Edit
2. Click on Add a form element
3. Add all types of form element
4. Go to "More" for each one
5. Notice how they have character limits even when that is irrelevant

## Details
- **Browser**: Edge
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Only show character limit if/when relevant, when a text input is expected by the form filler.

## Screenshots or videos
![characters](https://github.com/user-attachments/assets/477205c3-5788-4b30-8a0b-c87bd06c2fd3)

![limit](https://github.com/user-attachments/assets/0fd7c314-6201-41b3-8047-3e081346be95)

**Comment by Abi-Nada** [comment]
Issue resolved in [4175](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/4175)
