### ISSUE TITLE
Deleting a page brings you to an empty page that does not exist in "Tree view"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4135]
## Description
The removal of a page from the tree view, deletes the page and its contents, but afterwards, users land on an empty page that does not exist and cannot be edited.

## Steps to reproduce
1. Go to GC Forms
2. Add a new page
3. Add questions to the page
4. In the right panel "Pages" delete the page
5. See toast for successful action
6. See where end up

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Tablet

## Expected behaviour
Go back to previous page? Or back to start page?

## Screenshots or videos

<img width="1613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56dfa56e4af73ef181e49ae78eec016c49292126/Screenshot%202024-07-31%20at%2011.53.59%E2%80%AFAM.png" alt="Screenshot 2024-07-31 at 11.53.59 AM.png" />

<img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeklpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8ddf96c2baa63634663a387ddc81a8a7bc06e79/Screenshot%202024-07-31%20at%2011.50.56%E2%80%AFAM.png" alt="Screenshot 2024-07-31 at 11.50.56 AM.png" />

**Comment by dsamojlenko** [comment]
Fixed in #4155

**Comment by Abi-Nada** [comment]
Tested in Staging, LGTM! :) ✅
