### ISSUE TITLE
Unable to add branching to an imported form file that had branching

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4142]
## Description
Branching not conserved when publishing and when importing 

## Steps to reproduce
1. Create a simple form with branching.
2. Publish the file
3. Go to published form 
4. Branching does not work as expected
5. Download the file
6. Reopen the file to create a new draft
7. Try to add branching
8. Cannot add branching (disabled button/link)

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French
- **Viewport**: Desktop
- **Output**: clzaa9wwk0001pyw2g98fwcww

## Expected behaviour
Publish with branching
Import/open form file with branching

## Screenshots or videos
<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3edcc1e27bcf4a98faa992cd1eba3a5c01e3e236/Screenshot%202024-07-31%20at%204.14.46%E2%80%AFPM.png" alt="Screenshot 2024-07-31 at 4.14.46 PM.png" />

**Comment by Abi-Nada** [comment]
Unable to recreate the issue on my end/looks like the functionality works as intended 🤔 Will try to test this again later today
