### ISSUE TITLE
Logic View: Review page for single-page forms

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4150]
### Description:

[Slack thread:](https://gcdigital.slack.com/archives/C0676D34GPR/p1722516375609199?thread_ts=1722516206.149529&cid=C0676D34GPR)

> Pat also noticed that for a single-page form, in the logic view, a Review page is displayed. I was about to open a ticket, thought about it, maybe this is more of a design question. Should the logic view automatically update based on whether a form is a single page form or a multi-page form?

### Acceptance Criteria:
- [x] logic view should automatically update based on whether a form is a single page form or a multi-page form
- [x] We should use the same logic as is used for the forms form

**Comment by timarney** [comment]
PR: 

https://github.com/cds-snc/platform-forms-client/pull/4151

**Comment by Abi-Nada** [comment]
Tested in Staging and it works! ✅
