### ISSUE TITLE
Repeating Sets: Update Review Page

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#4166]
Update the Review page, both in Preview and Forms-form mode, to work with Repeating Sets.
The challenges with this story is working through the complex Repeating Sets and related logic e.g. how to map from formik repeating set form values to work with both Pages (Groups) and Rules (show-hide).

**Comment by Abi-Nada** [comment]
Ready to be tested :)

**Comment by thiessenp-cds** [comment]
Here is an example form for testing
[repeating-set-1-2024-08-14.json](https://github.com/user-attachments/files/16626897/repeating-set-1-2024-08-14.json)

**Comment by thiessenp-cds** [comment]
Here is an example form that you can use for testing: 
[repeating-set-1-2024-08-15.json](https://github.com/user-attachments/files/16627049/repeating-set-1-2024-08-15.json)

**Comment by thiessenp-cds** [comment]
Implemented and tested. There were some pre-existing issues e.g. form-builder toolbar text contrast but these can be fixed in a follow up PR.
