### ISSUE TITLE
Removing an option that has a branching rule attached to it breaks the branching rules

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#4169]
## Description

When removing an option that has a branching attached to it the rules indexes need to decrement as they do in this PR for conditional rules https://github.com/cds-snc/platform-forms-client/pull/4153

[my-form-2024-08-07.json](https://github.com/user-attachments/files/16523272/my-form-2024-08-07.json)

## Steps to reproduce
1. Load the attached JSON files
2. Look at the branching tab / rules
3. Remove an option 
4. View the branching rules --- noting they are now broken as the indexes don't match what the rules we're originally set to

## Expected behaviour
When an option is removed the rules auto update to match the new rule indexes

## Screenshots or videos

Example with attached file + removing an option 

https://github.com/user-attachments/assets/c2ae215d-987c-4916-ac00-9cd8e3968d35

**Comment by Abi-Nada** [comment]
For the most part the fix looks good, but it looks like the deleted branch still stays within Logic view?


https://github.com/user-attachments/assets/15d282e6-9e79-4903-9cea-f3d8c61431d4
