### ISSUE TITLE
Forms API OIDC role trust policy is incorrect

### ISSUE THREAD

**Issue by patheard** [cds-snc/platform-forms-client#4183]
# Summary
Currently the OIDC IAM `forms-api-apply` role in Staging has an incorrect trust policy.   This is because Forms normally uses the `develop` branch as its default branch, which means the SRE maintained OIDC roles [set develop](https://github.com/cds-snc/aft-account-request/blob/2d311a7feb1e5fbf01dba255fa693ddf1d476edb/terraform/staging.tf#L113) in the `*-apply` role's trust policy.

The impact of this is that the `forms-api-apply` OIDC role does not work for pushes to the `main` default branch.  [This has temporarily been fixed manually in the console]( https://github.com/cds-snc/platform-forms-client/issues/4128#issuecomment-2274173821), but will break again when the AFT account customization pipeline runs against the `Forms-Staging` account (symptom of this will be that workflows using this role will fail to assume the role).

There are two potential fixes:
1. Use the same default branch for all Forms' repos (either `develop` or `main`).
2. Create a new [OIDC role managed by the `forms-terraform` repo](https://github.com/cds-snc/forms-terraform/blob/34b4da018585b5b3a8829f75f1d63d80b3fe156c/aws/oidc_roles/iam_roles.tf) that is only used for pushing ECR images and deploying ECS changes. 

# Related
- https://github.com/cds-snc/platform-forms-client/issues/4128

**Comment by bryan-robitaille** [comment]
Going to move all 3 repos to the 'main' branch

**Comment by patheard** [comment]
Account Factory for Terrraform (AFT) change has been made as well, so now everything is in sync and we won't have to worry about the OIDC role trust policy being reset.
