### ISSUE TITLE
Clarification of linear flow reset text

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4243]
The text in this info box could be improved to provide more clarity. Hide-show rules are not removed. It's the branching that is reset to a linear progression. Something like:

Reset to linear page flow
Remove branching logic and custom page flow rules to reset the progression between pages to a simple linear flow. Hide and Show rules will not be affected.

<img width="674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f5f4dc7c9af2ad2f1971f1d341463f29be76a3f/image.png" alt="image.png" />

**Comment by anikbrazeau** [comment]
Addressed in PR #4697
