### ISSUE TITLE
User was able to add a text area question field to the confirmation page group

### ISSUE THREAD

**Issue by jprince-cds** [cds-snc/platform-forms-client#4260]
## Description

The user was able to add a text area question field to the confirmation page group, which hid it from the form builder editor. It prevented them from publishing the form, because they were unable to add a translation to it (the question completely disappears from view). 

## Steps to reproduce

1. Drag and drop the question to the Confirmation page
2. The question will visually disappear from the form builder, but it is still in the json file, causing confusion. 

## Expected behaviour

The confirmation page should only contain a rich-text single field. No question should be moveable to that page. 

## Screenshots or videos

<img width="926" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5DQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad624431b4893eeb68979745e71681bfda6ada4/image.png" alt="image.png" />

<img width="1659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ea0d088cd9e470c45722003a59282ca3a455e9f/image.png" alt="image.png" />

## Additional context

Reported in [Freshdesk Ticket #18952](https://cds-snc.freshdesk.com/a/tickets/18952)

**Comment by Abi-Nada** [comment]
Issue is fixed! Can no longer drag and drop into the Confirmation Page
