### ISSUE TITLE
Repeating Sets: Panel/Tree View

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4271]
### User Story
As a form builder, I want the Repeating Sets feature to be compatible with the right panel and drag-and-drop, so that I can easily configure and position the repeating set questions within the group.

### Acceptance Criteria:
- [x] Drag and drop is functional with all the form elements (noting for now we want to limit this to re-ordering within the group)
- [x] Within the panel, there will be a small icon to suggest a set of questions that can be repeated
  - [x]  the questions within that set will be a slightly smaller card width (normal: 358, set: 324) to show an indent
  - [x]  A line on the left side will indicate they are grouped together (slate-500, .5px)

<img width="765" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c0a2082ac8b12f23836295ae367d3d8d1d160f6/image.png" alt="image.png" />

- [x] The active state in the middle and the panel will match, change the stroke to indigo-700, 1px, and fill violet-50

<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e9e218c74511b5967b2dc89bc4f6c4d441f9e25/image.png" alt="image.png" />

[ ] Adding in translations

**Comment by Abi-Nada** [comment]
@anikbrazeau and @connorscarolyns

**Comment by anikbrazeau** [comment]
QA Testing link: https://xldg62gxflrlyk6zna7t3fu6i40plvzf.lambda-url.ca-central-1.on.aws/

**Comment by anikbrazeau** [comment]
**Question:**

- Should there be a way to drag an existing question that's not in the set into the repeating set?

**Comment by anikbrazeau** [comment]
**Question:**

- Should there be a way to drag an existing question that's not in the set into the repeating set?

**Comment by anikbrazeau** [comment]
Testing complete on tablet/staging

**Comment by Abi-Nada** [comment]
Potentially look to turning off feature flag tomorrow

**Comment by Abi-Nada** [comment]
Repeating Sets is now live on Production :)
