### ISSUE TITLE
GCDS Component - Feasibility check

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4273]
### Description:
Review GCDS Server Side Rendering to provide feedback on components.

### Acceptance Criteria:
- [ ] (Once the DS provides a dev contact) Check if the SSR works on our end and if using the components would be viable.

**Comment by timarney** [comment]
Ran into issue compiling 

https://github.com/cds-snc/platform-forms-client/pull/4281

**Comment by timarney** [comment]
Having done some initial investigation into feasibility we have 2 initial blockers.

Content security policy https://github.com/cds-snc/platform-forms-client/pull/4281#issuecomment-2358313268

i18N - browser detect script issue https://github.com/cds-snc/platform-forms-client/pull/4281#issuecomment-2355728595

**Comment by daine** [comment]
@Abi-Nada @timarney thanks for looking into this! My apologies, I didn't see my github notifications in time. If you need a dev contact, please feel free to ping me directly on Slack as well.

I'll take these two blockers and put it on our project board so we can look into it further.

**Comment by timarney** [comment]
Added a note on the CSP / nonce blocker here https://github.com/cds-snc/platform-forms-client/pull/4281#issuecomment-2377369468.

**Comment by timarney** [comment]
Adding some further notes.

Looking at other options i.e. just use the tokens / CSS

Given the Design system CSS relies on the `web components` existing in the markup we can't just grab the styles and use HTML elements + css classes etc...   makes sense as far as `css specificity` etc... goes just doesn't play well with our existing setup.

We will need manually update the CSS to match our HTML markup -- if GCDS gets updated the updates won't carry over to out end.


<hr>

![Screenshot 2024-09-26 at 10 29 38 AM](https://github.com/user-attachments/assets/c2316663-32ff-446f-85e8-12b8d510f3bf)



![Screenshot 2024-09-26 at 10 27 39 AM](https://github.com/user-attachments/assets/d5a5429f-d6d1-452f-874d-4a8189f42ece)

**Comment by timarney** [comment]
Looks like some others i.e. selects will port over easier 

We can grab the css vars from the GCDS repo

<img width="1112" alt="Screenshot 2024-09-26 at 12 54 32 PM" src="https://github.com/user-attachments/assets/33db9ce7-0666-48d5-9965-e3161f5cebf2">

Side note the CSS is nice :)
