### ISSUE TITLE
Repeating sets - Customizable content

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4297]
## Steps to reproduce
1. Add a repeating set
2. Click customize element
3. Remove all prepopulated content
4. Save

## Expected behaviour
Should this content be mandatory in some aspect? What happens if these are empty?

## Screenshots or videos

<img width="689" alt="Screenshot 2024-09-19 at 3 19 09 PM" src="https://github.com/user-attachments/assets/9abf8133-0d5b-4636-bcc5-6caa38de07af">

**Comment by timarney** [comment]
> Should this content be mandatory in some aspect? What happens if these are empty?

We do do some handling at the server level - currently "Item" defaults for `en` and `fr` --- this has been the case pre form builder.  

<img width="400" alt="Screenshot 2024-09-20 at 8 06 46 AM" src="https://github.com/user-attachments/assets/d5ce13f1-023f-4d7f-873d-b989756cbf6c">

**Comment by timarney** [comment]
@anikbrazeau 

I added a commit to add a generic error message if any of the fields are empty

https://github.com/cds-snc/platform-forms-client/pull/4263/commits/8fd102541d9caac49f845cb84c34fdbec26b10b6


I think given we default the content (pre-filled in) this should work well.
