### ISSUE TITLE
Moving a Repeating Set around removes the form elements within

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4303]
## Description
Moving a Repeating Set around the form (up/down) removes the form elements within.

## Steps to reproduce
1. Go to the PR Environment and go to a pre-existing Draft form with multiple questions
2. Add a Repeating Set element, with a question within it.
3. Move the entire question up or down in the form flow

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: EN

## Expected behaviour
The repeating set should remain as is/not be deleted when moving the form question around.

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkgwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcd6b4545780f60acf13a61daba99410f5bc7b1e/Screen%20Recording%202024-09-23%20at%209.28.57%E2%80%AFAM.mov)

**Comment by timarney** [comment]
I think I tracked down the issue and pushed a fix

https://github.com/cds-snc/platform-forms-client/pull/4263/commits/9215e1d6b33a8373a9f3715b2bdb2288d5149fca

**Comment by Abi-Nada** [comment]
Abi to re-test PR and close out this issue

**Comment by Abi-Nada** [comment]
Issue no longer persists!
