### ISSUE TITLE
French Privacy statement for fable testing is incorrect

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4304]
French Text requires a review to ensure consistency with the English content.

https://articles.alpha.canada.ca/forms-formulaires/fr/decidez-si-vous-souhaitez-participer-a-notre-recherche/

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzcxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cb96ceb431ab5cfe87411204d1e81850d86517e/image.png" alt="image.png" />

**Comment by anikbrazeau** [comment]
Comparative EN/FR content review. 
Discrepancies were fixed on Tuesday October 29.
