### ISSUE TITLE
GCDS: Button

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#4307]
Audit: 
- Button uses icons (remove for now - they may have a set of icons for us to choose from in the future)
- Typography and padding don't match

DESKTOP
- Forms: Font Size = 20px, Line Height = 28px (140%), Padding = 8px 20px
- GCDS: Font Size = 20px, Line Height = 24px (120%), Padding = 12px

*GCDS coded button is not aligned with our mobile button sizing in figma and 
fonts + padding do not scale down like the Forms buttons

MOBILE
- Forms: Font Size = 20px, Line Height = 28px (140%), Padding = 8px 20px
- GCDS: Font Size = 20px, Line Height = 24px (120%), Padding = 12px
- 
 
 	
- Button does not expand to 100% 
screen width on mobile

**Current state**
<img width="370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHoyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce96945e45df1450d1799512ec1846b4d8d59d9b/image.png" alt="image.png" />

**Desired state**
<img width="364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDcyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a176e38399206e0e5a6a85f17a3760928b2dcecb/image.png" alt="image.png" />

**Comment by timarney** [comment]
PR:

- Updated Padding
- Fixed active state to use black background
- Updated secondary button to use blue vs bg-gray-600

Forms

https://github.com/user-attachments/assets/0a5817e8-4da8-4e60-8ea1-f181d214a6b2


GCDS


https://github.com/user-attachments/assets/9a34b695-8b38-4456-9b87-b299b029ade4



https://github.com/cds-snc/platform-forms-client/pull/4319

**Comment by timarney** [comment]
> so possibly might need to make adjustments as we find them inside the builder.

For example the Accounts "filters"

<img width="1052" alt="Screenshot 2024-09-24 at 11 16 28 AM" src="https://github.com/user-attachments/assets/3cf4a583-69b5-4ba2-974a-cb74b62bfe48">

**Comment by timarney** [comment]
https://github.com/user-attachments/assets/a9edcfa6-2a67-4cfb-a386-fd521de73000

**Comment by timarney** [comment]
PR: https://github.com/cds-snc/platform-forms-client/pull/4319
