### ISSUE TITLE
AddressComplete: address box still remains after making a selection

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4313]
## Description
An addresses that is selected on a Published Form still shows the auto-complete entry. It is only removed on another click away.

## Steps to reproduce
1. Go to a Published form with Autocomplete.
2. Add and Address
3. See error

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: EN

## Expected behaviour
Once you click on an address, the box should go away.

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3o1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c758971743494afb606f8878d6f1d18a4ac6aaf/Screen%20Recording%202024-09-24%20at%208.28.26%E2%80%AFAM.mov)

<img width="1371" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3Y1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--343c0ed96711b1feaddbc90a2601a215eb380e4f/image.png" alt="image.png" />

**Comment by ShadeWyrm** [comment]
@Abi-Nada - can you re-test on the PR env?

**Comment by Abi-Nada** [comment]
@ShadeWyrm Hi hi! Looks like the issue still persists on the PR env - after selecting the address, I still have to click off to make the box go away:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjVVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de4854cfc7775d7e4c2a56a3d9453fa1bd32bf46/Screen%20Recording%202024-10-17%20at%208.26.08%E2%80%AFAM.mov)
