### ISSUE TITLE
AddressComplete: Address does not show up on the review page

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4315]
## Description
A Split address that doesn't select any specific fields doesn't show in the Review Page.

Note: I wonder if this needs a Design consideration? Like if you select "Split Address", you have to select all the fields that you want to use/not leave them blank? Or have them all appear as a default?

## Steps to reproduce
1. Create a Draft form
2. On Page one, add a "Verified Address" form element.
3. Click "Customize format" and choose "Split address". **Don't select specific fields**
4. Add a second page with a question to the form.
5. Go to Test and input an address//fill out the form. Stop at the Review page.
6. On the Review page, look at the address field.
7. See error

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: EN

## Expected behaviour
Response should appear in the Review Page

## Screenshots or videos
<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy81Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec4f60e7259de173004f5218cca092e0ed94ef38/image.png" alt="image.png" />

**Comment by ShadeWyrm** [comment]
Customization of the address is no longer a feature/design - so closing.
