### ISSUE TITLE
Some form elements don't initially appear in the Repeating Set when selected

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4323]
## Description
Some form elements don't initially appear in the Repeating Set when selected:
- Full name
- Individual name
- Contact
- Address
- Department

## Steps to reproduce
1. Create a Draft form, add a Repeating Set
2. Add any of the above form elements to the set
3. See error

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: EN

## Expected behaviour
Form element should appear in the Builder

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzcrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b33947c335ab9a78af6e5d73c6f295224b238b4/Screen%20Recording%202024-09-25%20at%208.13.36%E2%80%AFAM.mov)

**Comment by timarney** [comment]
When you get a chance 

The latest seems to be working now.


[Uploading... Kapture 2024-09-25 at 14.14.31.mp4]

**Comment by Abi-Nada** [comment]
Tested and issue no longer persists! :)
