### ISSUE TITLE
Repeating set: Adding/removing does not work and inconsistent across elements

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4333]
## Description
The "Add to set" button and "Remove from set" button do not work
They show up differently visually for address and individual names which include page text

## Steps to reproduce
1. Add repeating set
2. Add individual names component
3. Add address component
3. Click on each and try to add / remove
4. See weirdness

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
Does "Remove from set" delete or simply remove from nesting?
Do we need two "Add to set" links/buttons, the embedded and non-embedded?

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95fa8e4da0d88c61de104485f28873c7ed1a565f/Screen%20Recording%202024-09-26%20at%209.53.01%E2%80%AFAM.mov)

**Comment by timarney** [comment]
Tried address seems to work 


https://github.com/user-attachments/assets/ae5919e8-1df2-48be-884f-e4388f03b85a

**Comment by anikbrazeau** [comment]
Ah, I was trying to select the card by clicking the general areas, not click inside the text input.

I did find something similar with move up move down -- where it loses focus and also stops working?

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35ed97e9d1dcee37dba5ef5a87b3fd3dc51e5b48/Screen%20Recording%202024-09-26%20at%2012.06.25%E2%80%AFPM.mov)

**Comment by anikbrazeau** [comment]
Another example of the inconsistency: inside vs. outside of a set? <img width="943" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7e1f9629eb4047633a896ca842ce18f7efa2ce6/Screenshot%202024-09-26%20at%2012.20.48%E2%80%AFPM.png" alt="Screenshot 2024-09-26 at 12.20.48 PM.png" />

**Comment by timarney** [comment]
Working on some fixes here

https://github.com/cds-snc/platform-forms-client/pull/4346

**Comment by anikbrazeau** [comment]
This works, assuming you click inside the text input for the form element label.
