### ISSUE TITLE
Repeating set: Department list changes when inside repeating set

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4338]
## Description
Department list does not appear as intended when embedded in a repeating set?

## Steps to reproduce
1. Add a repeating set
2. Add department inside it
3. Add department outside it
4. Compare -- notice the list with empty 1. 

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English
- **Viewport**: desktop

## Expected behaviour
Consistency when elements are added inside or outside of repeating sets

## Screenshots or videos
<img width="1710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea36d67692a30b87bba0e22a6334dfb9f3734b4f/Screenshot%202024-09-26%20at%2012.03.40%E2%80%AFPM.png" alt="Screenshot 2024-09-26 at 12.03.40 PM.png" />

<img width="1702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3baf4ba91e42cd0c379cee10c31f8c8c333e681/Screenshot%202024-09-26%20at%2012.11.37%E2%80%AFPM.png" alt="Screenshot 2024-09-26 at 12.11.37 PM.png" />

**Comment by anikbrazeau** [comment]
Actually all selection-type elements lost all the options somehow?<img width="863" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bae37914c7f48e4703efe14b716eb45b1a01a9ad/Screenshot%202024-09-26%20at%201.10.43%E2%80%AFPM.png" alt="Screenshot 2024-09-26 at 1.10.43 PM.png" />

**Comment by timarney** [comment]
Should be fixed in the latest.

managed lists we're being handled properly for sub-elements ---- 

<img width="862" alt="Screenshot 2024-09-26 at 2 04 23 PM" src="https://github.com/user-attachments/assets/ddb6bbf8-8e4e-4b1e-8b74-1d514d306ab1">

**Comment by anikbrazeau** [comment]
Fixed! Thanks Tim!
