### ISSUE TITLE
Repeating set: Questions inside repeating set have letters associated in translation view

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4339]
## Description
We removed numbering, however have lettering for repeating set questions? Is this intentional? How will it work with conditionals? Is this legacy from when we numbered questions?

## Steps to reproduce
1. Add a bunch of questions to repeating sets
2. Click on Translations
3. See question a, b, c, d, etc.

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
Use "set name" instead as we do for "pages"?

## Screenshots or videos
<img width="1136" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96a92838ee4199a28c17a707ff8077eb5388f885/Screenshot%202024-09-26%20at%2010.51.59%E2%80%AFAM.png" alt="Screenshot 2024-09-26 at 10.51.59 AM.png" />

**Comment by timarney** [comment]
Will remove

**Comment by timarney** [comment]
Pushed an update https://github.com/cds-snc/platform-forms-client/pull/4263/commits/2af06faf2bc6df406081b414fa86ee7d9661e69f

Will be on the preview link in 5 min or so

**Comment by timarney** [comment]
<img width="1162" alt="Screenshot 2024-09-26 at 2 19 21 PM" src="https://github.com/user-attachments/assets/68d4f228-e003-4513-b9ac-2a7d1b2b0cba">

**Comment by anikbrazeau** [comment]
Amazing thanks Tim! Fixed!
