### ISSUE TITLE
AWS WAF blocking file uploads

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#434]
AWS Web Application Firewall is blocking some file uploads due to a positive detection of `AWS#AWSManagedRulesCommonRuleSet#CrossSiteScripting_BODY`.  This is due to image files having random characters in their metadata which can lead to false detections.  https://aws.amazon.com/premiumsupport/knowledge-center/waf-upload-blocked-files/
- **Proposed solution:** encode all files from browser to api endpoint as base64 strings.
- **Existing work-around:** disabled rule on WAF for staging environment to not impact demos.

**Comment by bryan-robitaille** [comment]
Also blocking on `AWS#AWSManagedRulesCommonRuleSet#GenericLFI_BODY`

**Comment by patheard** [comment]
Related to cds-snc/platform-sre-security-support#47

**Comment by patheard** [comment]
Some possible solutions to exclude only `GenericLFI_BODY` for specific URLs:
cds-snc/platform-sre-security-support#49

**Comment by patheard** [comment]
The `label_match_statement` is now part of the latest AWS Terraform provider, so you can use something like the following to exclude WAF ACL managed rules from specific URLs only:

https://github.com/cds-snc/platform-sre-security-support/issues/49#issuecomment-993877133

It's working nicely in Articles.
