### ISSUE TITLE
Response under Date component doesn't show up in Email delivery

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4363]
## Description

[Support ticket thread](https://gcdigital.slack.com/archives/C03T4FAE9FV/p1728069881452179)

## Steps to reproduce
1. Add a date field
2. Set response type to email
3. Submit

## Expected behaviour
Response under the date component should show up in Email Delivery.

## Screenshots or videos
<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3dwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88a2231963a4e4c0ad9c5ad52c47625e22aad032/image.png" alt="image.png" />

<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzRwQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c470e6c302c36e6289850ac69f8a539d8ff0817/image.png" alt="image.png" />

**Comment by Abi-Nada** [comment]
A consideration: what should we do with impacted forms? Any actions needed?

**Comment by timarney** [comment]
PR in the forms terraform repo

https://github.com/cds-snc/forms-terraform/pull/862
