### ISSUE TITLE
Broken text after Creating an Account

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4368]
## Description
After Signing up for an account and setting my security questions, this is the following textbox that persists in the following pages (Know your responsibilities, account created page):

<img width="1574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de4dfc28d633ef8dccca9e2a173f2f3c598a4c43/Screenshot%202024-10-07%20at%209.47.39%E2%80%AFPM.png" alt="Screenshot 2024-10-07 at 9.47.39 PM.png" />

<img width="1636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmdzQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f864b62ef163349b1454f09f8d61151026f8dfa/Screenshot%202024-10-07%20at%209.50.36%E2%80%AFPM.png" alt="Screenshot 2024-10-07 at 9.50.36 PM.png" />

**Comment by timarney** [comment]
PR:
https://github.com/cds-snc/platform-forms-client/pull/4369
