### ISSUE TITLE
Closing a Form: links not working on added content?

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4404]
## Description
When I input a Link into the text for closing a form, it doesn't seem to open the link? I can't recreate it in Production within a rich text field (the link opens fine in Prod).

## Steps to reproduce
1. Go to the PR Environment
2. Create a Draft form
3. Go to Settings -> Form Management. Add custom text "Reach out to Support" with the link to https://forms-formulaires.alpha.canada.ca/en/support
4. Go to Preview/Test
5. Click on the link
6. See error

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: PR
- **Language**: EN

## Expected behaviour
Link should open

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1JKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c751193f0b6a4fa4820be800f3901708fc23674c/Screen%20Recording%202024-10-15%20at%2011.16.34%E2%80%AFAM.mov)

What the link looks like in Settings:
<img width="882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--669707b52cbfec6a9f068657db709e4ab98e9352/Screenshot%202024-10-15%20at%2011.20.02%E2%80%AFAM.png" alt="Screenshot 2024-10-15 at 11.20.02 AM.png" />

What the link looks like in Preview/Test:
<img width="1135" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1pKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b85da716f9c27e7f78acb96e265d3503d506c702/Screenshot%202024-10-15%20at%2011.20.20%E2%80%AFAM.png" alt="Screenshot 2024-10-15 at 11.20.20 AM.png" />

What the link looks like when opened up:
<img width="1937" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--435e9ef4d77337152c23e6e3acee0f2a6878f16e/Screenshot%202024-10-15%20at%2011.21.03%E2%80%AFAM.png" alt="Screenshot 2024-10-15 at 11.21.03 AM.png" />

**Comment by timarney** [comment]
The screen above is missing the  ":" 

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVJLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8284fe9aa98eb7e0cddda9350c7c4bdd0edb457d/Screenshot%202024-10-15%20at%2011.33.11%E2%80%AFAM.png" alt="Screenshot 2024-10-15 at 11.33.11 AM.png" />

As per our sync call you did re-produce ...but I can't seem to get that same issue to re-produce locally.

Behind the scenes it's using the same Editor as the translation view.

**Comment by Abi-Nada** [comment]
Closing as I can't seem the replicate the issue anymore in Staging :)
