### ISSUE TITLE
update 4 - form open/closed Notice

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#4409]
TODOs
- update the form to show the  form open/closed Notice - Ask design about the timezones
- design elements from the Design System (should be in Tailwind config)

![Screenshot 2024-10-15 at 2 02 24 PM](https://github.com/user-attachments/assets/e9017a4f-bb69-4b4c-a2bf-5a4f5b62ef32)

**Comment by timarney** [comment]
https://github.com/cds-snc/platform-forms-client/pull/4426

**Comment by timarney** [comment]
Will close this one as the feature is out behind a feature flag.
