### ISSUE TITLE
AddressComplete  - nested address 

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#4417]
## Description

When searching for an address in some cases multiple  addresses can fall under the same address.

In this case the result ends up being `undefined undefined`

We should look to handle this use case.

<img width="624" alt="Screenshot 2024-10-16 at 11 15 31 AM" src="https://github.com/user-attachments/assets/b1426d0b-b1ea-4ad7-aa8c-1362ace2e89a">

**Comment by dsamojlenko** [comment]
@ShadeWyrm I suspect this might be one of those situations where the `retrievable` property comes back false?

**Comment by ShadeWyrm** [comment]
Yup! Perfect, will use that to update. :)
