### ISSUE TITLE
AddressComplete - submission missing data after turning feature flag off

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#4420]
## Description

- Created a form with the feature flag on
- Turned flag off
- Completed form 

Response data is missing - Country and St Address

<img width="720" alt="Screenshot 2024-10-16 at 12 16 48 PM" src="https://github.com/user-attachments/assets/bcb071ed-ad7c-491f-beec-f2286276a592">

Split
<img width="720" alt="Screenshot 2024-10-16 at 12 18 09 PM" src="https://github.com/user-attachments/assets/ea22d211-e901-45c0-8717-e76223ad0c67">

Full
<img width="1048" alt="Screenshot 2024-10-16 at 12 24 07 PM" src="https://github.com/user-attachments/assets/3de8d98e-9d80-441f-94d2-bb0c90ce5a86">

**Comment by ShadeWyrm** [comment]
It looks like this has been fixed by https://github.com/cds-snc/platform-forms-client/pull/4197/commits/22b49c3bb30d32f6b87f3aab522560ef5c0e3836

If you want to retest @timarney, it worked on my local copy with the current main branch.

**Comment by timarney** [comment]
Will re-test today.

**Comment by timarney** [comment]
This is working as expected now.

Created a ticket for some other things that happen for this use case

https://github.com/cds-snc/platform-forms-client/issues/4518

@Abi-Nada @anikbrazeau ---  it's a slight edge case to turn the feature off after it's been on but capturing for discussion there have been discussions around the need to possibly turn it off for "some" forms.  I don't consider this a release blocker but wanted to capture.
