### ISSUE TITLE
Embedded question within a Repeating set takes "set name" rather than "question label"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4428]
## Description
Issue with pre-populated text when going to "More" modal in questions within repeating set

## Steps to reproduce
1. Add a repeating set
2. Name the set something distinctive
3. Add form element such as name or address within repeating set
4. Add a question label that is different than the set name
5. Go to "Customize format" or "More"
4. See "Set name" appear as "Question" 
5. Saving/closing modal reverts the "Question" label to the "Set name"

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging and PROD
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
Continuity of question label within all instances (Edit, More, Translation, Preview, etc.)

## Screenshots or videos
<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5dc1f6ec0866dfd1e3a75e5940c2a6af3bd76e9/Screenshot%202024-10-17%20at%209.43.13%E2%80%AFAM.png" alt="Screenshot 2024-10-17 at 9.43.13 AM.png" />

<img width="1467" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlpWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb2a08e0faad7d5159c59183ce625da6da4a7c81/Screenshot%202024-10-17%20at%2011.39.11%E2%80%AFAM.png" alt="Screenshot 2024-10-17 at 11.39.11 AM.png" />

<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmxWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c06738adfe65bd9c50e4d6e3771d2621214be4c0/Screenshot%202024-10-17%20at%2011.39.43%E2%80%AFAM.png" alt="Screenshot 2024-10-17 at 11.39.43 AM.png" />

**Comment by timarney** [comment]
First can we narrow down to if this happens with simple elements (text, radio, checkbox) and the more menu

Seems to work -- but there are some syncing issues. 
https://github.com/user-attachments/assets/d0bf4b69-0c35-4f24-9c9e-e612f273c2ea

Note: @dsamojlenko is going to be looking at adjusting how we pop the modal for sub-elements (more menu) so that will likely take care of the syncing. 


We can look at the customize more advanced components after that.
