### ISSUE TITLE
Review page shows "Start Page" in enh for fr pages

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#4447]
## Description

The review page incorrectly shows en text for the "Start page" 
<img width="333" alt="Screenshot 2024-10-22 at 8 17 58 AM" src="https://github.com/user-attachments/assets/073a3b0b-5ec5-42b0-9f48-f662a0c509b0">

Noting the builder show the correct translation;
<img width="366" alt="Screenshot 2024-10-22 at 8 17 39 AM" src="https://github.com/user-attachments/assets/53f7904e-bbac-4613-b3d9-f9229d7df677">

**Comment by jprince-cds** [comment]
@Abi-Nada Can we prioritize this as it affects a published form, and is a OLA breach. Thanks!

**Comment by jprince-cds** [comment]
Reported in [Freshdesk #19586](https://cds-snc.freshdesk.com/a/tickets/19586)

**Comment by timarney** [comment]
@Abi-Nada assigning Pete (after the form timer) --- we should get this out in the next release.
