### ISSUE TITLE
AddressComplete "Customize format" alignment

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4460]
## Description
Align "Customize format" with "required" rather than the subfields

## Steps to reproduce
1. Go to Edit in form builder
2. Click on Add an element
3. Add Address
4. See placement of "Customize format" 

## Expected behaviour
Match date field format and other elements with "Customize format"

## Screenshots or videos
<img width="923" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzV2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--601119ac8d8f5ad23c7822a09d941e0cc24d5ba7/Screenshot%202024-10-24%20at%2010.53.40%E2%80%AFAM.png" alt="Screenshot 2024-10-24 at 10.53.40 AM.png" />

**Comment by ShadeWyrm** [comment]
Closed by PR #4471
