### ISSUE TITLE
API V2.0 - Second update for response page dashboard

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4486]
**Key user needs**
- [x] Display notification of responses awaiting API retrieval
- [x] Designs complete, ready for dev implementation
- [x] Ready to deploy to staging
- [x] Response statues
- [x] Empty stated

**Comment by connorscarolyns** [comment]
This update will provide a way for users to see if any responses are waiting to be pulled into their end system via API call.

**Comment by timarney** [comment]
Development to look into feasibility as to what's possible for this one.

**Comment by timarney** [comment]
@connorscarolyns @Abi-Nada 

I think we have this covered under the new responses waiting status box + we added the card view

**Comment by Abi-Nada** [comment]
I agree! Will close out this card
