### ISSUE TITLE
API V2.0.1 - API Response delivery  - Update 1

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#4497]
## Description

- [ ] Setup API key generation under the settings page response delivery more details under #4373
- [ ] Update code for response delivery to handle setting to API delivery (DB schema update required) https://github.com/cds-snc/platform-forms-client/issues/4498
- [ ] Update Responses page to "download only" of confirmed submissions 
- [ ] Update delivery types modal

**Settings page**

Add the API option

<img width="507" alt="Screenshot 2024-10-29 at 7 43 27 AM" src="https://github.com/user-attachments/assets/32bdbcb9-42a3-4bcb-8166-584108e2c8e4">

Move API key modal to under response delivery 

<img width="586" alt="Screenshot 2024-10-29 at 7 44 03 AM" src="https://github.com/user-attachments/assets/0d6deb17-aaab-4f6d-be81-0d0cad1ce7bf">

**Delivery options modal**

<img width="744" alt="Screenshot 2024-10-29 at 7 44 24 AM" src="https://github.com/user-attachments/assets/c792c3bc-95fe-470c-aa40-852833903c0c">

**Responses page**

Only  show responses that are already confirmed

![screenshot_2024-10-25_at_8 01 06___am_720](https://github.com/user-attachments/assets/f071fab3-e19c-413d-ba9c-62aaa64bf37f)

**Comment by anikbrazeau** [comment]
# Some content work/attention will be required for:

- [ ] Interface copy for API key tasks in EN
- [ ] Interface copy for API key tasks in FR
- [ ] Technical documentation corresponding updates for devs in EN
- [ ] Technical documentation corresponding updates for devs in FR
- [ ] General guidance creation for non-technical form builders in EN
- [ ] General guidance creation for non-technical form builders in FR

**Comment by timarney** [comment]
Closing this one for #4373
