### ISSUE TITLE
AddressComplete - QA Testing

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4499]
# Testing checklist 

_TO TEST IN [STAGING](https://forms-staging.cdssandbox.xyz/en/form-builder)_ 

We want to be confident in the AddressComplete component, so that we are ready to turn on the feature flag and release it widely once the MOU is signed. (Issue with past context: #3564)

> As a **form builder / program administrator**,
> I want to get complete and accurate addresses,
> So that what I collect is legitimate and what I send as correspondence gets to the right destination.

> As a **form filler / member of the public**,
> I want my address to be filled in correctly and in the right format,
> So that I can fill out the form seamlessly and get access to programs and services more easily, quickly, predictably, and efficiently.

## Jobs to be done
Actions to take to test the form functionality
- [x] Add address element to a form with multiple pages in the edit section
- [x] Test the form in the Test section
- [x] Check the address input on the review page
- [x] Publish the form
- [x] Fill out the form
- [x] Correcting address

## Different modalities / a11y considerations
Interacting with the address component in different ways
- [x] Test in French
- [x] Test in Windows Edge 
- [ ] Test with screenreader
- [x] Test with keyboard 
- [x] Test with increased magnification

## Form builder use cases / form configurations
Different states of the application or ways of gathering data
- [x] Test in unauthenticated, draft mode (people trying out GC Forms)
- [x] Creating a form with Address component (people trying to collect international addresses)
- [x] Adding for the possibility of multiple addresses (people wanting to collect a set of addresses)
- [x] Adding addresses on multiple pages with branching logic (people creating a complex form)
- [x] Adding a conditional address only if selection made previously (people giving their address only if agree to explicitly)

## Form administrator use cases / response delivery formats
Parsing a response with an address or multiple addresses in different delivery formats 
- [x] Email delivery
- [x] HTML response (1)
- [x] HTML responses (many)
- [x] CSV response
- [x] JSON response 
- [ ] API retrieval (no need to QA test, @timarney to do a quick check)
- [x] Testing output for multiple addresses (outputting of a repeating set of addresses)

## Variety of form filler use cases / different types of addresses
Published form output (people filling out a form with different types of addresses
- [x] Urban address with unit number/letter
- [x] Rural address with PO Box
- [x] Military address with service area
- [x] Commercial address with loading dock
- [x] Nicaraguan address with no street name
- [x] Japanese address with block and lot number
- [x] Columbian address with two street names
- [x] Bulgarian address with different order of elements
- [x] German address with different order of elements
- [x] Iranian address with different order of elements
- [x] Costa Rican address with different order of elements
- [x] Uzbekistani address with different order of elements
- [x] American address
- [x] Quebec address
- [x] Nunavut address

## Encountering errors / unhappy paths
- [x] Invalid address
- [x] Address not found
- [x] Unverified address
- [x] Fictional address

**Comment by anikbrazeau** [comment]
# Anik Testing Coverage
- [ ] Add address element to a form with multiple pages in the edit section
- [ ] Test the form in the Test section
- [ ] Check the address input on the review page
- [ ] Publish the form
- [ ] Fill out the form
- [ ] Correcting address
- [ ] Test in French
- [ ] Test in Windows Edge
- [ ] Test with screenreader
- [ ] Test with keyboard
- [ ] Test with increased magnification
- [ ] Test in unauthenticated, draft mode (people trying out GC Forms)
- [ ] Creating a form with Address component (people trying to collect international addresses)
- [ ] Adding for the possibility of multiple addresses (people wanting to collect a set of addresses)
- [ ] Adding addresses on multiple pages with branching logic (people creating a complex form)
- [ ] Adding a conditional address only if selection made previously (people giving their address only if agree to explicitly)
- [ ] Email delivery
- [ ] HTML response (1)
- [ ] HTML responses (many)
- [ ] CSV response
- [ ] JSON response 
- [ ] API retrieval
- [ ] Urban address with unit number/letter
- [ ] Rural address with PO Box
- [ ] Military address with service area
- [ ] Commercial address with loading dock
- [ ] Nicaraguan address with no street name
- [ ] Japanese address with block and lot number
- [ ] Columbian address with two street names
- [ ] Bulgarian address with different order of elements
- [ ] German address with different order of elements
- [ ] Iranian address with different order of elements
- [ ] Costa Rican address with different order of elements
- [ ] Uzbekistani address with different order of elements
- [ ] American address
- [ ] Quebec address
- [ ] Nunavut address
- [ ] Invalid address
- [ ] Address not found
- [ ] Unverified address
- [ ] Fictional address

**Comment by samsadasivan** [comment]
Downloading responses worked for me on HTML, JSON, and CSV - sending @anikbrazeau the form file
