### ISSUE TITLE
AddressComplete - Canadian addresses contain labels for states and zip codes

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4507]
Users have no control over the text in the address fields. 

As I user, if I select Canadian only, I would expect the fields to change to Canadian only format.

Given that the majority of addresses collected will likely be Canadian, I suggest we limit our field labels to Canadian format until we can offer more international formats, or provide control to users to change the label text.

That is not to say we limit address searches to Canada only. Just the text for now.

**Comment by ShadeWyrm** [comment]
Suggested change:
-> If International is selected keep labels as is.
-> If Canada only, use Canadian only elements. (eg: "Postal Code" instead of "Postal Code or Zip")

Would that work?

**Comment by connorscarolyns** [comment]
For sure that would work, but I don't want to add scope when a simple label change would suffice for now.

**Comment by ShadeWyrm** [comment]
Is about the same level of effort. :)

**Comment by connorscarolyns** [comment]
Then I think it's a question for you and @anikbrazeau to decide on the right approach. :)

**Comment by anikbrazeau** [comment]
Sounds good! 

If it's not a ton more effort we could do a more tailored set of labels for "Canadian addresses" and keep the generic broad labels for "International addresses"

**IF Country = Canada, THEN: Specific**
> - Street address // Adresse municipale
> - City, town, or community // Ville ou communauté
> - Province or territory // Province ou territoire
> - Postal code

**IF Country = Other, THEN: Generic**
> - Street address // Adresse municipale
> - City, town, or community  // Ville ou communauté
> - Province, territory, or state // Province, territoire ou état
> - Postal or zip code // Code postal ou zip

References:
****- https://www.canadapost-postescanada.ca/cpc/en/support/kb/business/address-accuracy/addressing-mail-accurately
- https://www.canadapost-postescanada.ca/cpc/en/support/articles/addressing-guidelines/international-addresses.page
