### ISSUE TITLE
AddressComplete - turning flag off after it was on

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#4518]
## Description

- Create a form including AddressComplete with the feature flag on
- Turned flag off
- Complete form
- Check response data

With flag off  --- after it was on.

1) 
A country select shows

<img width="300" alt="Screenshot 2024-10-30 at 10 48 34 AM" src="https://github.com/user-attachments/assets/82c3e462-b601-484f-9770-38dd4a1af94e">

Response has `-` for value
<img width="500" alt="Screenshot 2024-10-30 at 10 53 11 AM" src="https://github.com/user-attachments/assets/8f1851da-4658-4b2b-9984-45fa66575554">

2) 

Street address -- is using "typeahead" component and says start typing to search.  Given the flag is off this field will never have a dataset.  If the user is expecting a search to happen it won't.

<img width="700" alt="Screenshot 2024-10-30 at 10 55 53 AM" src="https://github.com/user-attachments/assets/3188ac16-c200-4dd5-b5bf-b57166598c82">

**Comment by ShadeWyrm** [comment]
I think the expected behavior for this one would be that the "Start typing an address to search" placeholder text simply doesn't appear?

@anikbrazeau - does that make sense for a form that we've turned AddressComplete off on?

**Comment by anikbrazeau** [comment]
Yes that makes sense to me!
