### ISSUE TITLE
Memory Leak - Contact Us

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#4519]
Starting October 25th the majority of POST requests to `/contact` have ended with the Load Balancer timing out for the application to respond and returning a 504 to the client.  These timeouts correspond to activity in the memory utilization where the app continually utilizes reserved memory capacity until erroring out and restarting.

**Comment by dsamojlenko** [comment]
Taking a closer look at the Contact form to see if there's any error handling or additional validation we can do, specifically around the freshdesk api call.

**Comment by dsamojlenko** [comment]
https://github.com/cds-snc/platform-forms-client/pull/4529

Added some client-side validation to those forms

**Comment by anikbrazeau** [comment]
Closed for now. We will wait and observe to see if this happens again: https://gcdigital.slack.com/archives/C07U6P00CTD/p1730476841165639
