### ISSUE TITLE
Schedule a closed form: Missing FR error messaging

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4525]
## Description
We're missing FR error messaging when scheduling to close a form.

## Steps to reproduce
1. Go to a Published Form -> Settings -> Form Management
2. Toggle to the FR interface
3. Click on 'Schedule form closing'
4. Add a date in the past. Click Save. 

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: French

## Expected behaviour
The FR translation for: "Date and time must be upcoming, in the future."

## Screenshots or videos
<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1e0abe38d53e9c4a21ef5ec68ff29dcb2cb70e9/Screenshot%202024-10-30%20at%202.23.17%E2%80%AFPM.png" alt="Screenshot 2024-10-30 at 2.23.17 PM.png" />

**Comment by timarney** [comment]
@anikbrazeau feel free to add the string here if that's easier :)

**Comment by anikbrazeau** [comment]
FR: `La date et l'heure doivent être à venir, dans le futur.`
