### ISSUE TITLE
V2 - Iterating on Documentation to match new changes / interface

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4558]
# Documentation site
**https://cds-snc.github.io/forms-api/**

## User story
As an infrastructure developer, I want the latest documentation know what I need to do to integrate with the GC Forms API so that I can retrieve form submissions programmatically, without reaching out for help.

## Context
As part of the self-serve version of the API release, we need open, published, bilingual documentation to help guide developers through the process. This version should be fully bilingual.

### Update content for full supported bilingual experience
- [x] Iterate on content based on interface changes --> API key creation
- [x] Entry paths from the application UI identified and linked
- [x] Create high-level guidance page for non-technical audience that links to API documentation --> new issue created #4698
- [x] Publish a pull request with changes to `docs` branch in French and English
- [x] Update Terms of Use and SLA accordingly --> new issue created #4673

## Further iterations
- Styling to match GC Forms / get closer to GC Notify Documentation
- Submenu structure to make navigation more scannable within API requests
- Explore dedicated domain and parallel structure to Notify docs VuePress site

**Comment by anikbrazeau** [comment]
Related https://github.com/cds-snc/forms-api/issues/104

**Comment by anikbrazeau** [comment]
Should be able to get this done pretty quickly upon my return (major change is to the API key creation / deletion process)

**Comment by anikbrazeau** [comment]
https://github.com/cds-snc/forms-api/pull/112

**Comment by Abi-Nada** [comment]
To be merged in with the release

**Comment by anikbrazeau** [comment]
Complete
