### ISSUE TITLE
Modifying the closing message on a form generates an error

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#4559]
![Screenshot 2024-11-01 at 3 01 17 PM](https://github.com/user-attachments/assets/9375f46e-fb89-472c-a236-2a495d1f4900)

**To replicate:**
Setup:
- Create a form
- Add a closing message and date to a form
- Save form
- Close tab / end session

Bug Replication:
- Sign in and go to Forms 
- Go to form-builder settings for Form
- Go to Form Management
- Change closing message and click "Save Changes"
- Error occurs.

![closing form error](https://github.com/user-attachments/assets/57f103e5-0e34-4891-8b6b-510857c0a1d1)

**Comment by timarney** [comment]
> Add a closing message and date to a form

@bryan-robitaille you scheduled a date via the modal ya?

**Comment by anikbrazeau** [comment]
## Impact 

This critical bug stops clients from using the functionality, as users cannot update the content of the message unless they also change the time the form is scheduled to close. So far only one known user has run into this error, their form is set to close a week from today.

## Brainstorming some potential options
- Decoupling scheduling changes from content changes
- Grouping all closing customizations in the modal
- Rolling back the feature or using a feature flag to hide it temporarily
- Interim content to let users know they need to update the scheduled time to update the message
