### ISSUE TITLE
AddressComplete: Street address field doesn't populate with selection

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/platform-forms-client#4608]
## Description
When you select the address, the Street Address field is left blank. It can read as an error. 

## Steps to reproduce
1. Select street address

## Details
- **Browser**: Chrome
- **Operating system**: OS
- **Environment**: Staging
- **Language**: EN/FR
- **Viewport**: Desktop

## Expected behaviour
For the selection to remain in the field

## Screenshots or videos

<img width="1173" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23e84c5e71f6dccc2e0b20616f7086fd86dc4677/image.png" alt="image.png" />

**Comment by anikbrazeau** [comment]
Related to #4595

**Comment by ShadeWyrm** [comment]
Can you provide what address you're typing in? @samsadasivan

**Comment by samsadasivan** [comment]
Address doesn't have a street address lol
