### ISSUE TITLE
Exporting Translation to CSV breaks when commas are included as part of radio button element options.

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#4656]
## Description

[Reference to support ticket](https://cds-snc.freshdesk.com/a/tickets/18068)

Broken CSV:
[beaver-dam-breaching-and-removal-code-of-practice-2024-11-13.csv](https://github.com/user-attachments/files/17737849/beaver-dam-breaching-and-removal-code-of-practice-2024-11-13.csv)

Form Template to Replicate:
[beaver-dam-breaching-and-removal-code-of-practice-final-2024-11-13.json](https://github.com/user-attachments/files/17737834/beaver-dam-breaching-and-removal-code-of-practice-final-2024-11-13.json)

- Create a form using the provided Form Template above (that includes radio buttons + drop-downs).
- Go to Translation Tab
- Export Translations
- Open CSV in Excel.

## Expected behaviour
The csv file is correct parsed and imported into Excel.

## Screenshots or videos

![image (4)](https://github.com/user-attachments/assets/9e370d16-4b90-41b0-b145-6038d84f5a41)

## Additional context
This happens to any element that contains "Options" (like radio buttons and dropdowns)

**Comment by thiessenp-cds** [comment]
@bryan-robitaille was this OS specific?

**Comment by thiessenp-cds** [comment]
I'll time-box this to about two days. From past work with CSV bugs, these can turn into a black hole of dev time

**Comment by thiessenp-cds** [comment]
For reference:

MacOS Excel
![Screenshot 2024-11-18 at 9 08 56 AM](https://github.com/user-attachments/assets/9a133c95-3a98-4fea-928b-ae39afe8dbda)


Windows Excel (Windows VM running Edge in Excel web app)
![Screenshot 2024-11-18 at 9 20 09 AM](https://github.com/user-attachments/assets/2b2e4f58-6ba4-4b54-b54e-c3c770f65992)
