### ISSUE TITLE
API self-serve: QA Testing

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4669]
### Description:

Card for QA Testing the API. Testing states flagged in the comments below.

**Comment by timarney** [comment]
Noting for QA --- testing without using the actual API

We can mimic using the API by performing actions i.e. download, confirm etc... using "vault mode" i.e form without an API key generated.

For example to test "API confirmed page"

- Create a form
- Keeps response delivery as "vault"
- Create some test responses 
- Confirm the responses (still using vault setup)
...
- You now have confirmed responses 

- Generate an API key
...
Your now in API "mode"
...
- Re-visit the responses page 
- You should now see the API responses "confirmed page"

---

New "never confirmed"
- Create a form
- Generate a key
- Create some test responses 
- You should land on "new responses available via API" card view 
...


New "no responses"
- Create a form
- Generate a key
- Create some test responses 

- You should land on "noresponses available" API card view 

---

"Mixed" --- 

- Perform the steps for "API confirmed page" .... but don't confirm them all
- You should now have confirmed and new submissions waiting
- Ensure view indicates confirmed + has a status box for "new" awaiting download.

**Comment by timarney** [comment]
For local testing 

I tested 6 different possible states for the API responses page

 A) 
<img width="992" alt="a" src="https://github.com/user-attachments/assets/aa0331c4-222a-47a9-8b41-5e369388ee6a">

B) 

<img width="1097" alt="b" src="https://github.com/user-attachments/assets/10870eeb-e4c7-4103-99c3-77cfd12cc6fb">

C)

<img width="1054" alt="c" src="https://github.com/user-attachments/assets/98878c52-add7-40ba-972f-9d119bc6bd77">

D)

<img width="951" alt="d" src="https://github.com/user-attachments/assets/5e782330-6e96-4ae0-86cd-267d09b0624e">

E) 

<img width="1156" alt="e" src="https://github.com/user-attachments/assets/cc355076-462a-43b8-a179-88370792b065">

F) 
<img width="976" alt="f" src="https://github.com/user-attachments/assets/780cd82e-e047-4727-9b92-f21c4573d951">

**Comment by anikbrazeau** [comment]
Some states we might want to test: 

- [ ] Draft form using all form elements, pages and branching
- [ ] Publishing a form with API response delivery
- [ ] Submitting and retrieving responses in English
- [ ] Submitting and retrieving responses in French
- [ ] Switching response delivery method from email to API
- [ ] Switching response delivery method from download to API
- [ ] Switching response delivery method from API to download

**Comment by anikbrazeau** [comment]
https://github.com/cds-snc/platform-forms-client/pull/4697

**Comment by anikbrazeau** [comment]
# Anik testing checklist

## Tablet / Edge / French

- [ ] Draft form using all form elements, pages and branching
- [ ] Select the API response delivery option
- [ ] Create/delete an API key (draft)
- [ ] Create/delete an API key (published)
- [ ] Submit test response in English and retrieve via API
- [ ] Submit test response in French and retrieve via API
- [ ] Submit response on published form in English and retrieve via API
- [ ] Submit response on published form in French and retrieve via API
- [ ] Submit a batch of responses and retrieve them via API
- [ ] Switch response delivery method from email to API
- [ ] Switch response delivery method from download to API
- [ ] Switch response delivery method from API to download
- [ ] Request higher API rate limit
- [ ] Check response page for form with no responses
- [ ] Check response page for form with some new responses not yet retrieved
- [ ] Check response page for responses reported as a problem via API
- [ ] Check response page for responses accessed but not confirmed
- [ ] Check overdue state if possible
- [ ] Test with vault mode without actually using the API
- [ ] None new, none confirmed
- [ ] Some new, some confirmed
- [ ] Check for missing translations

**Comment by Abi-Nada** [comment]
Confirmed that testing has been completed
