### ISSUE TITLE
API testing: Empty state

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4714]
There is a space missing before the link. 

The text (opens in a new tab) should be included in the link

Can we make the background white on all of these info boxes?

<img width="767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm51Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a785c561dd9ce01e249b5e4b2dc894500625be3/image.png" alt="image.png" />

**Comment by anikbrazeau** [comment]
Space addressed in https://github.com/cds-snc/platform-forms-client/pull/4697
Link text change to be addressed in same PR

**Comment by timarney** [comment]
@anikbrazeau can this one be closed now?

**Comment by anikbrazeau** [comment]
@timarney thoughts on "Can we make the background white on all of these info boxes?"
We can close if that is captured somewhere else.

**Comment by timarney** [comment]
PR for card background.

https://github.com/cds-snc/platform-forms-client/pull/4778

**Comment by Abi-Nada** [comment]
PR has been merged
