### ISSUE TITLE
Error when trying to import a form file [API v2 QA]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4723]
## Description
When trying to open a form file with all form elements in staging, get "Failed to read form file -- Invalid: lastGeneratedElementId".

Even when repeating sets, file upload and address are removed the error persists.

## Steps to reproduce
1. Sign in 
2. Create a multi-page form with all form types (Page 1: short/long answer, Page 2: all selection type questions, Page 3: presets)
3. Save a copy of the form file
4. Open the form file
5. Get error

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: English
- **Viewport**: Tablet
- **Output**: `cm40esdzo00017cldive704sz`

## Expected behaviour
Ability to import a file that was just created?

## Screenshots or videos
![error importing](https://github.com/user-attachments/assets/554200b0-b267-4ad4-8659-ac41e6e9ce4a)

**Comment by anikbrazeau** [comment]
It was happening for several form files

**Comment by timarney** [comment]
Is this still happening --- it's was flagged on slack and fixed.

**Comment by anikbrazeau** [comment]
Actually this appears to be fixed!
