### ISSUE TITLE
Deleting API key reverts to email rather than download [API v2 QA]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4724]
## Description
The toast messsage indicates that responses can be downloaded from the Responses page however it has reverted to email, if it was last method selected?

## Steps to reproduce
1. Go to a draft form
2. Select email delivery
3. Go to publishing checklist to see selected method
4. Switch to API delivery with API key creation
5. Go to publishing checklist to see selected method
6. Delete API key
7. Go to publishing checklist to see selected method

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: English
- **Viewport**: Tablet

## Expected behaviour
Reflect API when selected
Switch to Download when deleted
Switch the radio button input right away?

## Screenshots or videos
![Toast accuracy](https://github.com/user-attachments/assets/2a6958df-10bc-4010-9806-6a261dd91c06)
![deleted toast](https://github.com/user-attachments/assets/d9171029-74c2-4aed-9807-f5f36aeb473d)
![deleted key reverts to email](https://github.com/user-attachments/assets/caa39c44-0870-4248-a38b-746d335b2218)
![reverts to email](https://github.com/user-attachments/assets/9d34f7ae-8981-4f78-a9dd-19245b708720)

https://github.com/user-attachments/assets/1e1ecc47-cdf4-4ee4-9cca-1ddfa200a0e6

<img width="824" alt="Screenshot 2024-11-29 at 2 41 46 PM" src="https://github.com/user-attachments/assets/d6544f4b-686e-4668-a8a0-29f063797ba3">

**Comment by timarney** [comment]
@anikbrazeau 

Let's see if https://github.com/cds-snc/platform-forms-client/pull/4754 fixes.

The PR will default the radio setting to show download as selected.

Behind the scenes when using the API vault is the selected option when you have an API key

Email = email
Vault = vault
API = vault --- we fake the value on the settings screen when an API key exists.
