### ISSUE TITLE
API delivery method does not get reflected in the settings selected for the publishing checklist [API v2 QA]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4726]
## Description
The API response delivery method does not get reflected on the Publish page as the selected option

## Steps to reproduce
1. Go to a draft form
2. Select API delivery
3. Go to publishing checklist
4. See that the choice is not reflected

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: English
- **Viewport**: Tablet

## Expected behaviour
Reflect API on Publish page when it's selected.

## Screenshots or videos

![api method does not reflect in publish checklist](https://github.com/user-attachments/assets/29e7aac6-cd83-4877-8aef-20efbb964c05)

![does not reflect](https://github.com/user-attachments/assets/0a2606c9-adf6-45f3-9dcf-374a394b671e)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi8xQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3c01c975e17bd077211ba79317d4cdedd94e8c5/Screenshot%202024-11-29%20at%209.53.43%E2%80%AFAM.png" alt="Screenshot 2024-11-29 at 9.53.43 AM.png" />

<img width="1052" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjcxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac9dac92df904355f73c54ee6e40105c502e270e/Screenshot%202024-11-29%20at%209.53.36%E2%80%AFAM.png" alt="Screenshot 2024-11-29 at 9.53.36 AM.png" />

https://github.com/user-attachments/assets/735ff4cb-c8c0-44a7-aca3-164eaa0c20f8

## Additional context
#4724

**Comment by timarney** [comment]
@Abi-Nada I'll pick this one up.

**Comment by timarney** [comment]
PR

https://github.com/cds-snc/platform-forms-client/pull/4758
