### ISSUE TITLE
Consider moving email delivery to first radio option as it's for simpler use cases [API v2 QA]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4731]
## Description
We may want to rethink the format and order of delivery options to make these more parallel and clarify the progression / relationship to data classification. 

## Steps to reproduce
1. Go to Settings
2. See delivery options
3. Email in the middle seems out of place

## Details
- **Browser**: Chrome / Edge
- **Operating system**: Mac / Windows
- **Environment**: Staging
- **Language**: English
- **Viewport**: Tablet

## Expected behaviour
Parallel radio button structure with all having hint text.
Order from lowest to highest complexity?

## Screenshots or videos
<img width="1673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFR4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac2d541c939c4b10da44316127545fb5890c9ca9/Screenshot%202024-11-25%20at%209.47.36%E2%80%AFAM.png" alt="Screenshot 2024-11-25 at 9.47.36 AM.png" />

![radios](https://github.com/user-attachments/assets/67431f0c-2330-457a-aeba-f78aa41264b5)

## Additional context
#4725

**Comment by Abi-Nada** [comment]
Added as Acceptance Criteria in #4716
