### ISSUE TITLE
Broken link to closing a form in "Delete API key" modal [API v2 QA]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4736]
## Description
The link that nudges people to go close a form instead does not link to that place in the app

## Steps to reproduce
1. Go to a form
2. Select API delivery
3. Create API key
4. Delete API key
5. Click link in modal

## Details
- **Browser**: Edge
- **Operating system**: Windows
- **Environment**: Staging
- **Language**: EN and FR
- **Viewport**: Tablet

## Expected behaviour
A clear and concise description of what's expected instead.

## Screenshots or videos
![broken link](https://github.com/user-attachments/assets/9f613717-d79e-4e55-ae38-ec225c9c1f76)

**Comment by timarney** [comment]
PR 

https://github.com/cds-snc/platform-forms-client/pull/4760
