### ISSUE TITLE
Make download / sign off a requirement for switching from Download to API [API v2 QA]

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4750]
## Description
Without a check in place, some responses may be lost in the interim state "Downloaded" but not "Signed off for removal" meaning if switching from "Download" to "API" delivery method, they could get lost in the mix and not be visible/retrievable.

## Steps to reproduce
1. Go to GC Forms > Draft form
2. Select "Download" delivery method
3. Submit test responses so there are some in "New", some in "Downloaded", some in "Signed off for removal" and some in "Reported as a Problem" 
4. Switch to "API retrieval" delivery method
5. Retrieve all responses / confirm all responses
6. The one in download does not factor into the confirmation step.

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English
- **Viewport**: Desktop

## Expected behaviour
Must download/confirm all responses before changing delivery method?

## Screenshots or videos
<img width="1218" alt="Screenshot 2024-11-29 at 2 42 02 PM" src="https://github.com/user-attachments/assets/ffc3b58d-2b1e-493a-afd3-a0889b3f239d">
<img width="1230" alt="Screenshot 2024-11-29 at 2 50 16 PM" src="https://github.com/user-attachments/assets/7aca37c4-283b-4698-ac3e-6886cf0874b1">

**Comment by connorscarolyns** [comment]
The design for this is complete. It is triggered when the user tries to switch delivery methods with responses in the downloaded tab. It can appear inline. It should not be triggered in draft forms, as any responses in the download tab are deleted when publishing.

<img width="533" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHorQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55f5e1324e2d737008245387d3f66fa75aaeb73f/image.png" alt="image.png" />

**Comment by Abi-Nada** [comment]
Closing as Carolyn flagged this is intended functionality for draft forms
