### ISSUE TITLE
Oops we forgot about this one! Delivery options on the editing screen

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4768]
<img width="875" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlVBQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cea65be2afb646252a2a941423f4306838bdbb6/image.png" alt="image.png" />

We have three options here:

- 1 remove the purple bar and modal entirely
- 2 remove the delivery option radios from the list
- 3 We can present the info more like the publishing list & add a link to settings

@anikbrazeau @samsadasivan @timarney @Abi-Nada

**Comment by timarney** [comment]
Can we just remove the modal / "more" button and just keep the "purple bar" / quick select ?

---
Noting the current:

Like the form purpose I didn't add  all the API stuff to this dialog.  If an API key exists I do hide the delivery option.

**Comment by connorscarolyns** [comment]
If we keep the bar, we could remove the options to select anything (just show what is selected) and direct people to the settings tab with the button rather than open a modal.

**Comment by anikbrazeau** [comment]
I think we could probably remove the modal without losing anything? The specific settings (classification and delivery method) are now highlighted on the publishing checklist, which I don't think they were when we added this originally.

I also wonder how many folks chose branding from the purple bar versus in settings, it might be a bit redundant to have it in both spots especially given it's really a one-time choice and shows up on "Test" page with the preview as well?

**Comment by timarney** [comment]
PR to remove

https://github.com/cds-snc/platform-forms-client/pull/4776

This will help on the App maintenance / testing end.

541 lines of code remove in that PR.

**Comment by timarney** [comment]
@connorscarolyns @Abi-Nada 

Maybe 👍 before I merge that PR.

**Comment by Abi-Nada** [comment]
The PR LGTM! I agree, we've talked about the redundancy of that modal for a while now.

Before we merge, flagging to @srtalbot for visibility

**Comment by connorscarolyns** [comment]
When we added the administrative purpose, which has no default and forces the user to go to the settings page, the original problem this bar was created to solve resolved itself. Which was to surface those settings before the user could publish.

**Comment by Abi-Nada** [comment]
Thanks for the additional context, Carolyn!

@timarney just flagging we're good to merge whenever 👍

**Comment by anikbrazeau** [comment]
Completed, merged in #4776
