### ISSUE TITLE
Tech Debt: can useTemplateStore be simplified?

### ISSUE THREAD

**Issue by thiessenp-cds** [cds-snc/platform-forms-client#4783]
The template store (useTemplateStore.tsx) is an important part of the app and becoming difficult to read and maintain because of it's growing size.
One idea is to move much of the code in the template store out into separate reusable util functions. This would make skimming through the store much easer/readable. Also the utile functions could be more easily tested and by this probably improve app stability and debugging.

Another important and large file is templates.ts (over 1500 lines of code). Perhaps this file could be split up?

**Comment by timarney** [comment]
Agreed - as we've spoken about previously 


1) There's duplicated functionality and helper methods where code could be pulled out to.


2) The move up / down code can be simplified a bunch --- we don't actually need to be moving things up and down in the elements array as the editor and front facing use the layout array.    

3) I would also like to look at using a Map for the elements array so we can avoid all the index lookups.  The structure can remain an array for the JSON schema i.e. when saves occur we can write the data in the array format while the store uses a map.

4) I've had an idea for a while that we might be able to do more "silent" type updates at the store level --- possibly using a ref .  The thought is most of the components have local state.  While the store does needs to know about and indeed update the state we don't need to re-render all the way back though the app or at least not always.

**Comment by timarney** [comment]
@Abi-Nada this card can fall under the code re-org epic as well.

**Comment by timarney** [comment]
In and around the same area I think the Zustand selectors could be updated to look for specific elements vs the need to pull "all the elements".

**Comment by timarney** [comment]
Tracking a couple of related PRs

https://github.com/cds-snc/platform-forms-client/pull/4799

https://github.com/cds-snc/platform-forms-client/pull/4795

**Comment by timarney** [comment]
Breakout move helpers:
https://github.com/cds-snc/platform-forms-client/pull/4802

**Comment by timarney** [comment]
Closing --- focused on breaking out help files --- will re-visit as need in the future.
