### ISSUE TITLE
Reveal to users that a switch in data classification in the "quick" settings menu in "Edit" changes delivery method 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4786]
## Description
When a draft form is unclassified/Protected A and gets switched to Protected B within the "quick-select" purple menu at the top of the "Edit" page, the delivery method changes, but the user is not aware that this has been modified.

## Steps to reproduce
1. Go to draft form (signed in)
2. Click on "Settings"
3. Select "Protected A" and "email" delivery
4. Go to "Edit"
5. In the top bar that allows for setting selection, select "Protected B"
6. Go back to settings
7. See how delivery method has changed to download

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Staging
- **Language**: English / French
- **Viewport**: Desktop

## Expected behaviour
Either a toast or some sort of feedback that there has been a subsequent change?
Or removal of this entirely, as it might be considered redundant.

## Screenshots or videos
<img width="1826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlJQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e8b03340f78ef1b6ac31eb3abc55309377761a0/Screenshot%202024-12-05%20at%207.17.31%E2%80%AFAM.png" alt="Screenshot 2024-12-05 at 7.17.31 AM.png" />

**Comment by timarney** [comment]
:(  

Didn't think of that.

Should we just remove the bar all together?

**Comment by anikbrazeau** [comment]
Maybe that'd be easier? I think the potential confusion here might outweigh the usefulness?

**Comment by timarney** [comment]
Per @connorscarolyns here

The other option would be to turn the classification + branding selects into buttons and link them to settings. 

https://github.com/cds-snc/platform-forms-client/issues/4768#issuecomment-2517341446

Both easy to do ... just need consensus on the way forward.

**Comment by connorscarolyns** [comment]
I thought we were removing this bar?

**Comment by timarney** [comment]
Removed the modal with the previous 

Will create another PR to remove the bar.
