### ISSUE TITLE
Character limit functionality doesn't work

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#4869]
## Description
[Support Ticket 20650](https://gcdigital.slack.com/archives/C03T4FAE9FV/p1734639763575849): a client implemented validation//character limits to their forms, but it looks like that functionality is no longer working. As a result, end users are submitting answers that contain more than the required length, and therefore the response JSON on the client's end cannot be successfully transferred to their database.

## Steps to reproduce
1. Create a form with a short or long answer question
2. Add a character limit of "250"
3. Test out the form - input text for the short/long answer question

## Details
- **Browser**: Chrome
- **Operating system**: Mac
- **Environment**: Production
- **Language**: EN

## Expected behaviour
There should be data validation on that box//a count for how many characters are left.

## Screenshots or videos

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM001Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d492e62719a8e2adbcf85f0668de1e809073e8b9/Screen%20Recording%202024-12-20%20at%207.52.40%E2%80%AFAM.mov)

Client's published form (see no countdown):
<img width="1196" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2s1Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55e563cbcf472c28d1fef7410955b765425bde5d/Screenshot%202024-12-20%20at%208.02.22%E2%80%AFAM.png" alt="Screenshot 2024-12-20 at 8.02.22 AM.png" />

## Additional context
Given the holidays around the corner and what we have sitting in the pipeline, the fix for this will most likely go out in the new year release

**Comment by timarney** [comment]
Tested using a low char amount  (5 chars)

Seeing:

https://github.com/user-attachments/assets/2b66d8fa-90db-41e5-9d63-7ca7a698f509


Do you get different results?

**Comment by Abi-Nada** [comment]
Nvm - user error AND Abi error for flagging a bug 😅

For this user's specific form, they added the text "Maximum Character Length: 250" to the "Hint Text" field, as a description. They should've added the character length under the "Maximum character length" field. Closing out this card as it's not a bug
