### ISSUE TITLE
Migrate from Next JS 11 to 12

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#518]
With the release of Next JS 12 we should migrate the application to use it. Next JS 12 comes with some breaking changes so we want to ensure we do not break any functionality or accessibility. These are

- After making webpack 5 the default in Next.js 11, we've now officially removed webpack 4. We've worked closely with the community to ensure a smooth transition to webpack 5.
- target in next.config.js is no longer needed.
- next/image now uses a span as the wrapping element instead of a div.
- The minimum Node.js version has been bumped from 12.0.0 to 12.22.0, which is the first version of Node.js with native ES modules support.

Acceptance Criteria:

- [ ] Ensure all functionality works as expected and there are no regressions introduced 
- [ ] Ensure there are no a11y regressions introduced by the upgrade

**Comment by craigzour** [comment]
Even though everything looks good in development mode it appears that we will have to wait for Next JS to improve their build logic since it does not work at all. It just hangs on the creation of the optimized production build without returning any errors.

@bryan-robitaille suggestion

> I’d drop it for now until NExtJS supports the Emotion Babel plugin we use with SWC… they’re working on it, and other plugins, but they’re not ready yet.
> Our migration path should wait until they figure out these more complex instances of NextJS.
