### ISSUE TITLE
chore: lint rule for `no-return-await`

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#552]
Implement the lint rule for `no-return-await` as described here: https://github.com/eslint/eslint/blob/main/docs/rules/no-return-await.md 

This rule is not applied in several cases across the codebase, and could cause errors.

**Comment by Moro-Code** [comment]
Having an explicit return increases readability by making it clear when a function execution ends. I'm not seeing a clear case of a performance decrease by doing this so would prefer to keep explicit returns
