### ISSUE TITLE
refactor: change spelling of `organisation` to `organization`.

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#562]
There are 2 variations of the word `organization` (organisation) used throughout the code and database. For consistency and to reduce the possibility of errors, only one spelling of this word should be used.

**Suggestion:** Change all spellings for `organisation` to `organization`, replacing the `s` with `z`.  This applies to any variations of the word, such as `organisations`.

**Comment by bryan-robitaille** [comment]
Acceptance Criteria:
- [ ] All tests continue to pass
- [ ] All Functionality is intact
- [ ] A 'find all' returns no results for 'organisation' in the project

**Comment by falila** [comment]
Is Terraform repo included in this ticket ?  It seems that "organisation" appears as well.

**Comment by craigzour** [comment]
https://github.com/cds-snc/platform-forms-client/pull/589
https://github.com/cds-snc/forms-terraform/pull/165
