### ISSUE TITLE
Make the word required visible on required fields

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#625]
Currently only an asterisk is displayed on a field that requires a value 

![Screen Shot 2022-02-03 at 10.21.30 AM.png](https://images.zenhubusercontent.com/5e4d99e2b8781e7790b7e8cc/dd8e9613-a6df-435e-acb0-4f153370445b)

User's with disabilities such as dyslexia may not be able to infer the context of a red asterisk.

Acceptance Criteria:
- [x] Display the word "(required)" and its equivalent french translations when the language is set to french on every field that is required at the end of the label
- [x] Remove the red asterisks

**Comment by jeberhardt** [comment]
Will the word "(required)" remain in red, as the asterisk is?

**Comment by jeberhardt** [comment]
I'll also remove the existing code: `<i class="visually-hidden">Required Field</i>` as it would be redundant.
