### ISSUE TITLE
Review logMessage levels

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#699]
Review the codebase and determine the correct logMessage level dependent on whether the message should appear only in development or in Staging / Production level logs.

Current logMessage levels are:
- Debug : Only if debug env var is set
- Info: Development Environment
- Warn: Development Environment
- Error: Production and Staging Environment

Part of the scope of this PR is to determine the appropriate logMessage levels to output in each environment: Development, Staging & Production.

**Comment by craigzour** [comment]
@bryan-robitaille According to the following code it feels like we are also sending `Warn` logs in production. Am I correct?
````

export const logMessage = pino({
  level: process.env.DEBUG ? "debug" : process.env.NODE_ENV === "development" ? "info" : "warn",
  browser: {
````

**Comment by bryan-robitaille** [comment]
I like the proposed way forward :) 
And you are right that we are currently sending Warn logs to Staging and Production with the code line you highlighted.
