### ISSUE TITLE
Email address should be trimmed of blank space.

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#734]
When adding a user to a form's access, if there is a blank space at the end of the string, it will fail comparison and reject the email address as not being a Government of Canada email address. All blank spaces should be removed before comparing.

For example: "john.doe@cds-snc.ca " will not pass the validation.

**Comment by bryan-robitaille** [comment]
Also verify if text input form fields are properly being sanitized on email and other types of input.

**Comment by Abi-Nada** [comment]
Closing as issue no longer persists.
