### ISSUE TITLE
Backup and purge `admin_logs` PostgreSQL table

### ISSUE THREAD

**Issue by craigzour** [cds-snc/platform-forms-client#740]
**User story**
The system should backup and purge the `admin_logs` PostgreSQL table so that we do not run into performance issue.

**Story context**
With the implementation of #727, we introduced a new PostgreSQL table (`admin_logs`) which can quickly grow over time as admin are using the various features in the administration panel.

**Possible solutions**
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ExportSnapshot.html ; https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/postgresql-s3-export.html
- https://medium.com/analytics-vidhya/export-table-from-aurora-postgresql-to-amazon-s3-4eafee9fabb5 ; https://hevodata.com/learn/aws-rds-postgres-export-to-s3/
- https://schinckel.net/2021/09/09/automatically-expire-rows-in-postgres/

**Acceptance criteria**
- [ ] Data from `admin_logs` PostgreSQL older than three months is exported and saved in AWS S3
- [ ] `admin_logs` PostgreSQL table is purged (after backup)
- [ ] table is reindexed after purge to prune tree and speed up inserts and reads

**Comment by bryan-robitaille** [comment]
Addressed in #1696
