### ISSUE TITLE
Response output: HTML template

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#755]
**Feature**
- HTML template to hold response data

**UI/UX attachment**
- [Figma file](https://www.figma.com/file/6QAmUEq6d8tyXzWDGKO78s/v2.-Form-builder?node-id=2889%3A12574&t=3ypnk6RzkQvGDgRr-0)
- [Design Doc ](https://docs.google.com/document/d/1miPWCJnweaXds8K_QVy04Epwx1QGwz3DHW2p5QpGyMY/edit?usp=sharing)

**Scope**
- Branded header and footer
- Box declaring an official record and level of data protection
- Jump to: links to anchored points on the page
- Document is bilingual with language links
- Links to privacy, terms and help

**Prerequisite**
None identified

**Acceptance criteria**
-

*Accessible:*
- [ ] Sections of text that are in a language that is different from the main document are defined for the correct language
- [ ] There is a skip-to-content link at the top of each page that allows users to bypass the navigation and move focus to the main content
- [ ] Pages have unique and descriptive programmatic title
- [ ] The order of focusable items follows a logical sequence
- [ ] The purpose of links is clear
- [ ] Images that serve as links have an alt attribute or aria-label that describes the link destination
- [ ] All images, icons, charts, infographics and other visuals have alternative text
- [ ] Keyboard focus is visible
- [ ] Any changes in context are communicated, such as a new window opening, focus shifting to a different element, or a new page loading, that happen when an element receives focus
- [ ] Headings and labels are clear and descriptive
- [ ] The page contains a proper heading structure: 
- Contains a single h1 level heading per page that identifies the overall page topic.
- Follows a hierarchical structure
- Does not contain empty headings
- [ ] Lists, including navigation items and carousel slides, marked up correctly:
- Encases lists in a `<ul>` (unordered list) or `<ol>` (ordered list) tag, with each item tagged as `<li>`. 
- Does not split lists that are arranged in columns visually into separate lists. 
- [ ] Programmatic order of content matches the visual order
- [ ] Text/background colour combinations have acceptable contrast. The contrast requirement at Level AA is 4.5:1 for regular sized text and 3:1 for large text (18pt+) or bold text (14pt+). 
- [ ] Are there any display issues when resizing only the text on the page to 200%? Examples include overlapping, obscured or cut off content. 
- [ ] Text spacing can be adjusted 

*Inclusive:*
- [ ] Content is available in both official languages
- [ ] Sections of text that are in a language that is different from the main document language are defined
- [ ] Contextual text read aloud by screen readers such as alt text are available in the both official languages

**Comment by bryan-robitaille** [comment]
Updated design doc and figma file locations
