### ISSUE TITLE
Create Design for Acceptable use policy disclaimer

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#800]
For internal staff once they login to the retrieval UI

As internal staff member , after a successful login the system should display the Acceptable Use policy that the user should  agreed upon.

Acceptance criteria: 

- [ ] It should have a scrollable section with formatted text (Acceptable Use policy).
- [ ] It should have a checkbox  at the bottom of the text.
- [ ] A the bottom of the AUP, the user can select  the checkbox and submit.
- [ ] Following the submission, the user is directed to the data download page.
- [ ] Log an audit event that the user has accepted the AUP.
- [ ] **Redirect to the Retrieval Page after accepting theAcceptable Use.**
- [ ] Ensure the page is accessible.  
- [ ] Provide adequate tests at all level.

**Comment by connorscarolyns** [comment]
Link to page design:
[https://www.figma.com/file/ZPt6quJaJ2bVYZboCccWJs/Retrieval-UI?node-id=644%3A1720](url)

**Comment by connorscarolyns** [comment]
Deign Decision: 
To remove the checkbox and go with an acceptance button. By clicking the buttons users accept the terms. 

Also added a cancel button as a best practice. Users should be offered a way to  back out of the acceptance, cancel will log the users out and direct them to the logged-out page.
