### ISSUE TITLE
Create mock-ups and flow diagram for file upload document scanning

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#805]
Upper-end estimate for files to upload: https://forms-staging.cdssandbox.xyz/en/id/273 

Questions:
- What is a reasonable file size to support for one file?
... 

### Acceptance criteria:
- [x] Conduct exploratory design research
- [x] Connecting with Mohamed, Pat, and Sarah on possible micro-services
- [x] Outline service flow(s)
- [x] Identify the wait times for scanning at the front-door vs after submission
- [ ] Inform options analysis frame

**Comment by connorscarolyns** [comment]
Link to mural board with three upload service flow options
[https://app.mural.co/t/cppd0120/m/cppd0120/1655138742246/b7061fe88ad2da8acfb4cdaaa47a1e5f30e69bb7?sender=u0258ba6e17fe9b681b483023](url)

**Comment by bryan-robitaille** [comment]
Closing because a decision has been made to go with Asynchronous File Scanning.  No user impact/visibility into the process.
