### ISSUE TITLE
Create a secure API that will return a list of login attempts.

### ISSUE THREAD

**Issue by falila** [cds-snc/platform-forms-client#818]
As an admin of GC form, I would like to get all the "login attempts" as well as for a given form id.
These logs should come from the "access_log" table.

Acceptance criteria: 

- [ ] Create an API route that accepts `GET` requests.
- [ ] The API path should be  `/api/login/attempt`.
- [ ] This API endpoint should allow requests with valid admin bearer token or session*.
- [ ] This endpoint should return all the login attempts.
- [ ] if there is no "login-attempts" an empty list should be returned. Otherwise a list of "login attempt".
- [ ] A reasonable level of unit testing is required.
- [ ] if the bearer token is invalid return a 403 status code.

** To be approved :  with query parameters**
- [ ] with a query parameter **`user_id`**  '/api/login/attempt?user_id='.
- [ ] if the user_id cannot be found in access_log a 404 status code should be returned. otherwise return a list of "login-attempt".

**Comment by bryan-robitaille** [comment]
This information does not need to be exposed through an API.  The database call can be achieved through `getServerSideProps`.  If this was a pure React application this would have been the way to go however given that this is SSR (Server-Side Rendered) React we should take advantage of the platform.  Adding additional APIs, where the same functionality can be achieved purely server-side, exposes additional security attack paths.
Please modify the acceptance criteria.
