### ISSUE TITLE
Temporary Token Template incorrect display of token

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#839]
The temporary token can contain a sequence of characters that match markdown formatting.  When sent Notify will then render the token with the formatting instead of displaying all token characters.  When a user copy's and paste's the token it is found to be invalid by the server

![Screen Shot 2022-06-22 at 8.50.05 AM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/6bc7cc9d-729f-415a-800d-75d61664e408)

Acceptance Criteria:
- [ ] All the token characters are visible in the email

**Comment by jeberhardt** [comment]
It seems that Notify's templates will attempt to render character modifications (bold and italic), but the only overlap  between Markdown and characters allowed in a token is the potential for a double underscore (__). 

Are there any other character patterns that need to be accounted for?
