### ISSUE TITLE
Console Error: `Cannot read properties of null`

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#846]
Upon loading a form, the following console error sometimes appears:

> TypeError: Cannot read properties of null

This happens on `staging`, but I have not been able to replicate it on `localhost`.
Staging forms where this happens:
https://forms-staging.cdssandbox.xyz/en/id/272
https://forms-staging.cdssandbox.xyz/en/id/331

To reproduce this error, go to one of the above forms, and load the page, observing if the error appears in the console or not. It may require refreshing the page several times to cause the error to appear.

![Screen Shot 2022-06-21 at 10 26 48 AM](https://user-images.githubusercontent.com/77435/175944877-52eb4584-737a-4e23-bcec-8973e0ad4659.png)

**Comment by jeberhardt** [comment]
This error is specific to the RichText components, and is somewhere in the `markdown-to-jsx` package. It does not appear if the content in the string for the rich text is different. I am still trying to figure out what triggers the error exactly, and how to fix it, or at least catch the error.

**Comment by jeberhardt** [comment]
The error is being thrown by this line of code:
https://github.com/vercel/next.js/blob/48a3222ccc8dea2d1fa02926ee538fe301269d18/packages/next/client/index.tsx#L187

It seems that `document.getElementById('__NEXT_DATA__')` is null at this point for some reason.

**Comment by jeberhardt** [comment]
The following is the network traffic when the error occurs:
![with-error](https://user-images.githubusercontent.com/77435/176464558-c2e42fba-8748-49ca-95db-abbbf469b9d4.png)

The following is the network traffic when the error does not occur:
![without-error](https://user-images.githubusercontent.com/77435/176464572-35cc34d6-da33-4a35-a7f8-c37e46b79510.png)

**Comment by jeberhardt** [comment]
This bug does prevent the periodic calls to `/api/auth/session` and the checks for the feature flags.

**Comment by jeberhardt** [comment]
I've compared the main file that contains `__NEXT_DATA__`, between a response that throws the error, and when it doesn't throw the error, and the files are identical.

**Comment by jeberhardt** [comment]
As far as I can tell, this is the commit where the error was introduced.

https://github.com/cds-snc/platform-forms-client/commit/95e43633c77cea2903daf5e5911891f1caae8e19

**Comment by jeberhardt** [comment]
Next clue to solving this issue: In Chrome, when doing a `Hard Reload` (SHIFT + CMD + R), the error does not appear. When doing a `Normal Reload`, the error will sometimes happen.

**Comment by jeberhardt** [comment]
Just to confirm, this error is happening on Production as well: https://forms-formulaires.alpha.canada.ca/en/id/100

**Comment by bryan-robitaille** [comment]
See #848 for a potential fix
