### ISSUE TITLE
Page Authorization

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/platform-forms-client#874]
Existing authentication methods will need to be modified to allow for the new user type of a non-admin.  The current ‘requireAuthentication’ Page wrapper function checks for both a session and admin rights.  The function will need to be modified to take arguments in order to determine role requirements for a specific page.

Current Roles:  Admin (true / false)
Proposed Roles:  
“ProgramAdministrator” : A user that can view and download form responses.
“Administrator”: A user that can access all pages except to view and download form responses.

To support the new authentication wrapper function a new field will be created on the User object in the database.  The new ‘role’ field will replace the ‘admin’ field.  Logic that relies on the current admin field will need to be modified to ensure the acceptance of a string value and new role field.

![Screen Shot 2022-07-13 at 4.52.55 PM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/669a3a7a-ec29-43b7-b72a-d01dd834d09f)

## Existing Pseudo Code
![Screen Shot 2022-07-13 at 4.51.38 PM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/f20425f8-77d2-4e62-9d66-0f2505853e62)
## Proposed Pseudo Code
![Screen Shot 2022-07-13 at 4.52.19 PM.png](https://images.zenhubusercontent.com/60cb88ea0e362d8320f759f0/f9239678-9091-4cf6-a907-15f550335af9)

##Acceptance Criteria
- [x] A user is defined as "ProgramAdministrator" or "Administrator"
- [x] The function redirects to an 'unauthorized' page if the user does not possess the required role.  See `page/admin/unauthorized` as an example.
- [x] The function continues to render the page if the user possesses the required role.
- [x] The role requirements defined in this issue are respected and implemented on the appropriate pages.

**Comment by jeberhardt** [comment]
Because the permissions for the roles are exclusive, and there isn't any overlap, then I don't think that the `roleRequirement` should be an array.

**Comment by jeberhardt** [comment]
I think the default user role in the `User` table doesn't need to be `ProgramAdministrator`, since all of the users who are `ProgramAdministrators` are in the `FormUser` table.
