### ISSUE TITLE
Form response retrieval API file attachment scan verdict

### ISSUE THREAD

**Issue by patheard** [cds-snc/platform-forms-client#919]
# Summary
Add a new Form response retrieval API endpoint to get a form submission's file attachment scan verdicts.

Authorization will be performed by the temporary token passed as an authorization header to confirm that:

1. The submission ID belongs to the given form ID; and
1. The requesting user has permission to view the given form’s submissions.

```javascript
// request
/api/id/$FORM_ID/$SUBMISSION_ID/files/verdict

// response
​​{
    "submissionID": "$SUBMISSION_ID",
    "fileAttachments": [
       {
          "fileName": "$FILENAME",
          "avStatus": "$AV_STATUS",
          "avResult": "$AV_RESULT",
          "avScanner": "$AV_SCANNER",
          "avTimestamp": "$AV_TIMESTAMP"
       }
    ]
}
```

# Related
* #837

**Comment by patheard** [comment]
Work on this is being paused as the integration of file scanning with Forms is re-evaluated.

**Comment by craigzour** [comment]
Closing this as the whole feature around file scanning is being reworked
