### ISSUE TITLE
Error Messages on Sign In Page Need to Be Revised for Increased Clarity

### ISSUE THREAD

**Issue by Moro-Code** [cds-snc/platform-forms-client#948]
Current error messages on the sign in page and the way they are displayed are not clear enough to a user to be able to understand and then further correct their errors.

For example:

<img width="1208" alt="Screen Shot 2022-08-24 at 12 42 04 PM" src="https://user-images.githubusercontent.com/1763961/186660714-41aaeeaf-8712-4669-9bd0-0e6d2ee3be57.png">
<img width="1243" alt="Screen Shot 2022-08-24 at 10 32 01 AM" src="https://user-images.githubusercontent.com/1763961/186660721-37260dff-cc79-446a-8cda-d08974000eac.png">
<img width="1156" alt="Screen Shot 2022-08-24 at 10 30 27 AM" src="https://user-images.githubusercontent.com/1763961/186660722-262d02e4-05d8-46c1-b473-f63d2cdc08f9.png">

Please ensure you connect with @connorscarolyns when taking on this issue

Acceptance Criteria 
- [ ] Revise all possible error states and ensure that each one has descriptive content to inform the user clearly what the error is.

**Comment by bryan-robitaille** [comment]
For old login path
