### ISSUE TITLE
Content Security Policy (CSP) is absent

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/platform-forms-client#952]
scan-websites is reporting that the Content Security Policy (CSP) response header is no longer being set. Authenticate to [scan-websites](https://scan-websites.alpha.canada.ca/) and browse to [the report](https://scan-websites.alpha.canada.ca/en/results/9fa41b4e-40c3-48f9-8917-eac9c6bb6b16/security/d2df6f71-b0c8-407b-bfcc-d94543520c4c/870b1b70-cc68-4954-b0ac-5618ff64ee38/f73c504c-806f-4254-8d9d-8e212f032fcc) to view the full list.

Examples:
- https://forms-staging.cdssandbox.xyz/
- https://forms-staging.cdssandbox.xyz/en/auth/login
- https://forms-staging.cdssandbox.xyz/en/welcome-bienvenue

**Comment by bryan-robitaille** [comment]
CSP is present.  Scan-websites was only verifying the response headers while our application leverages CSP in a meta tag in order to implement the `strict-dynamic` property.
